package com.base.basesetup.repo;

import java.time.LocalDate;
import java.util.List;
import java.util.Optional;
import java.util.Set;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import com.base.basesetup.entity.AccountsVO;
import com.base.basesetup.entity.ArapAdjustmentsVO;

@Repository
public interface ArapAdjustmentsRepo extends JpaRepository<ArapAdjustmentsVO, Long> {

	@Query(nativeQuery = true, value = "select * from arapadjustments where orgid=?1")
	List<ArapAdjustmentsVO> getAllArapAdjustmentsByOrgId(Long orgId);

	@Query(nativeQuery = true, value = "select * from arapadjustments where arapadjustmentsid=?1")
	List<ArapAdjustmentsVO> getAllArapAdjustmentsById(Long id);
	@Query(nativeQuery = true, value = "select * from arapadjustments where active=1")
	
	List<ArapAdjustmentsVO> findArapAdjustmentsByActive();

	@Query(nativeQuery = true,value="select concat(prefixfield,lpad(lastno,5,0)) AS docid from documenttypemappingdetails where orgid=?1 and finyear=?2 and branchcode=?3 and screencode=?4")
	String getArapAdjustmentsDocId(Long orgId, String finYear, String branchCode, String screenCode);

	@Query(value = "select a from ArapAdjustmentsVO a where a.id=?1")
	ArapAdjustmentsVO findArapAdjustmentsByDocId(Long orgId, String docId);
	
	@Query(nativeQuery = true,value ="SELECT arapdetailsid,orgid,\r\n"
			+ "         branch,\r\n"
			+ "         subledgercode, partyname,\r\n"
			+ "         CONCAT(subledgername, ' , Cr. Limit - ', creditlimit, ' , Cr. Days - ', creditdays) AS subledgername,\r\n"
			+ "         partytype,\r\n"
			+ "         cbranch,\r\n"
			+ "         subledgerdivision,\r\n" 
			+ "         currency,\r\n"
			+ "         auser,\r\n"
			+ "         docid,\r\n"
			+ "         docdate,\r\n"
			+ "         supprefno,\r\n"
			+ "         duedate,\r\n"
			+ "         refno,\r\n"
			+ "         refdate,\r\n"
			+ "         amount,\r\n"
			+ "            outstanding,\r\n"
			+ "            totaldue,\r\n"
			+ "            unadjusted,\r\n"
			+ "          ddays,\r\n"
			+ " mslab1,\r\n"
			+ " mslab2,\r\n"
			+ " mslab3,\r\n"
			+ " mslab4,(mslab5 + mslab6 + mslab7) as mslab5,\r\n"
			+ "product,creditlimit,creditdays, \r\n"
			+ "         doctypecode\r\n"
			+ "FROM ( SELECT \r\n"
			+ "    a.arapdetailsid,a.orgid,\r\n"
			+ "    a.doctypecode,\r\n"
			+ "    br.branch,\r\n"
			+ "    p.partycode as subledgercode,\r\n"
			+ "   	p.partyname as subledgername,\r\n"
			+ "    'GST Party' as Partytype,\r\n"
			+ "   IFNULL(p.controllingoff, br.branchcode) AS cbranch,\r\n"
			+ "     a.subledgerdivision,\r\n"
			+ "    a.acccurrency AS currency,\r\n"
			+ "   'Base' AS auser,\r\n"
			+ "    a.docid,\r\n"
			+ "    a.docdate,\r\n"
			+ "    a.supprefno,\r\n"
			+ "   a.duedate,\r\n"
			+ "    a.refno,\r\n"
			+ "    a.refdate,\r\n"
			+ "	a.ipno,\r\n"
			+ "    a.hno,\r\n"
			+ "    a.amount AS amount,p.partyname ,\r\n"
			+ "    CASE \r\n"
			+ "        WHEN (a.doctypecode IN ('RC', 'PA') OR \r\n"
			+ "              (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%')) \r\n"
			+ "        THEN 0 \r\n"
			+ "        ELSE a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0) \r\n"
			+ "    END AS outstanding,\r\n"
			+ "    a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0) AS totaldue,\r\n"
			+ "    a.nativeamt AS bamount,\r\n"
			+ "   CASE\r\n"
			+ "    WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "          OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "    THEN 0\r\n"
			+ "    ELSE a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "END AS boutstanding,\r\n"
			+ "(a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)) AS btotaldue,\r\n"
			+ "a.nativeamt AS namount,\r\n"
			+ "CASE\r\n"
			+ "    WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "          OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "    THEN 0\r\n"
			+ "    ELSE a.nativeamt + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "END AS noutstanding,\r\n"
			+ "a.nativeamt + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0) AS ntotaldue ,\r\n"
			+ "     CASE\r\n"
			+ "    WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "          OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "         AND (a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)) <> 0\r\n"
			+ "    THEN a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS unadjusted,\r\n"
			+ "CASE\r\n"
			+ "    WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "          OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "         AND (a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)) <> 0\r\n"
			+ "    THEN a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS bunadjusted,\r\n"
			+ "CASE\r\n"
			+ "    WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "          OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "         AND (a.nativeamt + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)) <> 0\r\n"
			+ "    THEN a.nativeamt + IFNULL(SUM(IFNULL(r.nativeamt, 0)),0)\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS nunadjusted,\r\n"
			+ "STR_TO_DATE(?1, '%Y-%m-%d') AS asondt,\r\n"
			+ "CASE \r\n"
			+ "    WHEN ?2 = 'Due_Date' THEN a.duedate \r\n"
			+ "    ELSE a.docdate \r\n"
			+ "END AS ddays,\r\n"
			+ "CASE\r\n"
			+ "    WHEN  (DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'),   \r\n"
			+ "          CASE WHEN ?2 = 'Due_Date' THEN a.duedate ELSE a.docdate END) < 30)\r\n"
			+ "    THEN\r\n"
			+ "        CASE\r\n"
			+ "            WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                  OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "            THEN 0\r\n"
			+ "            ELSE a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "        END\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS mslab1,\r\n"
			+ "CASE\r\n"
			+ "    WHEN  (DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'),   \r\n"
			+ "          CASE WHEN ?2 = 'Due_Date' THEN a.duedate ELSE a.docdate END) < 30)\r\n"
			+ "    THEN\r\n"
			+ "        CASE\r\n"
			+ "            WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                  OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "            THEN 0\r\n"
			+ "            ELSE a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "        END\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS bmslab1,\r\n"
			+ "CASE\r\n"
			+ "    WHEN  (DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'),  \r\n"
			+ "          CASE WHEN ?2 = 'Due_Date' THEN a.duedate ELSE a.docdate END) < 30)\r\n"
			+ "    THEN\r\n"
			+ "        CASE\r\n"
			+ "            WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                  OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "            THEN 0\r\n"
			+ "            ELSE a.nativeamt + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "        END\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS nmslab1 ,\r\n"
			+ "CASE\r\n"
			+ "    WHEN (DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'), \r\n"
			+ "          CASE WHEN ?2 = 'Due_Date' THEN a.duedate ELSE a.docdate END)\r\n"
			+ "          BETWEEN 30 AND 45)\r\n"
			+ "    THEN\r\n"
			+ "        CASE\r\n"
			+ "            WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                  OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "            THEN 0\r\n"
			+ "            ELSE a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "        END\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS mslab2,\r\n"
			+ "CASE\r\n"
			+ "    WHEN (DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'), \r\n"
			+ "          CASE WHEN ?2 = 'Due_Date' THEN a.duedate ELSE a.docdate END)\r\n"
			+ "          BETWEEN  30 and 45)\r\n"
			+ "    THEN\r\n"
			+ "        CASE\r\n"
			+ "            WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                  OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "            THEN 0\r\n"
			+ "            ELSE a.nativeamt + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "        END\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS bmslab2,\r\n"
			+ "CASE\r\n"
			+ "    WHEN (DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'), \r\n"
			+ "          CASE WHEN ?2 = 'Due_Date' THEN a.duedate ELSE a.docdate END)\r\n"
			+ "         BETWEEN 30 AND 45)\r\n"
			+ "    THEN\r\n"
			+ "        CASE\r\n"
			+ "            WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                  OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "            THEN 0\r\n"
			+ "            ELSE a.nativeamt + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "        END\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS nmslab2,\r\n"
			+ "CASE\r\n"
			+ "    WHEN (DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'), \r\n"
			+ "          CASE WHEN ?2 = 'Due_Date' THEN a.duedate ELSE a.docdate END)\r\n"
			+ "           BETWEEN 45 AND 60)\r\n"
			+ "    THEN\r\n"
			+ "        CASE\r\n"
			+ "            WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                  OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "            THEN 0\r\n"
			+ "            ELSE a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "        END\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS mslab3,\r\n"
			+ "CASE\r\n"
			+ "    WHEN (DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'), \r\n"
			+ "          CASE WHEN ?2 = 'Due_Date' THEN a.duedate ELSE a.docdate END)\r\n"
			+ "       BETWEEN 45 AND 60)\r\n"
			+ "    THEN\r\n"
			+ "        CASE\r\n"
			+ "            WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                  OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "            THEN 0\r\n"
			+ "            ELSE a.nativeamt + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "        END\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS bmslab3,\r\n"
			+ "CASE\r\n"
			+ "    WHEN (DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'), \r\n"
			+ "          CASE WHEN ?2 = 'Due_Date' THEN a.duedate ELSE a.docdate END)\r\n"
			+ "              BETWEEN 45 AND 60)\r\n"
			+ "    THEN\r\n"
			+ "        CASE\r\n"
			+ "            WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                  OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "            THEN 0\r\n"
			+ "            ELSE a.nativeamt + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "        END\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS nmslab3,\r\n"
			+ "CASE\r\n"
			+ "    WHEN (DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'), \r\n"
			+ "          CASE WHEN ?2 = 'Due_Date' THEN a.duedate ELSE a.docdate END)\r\n"
			+ "              BETWEEN 60 AND 90)\r\n"
			+ "    THEN\r\n"
			+ "        CASE\r\n"
			+ "            WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                  OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "            THEN 0\r\n"
			+ "            ELSE a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "        END\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS mslab4,\r\n"
			+ "CASE\r\n"
			+ "    WHEN (DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'), \r\n"
			+ "          CASE WHEN ?2 = 'Due_Date' THEN a.duedate ELSE a.docdate END)\r\n"
			+ "           BETWEEN 60 AND 90)\r\n"
			+ "    THEN\r\n"
			+ "        CASE\r\n"
			+ "            WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                  OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "            THEN 0\r\n"
			+ "            ELSE a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "        END\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS bmslab4,\r\n"
			+ "CASE\r\n"
			+ "    WHEN (DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'), \r\n"
			+ "          CASE WHEN ?2 = 'Due_Date' THEN a.duedate ELSE a.docdate END)\r\n"
			+ "            BETWEEN 60 AND 90)\r\n"
			+ "    THEN\r\n"
			+ "        CASE\r\n"
			+ "            WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                  OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "            THEN 0\r\n"
			+ "            ELSE a.nativeamt + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "        END\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS nmslab4,\r\n"
			+ "CASE\r\n"
			+ "    WHEN (DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'), \r\n"
			+ "          CASE WHEN ?2 = 'Due_Date' THEN a.duedate ELSE a.docdate END)\r\n"
			+ "          BETWEEN 60 AND 105)\r\n"
			+ "    THEN\r\n"
			+ "        CASE\r\n"
			+ "            WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                  OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "            THEN 0\r\n"
			+ "            ELSE a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "        END\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS mslab5,\r\n"
			+ "CASE\r\n"
			+ "    WHEN (DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'), \r\n"
			+ "          CASE WHEN ?2 = 'Due_Date' THEN a.duedate ELSE a.docdate END)\r\n"
			+ "         BETWEEN 60 AND 105)\r\n"
			+ "    THEN\r\n"
			+ "        CASE\r\n"
			+ "            WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                  OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "            THEN 0\r\n"
			+ "            ELSE a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "        END\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS bmslab5,\r\n"
			+ "CASE\r\n"
			+ "    WHEN (DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'), \r\n"
			+ "          CASE WHEN ?2 = 'Due_Date' THEN a.duedate ELSE a.docdate END)\r\n"
			+ "          BETWEEN 60 AND 105)\r\n"
			+ "    THEN\r\n"
			+ "        CASE\r\n"
			+ "            WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                  OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "            THEN 0\r\n"
			+ "            ELSE a.nativeamt + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "        END\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS nmslab5,\r\n"
			+ "CASE\r\n"
			+ "    WHEN (DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'), \r\n"
			+ "          CASE WHEN ?2 = 'Due_Date' THEN a.duedate ELSE a.docdate END)\r\n"
			+ "          BETWEEN 60 AND 120)\r\n"
			+ "    THEN\r\n"
			+ "        CASE\r\n"
			+ "            WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                  OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "            THEN 0\r\n"
			+ "            ELSE a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "        END\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS mslab6,\r\n"
			+ "CASE\r\n"
			+ "    WHEN (DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'), \r\n"
			+ "          CASE WHEN ?2 = 'Due_Date' THEN a.duedate ELSE a.docdate END)\r\n"
			+ "          BETWEEN 60 AND 120)\r\n"
			+ "    THEN\r\n"
			+ "        CASE\r\n"
			+ "            WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                  OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "            THEN 0\r\n"
			+ "            ELSE a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "        END\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS bmslab6,\r\n"
			+ "CASE\r\n"
			+ "    WHEN (DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'), \r\n"
			+ "          CASE WHEN ?2 = 'Due_Date' THEN a.duedate ELSE a.docdate END)\r\n"
			+ "         BETWEEN 60 AND 120)\r\n"
			+ "    THEN\r\n"
			+ "        CASE\r\n"
			+ "            WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                  OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "            THEN 0\r\n"
			+ "            ELSE a.nativeamt + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "        END\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS nmslab6,\r\n"
			+ "CASE\r\n"
			+ "    WHEN (DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'), \r\n"
			+ "          CASE WHEN ?2 = 'Due_Date' THEN a.duedate ELSE a.docdate END) >= 120)\r\n"
			+ "    THEN\r\n"
			+ "        CASE\r\n"
			+ "            WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                  OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "            THEN 0\r\n"
			+ "            ELSE a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "        END\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS mslab7,\r\n"
			+ "CASE\r\n"
			+ "    WHEN (DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'), \r\n"
			+ "          CASE WHEN ?2 = 'Due_Date' THEN a.duedate ELSE a.docdate END) >= 120)\r\n"
			+ "    THEN\r\n"
			+ "        CASE\r\n"
			+ "            WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                  OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "            THEN 0\r\n"
			+ "            ELSE a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "        END\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS bmslab7,\r\n"
			+ "CASE\r\n"
			+ "    WHEN (DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'), \r\n"
			+ "          CASE WHEN ?2 = 'Due_Date' THEN a.duedate ELSE a.docdate END) >= 120 )\r\n"
			+ "    THEN\r\n"
			+ "        CASE\r\n"
			+ "            WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                  OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "            THEN 0\r\n"
			+ "            ELSE a.nativeamt + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "        END\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS nmslab7,\r\n"
			+ "                   z.product,p.creditlimit,p.creditdays\r\n"
			+ "FROM arapdetails a\r\n"
			+ " LEFT JOIN arapadjustments r ON a.subledgercode = r.subledgercode AND a.docid = r.docid\r\n"
			+ " LEFT JOIN partymaster p ON a.subledgercode = p.partycode\r\n"
			+ "LEFT JOIN branch br ON a.branch = br.branch\r\n"
			+ "LEFT JOIN accounts z ON a.docid = z.docid\r\n"
			+ "WHERE \r\n"
			+ "    a.docdate <= current_date() \r\n"
			+ "    AND (r.docdate IS NULL OR r.docdate <= current_date() )  \r\n"
			+ "    AND a.CANCEL = 'F' \r\n"
			+ "    AND (r.CANCEL IS NULL OR r.CANCEL = 'F')\r\n"
			+ "    AND br.branchcode = 'BLR'\r\n"
			+ "    AND 'Branch' = 'Branch'  \r\n"
			+ "    AND p.partytype <> 'IB'\r\n"
			+ "GROUP BY \r\n"
			+ "    a.arapdetailsid,a.orgid,\r\n"
			+ "   br.branch,\r\n"
			+ "     br.branchcode,\r\n"
			+ "         p.partycode,\r\n"
			+ "    p.partyname,\r\n"
			+ "     a.subledgerdivision,\r\n"
			+ "    a.currency,\r\n"
			+ "    a.acccurrency,\r\n"
			+ "    a.docid,\r\n"
			+ "    a.docdate,\r\n"
			+ "    a.creditdays,\r\n"
			+ "    a.amount,\r\n"
			+ "    a.refno,\r\n"
			+ "    a.refdate,\r\n"
			+ "    a.ipno,\r\n"
			+ "    a.hno,\r\n"
			+ "    a.duedate,\r\n"
			+ "    p.creditlimit,\r\n"
			+ "    p.creditdays,\r\n"
			+ "    p.controllingoff, a.doctypecode,z.product\r\n"
			+ "	 HAVING     (a.amount + IFNULL(SUM(IFNULL(r.amount, 0)), 0)) != 0) a\r\n"
			+ "	 where (partyname =?3 or 'ALL' = ?3 )\r\n"
			+ "	 and orgid =?4\r\n"
			+ " union\r\n"
			+ " SELECT arapdetailsid,orgid,\r\n"
			+ "         branch,\r\n"
			+ "         subledgercode, partyname ,\r\n"
			+ "         CONCAT(subledgername, ' , Cr. Limit - ', creditlimit, ' , Cr. Days - ', creditdays) AS subledgername,\r\n"
			+ "         partytype,\r\n"
			+ "         cbranch,\r\n"
			+ "         subledgerdivision,\r\n"
			+ "         currency,\r\n"
			+ "         auser,\r\n"
			+ "         docid,\r\n"
			+ "         docdate,\r\n"
			+ "         supprefno,\r\n"
			+ "         duedate,\r\n"
			+ "         refno,\r\n"
			+ "         refdate,\r\n"
			+ "        amount,\r\n"
			+ "            outstanding,\r\n"
			+ "            totaldue,\r\n"
			+ "            unadjusted,\r\n"
			+ "          ddays,\r\n"
			+ "       mslab1,\r\n"
			+ " mslab2,\r\n"
			+ " mslab3,\r\n"
			+ " mslab4,(mslab5 + mslab6 + mslab7) as mslab5,\r\n"
			+ "             product,creditlimit,creditdays ,\r\n"
			+ "         doctypecode\r\n"
			+ "    FROM (      \r\n"
			+ "    SELECT a.arapdetailsid,a.orgid,\r\n"
			+ "                   a.doctypecode,\r\n"
			+ "                   jbr.branch,\r\n"
			+ "                  p.partycode as subledgercode,\r\n"
			+ "   				p.partyname as subledgername,\r\n"
			+ "   				          ac.product,\r\n"
			+ "                    'GST Party' as Partytype,\r\n"
			+ "                    IFNULL(br.branch,jbr.branch) cbranch,\r\n"
			+ "                   p.creditlimit,\r\n"
			+ "                   p.creditdays,\r\n"
			+ "                   a.subledgerdivision,\r\n"
			+ "                   a.currency as  currency,\r\n"
			+ "                   'Base' AS auser,\r\n"
			+ "                   a.docid ,\r\n"
			+ "                   a.docdate,\r\n"
			+ "                   a.supprefno,\r\n"
			+ "                   a.duedate,\r\n"
			+ "                   a.refno,\r\n"
			+ "                   a.refdate,\r\n"
			+ "                   a.hno,\r\n"
			+ "                   a.amount AS amount,p.partyname,\r\n"
			+ "                   CASE \r\n"
			+ "        WHEN (a.doctypecode IN ('RC', 'PA') OR \r\n"
			+ "              (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%')) \r\n"
			+ "        THEN 0 \r\n"
			+ "        ELSE a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0) \r\n"
			+ "    END AS outstanding,\r\n"
			+ "    a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0) AS totaldue,\r\n"
			+ "    a.nativeamt AS bamount,\r\n"
			+ "   CASE\r\n"
			+ "    WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "          OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "    THEN 0\r\n"
			+ "    ELSE a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "END AS boutstanding,\r\n"
			+ "(a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)) AS btotaldue,\r\n"
			+ "a.nativeamt AS namount,\r\n"
			+ "CASE\r\n"
			+ "    WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "          OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "    THEN 0\r\n"
			+ "    ELSE a.nativeamt + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "END AS noutstanding,\r\n"
			+ "a.nativeamt + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0) AS ntotaldue ,\r\n"
			+ "                 CASE\r\n"
			+ "    WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "          OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "         AND (a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)) <> 0\r\n"
			+ "    THEN a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS unadjusted,\r\n"
			+ "CASE\r\n"
			+ "    WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "          OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "         AND (a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)) <> 0\r\n"
			+ "    THEN a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS bunadjusted,\r\n"
			+ "CASE\r\n"
			+ "    WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "          OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "         AND (a.nativeamt + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)) <> 0\r\n"
			+ "    THEN a.nativeamt + IFNULL(SUM(IFNULL(r.nativeamt, 0)),0)\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS nunadjusted,\r\n"
			+ "STR_TO_DATE(?1, '%Y-%m-%d') AS asondt,\r\n"
			+ "CASE \r\n"
			+ "    WHEN ?2 = 'Due_Date' THEN a.duedate \r\n"
			+ "    ELSE a.docdate \r\n"
			+ "END AS ddays,\r\n"
			+ "   CASE\r\n"
			+ "    WHEN  (DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'),   \r\n"
			+ "          CASE WHEN ?2 = 'Due_Date' THEN a.duedate ELSE a.docdate END) < 30)\r\n"
			+ "    THEN\r\n"
			+ "        CASE\r\n"
			+ "            WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                  OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "            THEN 0\r\n"
			+ "            ELSE a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "        END\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS mslab1,\r\n"
			+ "CASE\r\n"
			+ "    WHEN  (DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'),   \r\n"
			+ "          CASE WHEN ?2 = 'Due_Date' THEN a.duedate ELSE a.docdate END) < 30)\r\n"
			+ "    THEN\r\n"
			+ "        CASE\r\n"
			+ "            WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                  OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "            THEN 0\r\n"
			+ "            ELSE a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "        END\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS bmslab1,\r\n"
			+ "CASE\r\n"
			+ "    WHEN  (DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'),  \r\n"
			+ "          CASE WHEN ?2 = 'Due_Date' THEN a.duedate ELSE a.docdate END) < 30)\r\n"
			+ "    THEN\r\n"
			+ "        CASE\r\n"
			+ "            WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                  OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "            THEN 0\r\n"
			+ "            ELSE a.nativeamt + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "        END\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS nmslab1 ,\r\n"
			+ "CASE\r\n"
			+ "    WHEN (DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'), \r\n"
			+ "          CASE WHEN ?2 = 'Due_Date' THEN a.duedate ELSE a.docdate END)\r\n"
			+ "          BETWEEN 30 AND 45)\r\n"
			+ "    THEN\r\n"
			+ "        CASE\r\n"
			+ "            WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                  OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "            THEN 0\r\n"
			+ "            ELSE a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "        END\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS mslab2,\r\n"
			+ "CASE\r\n"
			+ "    WHEN (DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'), \r\n"
			+ "          CASE WHEN ?2 = 'Due_Date' THEN a.duedate ELSE a.docdate END)\r\n"
			+ "          BETWEEN  30 and 45)\r\n"
			+ "    THEN\r\n"
			+ "        CASE\r\n"
			+ "            WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                  OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "            THEN 0\r\n"
			+ "            ELSE a.nativeamt + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "        END\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS bmslab2,\r\n"
			+ "CASE\r\n"
			+ "    WHEN (DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'), \r\n"
			+ "          CASE WHEN ?2 = 'Due_Date' THEN a.duedate ELSE a.docdate END)\r\n"
			+ "         BETWEEN 30 AND 45)\r\n"
			+ "    THEN\r\n"
			+ "        CASE\r\n"
			+ "            WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                  OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "            THEN 0\r\n"
			+ "            ELSE a.nativeamt + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "        END\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS nmslab2,\r\n"
			+ "CASE\r\n"
			+ "    WHEN (DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'), \r\n"
			+ "          CASE WHEN ?2 = 'Due_Date' THEN a.duedate ELSE a.docdate END)\r\n"
			+ "           BETWEEN 45 AND 60)\r\n"
			+ "    THEN\r\n"
			+ "        CASE\r\n"
			+ "            WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                  OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "            THEN 0\r\n"
			+ "            ELSE a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "        END\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS mslab3,\r\n"
			+ "CASE\r\n"
			+ "    WHEN (DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'), \r\n"
			+ "          CASE WHEN ?2 = 'Due_Date' THEN a.duedate ELSE a.docdate END)\r\n"
			+ "       BETWEEN 45 AND 60)\r\n"
			+ "    THEN\r\n"
			+ "        CASE\r\n"
			+ "            WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                  OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "            THEN 0\r\n"
			+ "            ELSE a.nativeamt + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "        END\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS bmslab3,\r\n"
			+ "CASE\r\n"
			+ "    WHEN (DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'), \r\n"
			+ "          CASE WHEN ?2 = 'Due_Date' THEN a.duedate ELSE a.docdate END)\r\n"
			+ "              BETWEEN 45 AND 60)\r\n"
			+ "    THEN\r\n"
			+ "        CASE\r\n"
			+ "            WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                  OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "            THEN 0\r\n"
			+ "            ELSE a.nativeamt + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "        END\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS nmslab3,\r\n"
			+ "CASE\r\n"
			+ "    WHEN (DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'), \r\n"
			+ "          CASE WHEN ?2 = 'Due_Date' THEN a.duedate ELSE a.docdate END)\r\n"
			+ "              BETWEEN 60 AND 90)\r\n"
			+ "    THEN\r\n"
			+ "        CASE\r\n"
			+ "            WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                  OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "            THEN 0\r\n"
			+ "            ELSE a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "        END\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS mslab4,\r\n"
			+ "CASE\r\n"
			+ "    WHEN (DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'), \r\n"
			+ "          CASE WHEN ?2 = 'Due_Date' THEN a.duedate ELSE a.docdate END)\r\n"
			+ "           BETWEEN 60 AND 90)\r\n"
			+ "    THEN\r\n"
			+ "        CASE\r\n"
			+ "            WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                  OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "            THEN 0\r\n"
			+ "            ELSE a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "        END\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS bmslab4,\r\n"
			+ "CASE\r\n"
			+ "    WHEN (DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'), \r\n"
			+ "          CASE WHEN ?2 = 'Due_Date' THEN a.duedate ELSE a.docdate END)\r\n"
			+ "            BETWEEN 60 AND 90)\r\n"
			+ "    THEN\r\n"
			+ "        CASE\r\n"
			+ "            WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                  OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "            THEN 0\r\n"
			+ "            ELSE a.nativeamt + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "        END\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS nmslab4,\r\n"
			+ "CASE\r\n"
			+ "    WHEN (DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'), \r\n"
			+ "          CASE WHEN ?2 = 'Due_Date' THEN a.duedate ELSE a.docdate END)\r\n"
			+ "          BETWEEN 60 AND 105)\r\n"
			+ "    THEN\r\n"
			+ "        CASE\r\n"
			+ "            WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                  OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "            THEN 0\r\n"
			+ "            ELSE a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "        END\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS mslab5,\r\n"
			+ "CASE\r\n"
			+ "    WHEN (DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'), \r\n"
			+ "          CASE WHEN ?2 = 'Due_Date' THEN a.duedate ELSE a.docdate END)\r\n"
			+ "         BETWEEN 60 AND 105)\r\n"
			+ "    THEN\r\n"
			+ "        CASE\r\n"
			+ "            WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                  OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "            THEN 0\r\n"
			+ "            ELSE a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "        END\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS bmslab5,\r\n"
			+ "CASE\r\n"
			+ "    WHEN (DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'), \r\n"
			+ "          CASE WHEN ?2 = 'Due_Date' THEN a.duedate ELSE a.docdate END)\r\n"
			+ "          BETWEEN 60 AND 105)\r\n"
			+ "    THEN\r\n"
			+ "        CASE\r\n"
			+ "            WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                  OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "            THEN 0\r\n"
			+ "            ELSE a.nativeamt + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "        END\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS nmslab5,\r\n"
			+ "CASE\r\n"
			+ "    WHEN (DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'), \r\n"
			+ "          CASE WHEN ?2 = 'Due_Date' THEN a.duedate ELSE a.docdate END)\r\n"
			+ "          BETWEEN 60 AND 120)\r\n"
			+ "    THEN\r\n"
			+ "        CASE\r\n"
			+ "            WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                  OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "            THEN 0\r\n"
			+ "            ELSE a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "        END\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS mslab6,\r\n"
			+ "CASE\r\n"
			+ "    WHEN (DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'), \r\n"
			+ "          CASE WHEN ?2 = 'Due_Date' THEN a.duedate ELSE a.docdate END)\r\n"
			+ "          BETWEEN 60 AND 120)\r\n"
			+ "    THEN\r\n"
			+ "        CASE\r\n"
			+ "            WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                  OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "            THEN 0\r\n"
			+ "            ELSE a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "        END\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS bmslab6,\r\n"
			+ "CASE\r\n"
			+ "    WHEN (DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'), \r\n"
			+ "          CASE WHEN ?2 = 'Due_Date' THEN a.duedate ELSE a.docdate END)\r\n"
			+ "         BETWEEN 60 AND 120)\r\n"
			+ "    THEN\r\n"
			+ "        CASE\r\n"
			+ "            WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                  OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "            THEN 0\r\n"
			+ "            ELSE a.nativeamt + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "        END\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS nmslab6,\r\n"
			+ "CASE\r\n"
			+ "    WHEN (DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'), \r\n"
			+ "          CASE WHEN ?2 = 'Due_Date' THEN a.duedate ELSE a.docdate END) >= 120)\r\n"
			+ "    THEN\r\n"
			+ "        CASE\r\n"
			+ "            WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                  OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "            THEN 0\r\n"
			+ "            ELSE a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "        END\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS mslab7,\r\n"
			+ "CASE\r\n"
			+ "    WHEN (DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'), \r\n"
			+ "          CASE WHEN ?2 = 'Due_Date' THEN a.duedate ELSE a.docdate END) >= 120)\r\n"
			+ "    THEN\r\n"
			+ "        CASE\r\n"
			+ "            WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                  OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "            THEN 0\r\n"
			+ "            ELSE a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "        END\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS bmslab7,\r\n"
			+ "CASE\r\n"
			+ "    WHEN (DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'), \r\n"
			+ "          CASE WHEN ?2 = 'Due_Date' THEN a.duedate ELSE a.docdate END) >= 120 )\r\n"
			+ "    THEN\r\n"
			+ "        CASE\r\n"
			+ "            WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                  OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "            THEN 0\r\n"
			+ "            ELSE a.nativeamt + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)\r\n"
			+ "        END\r\n"
			+ "    ELSE 0\r\n"
			+ "END AS nmslab7\r\n"
			+ "                   FROM arapdetails a\r\n"
			+ "LEFT JOIN accounts ac ON a.docid = ac.docid\r\n"
			+ "LEFT JOIN arapadjustments r ON a.subledgercode = r.subledgercode AND a.docid = r.docid\r\n"
			+ "JOIN partymaster p ON a.subledgercode = p.partycode\r\n"
			+ "JOIN branch jbr ON a.branch = jbr.branch\r\n"
			+ "JOIN branch br ON IFNULL(p.controllingoff, jbr.branchcode) = br.branchcode\r\n"
			+ "WHERE a.docdate <= ?1\r\n"
			+ "  AND (r.docdate IS NULL OR r.docdate <= ?1)\r\n"
			+ "  AND a.CANCEL = 'F'\r\n"
			+ "  AND (r.CANCEL IS NULL OR r.CANCEL = 'F')\r\n"
			+ "  AND p.partytype <> 'IB'\r\n"
			+ "GROUP BY a.arapdetailsid,a.orgid,\r\n"
			+ "         br.branch,\r\n"
			+ "         jbr.branch,\r\n"
			+ "          p.partycode,\r\n"
			+ "   		p.partyname,\r\n"
			+ "         ac.product,\r\n"
			+ "         p.controllingoff,\r\n"
			+ "         a.subledgerdivision,\r\n"
			+ "         a.currency,\r\n"
			+ "         a.docid,\r\n"
			+ "         a.docdate,\r\n"
			+ "         a.supprefno,\r\n"
			+ "         a.creditdays,\r\n"
			+ "         p.creditdays,\r\n"
			+ "         p.creditlimit,\r\n"
			+ "         a.amount,\r\n"
			+ "         a.refdate,\r\n"
			+ "         a.duedate,\r\n"
			+ "         a.doctypecode\r\n"
			+ "HAVING (a.amount + IFNULL(SUM(IFNULL(r.amount, 0)), 0)) != 0) a\r\n"
			+ "where (partyname =?3 or 'ALL' = ?3 )\r\n"
			+ " and orgid =?4\r\n"
			+ "")
	Set<Object[]> findArapAgeing(String asondate,String pdate, String partyname, Long orgId);
	
	@Query(nativeQuery = true,value ="WITH a AS ( \r\n"
			+ " 			 			 SELECT a.arapdetailsid,  \r\n"
			+ " 			 			                    br.branch,  \r\n"
			+ " 			 			                    partycode as subledgercode,  \r\n"
			+ " 			 			                    partyname as subledgername,  \r\n"
			+ " 			 			                    jbr.branch jobbranch,  \r\n"
			+ " 			 			                    a.docid,  \r\n"
			+ " 			 			                    a.docdate,  \r\n"
			+ " 			 			                    a.duedate,  \r\n"
			+ " 			 			                    a.refno,  \r\n"
			+ " 			 			                    a.refdate, a.currency,a.amount,A.finyear,p.PARTYTYPE,  \r\n"
			+ " 			 			                    CASE   \r\n"
			+ " 			 			         WHEN   \r\n"
			+ " 			 			               (a.refno LIKE '%RT%' OR a.refno LIKE  '%PT%')   \r\n"
			+ " 			 			         THEN 0   \r\n"
			+ " 			 			         ELSE a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)   \r\n"
			+ " 			 			     END AS outstanding,  \r\n"
			+ " 			 			     a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0) AS totaldue,  \r\n"
			+ " 			 			     a.nativeamt AS bamount,  \r\n"
			+ " 			 			    CASE  \r\n"
			+ " 			 			     WHEN   \r\n"
			+ " 			 			            (a.refno LIKE '%RT%' OR a.refno LIKE  '%PT%')  \r\n"
			+ " 			 			     THEN 0  \r\n"
			+ " 			 			     ELSE a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)  \r\n"
			+ " 			 			 END AS boutstanding,  \r\n"
			+ " 			 			 (a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)) AS btotaldue,  \r\n"
			+ " 			 			 a.nativeamt AS namount,  \r\n"
			+ " 			 			 CASE  \r\n"
			+ " 			 			     WHEN   \r\n"
			+ " 			 			            (a.refno LIKE '%RT%' OR a.refno LIKE  '%PT%')  \r\n"
			+ " 			 			     THEN 0  \r\n"
			+ " 			 			     ELSE a.nativeamt + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)  \r\n"
			+ " 			 			 END AS noutstanding,  \r\n"
			+ " 			 			 a.nativeamt + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0) AS ntotaldue ,  \r\n"
			+ " 			 			    CASE  \r\n"
			+ " 			 			     WHEN   \r\n"
			+ " 			 			            (a.refno LIKE '%PT%' OR a.refno LIKE '%RT%')  \r\n"
			+ " 			 			          AND (a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)) <> 0  \r\n"
			+ " 			 			     THEN a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)  \r\n"
			+ " 			 			     ELSE 0  \r\n"
			+ " 			 			 END AS unadjusted,  \r\n"
			+ " 			 			 CASE  \r\n"
			+ " 			 			     WHEN   \r\n"
			+ " 			 			            (a.refno LIKE '%RT%' OR a.refno LIKE  '%PT%')  \r\n"
			+ " 			 			          AND (a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)) <> 0  \r\n"
			+ " 			 			     THEN a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)  \r\n"
			+ " 			 			     ELSE 0  \r\n"
			+ " 			 			 END AS bunadjusted,  \r\n"
			+ " 			 			 CASE  \r\n"
			+ " 			 			     WHEN   \r\n"
			+ " 			 			            (a.refno LIKE '%RT%' OR a.refno LIKE  '%PT%')  \r\n"
			+ " 			 			          AND (a.nativeamt + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)) <> 0  \r\n"
			+ " 			 			     THEN a.nativeamt + IFNULL(SUM(IFNULL(r.nativeamt, 0)),0)  \r\n"
			+ " 			 			     ELSE 0  \r\n"
			+ " 			 			 END AS nunadjusted,  \r\n"
			+ " 			 			     date(?1)AS asondt,  \r\n"
			+ " 			 			 CASE   \r\n"
			+ " 			 			     WHEN ?5 = 'Due_Date' THEN a.duedate   \r\n"
			+ " 			 			     ELSE a.docdate   \r\n"
			+ " 			 			 END AS ddays,  \r\n"
			+ " 			 			 CASE  \r\n"
			+ " 			 			     WHEN  (DATEDIFF(date(?1),     \r\n"
			+ " 			 			           CASE WHEN ?5 = 'Due_Date' THEN a.duedate ELSE a.docdate END) < 30)  \r\n"
			+ " 			 			     THEN  \r\n"
			+ " 			 			         CASE  \r\n"
			+ " 			 			             WHEN   \r\n"
			+ " 			 			                    (a.refno LIKE '%RT%' OR a.refno LIKE  '%PT%')  \r\n"
			+ " 			 			             THEN 0  \r\n"
			+ " 			 			             ELSE a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)  \r\n"
			+ " 			 			         END  \r\n"
			+ " 			 			     ELSE 0  \r\n"
			+ " 			 			 END AS mslab1,  \r\n"
			+ " 			 			 CASE  \r\n"
			+ " 			 			     WHEN (DATEDIFF(date(?1),     \r\n"
			+ " 			 			           CASE WHEN ?5 = 'Due_Date' THEN a.duedate ELSE a.docdate END)  \r\n"
			+ " 			 			           BETWEEN 30 AND 45)  \r\n"
			+ " 			 			     THEN  \r\n"
			+ " 			 			         CASE  \r\n"
			+ " 			 			             WHEN   \r\n"
			+ " 			 			                    (a.refno LIKE '%RT%' OR a.refno LIKE  '%PT%')  \r\n"
			+ " 			 			             THEN 0  \r\n"
			+ " 			 			             ELSE a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)  \r\n"
			+ " 			 			         END  \r\n"
			+ " 			 			     ELSE 0  \r\n"
			+ " 			 			 END AS mslab2,  \r\n"
			+ " 			 			 CASE  \r\n"
			+ " 			 			     WHEN (DATEDIFF(date(?1),     \r\n"
			+ " 			 			           CASE WHEN ?5 = 'Due_Date' THEN a.duedate ELSE a.docdate END)  \r\n"
			+ " 			 			            BETWEEN 45 AND 60)  \r\n"
			+ " 			 			     THEN  \r\n"
			+ " 			 			         CASE  \r\n"
			+ " 			 			             WHEN   \r\n"
			+ " 			 			                    (a.refno LIKE '%RT%' OR a.refno LIKE  '%PT%')  \r\n"
			+ " 			 			             THEN 0  \r\n"
			+ " 			 			             ELSE a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)  \r\n"
			+ " 			 			         END  \r\n"
			+ " 			 			     ELSE 0  \r\n"
			+ " 			 			 END AS mslab3,  \r\n"
			+ " 			 			 CASE  \r\n"
			+ " 			 			     WHEN(DATEDIFF(date(?1),     \r\n"
			+ " 			 			           CASE WHEN ?5 = 'Due_Date' THEN a.duedate ELSE a.docdate END)  \r\n"
			+ " 			 			               BETWEEN 60 AND 90)  \r\n"
			+ " 			 			     THEN  \r\n"
			+ " 			 			         CASE  \r\n"
			+ " 			 			             WHEN   \r\n"
			+ " 			 			                    (a.refno LIKE '%RT%' OR a.refno LIKE  '%PT%')  \r\n"
			+ " 			 			             THEN 0  \r\n"
			+ " 			 			             ELSE a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)  \r\n"
			+ " 			 			         END  \r\n"
			+ " 			 			     ELSE 0  \r\n"
			+ " 			 			 END AS mslab4,  \r\n"
			+ " 			 			 CASE  \r\n"
			+ " 			 			     WHEN (DATEDIFF(date(?1),     \r\n"
			+ " 			 			           CASE WHEN ?5 = 'Due_Date' THEN a.duedate ELSE a.docdate END)  \r\n"
			+ " 			 			           BETWEEN 60 AND 105)  \r\n"
			+ " 			 			     THEN  \r\n"
			+ " 			 			         CASE  \r\n"
			+ " 			 			             WHEN   \r\n"
			+ " 			 			                    (a.refno LIKE '%RT%' OR a.refno LIKE  '%PT%')  \r\n"
			+ " 			 			             THEN 0  \r\n"
			+ " 			 			             ELSE a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)  \r\n"
			+ " 			 			         END  \r\n"
			+ " 			 			     ELSE 0  \r\n"
			+ " 			 			 END AS mslab5,  \r\n"
			+ " 			 			 CASE  \r\n"
			+ " 			 			     WHEN (DATEDIFF(date(?1),     \r\n"
			+ " 			 			           CASE WHEN ?5 = 'Due_Date' THEN a.duedate ELSE a.docdate END)  \r\n"
			+ " 			 			           BETWEEN 60 AND 120)  \r\n"
			+ " 			 			     THEN  \r\n"
			+ " 			 			         CASE  \r\n"
			+ " 			 			             WHEN   \r\n"
			+ " 			 			                    (a.refno LIKE '%RT%' OR a.refno LIKE  '%PT%')  \r\n"
			+ " 			 			             THEN 0  \r\n"
			+ " 			 			             ELSE a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)  \r\n"
			+ " 			 			         END  \r\n"
			+ " 			 			     ELSE 0  \r\n"
			+ " 			 			 END AS mslab6,  \r\n"
			+ " 			 			 CASE  \r\n"
			+ " 			 			     WHEN (DATEDIFF(date(?1),     \r\n"
			+ " 			 			           CASE WHEN ?5 = 'Due_Date' THEN a.duedate ELSE a.docdate END) >= 120)  \r\n"
			+ " 			 			     THEN  \r\n"
			+ " 			 			         CASE  \r\n"
			+ " 			 			             WHEN   \r\n"
			+ " 			 			                    (a.refno LIKE '%RT%' OR a.refno LIKE  '%PT%')  \r\n"
			+ " 			 			             THEN 0  \r\n"
			+ " 			 			             ELSE a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)  \r\n"
			+ " 			 			         END  \r\n"
			+ " 			 			     ELSE 0  \r\n"
			+ " 			 			 END AS mslab7,p.creditdays,p.creditlimit,a.orgid  \r\n"
			+ " 			 			                                       FROM arapdetails a  \r\n"
			+ " 			 			 LEFT JOIN arapadjustments r ON a.subledgercode = r.subledgercode AND a.docid = r.docid  \r\n"
			+ " 			 			 LEFT JOIN partymaster p ON a.subledgercode = p.partycode  \r\n"
			+ " 			 			 LEFT JOIN branch br ON a.branch = br.branch  \r\n"
			+ " 			 			 LEFT JOIN branch jbr ON a.branch = jbr.branch  \r\n"
			+ " 			 			                  WHERE  a.docdate <= STR_TO_DATE(?1, '%Y-%m-%d')   \r\n"
			+ " 			 			                     AND a.CANCEL = 'F'  \r\n"
			+ " 			 			                  AND (r.CANCEL = 'F' OR r.CANCEL IS NULL)  \r\n"
			+ " 			 			                    AND a.branch = jbr.branch  \r\n"
			+ " 			 			                    And P.PARTYTYPE ='CUSTOMER' and a.finyear =?6 \r\n"
			+ " 			 			 				   GROUP BY a.arapdetailsid,  \r\n"
			+ " 			 			                    partycode ,  \r\n"
			+ " 			 			                    partyname,  \r\n"
			+ " 			 			                    jbr.branchcode,  \r\n"
			+ " 			 			                    a.docid,  \r\n"
			+ " 			 			                    a.docdate,a.amount,  \r\n"
			+ " 			 			                    a.doctypecode,br.branch,  \r\n"
			+ " 			 			                    a.creditdays,p.creditlimit,  \r\n"
			+ " 			 			                    a.amount,a.finyear,  \r\n"
			+ " 			 			                    a.refno,  \r\n"
			+ " 			 			                    a.refdate,  \r\n"
			+ " 			 			                    a.duedate,  \r\n"
			+ " 			 			                    a.currency,  \r\n"
			+ " 			 			                    p.creditdays,p.creditdays,p.creditlimit,a.orgid  \r\n"
			+ " 			 			             HAVING (a.amount + COALESCE(SUM(COALESCE(r.amount, 0)), 0)) != 0  \r\n"
			+ " 			 			           ORDER BY docdate  \r\n"
			+ " 			 			                     )  \r\n"
			+ " 			 			                    SELECT 1 AS no, '' AS orgid, '' AS subledgercode, subledgername AS partyname, subledgername, '' AS partytype, '' AS branch,  \r\n"
			+ " 			 			                    '' AS currency, '' AS creditdays, '' AS creditlimit, '' AS amount, '' AS outstanding, '' AS unadjusted, '' AS totaldue \r\n"
			+ " 			 			                    FROM a where ( branch = ?3 or ?3 = 'ALL' )  \r\n"
			+ " 			 			                     and orgid =?4  \r\n"
			+ " 			 			                     and (subledgername = ?2 or ?2 = 'ALL' )  \r\n"
			+ " 			 			                     GROUP BY subledgername \r\n"
			+ " 			 UNION \r\n"
			+ " 			 SELECT 2 AS no, orgid, subledgercode, subledgername AS partyname, subledgername, partytype, branch, currency, creditdays, creditlimit, \r\n"
			+ " 			 SUM(amount) AS amount, SUM(outstanding) AS outstanding, SUM(unadjusted) AS unadjusted, SUM(totaldue) AS totaldue  \r\n"
			+ " 			 FROM a where  ( branch = ?3 or ?3 = 'ALL' )   \r\n"
			+ " 			 			                     and orgid =?4  \r\n"
			+ " 			 			                     and (subledgername = ?2 or ?2 = 'ALL' ) GROUP BY orgid, subledgercode, subledgername, partytype, branch, currency, creditdays, creditlimit \r\n"
			+ " 			 UNION \r\n"
			+ " 			 SELECT 3 AS no, '' AS orgid, '' AS subledgercode, subledgername AS partyname, 'Total' AS subledgername, '' AS partytype, '' AS branch,'' currency,'' creditdays, '' creditlimit, \r\n"
			+ " 			 SUM(amount) AS amount, SUM(outstanding) AS outstanding, SUM(unadjusted) AS unadjusted, SUM(totaldue) AS totaldue  \r\n"
			+ " 			 FROM a where ( branch = ?3 or ?3 = 'ALL' )   \r\n"
			+ " 			 			                     and orgid =?4  \r\n"
			+ " 			 			                     and (subledgername = ?2 or ?2 = 'ALL' ) GROUP BY subledgername, currency, creditdays, creditlimit \r\n"
			+ " 			 ORDER BY partyname, no")
	Set<Object[]> findArapAdjustments(String Asondate, String partyname, String branch, Long orgId,String pdate,Long finyear);
	
	@Query(nativeQuery = true,value =  "SELECT  orgid, \r\n"
 			+ "    arapdetailsid,\r\n"
 			+ "    doctypecode,\r\n"
 			+ "    branch,\r\n"
 			+ "    subledgercode,\r\n"
 			+ "    subledgername,\r\n"
 			+ "    partytype,\r\n"
 			+ "    subledgerdivision,\r\n"
 			+ "    currency,\r\n"
 			+ "    docid,\r\n"
 			+ "    docdate,\r\n"
 			+ "    supprefno,\r\n"
 			+ "    duedate,\r\n"
 			+ "    refno,\r\n"
 			+ "    refdate,\r\n"
 			+ "    amount,\r\n"
 			+ "    outstanding,\r\n"
 			+ "    totaldue,\r\n"
 			+ "    unadjusted,\r\n"
 			+ "    ddays,\r\n"
 			+ "    mslab1,\r\n"
 			+ "    mslab2,\r\n"
 			+ "    mslab3,\r\n"
 			+ "    mslab4,\r\n"
 			+ "    mslab5 + mslab6 + mslab7 AS mslab5,\r\n"
 			+ "    name\r\n"
 			+ "FROM (\r\n"
 			+ "    SELECT\r\n"
 			+ "        a.orgid,\r\n"
 			+ "        a.arapdetailsid,\r\n"
 			+ "        a.doctypecode,\r\n"
 			+ "        br.branch,\r\n"
 			+ "        p.partycode AS subledgercode,\r\n"
 			+ "        p.partyshortname AS name,\r\n"
 			+ "        p.partyname AS subledgername,\r\n"
 			+ "        'GST Party' AS Partytax,\r\n"
 			+ "        'GST Party' AS Partytype,\r\n"
 			+ "        a.subledgerdivision,\r\n"
 			+ "        'Base' AS currency,\r\n"
 			+ "        a.docid,\r\n"
 			+ "        a.docdate,\r\n"
 			+ "        a.supprefno,\r\n"
 			+ "        a.duedate,\r\n"
 			+ "        a.refno,\r\n"
 			+ "        a.refdate,\r\n"
 			+ "        a.amount,\r\n"
 			+ "        CASE\r\n"
 			+ "            WHEN ?3 = 'Due_Date' THEN a.duedate\r\n"
 			+ "            ELSE a.docdate\r\n"
 			+ "        END AS ddays,\r\n"
 			+ "        CASE\r\n"
 			+ "            WHEN a.doctypecode IN ('RC', 'PA') OR a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'\r\n"
 			+ "                THEN 0\r\n"
 			+ "            ELSE a.amount + IFNULL(SUM(IFNULL(r.amount, 0)), 0)\r\n"
 			+ "        END AS outstanding,\r\n"
 			+ "        a.amount + IFNULL(SUM(IFNULL(r.amount, 0)), 0) AS totaldue,\r\n"
 			+ "        CASE\r\n"
 			+ "            WHEN (a.doctypecode IN ('RC', 'PA')\r\n"
 			+ "                  OR a.refno LIKE '%CREC%'\r\n"
 			+ "                  OR a.refno LIKE '%CPAY%')\r\n"
 			+ "                 AND a.amount + IFNULL(SUM(IFNULL(r.amount, 0)), 0) <> 0\r\n"
 			+ "                THEN a.amount + IFNULL(SUM(IFNULL(r.amount, 0)), 0)\r\n"
 			+ "            ELSE 0\r\n"
 			+ "        END AS unadjusted,\r\n"
 			+ "        CASE\r\n"
 			+ "            WHEN DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'),\r\n"
 			+ "                          CASE WHEN ?3 = 'Due_Date' THEN a.duedate ELSE a.docdate END) < 30\r\n"
 			+ "                THEN\r\n"
 			+ "                    CASE\r\n"
 			+ "                        WHEN a.doctypecode IN ('RC', 'PA')\r\n"
 			+ "                             OR a.refno LIKE '%CREC%'\r\n"
 			+ "                             OR a.refno LIKE '%CPAY%'\r\n"
 			+ "                            THEN 0\r\n"
 			+ "                        ELSE a.amount + IFNULL(SUM(IFNULL(r.amount, 0)), 0)\r\n"
 			+ "                    END\r\n"
 			+ "            ELSE 0\r\n"
 			+ "        END AS mslab1,\r\n"
 			+ "        CASE\r\n"
 			+ "            WHEN DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'),\r\n"
 			+ "                          CASE WHEN ?3 = 'Due_Date' THEN a.duedate ELSE a.docdate END)\r\n"
 			+ "                 BETWEEN 30 AND 60\r\n"
 			+ "                THEN\r\n"
 			+ "                    CASE\r\n"
 			+ "                        WHEN a.doctypecode IN ('RC', 'PA')\r\n"
 			+ "                             OR a.refno LIKE '%CREC%'\r\n"
 			+ "                             OR a.refno LIKE '%CPAY%'\r\n"
 			+ "                            THEN 0\r\n"
 			+ "                        ELSE a.amount + IFNULL(SUM(IFNULL(r.amount, 0)), 0)\r\n"
 			+ "                    END\r\n"
 			+ "            ELSE 0\r\n"
 			+ "        END AS mslab2,\r\n"
 			+ "        CASE\r\n"
 			+ "            WHEN DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'),\r\n"
 			+ "                          CASE WHEN ?3 = 'Due_Date' THEN a.duedate ELSE a.docdate END)\r\n"
 			+ "                 BETWEEN 60 AND 90\r\n"
 			+ "                THEN\r\n"
 			+ "                    CASE\r\n"
 			+ "                        WHEN a.doctypecode IN ('RC', 'PA')\r\n"
 			+ "                             OR a.refno LIKE '%CREC%'\r\n"
 			+ "                             OR a.refno LIKE '%CPAY%'\r\n"
 			+ "                            THEN 0\r\n"
 			+ "                        ELSE a.amount + IFNULL(SUM(IFNULL(r.amount, 0)), 0)\r\n"
 			+ "                    END\r\n"
 			+ "            ELSE 0\r\n"
 			+ "        END AS mslab3,\r\n"
 			+ "        CASE\r\n"
 			+ "            WHEN DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'),\r\n"
 			+ "                          CASE WHEN ?3 = 'Due_Date' THEN a.duedate ELSE a.docdate END)\r\n"
 			+ "                 BETWEEN 90 AND 120\r\n"
 			+ "                THEN\r\n"
 			+ "                    CASE\r\n"
 			+ "                        WHEN a.doctypecode IN ('RC', 'PA')\r\n"
 			+ "                             OR a.refno LIKE '%CREC%'\r\n"
 			+ "                             OR a.refno LIKE '%CPAY%'\r\n"
 			+ "                            THEN 0\r\n"
 			+ "                        ELSE a.amount + IFNULL(SUM(IFNULL(r.amount, 0)), 0)\r\n"
 			+ "                    END\r\n"
 			+ "            ELSE 0\r\n"
 			+ "        END AS mslab4,\r\n"
 			+ "        CASE\r\n"
 			+ "            WHEN DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'),\r\n"
 			+ "                          CASE WHEN ?3 = 'Due_Date' THEN a.duedate ELSE a.docdate END)\r\n"
 			+ "                 BETWEEN 120 AND 150\r\n"
 			+ "                THEN\r\n"
 			+ "                    CASE\r\n"
 			+ "                        WHEN a.doctypecode IN ('RC', 'PA')\r\n"
 			+ "                             OR a.refno LIKE '%CREC%'\r\n"
 			+ "                             OR a.refno LIKE '%CPAY%'\r\n"
 			+ "                            THEN 0\r\n"
 			+ "                        ELSE a.amount + IFNULL(SUM(IFNULL(r.amount, 0)), 0)\r\n"
 			+ "                    END\r\n"
 			+ "            ELSE 0\r\n"
 			+ "        END AS mslab5,\r\n"
 			+ "        CASE\r\n"
 			+ "            WHEN DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'),\r\n"
 			+ "                          CASE WHEN ?3 = 'Due_Date' THEN a.duedate ELSE a.docdate END)\r\n"
 			+ "                 BETWEEN 180 AND 210\r\n"
 			+ "                THEN\r\n"
 			+ "                    CASE\r\n"
 			+ "                        WHEN a.doctypecode IN ('RC', 'PA')\r\n"
 			+ "                             OR a.refno LIKE '%CREC%'\r\n"
 			+ "                             OR a.refno LIKE '%CPAY%'\r\n"
 			+ "                            THEN 0\r\n"
 			+ "                        ELSE a.amount + IFNULL(SUM(IFNULL(r.amount, 0)), 0)\r\n"
 			+ "                    END\r\n"
 			+ "            ELSE 0\r\n"
 			+ "        END AS mslab6,\r\n"
 			+ "        CASE\r\n"
 			+ "            WHEN DATEDIFF(STR_TO_DATE(?1, '%Y-%m-%d'),\r\n"
 			+ "                          CASE WHEN ?3 = 'Due_Date' THEN a.duedate ELSE a.docdate END) >= 210\r\n"
 			+ "                THEN\r\n"
 			+ "                    CASE\r\n"
 			+ "                        WHEN a.doctypecode IN ('RC', 'PA')\r\n"
 			+ "                             OR a.refno LIKE '%CREC%'\r\n"
 			+ "                             OR a.refno LIKE '%CPAY%'\r\n"
 			+ "                            THEN 0\r\n"
 			+ "                        ELSE a.amount + IFNULL(SUM(IFNULL(r.amount, 0)), 0)\r\n"
 			+ "                    END\r\n"
 			+ "            ELSE 0\r\n"
 			+ "        END AS mslab7\r\n"
 			+ "        FROM arapdetails a\r\n"
 			+ "    LEFT JOIN arapadjustments r\r\n"
 			+ "        ON a.subledgercode = r.subledgercode\r\n"
 			+ "       AND a.docid        = r.docid\r\n"
 			+ "    JOIN branch br\r\n"
 			+ "        ON a.branch = br.branch\r\n"
 			+ "    JOIN partymaster p\r\n"
 			+ "        ON a.subledgercode = p.partycode\r\n"
 			+ "    WHERE\r\n"
 			+ "        a.docdate      <= ?1\r\n"
 			+ "        AND (r.docdate <= ?1 OR r.docdate IS NULL)\r\n"
 			+ "        AND a.CANCEL     = 'F'\r\n"
 			+ "        AND (r.CANCEL = 'F' OR r.CANCEL IS NULL)\r\n"
 			+ "        AND p.partytype NOT IN ('PARTNER', 'INTERCOMPANY', 'FX')\r\n"
 			+ "       -- AND p.accounttype ='PAYABLE'\r\n"
 			+ "        AND (\r\n"
 			+ "            LOWER(TRIM(p.partyname)) LIKE CONCAT('%', LOWER(TRIM(?2)), '%')\r\n"
 			+ "            OR LOWER(TRIM(?2)) = 'ALL'\r\n"
 			+ "        )\r\n"
 			+ "        AND a.orgid = ?4\r\n"
 			+ "    GROUP BY\r\n"
 			+ "        a.orgid,\r\n"
 			+ "        a.arapdetailsid,\r\n"
 			+ "        br.branch,\r\n"
 			+ "        p.partycode,\r\n"
 			+ "        p.partyname,\r\n"
 			+ "        p.partyshortname,\r\n"
 			+ "        partytax,\r\n"
 			+ "        partytype,\r\n"
 			+ "        a.subledgerdivision,\r\n"
 			+ "        a.currency,\r\n"
 			+ "        a.docid,\r\n"
 			+ "        a.docdate,\r\n"
 			+ "        a.supprefno,\r\n"
 			+ "        a.creditdays,\r\n"
 			+ "        a.amount,\r\n"
 			+ "        a.refno,\r\n"
 			+ "        a.refdate,\r\n"
 			+ "        a.hno,\r\n"
 			+ "        a.duedate,\r\n"
 			+ "        a.doctypecode\r\n"
 			+ "    HAVING (a.amount + IFNULL(SUM(IFNULL(r.amount, 0)), 0)) != 0) as a \r\n"
 			+ "")
	Set<Object[]> findAPAgenig(String Asondate, String partyname, String pdate, Long orgId);
 	
 	
 	@Query(nativeQuery = true,value = " WITH a AS (\r\n"
 			+ "			 SELECT a.arapdetailsid, \r\n"
 			+ "			                    br.branch, \r\n"
 			+ "			                    partycode as subledgercode, \r\n"
 			+ "			                    partyname as subledgername, \r\n"
 			+ "			                    jbr.branch jobbranch, \r\n"
 			+ "			                    a.docid, \r\n"
 			+ "			                    a.docdate, \r\n"
 			+ "			                    a.duedate, \r\n"
 			+ "			                    a.refno, \r\n"
 			+ "			                    a.refdate, a.currency,a.amount,A.finyear,p.PARTYTYPE, \r\n"
 			+ "			                    CASE  \r\n"
 			+ "			         WHEN  \r\n"
 			+ "			               (a.refno LIKE '%RT%' OR a.refno LIKE  '%PT%')  \r\n"
 			+ "			         THEN 0  \r\n"
 			+ "			         ELSE a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)  \r\n"
 			+ "			     END AS outstanding, \r\n"
 			+ "			     a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0) AS totaldue, \r\n"
 			+ "			     a.nativeamt AS bamount, \r\n"
 			+ "			    CASE \r\n"
 			+ "			     WHEN  \r\n"
 			+ "			            (a.refno LIKE '%RT%' OR a.refno LIKE  '%PT%') \r\n"
 			+ "			     THEN 0 \r\n"
 			+ "			     ELSE a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0) \r\n"
 			+ "			 END AS boutstanding, \r\n"
 			+ "			 (a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)) AS btotaldue, \r\n"
 			+ "			 a.nativeamt AS namount, \r\n"
 			+ "			 CASE \r\n"
 			+ "			     WHEN  \r\n"
 			+ "			            (a.refno LIKE '%RT%' OR a.refno LIKE  '%PT%') \r\n"
 			+ "			     THEN 0 \r\n"
 			+ "			     ELSE a.nativeamt + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0) \r\n"
 			+ "			 END AS noutstanding, \r\n"
 			+ "			 a.nativeamt + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0) AS ntotaldue , \r\n"
 			+ "			    CASE \r\n"
 			+ "			     WHEN  \r\n"
 			+ "			            (a.refno LIKE '%PT%' OR a.refno LIKE '%RT%') \r\n"
 			+ "			          AND (a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)) <> 0 \r\n"
 			+ "			     THEN a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0) \r\n"
 			+ "			     ELSE 0 \r\n"
 			+ "			 END AS unadjusted, \r\n"
 			+ "			 CASE \r\n"
 			+ "			     WHEN  \r\n"
 			+ "			            (a.refno LIKE '%RT%' OR a.refno LIKE  '%PT%') \r\n"
 			+ "			          AND (a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)) <> 0 \r\n"
 			+ "			     THEN a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0) \r\n"
 			+ "			     ELSE 0 \r\n"
 			+ "			 END AS bunadjusted, \r\n"
 			+ "			 CASE \r\n"
 			+ "			     WHEN  \r\n"
 			+ "			            (a.refno LIKE '%RT%' OR a.refno LIKE  '%PT%') \r\n"
 			+ "			          AND (a.nativeamt + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0)) <> 0 \r\n"
 			+ "			     THEN a.nativeamt + IFNULL(SUM(IFNULL(r.nativeamt, 0)),0) \r\n"
 			+ "			     ELSE 0 \r\n"
 			+ "			 END AS nunadjusted, \r\n"
 			+ "			     date(?1)AS asondt, \r\n"
 			+ "			 CASE  \r\n"
 			+ "			     WHEN ?5 = 'Due_Date' THEN a.duedate  \r\n"
 			+ "			     ELSE a.docdate  \r\n"
 			+ "			 END AS ddays, \r\n"
 			+ "			 CASE \r\n"
 			+ "			     WHEN  (DATEDIFF(date(?1),    \r\n"
 			+ "			           CASE WHEN ?5 = 'Due_Date' THEN a.duedate ELSE a.docdate END) < 30) \r\n"
 			+ "			     THEN \r\n"
 			+ "			         CASE \r\n"
 			+ "			             WHEN  \r\n"
 			+ "			                    (a.refno LIKE '%RT%' OR a.refno LIKE  '%PT%') \r\n"
 			+ "			             THEN 0 \r\n"
 			+ "			             ELSE a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0) \r\n"
 			+ "			         END \r\n"
 			+ "			     ELSE 0 \r\n"
 			+ "			 END AS mslab1, \r\n"
 			+ "			 CASE \r\n"
 			+ "			     WHEN (DATEDIFF(date(?1),    \r\n"
 			+ "			           CASE WHEN ?5 = 'Due_Date' THEN a.duedate ELSE a.docdate END) \r\n"
 			+ "			           BETWEEN 30 AND 45) \r\n"
 			+ "			     THEN \r\n"
 			+ "			         CASE \r\n"
 			+ "			             WHEN  \r\n"
 			+ "			                    (a.refno LIKE '%RT%' OR a.refno LIKE  '%PT%') \r\n"
 			+ "			             THEN 0 \r\n"
 			+ "			             ELSE a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0) \r\n"
 			+ "			         END \r\n"
 			+ "			     ELSE 0 \r\n"
 			+ "			 END AS mslab2, \r\n"
 			+ "			 CASE \r\n"
 			+ "			     WHEN (DATEDIFF(date(?1),    \r\n"
 			+ "			           CASE WHEN ?5 = 'Due_Date' THEN a.duedate ELSE a.docdate END) \r\n"
 			+ "			            BETWEEN 45 AND 60) \r\n"
 			+ "			     THEN \r\n"
 			+ "			         CASE \r\n"
 			+ "			             WHEN  \r\n"
 			+ "			                    (a.refno LIKE '%RT%' OR a.refno LIKE  '%PT%') \r\n"
 			+ "			             THEN 0 \r\n"
 			+ "			             ELSE a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0) \r\n"
 			+ "			         END \r\n"
 			+ "			     ELSE 0 \r\n"
 			+ "			 END AS mslab3, \r\n"
 			+ "			 CASE \r\n"
 			+ "			     WHEN(DATEDIFF(date(?1),    \r\n"
 			+ "			           CASE WHEN ?5 = 'Due_Date' THEN a.duedate ELSE a.docdate END) \r\n"
 			+ "			               BETWEEN 60 AND 90) \r\n"
 			+ "			     THEN \r\n"
 			+ "			         CASE \r\n"
 			+ "			             WHEN  \r\n"
 			+ "			                    (a.refno LIKE '%RT%' OR a.refno LIKE  '%PT%') \r\n"
 			+ "			             THEN 0 \r\n"
 			+ "			             ELSE a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0) \r\n"
 			+ "			         END \r\n"
 			+ "			     ELSE 0 \r\n"
 			+ "			 END AS mslab4, \r\n"
 			+ "			 CASE \r\n"
 			+ "			     WHEN (DATEDIFF(date(?1),    \r\n"
 			+ "			           CASE WHEN ?5 = 'Due_Date' THEN a.duedate ELSE a.docdate END) \r\n"
 			+ "			           BETWEEN 60 AND 105) \r\n"
 			+ "			     THEN \r\n"
 			+ "			         CASE \r\n"
 			+ "			             WHEN  \r\n"
 			+ "			                    (a.refno LIKE '%RT%' OR a.refno LIKE  '%PT%') \r\n"
 			+ "			             THEN 0 \r\n"
 			+ "			             ELSE a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0) \r\n"
 			+ "			         END \r\n"
 			+ "			     ELSE 0 \r\n"
 			+ "			 END AS mslab5, \r\n"
 			+ "			 CASE \r\n"
 			+ "			     WHEN (DATEDIFF(date(?1),    \r\n"
 			+ "			           CASE WHEN ?5 = 'Due_Date' THEN a.duedate ELSE a.docdate END) \r\n"
 			+ "			           BETWEEN 60 AND 120) \r\n"
 			+ "			     THEN \r\n"
 			+ "			         CASE \r\n"
 			+ "			             WHEN  \r\n"
 			+ "			                    (a.refno LIKE '%RT%' OR a.refno LIKE  '%PT%') \r\n"
 			+ "			             THEN 0 \r\n"
 			+ "			             ELSE a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0) \r\n"
 			+ "			         END \r\n"
 			+ "			     ELSE 0 \r\n"
 			+ "			 END AS mslab6, \r\n"
 			+ "			 CASE \r\n"
 			+ "			     WHEN (DATEDIFF(date(?1),    \r\n"
 			+ "			           CASE WHEN ?5 = 'Due_Date' THEN a.duedate ELSE a.docdate END) >= 120) \r\n"
 			+ "			     THEN \r\n"
 			+ "			         CASE \r\n"
 			+ "			             WHEN  \r\n"
 			+ "			                    (a.refno LIKE '%RT%' OR a.refno LIKE  '%PT%') \r\n"
 			+ "			             THEN 0 \r\n"
 			+ "			             ELSE a.amount + IFNULL(SUM(IFNULL(r.nativeamt, 0)), 0) \r\n"
 			+ "			         END \r\n"
 			+ "			     ELSE 0 \r\n"
 			+ "			 END AS mslab7,p.creditdays,p.creditlimit,a.orgid \r\n"
 			+ "			                                       FROM arapdetails a \r\n"
 			+ "			 LEFT JOIN arapadjustments r ON a.subledgercode = r.subledgercode AND a.docid = r.docid \r\n"
 			+ "			 LEFT JOIN partymaster p ON a.subledgercode = p.partycode \r\n"
 			+ "			 LEFT JOIN branch br ON a.branch = br.branch \r\n"
 			+ "			 LEFT JOIN branch jbr ON a.branch = jbr.branch \r\n"
 			+ "			                  WHERE  a.docdate <= STR_TO_DATE(?1, '%Y-%m-%d')  \r\n"
 			+ "			                     AND a.CANCEL = 'F' \r\n"
 			+ "			                  AND (r.CANCEL = 'F' OR r.CANCEL IS NULL) \r\n"
 			+ "			                    AND a.branch = jbr.branch \r\n"
 			+ "			                    And P.PARTYTYPE ='VENDOR' and a.finyear =?6\r\n"
 			+ "			 				   GROUP BY a.arapdetailsid, \r\n"
 			+ "			                    partycode , \r\n"
 			+ "			                    partyname, \r\n"
 			+ "			                    jbr.branchcode, \r\n"
 			+ "			                    a.docid, \r\n"
 			+ "			                    a.docdate,a.amount, \r\n"
 			+ "			                    a.doctypecode,br.branch, \r\n"
 			+ "			                    a.creditdays,p.creditlimit, \r\n"
 			+ "			                    a.amount,a.finyear, \r\n"
 			+ "			                    a.refno, \r\n"
 			+ "			                    a.refdate, \r\n"
 			+ "			                    a.duedate, \r\n"
 			+ "			                    a.currency, \r\n"
 			+ "			                    p.creditdays,p.creditdays,p.creditlimit,a.orgid \r\n"
 			+ "			             HAVING (a.amount + COALESCE(SUM(COALESCE(r.amount, 0)), 0)) != 0 \r\n"
 			+ "			           ORDER BY docdate \r\n"
 			+ "			                     ) \r\n"
 			+ "			                    SELECT 1 AS no, '' AS orgid, '' AS subledgercode, subledgername AS partyname, subledgername, '' AS partytype, '' AS branch, \r\n"
 			+ "			                    '' AS currency, '' AS creditdays, '' AS creditlimit, '' AS amount, '' AS outstanding, '' AS unadjusted, '' AS totaldue\r\n"
 			+ "			                    FROM a where ( branch = ?3 or ?3 = 'ALL' ) \r\n"
 			+ "			                     and orgid =?4 \r\n"
 			+ "			                     and (subledgername = ?2 or ?2 = 'ALL' ) \r\n"
 			+ "			                     GROUP BY subledgername\r\n"
 			+ "UNION\r\n"
 			+ "SELECT 2 AS no, orgid, subledgercode, subledgername AS partyname, subledgername, partytype, branch, currency, creditdays, creditlimit,\r\n"
 			+ "SUM(amount) AS amount, SUM(outstanding) AS outstanding, SUM(unadjusted) AS unadjusted, SUM(totaldue) AS totaldue \r\n"
 			+ "FROM a where  ( branch = ?3 or ?3 = 'ALL' )  \r\n"
 			+ "			                     and orgid =?4 \r\n"
 			+ "			                     and (subledgername = ?2 or ?2 = 'ALL' ) GROUP BY orgid, subledgercode, subledgername, partytype, branch, currency, creditdays, creditlimit\r\n"
 			+ "UNION\r\n"
 			+ "SELECT 3 AS no, '' AS orgid, '' AS subledgercode, subledgername AS partyname, 'Total' AS subledgername, '' AS partytype, '' AS branch,'' currency,'' creditdays, '' creditlimit,\r\n"
 			+ "SUM(amount) AS amount, SUM(outstanding) AS outstanding, SUM(unadjusted) AS unadjusted, SUM(totaldue) AS totaldue \r\n"
 			+ "FROM a where ( branch = ?3 or ?3 = 'ALL' )  \r\n"
 			+ "			                     and orgid =?4 \r\n"
 			+ "			                     and (subledgername = ?2 or ?2 = 'ALL' ) GROUP BY subledgername, currency, creditdays, creditlimit\r\n"
 			+ "ORDER BY partyname, no") 
 	Set<Object[]> findAPOutstanding(String Asondate, String partyname, String branch, Long orgId,String pdate,Long finyear);

 	
	@Query(nativeQuery = true, value = "select * from arapadjustments a where a.docid=?1  and a.refno=?2 and a.orgid=?3 and a.subledgercode=?4")
	ArapAdjustmentsVO findByDocIdAndRefNoAndOrgIdAndSubledgerCode(String docId,String refNo,Long orgId ,String subledgerCode);

// 	Optional<ArapAdjustmentsVO> findByUniqueKeys(String partyCode, String docId, LocalDate docDate, String refNo, LocalDate refDate);

}
