package com.base.basesetup.repo;

import java.util.List;
import java.util.Set;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;

import com.base.basesetup.entity.BudgetHeadCountVO;

public interface BudgetHeadCountRepo extends JpaRepository<BudgetHeadCountVO, Long> {

	@Query(nativeQuery = true,value = "select a.* from budgetheadcount a where a.orgid=?1 and a.clientcode=?2 and a.year=?3")
	List<BudgetHeadCountVO> getClientBudgetDls(Long org, String clientcode, String yr);

	@Query(nativeQuery = true,value = "WITH Months AS (\r\n"
			+ "    SELECT 'April' AS month UNION ALL\r\n"
			+ "    SELECT 'May' UNION ALL\r\n"
			+ "    SELECT 'June' UNION ALL\r\n"
			+ "    SELECT 'July' UNION ALL\r\n"
			+ "    SELECT 'August' UNION ALL\r\n"
			+ "    SELECT 'September' UNION ALL\r\n"
			+ "    SELECT 'October' UNION ALL\r\n"
			+ "    SELECT 'November' UNION ALL\r\n"
			+ "    SELECT 'December' UNION ALL\r\n"
			+ "    SELECT 'January' UNION ALL\r\n"
			+ "    SELECT 'February' UNION ALL\r\n"
			+ "    SELECT 'March'\r\n"
			+ "),\r\n"
			+ "Accounts AS (\r\n"
			+ "    select department,employmenttype,category,month,sum(headcount)headcount,sum(ctc)ctc from budgetheadcount where orgid=?1 and clientcode=?3 and year=?2 group by \r\n"
			+ "department,employmenttype,category,month\r\n"
			+ ")\r\n"
			+ "SELECT \r\n"
			+ "    a.department,a.employmenttype,a.category,\r\n"
			+ "    m.month, \r\n"
			+ "    b.headcount,b.ctc\r\n"
			+ "FROM Accounts a\r\n"
			+ "CROSS JOIN Months m \r\n"
			+ "left join budgetheadcount b\r\n"
			+ "    on b.orgid = ?1\r\n"
			+ "    AND b.year = ?2\r\n"
			+ "    AND b.clientcode = ?3\r\n"
			+ "    AND b.month = m.month and a.department=b.department\r\n"
			+ "    and a.employmenttype=b.employmenttype\r\n"
			+ "    and a.category=b.category \r\n"
			+ "GROUP BY \r\n"
			+ "    a.department,a.employmenttype,a.category,\r\n"
			+ "    m.month, \r\n"
			+ "    b.headcount,b.ctc,\r\n"
			+ "    FIELD(m.month, 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December', 'January', 'February', 'March')\r\n"
			+ "ORDER BY \r\n"
			+ "    FIELD(m.month, 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December', 'January', 'February', 'March')")
	Set<Object[]> getDetails(Long orgId, String year, String clientCode);
	
	
	@Query(nativeQuery = true, value = "SELECT \r\n"
			+ "    department,\r\n"
			+ "    category,\r\n"
			+ "    quater,\r\n"
			+ "    type,\r\n"
			+ "    SUM(bud) AS bud_total,\r\n"
			+ "    SUM(py)  AS py_total\r\n"
			+ "FROM (\r\n"
			+ "    -- ============================\r\n"
			+ "    -- Quarterly Data\r\n"
			+ "    -- ============================\r\n"
			+ "    SELECT \r\n"
			+ "        department, \r\n"
			+ "        category, \r\n"
			+ "        quater, \r\n"
			+ "        'Head Count' AS type, \r\n"
			+ "        headcount AS bud, \r\n"
			+ "        0 AS py\r\n"
			+ "    FROM budgetheadcount\r\n"
			+ "    WHERE orgid = ?1\r\n"
			+ "      AND clientcode = ?3\r\n"
			+ "      AND year = ?2\r\n"
			+ "      AND monthsequence % 3 = 0\r\n"
			+ "      AND LENGTH(employmenttype) > 0\r\n"
			+ "    \r\n"
			+ "    UNION ALL\r\n"
			+ "    \r\n"
			+ "    SELECT \r\n"
			+ "        department, \r\n"
			+ "        category, \r\n"
			+ "        quater, \r\n"
			+ "        'CTC' AS type, \r\n"
			+ "        SUM(ctc) AS bud, \r\n"
			+ "        0 AS py\r\n"
			+ "    FROM budgetheadcount\r\n"
			+ "    WHERE clientcode = ?3\r\n"
			+ "      AND year = ?2\r\n"
			+ "      AND LENGTH(employmenttype) > 0\r\n"
			+ "    GROUP BY department, category, quater\r\n"
			+ "\r\n"
			+ "    UNION ALL\r\n"
			+ "    \r\n"
			+ "    SELECT \r\n"
			+ "        department, \r\n"
			+ "        category, \r\n"
			+ "        quater, \r\n"
			+ "        'Head Count' AS type, \r\n"
			+ "        0 AS bud, \r\n"
			+ "        headcount AS py\r\n"
			+ "    FROM pyheadcount\r\n"
			+ "    WHERE orgid = ?1\r\n"
			+ "      AND clientcode = ?3\r\n"
			+ "      AND year = ?4\r\n"
			+ "      AND monthsequence % 3 = 0\r\n"
			+ "      AND LENGTH(employmenttype) > 0\r\n"
			+ "    \r\n"
			+ "    UNION ALL\r\n"
			+ "    \r\n"
			+ "    SELECT \r\n"
			+ "        department, \r\n"
			+ "        category, \r\n"
			+ "        quater, \r\n"
			+ "        'CTC' AS type, \r\n"
			+ "        0 AS bud, \r\n"
			+ "        SUM(ctc) AS py\r\n"
			+ "    FROM pyheadcount\r\n"
			+ "    WHERE orgid = ?1\r\n"
			+ "      AND clientcode = ?3\r\n"
			+ "      AND year = ?4\r\n"
			+ "      AND LENGTH(employmenttype) > 0\r\n"
			+ "    GROUP BY department, category, quater\r\n"
			+ "\r\n"
			+ "    -- ============================\r\n"
			+ "    -- Full Year Data\r\n"
			+ "    -- ============================\r\n"
			+ "    UNION ALL\r\n"
			+ "    \r\n"
			+ "    SELECT \r\n"
			+ "        department, \r\n"
			+ "        category, \r\n"
			+ "        'fullYear' AS quater, \r\n"
			+ "        'Head Count' AS type, \r\n"
			+ "        SUM(headcount) AS bud, \r\n"
			+ "        0 AS py\r\n"
			+ "    FROM budgetheadcount\r\n"
			+ "    WHERE orgid = ?1\r\n"
			+ "      AND clientcode = ?3\r\n"
			+ "      AND year = ?2\r\n"
			+ "      AND monthsequence % 3 = 0\r\n"
			+ "      AND LENGTH(employmenttype) > 0\r\n"
			+ "    GROUP BY department, category\r\n"
			+ "    \r\n"
			+ "    UNION ALL\r\n"
			+ "    \r\n"
			+ "    SELECT \r\n"
			+ "        department, \r\n"
			+ "        category, \r\n"
			+ "        'fullYear' AS quater, \r\n"
			+ "        'CTC' AS type, \r\n"
			+ "        SUM(ctc) AS bud, \r\n"
			+ "        0 AS py\r\n"
			+ "    FROM budgetheadcount\r\n"
			+ "    WHERE orgid = ?1 and clientcode = ?3\r\n"
			+ "      AND year = ?2\r\n"
			+ "      AND LENGTH(employmenttype) > 0\r\n"
			+ "    GROUP BY department, category\r\n"
			+ "\r\n"
			+ "    UNION ALL\r\n"
			+ "    \r\n"
			+ "    SELECT \r\n"
			+ "        department, \r\n"
			+ "        category, \r\n"
			+ "        'fullYear' AS quater, \r\n"
			+ "        'Head Count' AS type, \r\n"
			+ "        0 AS bud, \r\n"
			+ "        SUM(headcount) AS py\r\n"
			+ "    FROM pyheadcount\r\n"
			+ "    WHERE orgid = ?1\r\n"
			+ "      AND clientcode = ?3\r\n"
			+ "      AND year = ?4\r\n"
			+ "      AND monthsequence % 3 = 0\r\n"
			+ "      AND LENGTH(employmenttype) > 0\r\n"
			+ "    GROUP BY department, category\r\n"
			+ "    \r\n"
			+ "    UNION ALL\r\n"
			+ "    \r\n"
			+ "    SELECT \r\n"
			+ "        department, \r\n"
			+ "        category, \r\n"
			+ "        'fullYear' AS quater, \r\n"
			+ "        'CTC' AS type, \r\n"
			+ "        0 AS bud, \r\n"
			+ "        SUM(ctc) AS py\r\n"
			+ "    FROM pyheadcount\r\n"
			+ "    WHERE orgid = ?1\r\n"
			+ "      AND clientcode = ?3\r\n"
			+ "      AND year = ?4\r\n"
			+ "      AND LENGTH(employmenttype) > 0\r\n"
			+ "    GROUP BY department, category\r\n"
			+ ") combined\r\n"
			+ "GROUP BY department, category, quater, type\r\n"
			+ "ORDER BY department, category, quater, type")
	Set<Object[]> getELBudgetHCDetails(Long orgId, String finYear, String clientCode,
			String previousYear);

	@Query(nativeQuery = true, value = "SELECT \r\n"
			+ "    department,\r\n"
			+ "    category,\r\n"
			+ "    quater,\r\n"
			+ "    type,\r\n"
			+ "    SUM(py) AS py_total\r\n"
			+ "FROM (    \r\n"
			+ "    -- Quarterly Head Count\r\n"
			+ "    SELECT \r\n"
			+ "        department, \r\n"
			+ "        category, \r\n"
			+ "        quater, \r\n"
			+ "        'Head Count' AS type, \r\n"
			+ "        headcount AS py\r\n"
			+ "    FROM pyheadcount\r\n"
			+ "    WHERE orgid = ?1\r\n"
			+ "      AND clientcode = ?3\r\n"
			+ "      AND year = ?2\r\n"
			+ "      AND monthsequence % 3 = 0\r\n"
			+ "      AND LENGTH(employmenttype) > 0\r\n"
			+ "    \r\n"
			+ "    UNION ALL\r\n"
			+ "    \r\n"
			+ "    -- Quarterly CTC\r\n"
			+ "    SELECT \r\n"
			+ "        department, \r\n"
			+ "        category, \r\n"
			+ "        quater, \r\n"
			+ "        'CTC' AS type, \r\n"
			+ "        SUM(ctc) AS py\r\n"
			+ "    FROM pyheadcount\r\n"
			+ "    WHERE orgid = ?1\r\n"
			+ "      AND clientcode = ?3\r\n"
			+ "      AND year = ?2\r\n"
			+ "      AND LENGTH(employmenttype) > 0\r\n"
			+ "    GROUP BY department, category, quater\r\n"
			+ "\r\n"
			+ "    -- =====================\r\n"
			+ "    -- YTD\r\n"
			+ "    -- =====================\r\n"
			+ "    UNION ALL\r\n"
			+ "    \r\n"
			+ "    SELECT \r\n"
			+ "        department, \r\n"
			+ "        category, \r\n"
			+ "        'ytd' AS quater, \r\n"
			+ "        'Head Count' AS type, \r\n"
			+ "        SUM(headcount) AS py\r\n"
			+ "    FROM pyheadcount\r\n"
			+ "    WHERE orgid = ?1\r\n"
			+ "      AND clientcode = ?3\r\n"
			+ "      AND year = ?2\r\n"
			+ "      AND month = ?4\r\n"
			+ "      AND LENGTH(employmenttype) > 0\r\n"
			+ "    GROUP BY department, category\r\n"
			+ "    \r\n"
			+ "    UNION ALL\r\n"
			+ "    \r\n"
			+ "    SELECT \r\n"
			+ "        department, \r\n"
			+ "        category, \r\n"
			+ "        'ytd' AS quater, \r\n"
			+ "        'CTC' AS type, \r\n"
			+ "        SUM(ctc) AS py\r\n"
			+ "    FROM pyheadcount\r\n"
			+ "    WHERE orgid = ?1\r\n"
			+ "      AND clientcode = ?3\r\n"
			+ "      AND year = ?2\r\n"
			+ "      AND monthsequence <= (\r\n"
			+ "            SELECT MAX(monthsequence)\r\n"
			+ "            FROM pyheadcount\r\n"
			+ "            WHERE year = ?2\r\n"
			+ "              AND month = ?4\r\n"
			+ "              AND clientcode = ?3\r\n"
			+ "        )\r\n"
			+ "      AND LENGTH(employmenttype) > 0\r\n"
			+ "    GROUP BY department, category\r\n"
			+ "\r\n"
			+ "    -- ============================\r\n"
			+ "    -- Full Year Data\r\n"
			+ "    -- ============================\r\n"
			+ "    UNION ALL\r\n"
			+ "    \r\n"
			+ "    SELECT \r\n"
			+ "        department, \r\n"
			+ "        category, \r\n"
			+ "        'fullYear' AS quater, \r\n"
			+ "        'Head Count' AS type, \r\n"
			+ "        SUM(headcount) AS py\r\n"
			+ "    FROM pyheadcount\r\n"
			+ "    WHERE orgid = ?1\r\n"
			+ "      AND clientcode = ?3\r\n"
			+ "      AND year = ?2\r\n"
			+ "      AND monthsequence % 3 = 0\r\n"
			+ "      AND LENGTH(employmenttype) > 0\r\n"
			+ "    GROUP BY department, category\r\n"
			+ "    \r\n"
			+ "    UNION ALL\r\n"
			+ "    \r\n"
			+ "    SELECT \r\n"
			+ "        department, \r\n"
			+ "        category, \r\n"
			+ "        'fullYear' AS quater, \r\n"
			+ "        'CTC' AS type, \r\n"
			+ "        SUM(ctc) AS py\r\n"
			+ "    FROM budgetheadcount\r\n"
			+ "    WHERE orgid = ?1\r\n"
			+ "      AND clientcode = ?3\r\n"
			+ "      AND year = ?2\r\n"
			+ "      AND LENGTH(employmenttype) > 0\r\n"
			+ "    GROUP BY department, category\r\n"
			+ ") combined\r\n"
			+ "GROUP BY department, category, quater, type\r\n"
			+ "ORDER BY department, category, quater, type")
	Set<Object[]> getELPyHCDetails(Long orgId, String previousYear, String clientCode,String month);
}
