package com.base.basesetup.repo;

import java.util.List;
import java.util.Set;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.transaction.annotation.Transactional;

import com.base.basesetup.entity.BudgetVO;

public interface BudgetRepo extends JpaRepository<BudgetVO, Long> {

	@Query(nativeQuery = true, value = "SELECT \r\n"
			+ "    ROW_NUMBER() OVER (ORDER BY accountcode) AS `ELGLS.No`,\r\n"
			+ "    accountname AS `ELGL`,\r\n"
			+ "    accountcode AS `ELGLCode`,\r\n"
			+ "    natureofaccount AS `NLDN/CR`,\r\n"
			+ "    MAX(CASE WHEN month = 'January' THEN amount ELSE 0 END) AS 'January',\r\n"
			+ "    MAX(CASE WHEN month = 'February' THEN amount ELSE 0 END) AS 'February',\r\n"
			+ "    MAX(CASE WHEN month = 'March' THEN amount ELSE 0 END) AS 'March',\r\n"
			+ "    MAX(CASE WHEN month = 'April' THEN amount ELSE 0 END) AS 'April',\r\n"
			+ "    MAX(CASE WHEN month = 'May' THEN amount ELSE 0 END) AS 'May',\r\n"
			+ "    MAX(CASE WHEN month = 'June' THEN amount ELSE 0 END) AS 'June',\r\n"
			+ "    MAX(CASE WHEN month = 'July' THEN amount ELSE 0 END) AS 'July',\r\n"
			+ "    MAX(CASE WHEN month = 'August' THEN amount ELSE 0 END) AS 'August',\r\n"
			+ "    MAX(CASE WHEN month = 'September' THEN amount ELSE 0 END) AS 'September',\r\n"
			+ "    MAX(CASE WHEN month = 'October' THEN amount ELSE 0 END) AS 'October',\r\n"
			+ "    MAX(CASE WHEN month = 'November' THEN amount ELSE 0 END) AS 'November',\r\n"
			+ "    MAX(CASE WHEN month = 'December' THEN amount ELSE 0 END) AS 'December'\r\n"
			+ "FROM budget where year=?2 and orgid=?1 and client=?3 and clientcode=?4 \r\n"
			+ "GROUP BY accountname, accountcode, natureofaccount\r\n"
			+ "ORDER BY accountcode")
	Set<Object[]> getClientBudgetDetails(Long orgId, String year, String client, String clientCode);

	@Query(nativeQuery = true,value = "select * from budget where orgid=?1 and clientcode=?2 and year=?3 and month=?4 and maingroup=?5 and subgroupcode=?6 and accountcode=?7")
	BudgetVO getBudgetDetails(Long orgId, String clientCode, String year, String month, String mainGroup,
			String subGroupCode, String accountCode);

	@Query(nativeQuery = true,value = "select g.maingroup,g.subgroup,g.subgroupcode,g.accountcode,g.accountname,g.natureofaccount,g.quater,sum(g.currentYear)currentYear,sum(g.previousYear)previousYear from(\r\n"
			+ "select maingroup,subgroup,subgroupcode,accountcode,accountname,natureofaccount,quater,sum(amount) currentYear,0 previousYear from budget where orgid=?1 and clientcode=?4 and year=?2\r\n"
			+ "group by maingroup,subgroup,subgroupcode,accountcode,natureofaccount,accountname,quater \r\n"
			+ "union\r\n"
			+ "select maingroup,subgroup,subgroupcode,accountcode,accountname,natureofaccount,quater,0 currentYear,sum(amount)previousYear from previousyearactual where orgid=?1 and clientcode=?4 and year=?3\r\n"
			+ "group by maingroup,subgroup,natureofaccount,subgroupcode,accountcode,accountname,quater) g JOIN groupledgers gl ON g.accountname = gl.accountname and gl.groupname=?5 and g.maingroup=?5 and (g.subgroup=?6 or 'ALL'=?6) group by g.maingroup,g.subgroup,g.natureofaccount,g.subgroupcode,g.accountcode,g.accountname,g.quater,gl.displayseq  \r\n"
			+ "ORDER BY cast(gl.displayseq as unsigned), g.quater asc")
	Set<Object[]> getELBudgetDetails(Long orgId, String finyear, String previousYear, String clientCode,
			String mainGroupName, String subGroupCode);

	@Query(nativeQuery = true,value = "SELECT \r\n"
			+ "    a.maingroup,\r\n"
			+ "    a.subgroup,\r\n"
			+ "    a.subgroupcode,\r\n"
			+ "    a.accountcode,\r\n"
			+ "    a.accountname,\r\n"
			+ "    a.natureofaccount,\r\n"
			+ "    ROUND(SUM(a.budget), 2) AS budget,\r\n"
			+ "    ROUND(SUM(a.actual), 2) AS actual,\r\n"
			+ "    ROUND(SUM(a.PY), 2) AS PY,\r\n"
			+ "    ROUND(SUM(a.budgetYTD), 2) AS budgetYTD,\r\n"
			+ "    ROUND(SUM(a.ActYTD), 2) AS ActYTD,\r\n"
			+ "    ROUND(SUM(a.PyYTD), 2) AS PyYTD,\r\n"
			+ "    ROUND(SUM(a.fullBudget), 2) AS fullBudget,\r\n"
			+ "    ROUND(\r\n"
			+ "        (SUM(a.ActYTD) / \r\n"
			+ "        (SELECT monthsequence FROM budget WHERE year=?3 AND month=?5 GROUP BY monthsequence) * 12),\r\n"
			+ "        2\r\n"
			+ "    ) AS Estimate,\r\n"
			+ "    ROUND(SUM(a.fullPY), 2) AS fullPY,gl.displayseq\r\n"
			+ "FROM (\r\n"
			+ "    select maingroup,subgroup,subgroupcode,accountcode,accountname,natureofaccount,sum(amount) budget,0 actual,0 PY,0 budgetYTD,0 ActYTD,0 PyYTD,0 fullBudget,0 fullPY from budget where orgid=?1 and clientcode=?2 and year=?3 and month=?5\r\n"
			+ "group by maingroup,subgroup,subgroupcode,accountcode,natureofaccount,accountname \r\n"
			+ "union\r\n"
			+ "select maingroup,subgroup,subgroupcode,accountcode,accountname,natureofaccount,0 budget,sum(amount)actual,0 PY,0 budgetYTD,0 ActYTD,0 PyYTD,0 fullBudget,0 fullPY from previousyearactual where orgid=?1 and clientcode=?2 and year=?3 and month=?5  group by maingroup,subgroup,natureofaccount,subgroupcode,accountcode,accountname\r\n"
			+ "union\r\n"
			+ "select maingroup,subgroup,subgroupcode,accountcode,accountname,natureofaccount,0 budget,0 actual,sum(amount)PY,0 budgetYTD,0 ActYTD,0 PyYTD,0 fullBudget,0 fullPY from previousyearactual where orgid=?1 and clientcode=?2 and year=?4 and month=?5  group by maingroup,subgroup,natureofaccount,subgroupcode,accountcode,accountname\r\n"
			+ "union\r\n"
			+ "select maingroup,subgroup,subgroupcode,accountcode,accountname,natureofaccount,0 budget,0 actual,0 PY,sum(amount)budgetYTD,0 ActYTD,0 PyYTD,0 fullBudget,0 fullPY from budget where orgid=?1 and clientcode=?2 and year=?3  and monthsequence<=(select monthsequence from budget where year=?3 and month=?5 group by monthsequence)\r\n"
			+ "group by maingroup,subgroup,subgroupcode,accountcode,natureofaccount,accountname,quater\r\n"
			+ "union\r\n"
			+ "select maingroup,subgroup,subgroupcode,accountcode,accountname,natureofaccount,0 budget,0 actual,0 PY,0 budgetYTD,sum(amount) ActYTD,0 PyYTD,0 fullBudget,0 fullPY from previousyearactual where orgid=?1 and clientcode=?2 and year=?3 and monthsequence<=(select monthsequence from previousyearactual where year=?3 and month=?5 group by monthsequence)\r\n"
			+ "group by maingroup,subgroup,subgroupcode,accountcode,accountname,natureofaccount\r\n"
			+ "union\r\n"
			+ "select maingroup,subgroup,subgroupcode,accountcode,accountname,natureofaccount,0 budget,0 actual,0 PY,0 budgetYTD,0 ActYTD,sum(amount) PyYTD,0 fullBudget,0 fullPY from previousyearactual where orgid=?1 and clientcode=?2 and year=?4 and monthsequence<=(select monthsequence from previousyearactual where year=?4 and month=?5 group by monthsequence)\r\n"
			+ "group by maingroup,subgroup,subgroupcode,accountcode,accountname,natureofaccount\r\n"
			+ "union\r\n"
			+ "select maingroup,subgroup,subgroupcode,accountcode,accountname,natureofaccount,0 budget,0 actual,0 PY,0 budgetYTD,0 ActYTD,0 PyYTD,sum(amount)fullBudget,0 fullPY from budget a where a.orgid=?1 and a.clientcode=?2 and a.year=?3\r\n"
			+ "group by maingroup,subgroup,subgroupcode,accountcode,accountname,natureofaccount\r\n"
			+ "union\r\n"
			+ "select maingroup,subgroup,subgroupcode,accountcode,accountname,natureofaccount,0 budget,0 actual,0 PY,0 budgetYTD,0 ActYTD,0 PyYTD,0 fullBudget,sum(amount) fullPY from previousyearactual a where a.orgid=?1 and a.clientcode=?2 and a.year=?4\r\n"
			+ "group by maingroup,subgroup,subgroupcode,accountcode,accountname,natureofaccount\r\n"
			+ ") a   JOIN groupledgers gl ON a.accountname = gl.accountname and gl.groupname=?6  and a.maingroup=?6 and (a.subgroup=?7 or 'ALL'=?7)\r\n"
			+ "GROUP BY \r\n"
			+ "    a.maingroup,\r\n"
			+ "    a.subgroup,\r\n"
			+ "    a.subgroupcode,\r\n"
			+ "    a.accountcode,\r\n"
			+ "    a.accountname,\r\n"
			+ "    a.natureofaccount,gl.displayseq ORDER BY cast(gl.displayseq as unsigned) ASC")
	Set<Object[]> getELActualDetails(Long orgId, String clientCode, String finyear, String previousYear, String month,
			String mainGroupName, String subGroupCode);
	
	@Query(nativeQuery = true, value = "WITH Accounts AS (\r\n"
			+ "    SELECT \r\n"
			+ "        a.displayseq, \r\n"
			+ "        a.accountname,\r\n"
			+ "        a.accountcode,\r\n"
			+ "        a.subgroupname,\r\n"
			+ "        a.subgroupcode\r\n"
			+ "    FROM groupledgers a\r\n"
			+ "    JOIN groupmapping b ON a.groupmappingid = b.groupmappingid\r\n"
			+ "    WHERE b.groupname = ?4\r\n"
			+ "      AND a.active = 1\r\n"
			+ "    GROUP BY a.accountname, a.displayseq, a.accountcode, a.subgroupname, a.subgroupcode\r\n"
			+ ")\r\n"
			+ "SELECT\r\n"
			+ "    h.accountcode,\r\n"
			+ "    h.accountname,\r\n"
			+ "    ROUND(SUM(h.budget), 2) AS budget,\r\n"
			+ "    ROUND(SUM(h.actual), 2) AS actual,\r\n"
			+ "    ROUND(SUM(h.PY), 2) AS PY,\r\n"
			+ "    ROUND(SUM(h.budgetYTD), 2) AS budgetYTD,\r\n"
			+ "    ROUND(SUM(h.ActYTD), 2) AS ActYTD,\r\n"
			+ "    ROUND(SUM(h.PyYTD), 2) AS PyYTD,\r\n"
			+ "    ROUND(SUM(h.fullBudget), 2) AS fullBudget,\r\n"
			+ "    ROUND(\r\n"
			+ "        (SUM(h.ActYTD) /\r\n"
			+ "         (SELECT monthsequence FROM budget WHERE year = ?2 AND month = ?5 GROUP BY monthsequence) * 12),\r\n"
			+ "        2\r\n"
			+ "    ) AS Estimate,\r\n"
			+ "    ROUND(SUM(h.fullPY), 2) AS fullPY\r\n"
			+ "FROM (\r\n"
			+ "-- budget\r\n"
			+ "SELECT b.maingroup, b.subgroup, b.subgroupcode, acc.accountcode, acc.accountname, b.natureofaccount,\r\n"
			+ "       SUM(b.amount) budget, 0 actual, 0 PY, 0 budgetYTD, 0 ActYTD, 0 PyYTD, 0 fullBudget, 0 fullPY,\r\n"
			+ "       acc.displayseq AS display_sequence\r\n"
			+ "FROM  Accounts acc\r\n"
			+ "LEFT JOIN automation h ON h.maingroupname = ?4\r\n"
			+ "LEFT JOIN automationdetails j ON h.automationid = j.automationid\r\n"
			+ "LEFT JOIN budget b \r\n"
			+ "    ON acc.accountname = h.subheading\r\n"
			+ "    AND b.accountname = j.accountname\r\n"
			+ "    AND j.accountname = b.accountname\r\n"
			+ "    AND j.maingroup = b.maingroup\r\n"
			+ "    AND j.subgroup = b.subgroup\r\n"
			+ "    AND b.year = ?2\r\n"
			+ "    AND b.orgid = ?1\r\n"
			+ "    AND b.clientcode = ?3 AND  b.month = ?5 \r\n"
			+ "GROUP BY b.maingroup, b.subgroup, b.subgroupcode, acc.accountcode, acc.accountname, b.natureofaccount, acc.displayseq\r\n"
			+ "\r\n"
			+ "UNION\r\n"
			+ "\r\n"
			+ "-- actual\r\n"
			+ "SELECT b.maingroup, b.subgroup, b.subgroupcode, acc.accountcode, acc.accountname, b.natureofaccount,\r\n"
			+ "       0 budget, SUM(b.amount) actual, 0 PY, 0 budgetYTD, 0 ActYTD, 0 PyYTD, 0 fullBudget, 0 fullPY,\r\n"
			+ "       acc.displayseq AS display_sequence\r\n"
			+ "FROM  Accounts acc\r\n"
			+ "LEFT JOIN automation h ON h.maingroupname = ?4\r\n"
			+ "LEFT JOIN automationdetails j ON h.automationid = j.automationid\r\n"
			+ "LEFT JOIN previousyearactual b \r\n"
			+ "    ON acc.accountname = h.subheading\r\n"
			+ "    AND b.accountname = j.accountname\r\n"
			+ "    AND j.accountname = b.accountname\r\n"
			+ "    AND j.maingroup = b.maingroup\r\n"
			+ "    AND j.subgroup = b.subgroup\r\n"
			+ "    AND b.year = ?2\r\n"
			+ "    AND b.orgid = ?1\r\n"
			+ "    AND b.clientcode = ?3 AND  b.month = ?5 \r\n"
			+ "GROUP BY b.maingroup, b.subgroup, b.subgroupcode, acc.accountcode, acc.accountname, b.natureofaccount, acc.displayseq\r\n"
			+ "\r\n"
			+ "UNION\r\n"
			+ "\r\n"
			+ "-- PY\r\n"
			+ "SELECT b.maingroup, b.subgroup, b.subgroupcode, acc.accountcode, acc.accountname, b.natureofaccount,\r\n"
			+ "       0 budget, 0 actual, SUM(b.amount) PY, 0 budgetYTD, 0 ActYTD, 0 PyYTD, 0 fullBudget, 0 fullPY,\r\n"
			+ "       acc.displayseq AS display_sequence\r\n"
			+ "FROM  Accounts acc\r\n"
			+ "LEFT JOIN automation h ON h.maingroupname = ?4\r\n"
			+ "LEFT JOIN automationdetails j ON h.automationid = j.automationid\r\n"
			+ "LEFT JOIN previousyearactual b \r\n"
			+ "    ON acc.accountname = h.subheading\r\n"
			+ "    AND b.accountname = j.accountname\r\n"
			+ "    AND j.accountname = b.accountname\r\n"
			+ "    AND j.maingroup = b.maingroup\r\n"
			+ "    AND j.subgroup = b.subgroup\r\n"
			+ "    AND b.year = ?6\r\n"
			+ "    AND b.orgid = ?1\r\n"
			+ "    AND b.clientcode = ?3 AND  b.month = ?5 \r\n"
			+ "GROUP BY b.maingroup, b.subgroup, b.subgroupcode, acc.accountcode, acc.accountname, b.natureofaccount, acc.displayseq\r\n"
			+ "\r\n"
			+ "UNION\r\n"
			+ "\r\n"
			+ "-- budget YTD\r\n"
			+ "SELECT b.maingroup, b.subgroup, b.subgroupcode, acc.accountcode, acc.accountname, b.natureofaccount,\r\n"
			+ "       0 budget, 0 actual, 0 PY, SUM(b.amount) budgetYTD, 0 ActYTD, 0 PyYTD, 0 fullBudget, 0 fullPY,\r\n"
			+ "       acc.displayseq AS display_sequence\r\n"
			+ "FROM  Accounts acc\r\n"
			+ "LEFT JOIN automation h ON h.maingroupname = ?4\r\n"
			+ "LEFT JOIN automationdetails j ON h.automationid = j.automationid\r\n"
			+ "LEFT JOIN budget b \r\n"
			+ "    ON acc.accountname = h.subheading\r\n"
			+ "    AND b.accountname = j.accountname\r\n"
			+ "    AND j.accountname = b.accountname\r\n"
			+ "    AND j.maingroup = b.maingroup\r\n"
			+ "    AND j.subgroup = b.subgroup\r\n"
			+ "    AND b.year = ?2\r\n"
			+ "    AND b.orgid = ?1\r\n"
			+ "    AND b.clientcode = ?3 AND b.monthsequence <= (\r\n"
			+ "              SELECT monthsequence FROM budget WHERE year = ?2 AND month = ?5 GROUP BY monthsequence\r\n"
			+ "          )\r\n"
			+ "GROUP BY b.maingroup, b.subgroup, b.subgroupcode, acc.accountcode, acc.accountname, b.natureofaccount, acc.displayseq\r\n"
			+ "\r\n"
			+ "UNION\r\n"
			+ "\r\n"
			+ "-- Act YTD\r\n"
			+ "SELECT b.maingroup, b.subgroup, b.subgroupcode, acc.accountcode, acc.accountname, b.natureofaccount,\r\n"
			+ "       0 budget, 0 actual, 0 PY, 0 budgetYTD, SUM(b.amount) ActYTD, 0 PyYTD, 0 fullBudget, 0 fullPY,\r\n"
			+ "       acc.displayseq AS display_sequence\r\n"
			+ "FROM  Accounts acc\r\n"
			+ "LEFT JOIN automation h ON h.maingroupname = ?4\r\n"
			+ "LEFT JOIN automationdetails j ON h.automationid = j.automationid\r\n"
			+ "LEFT JOIN previousyearactual b \r\n"
			+ "    ON acc.accountname = h.subheading\r\n"
			+ "    AND b.accountname = j.accountname\r\n"
			+ "    AND j.accountname = b.accountname\r\n"
			+ "    AND j.maingroup = b.maingroup\r\n"
			+ "    AND j.subgroup = b.subgroup\r\n"
			+ "    AND b.year = ?2\r\n"
			+ "    AND b.orgid = ?1\r\n"
			+ "    AND b.clientcode = ?3 AND b.monthsequence <= (\r\n"
			+ "              SELECT monthsequence FROM previousyearactual WHERE year = ?2 AND month = ?5 GROUP BY monthsequence\r\n"
			+ "          )\r\n"
			+ "GROUP BY b.maingroup, b.subgroup, b.subgroupcode, acc.accountcode, acc.accountname, b.natureofaccount, acc.displayseq\r\n"
			+ "\r\n"
			+ "UNION\r\n"
			+ "\r\n"
			+ "-- PY YTD\r\n"
			+ "SELECT b.maingroup, b.subgroup, b.subgroupcode, acc.accountcode, acc.accountname, b.natureofaccount,\r\n"
			+ "       0 budget, 0 actual, 0 PY, 0 budgetYTD, 0 ActYTD, SUM(b.amount) PyYTD, 0 fullBudget, 0 fullPY,\r\n"
			+ "       acc.displayseq AS display_sequence\r\n"
			+ "FROM  Accounts acc\r\n"
			+ "LEFT JOIN automation h ON h.maingroupname = ?4\r\n"
			+ "LEFT JOIN automationdetails j ON h.automationid = j.automationid\r\n"
			+ "LEFT JOIN previousyearactual b \r\n"
			+ "    ON acc.accountname = h.subheading\r\n"
			+ "    AND b.accountname = j.accountname\r\n"
			+ "    AND j.accountname = b.accountname\r\n"
			+ "    AND j.maingroup = b.maingroup\r\n"
			+ "    AND j.subgroup = b.subgroup\r\n"
			+ "    AND b.year = ?6\r\n"
			+ "    AND b.orgid = ?1\r\n"
			+ "    AND b.clientcode = ?3  AND b.monthsequence <= (\r\n"
			+ "              SELECT monthsequence FROM previousyearactual WHERE year = ?6 AND month = ?5 GROUP BY monthsequence\r\n"
			+ "          ) \r\n"
			+ "GROUP BY b.maingroup, b.subgroup, b.subgroupcode, acc.accountcode, acc.accountname, b.natureofaccount, acc.displayseq\r\n"
			+ "\r\n"
			+ "UNION\r\n"
			+ "\r\n"
			+ "-- full budget\r\n"
			+ "SELECT b.maingroup, b.subgroup, b.subgroupcode, acc.accountcode, acc.accountname, b.natureofaccount,\r\n"
			+ "       0 budget, 0 actual, 0 PY, 0 budgetYTD, 0 ActYTD, 0 PyYTD, SUM(b.amount) fullBudget, 0 fullPY,\r\n"
			+ "       acc.displayseq AS display_sequence\r\n"
			+ "FROM  Accounts acc\r\n"
			+ "LEFT JOIN automation h ON h.maingroupname = ?4\r\n"
			+ "LEFT JOIN automationdetails j ON h.automationid = j.automationid\r\n"
			+ "LEFT JOIN budget b \r\n"
			+ "    ON acc.accountname = h.subheading\r\n"
			+ "    AND b.accountname = j.accountname\r\n"
			+ "    AND j.accountname = b.accountname\r\n"
			+ "    AND j.maingroup = b.maingroup\r\n"
			+ "    AND j.subgroup = b.subgroup\r\n"
			+ "    AND b.year = ?2\r\n"
			+ "    AND b.orgid = ?1\r\n"
			+ "    AND b.clientcode = ?3\r\n"
			+ "GROUP BY b.maingroup, b.subgroup, b.subgroupcode, acc.accountcode, acc.accountname, b.natureofaccount, acc.displayseq\r\n"
			+ "\r\n"
			+ "UNION\r\n"
			+ "\r\n"
			+ "-- full PY\r\n"
			+ "SELECT b.maingroup, b.subgroup, b.subgroupcode, acc.accountcode, acc.accountname, b.natureofaccount,\r\n"
			+ "       0 budget, 0 actual, 0 PY, 0 budgetYTD, 0 ActYTD, 0 PyYTD, 0 fullBudget, SUM(b.amount) fullPY,\r\n"
			+ "       acc.displayseq AS display_sequence\r\n"
			+ "FROM  Accounts acc\r\n"
			+ "LEFT JOIN automation h ON h.maingroupname = ?4\r\n"
			+ "LEFT JOIN automationdetails j ON h.automationid = j.automationid\r\n"
			+ "LEFT JOIN previousyearactual b \r\n"
			+ "    ON acc.accountname = h.subheading\r\n"
			+ "    AND b.accountname = j.accountname\r\n"
			+ "    AND j.accountname = b.accountname\r\n"
			+ "    AND j.maingroup = b.maingroup\r\n"
			+ "    AND j.subgroup = b.subgroup\r\n"
			+ "    AND b.year = ?6\r\n"
			+ "    AND b.orgid = ?1\r\n"
			+ "    AND b.clientcode = ?3 \r\n"
			+ "GROUP BY b.maingroup, b.subgroup, b.subgroupcode, acc.accountcode, acc.accountname, b.natureofaccount, acc.displayseq \r\n"
			+ "ORDER BY CAST(display_sequence AS UNSIGNED)\r\n"
			+ ") h\r\n"
			+ "WHERE h.accountname IS NOT NULL\r\n"
			+ "GROUP BY h.accountcode, h.accountname")
	Set<Object[]> getELActualDetailsAutomatic(Long orgId,String finyear, String clientCode,String mainGroupName, String month, String previousYear);

	@Query(nativeQuery = true,value = "select a.* from budget a where a.orgid=?1 and a.clientcode=?2 and a.year=?3 and a.maingroup=?4 and a.subgroup=?5")
	List<BudgetVO> getClientBudgetDls(Long orgId, String clientCode, String year, String mainGroup, String subGroup);


	@Query(nativeQuery = true,value = "WITH Months AS (\r\n"
			+ "    SELECT 'April' AS month UNION ALL\r\n"
			+ "    SELECT 'May' UNION ALL\r\n"
			+ "    SELECT 'June' UNION ALL\r\n"
			+ "    SELECT 'July' UNION ALL\r\n"
			+ "    SELECT 'August' UNION ALL\r\n"
			+ "    SELECT 'September' UNION ALL\r\n"
			+ "    SELECT 'October' UNION ALL\r\n"
			+ "    SELECT 'November' UNION ALL\r\n"
			+ "    SELECT 'December' UNION ALL\r\n"
			+ "    SELECT 'January' UNION ALL\r\n"
			+ "    SELECT 'February' UNION ALL\r\n"
			+ "    SELECT 'March'\r\n"
			+ "),\r\n"
			+ "Accounts AS (\r\n"
			+ "    SELECT \r\n"
			+ "        a.displayseq, \r\n"
			+ "        a.accountname,\r\n"
			+ "        a.accountcode,\r\n"
			+ "        a.subgroupname,\r\n"
			+ "        a.subgroupcode\r\n"
			+ "    FROM groupledgers a\r\n"
			+ "    JOIN groupmapping b ON a.groupmappingid = b.groupmappingid\r\n"
			+ "    WHERE b.groupname = ?4\r\n"
			+ "      AND a.active = 1\r\n"
			+ "    GROUP BY a.accountname, a.displayseq, a.accountcode, a.subgroupname, a.subgroupcode\r\n"
			+ ")\r\n"
			+ "SELECT \r\n"
			+ "    acc.accountcode,\r\n"
			+ "    acc.accountname,\r\n"
			+ "    m.month,\r\n"
			+ "    SUM(b.amount) AS total_amount\r\n"
			+ "FROM Months m\r\n"
			+ "CROSS JOIN Accounts acc\r\n"
			+ "LEFT JOIN automation h ON h.maingroupname = ?4\r\n"
			+ "LEFT JOIN automationdetails j ON h.automationid = j.automationid\r\n"
			+ "LEFT JOIN budget b \r\n"
			+ "    ON acc.accountname = h.subheading\r\n"
			+ "    AND b.accountname=j.accountname\r\n"
			+ "    AND j.accountname = b.accountname\r\n"
			+ "    AND j.maingroup = b.maingroup\r\n"
			+ "    AND j.subgroup = b.subgroup\r\n"
			+ "    AND b.month = m.month\r\n"
			+ "    AND b.year = ?2\r\n"
			+ "    AND b.orgid = ?1\r\n"
			+ "    AND b.clientcode = ?3\r\n"
			+ "GROUP BY acc.accountname, acc.accountcode, m.month, acc.displayseq\r\n"
			+ "ORDER BY \r\n"
			+ "    CAST(acc.displayseq AS UNSIGNED),\r\n"
			+ "    FIELD(m.month, 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December', 'January', 'February', 'March')")
	Set<Object[]> getBudgetDetailsAuto(Long orgId, String finyear,  String clientCode,String mainGroupName);
	
	
	@Query(nativeQuery = true,value = "WITH Months AS (\r\n"
			+ "    SELECT 'April' AS month UNION ALL\r\n"
			+ "    SELECT 'May' UNION ALL\r\n"
			+ "    SELECT 'June' UNION ALL\r\n"
			+ "    SELECT 'July' UNION ALL\r\n"
			+ "    SELECT 'August' UNION ALL\r\n"
			+ "    SELECT 'September' UNION ALL\r\n"
			+ "    SELECT 'October' UNION ALL\r\n"
			+ "    SELECT 'November' UNION ALL\r\n"
			+ "    SELECT 'December' UNION ALL\r\n"
			+ "    SELECT 'January' UNION ALL\r\n"
			+ "    SELECT 'February' UNION ALL\r\n"
			+ "    SELECT 'March'\r\n"
			+ "),\r\n"
			+ "Accounts AS (\r\n"
			+ "    SELECT \r\n"
			+ "        a.displayseq, \r\n"
			+ "        a.accountname,\r\n"
			+ "        a.accountcode,\r\n"
			+ "        a.subgroupname,\r\n"
			+ "        a.subgroupcode\r\n"
			+ "    FROM groupledgers a\r\n"
			+ "    JOIN groupmapping b ON a.groupmappingid = b.groupmappingid\r\n"
			+ "    WHERE b.groupname = ?4\r\n"
			+ "      AND a.active = 1\r\n"
			+ "    GROUP BY a.accountname, a.displayseq, a.accountcode, a.subgroupname, a.subgroupcode\r\n"
			+ ")\r\n"
			+ "SELECT \r\n"
			+ "    acc.accountcode,\r\n"
			+ "    acc.accountname,\r\n"
			+ "    m.month,\r\n"
			+ "    SUM(b.amount) AS total_amount\r\n"
			+ "FROM Months m\r\n"
			+ "CROSS JOIN Accounts acc\r\n"
			+ "LEFT JOIN automation h ON h.maingroupname = ?4\r\n"
			+ "LEFT JOIN automationdetails j ON h.automationid = j.automationid\r\n"
			+ "LEFT JOIN previousyearactual b \r\n"
			+ "    ON acc.accountname = h.subheading\r\n"
			+ "    AND b.accountname=j.accountname\r\n"
			+ "    AND j.accountname = b.accountname\r\n"
			+ "    AND j.maingroup = b.maingroup\r\n"
			+ "    AND j.subgroup = b.subgroup\r\n"
			+ "    AND b.month = m.month\r\n"
			+ "    AND b.year = ?2\r\n"
			+ "    AND b.orgid = ?1\r\n"
			+ "    AND b.clientcode = ?3\r\n"
			+ "GROUP BY acc.accountname, acc.accountcode, m.month, acc.displayseq\r\n"
			+ "ORDER BY \r\n"
			+ "    CAST(acc.displayseq AS UNSIGNED),\r\n"
			+ "    FIELD(m.month, 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December', 'January', 'February', 'March')")
	Set<Object[]> getPYDetailsAuto(Long orgId, String finyear,  String clientCode,String mainGroupName);

	@Query(nativeQuery = true,value = "WITH Months AS (\r\n"
			+ "    SELECT 'April' AS month, 1 AS month_order UNION ALL\r\n"
			+ "    SELECT 'May', 2 UNION ALL\r\n"
			+ "    SELECT 'June', 3 UNION ALL\r\n"
			+ "    SELECT 'July', 4 UNION ALL\r\n"
			+ "    SELECT 'August', 5 UNION ALL\r\n"
			+ "    SELECT 'September', 6 UNION ALL\r\n"
			+ "    SELECT 'October', 7 UNION ALL\r\n"
			+ "    SELECT 'November', 8 UNION ALL\r\n"
			+ "    SELECT 'December', 9 UNION ALL\r\n"
			+ "    SELECT 'January', 10 UNION ALL\r\n"
			+ "    SELECT 'February', 11 UNION ALL\r\n"
			+ "    SELECT 'March', 12\r\n"
			+ "),Accounts AS (\r\n"
			+ "    SELECT \r\n"
			+ "        a.displayseq, \r\n"
			+ "        a.accountname,\r\n"
			+ "        a.accountcode,\r\n"
			+ "        a.subgroupname,\r\n"
			+ "        a.subgroupcode\r\n"
			+ "    FROM groupledgers a\r\n"
			+ "    JOIN groupmapping b ON a.groupmappingid = b.groupmappingid\r\n"
			+ "    WHERE b.groupname = ?4\r\n"
			+ "      AND a.active = 1\r\n"
			+ "    GROUP BY a.accountname, a.displayseq, a.accountcode, a.subgroupname, a.subgroupcode\r\n"
			+ ")SELECT \r\n"
			+ "    acc.accountcode,\r\n"
			+ "    acc.accountname,\r\n"
			+ "    m.month,\r\n"
			+ "        SUM(b.amount)total_amount\r\n"
			+ "FROM Months m CROSS JOIN \r\n"
			+ "Accounts acc \r\n"
			+ "LEFT JOIN automation h ON h.maingroupname = ?4 \r\n"
			+ "and acc.accountname = h.subheading\r\n"
			+ "LEFT JOIN automationdetails j ON h.automationid = j.automationid\r\n"
			+ "LEFT JOIN budget b on b.month = m.month\r\n"
			+ "AND b.accountname = j.accountname\r\n"
			+ "AND j.maingroup = b.maingroup\r\n"
			+ "AND j.subgroup = b.subgroup\r\n"
			+ "    AND b.year = ?2\r\n"
			+ "    AND b.orgid = ?1\r\n"
			+ "    AND b.clientcode = ?3\r\n"
			+ "    GROUP BY acc.accountname, acc.accountcode, m.month, acc.displayseq, m.month_order ORDER BY \r\n"
			+ "    CAST(acc.displayseq AS UNSIGNED),\r\n"
			+ "    m.month_order")
	Set<Object[]> getProfitAndLossBudgetDetailsAuto(Long orgId, String year, String clientCode, String mainGroup,
			String clientYear, String previousYear);

	@Query(nativeQuery = true, value = "select * from budget where orgid=?1 and clientcode=?2 and year=?3 and maingroup=?4 and subgroup=?5")
	List<BudgetVO> findStockDetails(Long org, String clientcode, String yr, String mGroup, String subGroup);

	@Query(nativeQuery = true,value = "SELECT p.month, SUM(p.amount) FROM budget p \r\n"
			+ "		       WHERE p.orgid = ?1 AND p.clientcode = ?2 AND p.year = ?3 \r\n"
			+ "		       AND p.maingroup = 'Closing Stock' GROUP BY p.month")
	List<Object[]> getMonthWiseSumAmountForClosingStock(Long org, String clientcode, String yr);

	@Query(nativeQuery = true, value = "select * from budget where orgid=?1 and clientcode=?2 and year=?3 and maingroup=?4 and subgroup=?5 and accountname=?6 ")
	List<BudgetVO> findOldDetails(Long orgId, String clientCode, String year, String mg, String mg2, String raw);
	
	@Query(nativeQuery = true,value ="SELECT p.month, SUM(p.amount) FROM budget p " +
		       "WHERE p.orgId = ?1 AND p.clientCode = ?2 AND p.year = ?3 " +
		       "AND p.mainGroup = 'Closing Stock' AND p.accountCode IN (?4) "+
		       "GROUP BY p.month")
	List<Object[]> getDrawingPowerMonthWiseSum(Long org, String clientcode, String yr, List<String> accountCodeList);

	@Query(nativeQuery = true,value ="SELECT p.month, SUM(p.amount) FROM budget p " +
		       "WHERE p.orgId = ?1 AND p.clientCode = ?2 AND p.year = ?3 " +
		       "AND p.mainGroup = 'Closing Stock' AND p.accountCode = '4009' " +
		       "GROUP BY p.month")
	List<Object[]> getMonthWiseSumForWIP(Long org, String clientcode, String yr);

	@Query(nativeQuery = true,value ="SELECT p.month, SUM(p.amount) FROM budget p " +
		       "WHERE p.orgId = ?1 AND p.clientCode = ?2 AND p.year = ?3 " +
		       "AND p.mainGroup = 'Closing Stock' AND p.accountCode IN (?4) "+
		       "GROUP BY p.month")
	List<Object[]> getMonthWiseSumForFinishedGoods(Long org, String clientcode, String yr,
			List<String> finishedGoodsCodes);

	
	@Query(nativeQuery = true, value = "SELECT\r\n"
			+ "    a.accountcode,\r\n"
			+ "    a.accountname,\r\n"
			+ "    ROUND(SUM(a.budgetYTD), 2) AS budgetYTD,\r\n"
			+ "    ROUND(SUM(a.ActYTD), 2) AS ActYTD\r\n"
			+ "FROM (\r\n"
			+ "    SELECT accountcode, accountname, SUM(amount) AS budgetYTD, 0 AS ActYTD\r\n"
			+ "    FROM budgetincrementalprofit\r\n"
			+ "    WHERE orgid = ?1 AND clientcode = ?2 AND year = ?3\r\n"
			+ "    GROUP BY accountcode, accountname\r\n"
			+ "\r\n"
			+ "    UNION ALL\r\n"
			+ "\r\n"
			+ "    SELECT accountcode, accountname, 0 AS budgetYTD, SUM(amount) AS ActYTD\r\n"
			+ "    FROM pyincrementalprofit\r\n"
			+ "    WHERE orgid = ?1 AND clientcode = ?2 AND year = ?3\r\n"
			+ "    GROUP BY accountcode, accountname\r\n"
			+ ") a , groupledger b where a.acountname=b.accountname\r\n"
			+ "GROUP BY\r\n"
			+ "    a.accountcode,\r\n"
			+ "    a.accountname order by b.displayseq asc")
	Set<Object[]>getELActualIncrementalProfitReport(Long orgId, String clientCode,String year);
	
	@Query(nativeQuery = true, value = "SELECT\r\n"
			+ "a.department,a.category,\r\n"
			+ "    ROUND(SUM(a.budgetYTD), 2) AS budgetYTD,\r\n"
			+ "    ROUND(SUM(a.ActYTD), 2) AS ActYTD,\r\n"
			+ "    ROUND(SUM(a.PyYTD), 2) AS PyYTD\r\n"
			+ "FROM (\r\n"
			+ "    SELECT  department,category, SUM(ctc) budgetYTD, 0 ActYTD, 0 PyYTD\r\n"
			+ "    FROM budgetheadcount\r\n"
			+ "    WHERE orgid = ?1 AND clientcode = ?2 AND year = ?3\r\n"
			+ "          AND monthsequence <= (SELECT monthsequence FROM budgetheadcount WHERE year = ?3 AND month = ?5 GROUP BY monthsequence)\r\n"
			+ "    GROUP BY department,category\r\n"
			+ "\r\n"
			+ "    UNION\r\n"
			+ "\r\n"
			+ "    SELECT department,category, 0 budgetYTD, SUM(ctc) ActYTD, 0 PyYTD\r\n"
			+ "    FROM pyheadcount\r\n"
			+ "    WHERE orgid = ?1 AND clientcode = ?2 AND year = ?3\r\n"
			+ "          AND monthsequence <= (SELECT monthsequence FROM pyheadcount WHERE  year = ?3 AND month = ?5 GROUP BY monthsequence)\r\n"
			+ "    GROUP BY department,category\r\n"
			+ "\r\n"
			+ "    UNION\r\n"
			+ "\r\n"
			+ "    SELECT department,category,  0 budgetYTD, 0 ActYTD, SUM(ctc) PyYTD\r\n"
			+ "    FROM pyheadcount\r\n"
			+ "    WHERE orgid = ?1 AND clientcode = ?2 AND year = ?4\r\n"
			+ "          AND monthsequence <= (SELECT monthsequence FROM pyheadcount WHERE  year = ?4 AND month = ?5 GROUP BY monthsequence)\r\n"
			+ "    GROUP BY department,category\r\n"
			+ ") a\r\n"
			+ "GROUP BY\r\n"
			+ "   a.department,a.category")
	Set<Object[]>getELActualHeadCountReport(Long orgId, String clientCode,String finYear,String previousYear,String month);
	
	
	@Query(nativeQuery = true,value = "SELECT supplier,SUM(slab1) slab1,SUM(slab2) slab2,SUM(slab3) slab3,SUM(slab4) slab4,SUM(slab5) slab5,SUM(slab6) slab6\r\n"
			+ "    FROM pyarap\r\n"
			+ "    WHERE orgid = ?1 AND clientcode = ?2 AND year = ?3 and type=?4 \r\n"
			+ "          AND monthsequence <= (SELECT monthsequence FROM pyarap WHERE  year = ?3 AND month = ?5 GROUP BY monthsequence)\r\n"
			+ "    GROUP BY supplier")
	Set<Object[]>getELActualARAPReport(Long orgId,String clientCode,String finYear,String type,String month);

	@Query(nativeQuery = true,value = "SELECT\r\n"
			+ "    a.accountname,\r\n"
			+ "    ROUND(SUM(a.budgetYTD), 2) AS budgetYTD,\r\n"
			+ "    ROUND(SUM(a.ActYTD), 2) AS ActYTD,\r\n"
			+ "    ROUND(SUM(a.PyYTD), 2) AS PyYTD\r\n"
			+ "FROM (\r\n"
			+ " SELECT maingroup, accountname,\r\n"
			+ "            SUM(amount) budgetYTD, 0 ActYTD, 0 PyYTD\r\n"
			+ "    FROM budget\r\n"
			+ "    WHERE orgid = ?1 AND clientcode = ?2 AND year = ?3 and maingroup=?6 and subgroup=?7\r\n"
			+ "          AND monthsequence <= (SELECT monthsequence FROM budget WHERE year = ?3 AND month = ?5 GROUP BY monthsequence)\r\n"
			+ "    GROUP BY maingroup, accountname\r\n"
			+ "    union\r\n"
			+ "    SELECT maingroup, accountname,\r\n"
			+ "            0 budgetYTD, SUM(amount) ActYTD, 0 PyYTD\r\n"
			+ "    FROM previousyearactual\r\n"
			+ "    WHERE orgid = ?1 AND clientcode = ?2 AND year = ?3 and maingroup=?6 and subgroup=?7\r\n"
			+ "          AND monthsequence <= (SELECT monthsequence FROM previousyearactual WHERE year = ?3 AND month = ?5 GROUP BY monthsequence)\r\n"
			+ "    GROUP BY maingroup, accountname\r\n"
			+ "    union\r\n"
			+ "    SELECT maingroup, accountname,\r\n"
			+ "            0 budgetYTD,  0 ActYTD, SUM(amount) PyYTD\r\n"
			+ "    FROM previousyearactual\r\n"
			+ "    WHERE orgid = ?1 AND clientcode = ?2 AND year = ?4 and maingroup=?6 and subgroup=?7\r\n"
			+ "          AND monthsequence <= (SELECT monthsequence FROM previousyearactual WHERE year = ?4 AND month = ?5 GROUP BY monthsequence)\r\n"
			+ "    GROUP BY  maingroup,accountname)a  WHERE a.maingroup = ?6  \r\n"
			+ "GROUP BY\r\n"
			+ "    a.accountname")
	Set<Object[]> getELActualRatioAnalysisReport(Long orgId, String clientCode, String finyear, String previousYear,
			String month, String mainGroupName,String subGroup);

	@Query(nativeQuery = true, value = "SELECT\r\n"
			+ "    a.description,\r\n"
			+ "    ROUND(SUM(a.budgetYTD), 2) AS budgetYTD,\r\n"
			+ "    ROUND(SUM(a.ActYTD), 2) AS ActYTD,\r\n"
			+ "    ROUND(SUM(a.PyYTD), 2) AS PyYTD\r\n"
			+ "FROM (\r\n"
			+ "    SELECT \r\n"
			+ "        description, \r\n"
			+ "        SUM(amount) AS budgetYTD, \r\n"
			+ "        0 AS ActYTD, \r\n"
			+ "        0 AS PyYTD\r\n"
			+ "    FROM budgetsalespurchase\r\n"
			+ "    WHERE \r\n"
			+ "        orgid = ?1\r\n"
			+ "        AND clientcode = ?2\r\n"
			+ "        AND year = ?3\r\n"
			+ "        AND type = ?6\r\n"
			+ "        AND monthsequence <= (\r\n"
			+ "            SELECT monthsequence \r\n"
			+ "            FROM budgetsalespurchase \r\n"
			+ "            WHERE year = ?3 AND month = ?5 \r\n"
			+ "            GROUP BY monthsequence\r\n"
			+ "        )\r\n"
			+ "    GROUP BY description\r\n"
			+ "\r\n"
			+ "    UNION\r\n"
			+ "\r\n"
			+ "    SELECT \r\n"
			+ "        description,\r\n"
			+ "        0 AS budgetYTD, \r\n"
			+ "        SUM(amount) AS ActYTD, \r\n"
			+ "        0 AS PyYTD\r\n"
			+ "    FROM pysalespurchase\r\n"
			+ "    WHERE \r\n"
			+ "        orgid = ?1\r\n"
			+ "        AND clientcode = ?2\r\n"
			+ "        AND year = ?3\r\n"
			+ "        AND type = ?6\r\n"
			+ "        AND monthsequence <= (\r\n"
			+ "            SELECT monthsequence \r\n"
			+ "            FROM pysalespurchase \r\n"
			+ "            WHERE year = ?3 AND month = ?5 \r\n"
			+ "            GROUP BY monthsequence\r\n"
			+ "        )\r\n"
			+ "    GROUP BY description\r\n"
			+ "\r\n"
			+ "    UNION\r\n"
			+ "\r\n"
			+ "    SELECT \r\n"
			+ "        description,\r\n"
			+ "        0 AS budgetYTD,  \r\n"
			+ "        0 AS ActYTD, \r\n"
			+ "        SUM(amount) AS PyYTD\r\n"
			+ "    FROM pysalespurchase\r\n"
			+ "    WHERE \r\n"
			+ "        orgid = ?1\r\n"
			+ "        AND clientcode = ?2\r\n"
			+ "        AND year = ?4\r\n"
			+ "        AND type = ?6\r\n"
			+ "        AND monthsequence <= (\r\n"
			+ "            SELECT monthsequence \r\n"
			+ "            FROM pysalespurchase \r\n"
			+ "            WHERE year = ?4 AND month = ?5 \r\n"
			+ "            GROUP BY monthsequence\r\n"
			+ "        )\r\n"
			+ "    GROUP BY description\r\n"
			+ ") a\r\n"
			+ "GROUP BY a.description")
	Set<Object[]> getELActualSalesPurchaseAnalysisReport(Long orgId, String clientCode, String finyear,
			String previousYear, String month, String type);

	@Query(nativeQuery = true, value = "WITH Accounts AS (\r\n"
			+ "    SELECT \r\n"
			+ "        a.displayseq, \r\n"
			+ "        a.accountname,\r\n"
			+ "        a.accountcode,\r\n"
			+ "        a.subgroupname,\r\n"
			+ "        a.subgroupcode\r\n"
			+ "    FROM groupledgers a\r\n"
			+ "    JOIN groupmapping b ON a.groupmappingid = b.groupmappingid\r\n"
			+ "    WHERE b.groupname = ?5\r\n"
			+ "      AND a.active = 1\r\n"
			+ "    GROUP BY a.accountname, a.displayseq, a.accountcode, a.subgroupname, a.subgroupcode\r\n"
			+ ")\r\n"
			+ "SELECT\r\n"
			+ "    h.accountcode,\r\n"
			+ "    h.accountname,\r\n"
			+ "    h.quater,\r\n"
			+ "    h.display_sequence,\r\n"
			+ "    ROUND(SUM(h.budget), 2) AS CY,\r\n"
			+ "    ROUND(SUM(h.PY), 2) AS PY\r\n"
			+ "FROM (\r\n"
			+ "    -- CY budget\r\n"
			+ "    SELECT \r\n"
			+ "        b.maingroup, b.subgroup, b.subgroupcode,\r\n"
			+ "        acc.accountcode, acc.accountname, b.natureofaccount,\r\n"
			+ "        SUM(b.amount) AS budget,\r\n"
			+ "        0 AS PY,\r\n"
			+ "        acc.displayseq AS display_sequence,\r\n"
			+ "        b.quater\r\n"
			+ "    FROM Accounts acc\r\n"
			+ "    LEFT JOIN automation h ON h.maingroupname = ?5\r\n"
			+ "    LEFT JOIN automationdetails j ON h.automationid = j.automationid\r\n"
			+ "    LEFT JOIN budget b \r\n"
			+ "        ON acc.accountname = h.subheading\r\n"
			+ "        AND b.accountname = j.accountname\r\n"
			+ "        AND j.maingroup = b.maingroup\r\n"
			+ "        AND j.subgroup = b.subgroup\r\n"
			+ "        AND b.year = ?2\r\n"
			+ "        AND b.orgid = ?1\r\n"
			+ "        AND b.clientcode = ?4 AND (\r\n"
			+ "    (?5 = 'Balance Sheet' AND b.monthsequence % 3 = 0)\r\n"
			+ "    OR\r\n"
			+ "    (?5 = 'Profit And Loss Account')\r\n"
			+ ")\r\n"
			+ "    GROUP BY b.maingroup, b.subgroup, b.subgroupcode, acc.accountcode, acc.accountname, \r\n"
			+ "             b.natureofaccount, acc.displayseq, b.quater\r\n"
			+ "\r\n"
			+ "    UNION ALL\r\n"
			+ "\r\n"
			+ "    -- PY\r\n"
			+ "    SELECT \r\n"
			+ "        b.maingroup, b.subgroup, b.subgroupcode,\r\n"
			+ "        acc.accountcode, acc.accountname, b.natureofaccount,\r\n"
			+ "        0 AS budget,\r\n"
			+ "        SUM(b.amount) AS PY,\r\n"
			+ "        acc.displayseq AS display_sequence,\r\n"
			+ "        b.quater\r\n"
			+ "    FROM Accounts acc\r\n"
			+ "    LEFT JOIN automation h ON h.maingroupname = ?5\r\n"
			+ "    LEFT JOIN automationdetails j ON h.automationid = j.automationid\r\n"
			+ "    LEFT JOIN previousyearactual b \r\n"
			+ "        ON acc.accountname = h.subheading\r\n"
			+ "        AND b.accountname = j.accountname\r\n"
			+ "        AND j.maingroup = b.maingroup\r\n"
			+ "        AND j.subgroup = b.subgroup\r\n"
			+ "        AND b.year = ?3\r\n"
			+ "        AND b.orgid = ?1\r\n"
			+ "        AND b.clientcode = ?4 AND (\r\n"
			+ "    (?5 = 'Balance Sheet' AND b.monthsequence % 3 = 0)\r\n"
			+ "    OR\r\n"
			+ "    (?5 = 'Profit And Loss Account')\r\n"
			+ ")\r\n"
			+ "    GROUP BY b.maingroup, b.subgroup, b.subgroupcode, acc.accountcode, acc.accountname, \r\n"
			+ "             b.natureofaccount, acc.displayseq, b.quater\r\n"
			+ ") h\r\n"
			+ "WHERE h.accountname IS NOT NULL AND h.quater IS NOT NULL\r\n"
			+ "GROUP BY h.accountcode, h.accountname, h.quater, h.display_sequence\r\n"
			+ "ORDER BY CAST(display_sequence AS UNSIGNED), h.quater ASC")
	Set<Object[]> getELBudgetAutomaticDetails(Long orgId, String finyear, String previousYear, String clientCode,
			String mainGroupName);
	
	@Query(nativeQuery = true, value = "WITH Accounts AS (\r\n"
			+ "    SELECT \r\n"
			+ "        a.displayseq, \r\n"
			+ "        a.accountname,\r\n"
			+ "        a.accountcode,\r\n"
			+ "        a.subgroupname,\r\n"
			+ "        a.subgroupcode\r\n"
			+ "    FROM groupledgers a\r\n"
			+ "    JOIN groupmapping b ON a.groupmappingid = b.groupmappingid\r\n"
			+ "    WHERE b.groupname = ?4\r\n"
			+ "      AND a.active = 1\r\n"
			+ "    GROUP BY a.accountname, a.displayseq, a.accountcode, a.subgroupname, a.subgroupcode\r\n"
			+ ")\r\n"
			+ "SELECT\r\n"
			+ "    h.accountcode,\r\n"
			+ "    h.accountname,\r\n"
			+ "    h.quater,\r\n"
			+ "    h.display_sequence,\r\n"
			+ "    ROUND(SUM(h.PY), 2) AS PY\r\n"
			+ "FROM ( \r\n"
			+ "    -- PY\r\n"
			+ "    SELECT \r\n"
			+ "        b.maingroup, b.subgroup, b.subgroupcode,\r\n"
			+ "        acc.accountcode, acc.accountname, b.natureofaccount,\r\n"
			+ "        SUM(b.amount) AS PY,\r\n"
			+ "        acc.displayseq AS display_sequence,\r\n"
			+ "        b.quater\r\n"
			+ "    FROM Accounts acc\r\n"
			+ "    LEFT JOIN automation h ON h.maingroupname = ?4\r\n"
			+ "    LEFT JOIN automationdetails j ON h.automationid = j.automationid\r\n"
			+ "    LEFT JOIN previousyearactual b \r\n"
			+ "        ON acc.accountname = h.subheading\r\n"
			+ "        AND b.accountname = j.accountname\r\n"
			+ "        AND j.maingroup = b.maingroup\r\n"
			+ "        AND j.subgroup = b.subgroup\r\n"
			+ "        AND b.year = ?2\r\n"
			+ "        AND b.orgid = ?1\r\n"
			+ "        AND b.clientcode = ?3 AND (\r\n"
			+ "    (?4 = 'Balance Sheet' AND b.monthsequence % 3 = 0)\r\n"
			+ "    OR\r\n"
			+ "    (?4 = 'Profit And Loss Account')\r\n"
			+ ")\r\n"
			+ "    GROUP BY b.maingroup, b.subgroup, b.subgroupcode, acc.accountcode, acc.accountname, \r\n"
			+ "             b.natureofaccount, acc.displayseq, b.quater\r\n"
			+ "\r\n"
			+ "    UNION\r\n"
			+ "\r\n"
			+ "    SELECT \r\n"
			+ "        b.maingroup, b.subgroup, b.subgroupcode,\r\n"
			+ "        acc.accountcode, acc.accountname, b.natureofaccount,\r\n"
			+ "        SUM(b.amount) AS PY,\r\n"
			+ "        acc.displayseq AS display_sequence,\r\n"
			+ "        'YTD' as quater\r\n"
			+ "    FROM Accounts acc\r\n"
			+ "    LEFT JOIN automation h ON h.maingroupname = ?4\r\n"
			+ "    LEFT JOIN automationdetails j ON h.automationid = j.automationid\r\n"
			+ "    LEFT JOIN previousyearactual b \r\n"
			+ "        ON acc.accountname = h.subheading\r\n"
			+ "        AND b.accountname = j.accountname\r\n"
			+ "        AND j.maingroup = b.maingroup\r\n"
			+ "        AND j.subgroup = b.subgroup\r\n"
			+ "        AND b.year = ?2\r\n"
			+ "        AND b.orgid = ?1\r\n"
			+ "        AND b.clientcode = ?3\r\n"
			+ "        AND (\r\n"
			+ "    (?4 = 'Balance Sheet' AND b.month=?5)\r\n"
			+ "    OR\r\n"
			+ "    (?4 = 'Profit And Loss Account'AND monthsequence <= (\r\n"
			+ "            SELECT MAX(monthsequence)\r\n"
			+ "            FROM previousyearactual\r\n"
			+ "            WHERE year = ?2\r\n"
			+ "              AND month = ?5\r\n"
			+ "              AND clientcode = ?3\r\n"
			+ "        )))\r\n"
			+ "    GROUP BY b.maingroup, b.subgroup, b.subgroupcode, acc.accountcode, acc.accountname, \r\n"
			+ "             b.natureofaccount, acc.displayseq, b.quater\r\n"
			+ ") h\r\n"
			+ "WHERE h.accountname IS NOT NULL AND h.quater IS NOT NULL\r\n"
			+ "GROUP BY h.accountcode, h.accountname, h.quater, h.display_sequence\r\n"
			+ "ORDER BY CAST(display_sequence AS UNSIGNED), h.quater ASC")
	Set<Object[]> getELPyAutomaticDetails(Long orgId, String previousYear, String clientCode,
			String mainGroupName,String month);
	
	
	@Query(nativeQuery = true, value = "SELECT accountname,\r\n"
			+ "       quater,\r\n"
			+ "       SUM(amount)\r\n"
			+ "FROM previousyearactual\r\n"
			+ "WHERE orgid = ?1\r\n"
			+ "  AND maingroup = ?4\r\n"
			+ "  AND clientcode = ?3\r\n"
			+ "  AND subgroup = ?5\r\n"
			+ "  AND year = ?2\r\n"
			+ "GROUP BY accountname, quater\r\n"
			+ "\r\n"
			+ "UNION\r\n"
			+ "\r\n"
			+ "SELECT accountname,\r\n"
			+ "       'ytd' AS quater,\r\n"
			+ "       SUM(amount)\r\n"
			+ "FROM previousyearactual\r\n"
			+ "WHERE orgid = ?1\r\n"
			+ "  AND maingroup = ?4\r\n"
			+ "  AND clientcode = ?3\r\n"
			+ "  AND subgroup = ?5\r\n"
			+ "  AND year = ?2\r\n"
			+ "  AND month= ?6\r\n"
			+ "GROUP BY accountname\r\n"
			+ "union\r\n"
			+ "SELECT accountname,\r\n"
			+ "       'fullYear' AS quater,\r\n"
			+ "       SUM(amount)\r\n"
			+ "FROM previousyearactual\r\n"
			+ "WHERE orgid = ?1\r\n"
			+ "  AND maingroup = ?4\r\n"
			+ "  AND clientcode = ?3\r\n"
			+ "  AND subgroup = ?5\r\n"
			+ "  AND year = ?2\r\n"
			+ "GROUP BY accountname")
	Set<Object[]> getELPyRatioAnalysisDetails(Long orgId, String previousYear, String clientCode,
			String mainGroupName,String subGroupName,String month);

	@Query(nativeQuery = true, value = "select t.accountname, t.quater,sum(t.bud) bud,sum(t.py)py from(\r\n"
			+ "    SELECT \r\n"
			+ "        accountname, \r\n"
			+ "        quater,\r\n"
			+ "        amount AS bud, \r\n"
			+ "        0 AS py\r\n"
			+ "    FROM budget\r\n"
			+ "    WHERE orgid = ?1\r\n"
			+ "      AND clientcode = ?3\r\n"
			+ "      AND year = ?2 and subgroup='Ratio'\r\n"
			+ "      AND monthsequence % 3 = 0\r\n"
			+ "    UNION ALL\r\n"
			+ "    SELECT \r\n"
			+ "        accountname, \r\n"
			+ "        quater,\r\n"
			+ "        0 AS bud, \r\n"
			+ "        amount AS py\r\n"
			+ "    FROM previousyearactual\r\n"
			+ "    WHERE orgid = ?1\r\n"
			+ "      AND clientcode = ?3\r\n"
			+ "      AND year = ?4 and subgroup='Ratio'\r\n"
			+ "      AND monthsequence % 3 = 0) t group by t.accountname,t.quater")
	Set<Object[]> getELBudgetRatioAnalysisDetails(Long orgId, String finyear, String clientCode, String previousYear);

	@Query(nativeQuery = true, value = "SELECT \r\n"
			+ "    t.description,\r\n"
			+ "    t.natureofaccount,\r\n"
			+ "    t.quater,\r\n"
			+ "    SUM(t.bud) AS bud,\r\n"
			+ "    SUM(t.py) AS py\r\n"
			+ "FROM (\r\n"
			+ "    -- Budget\r\n"
			+ "    SELECT \r\n"
			+ "        description,\r\n"
			+ "        natureofaccount,\r\n"
			+ "        quater,\r\n"
			+ "        SUM(amount) AS bud,\r\n"
			+ "        0 AS py\r\n"
			+ "    FROM budgetsalespurchase\r\n"
			+ "    WHERE orgid = ?1\r\n"
			+ "      AND year = ?2\r\n"
			+ "      AND clientcode = ?3\r\n"
			+ "      AND type = ?5\r\n"
			+ "    GROUP BY description, natureofaccount, quater\r\n"
			+ "\r\n"
			+ "    UNION ALL\r\n"
			+ "    \r\n"
			+ "    -- Previous Year\r\n"
			+ "    SELECT \r\n"
			+ "        description,\r\n"
			+ "        natureofaccount,\r\n"
			+ "        quater,\r\n"
			+ "        0 AS bud,\r\n"
			+ "        SUM(amount) AS py\r\n"
			+ "    FROM pysalespurchase\r\n"
			+ "    WHERE orgid = ?1\r\n"
			+ "      AND year = ?4\r\n"
			+ "      AND clientcode = ?3\r\n"
			+ "      AND type = ?5\r\n"
			+ "    GROUP BY description, natureofaccount, quater\r\n"
			+ "    \r\n"
			+ "    UNION ALL\r\n"
			+ "    \r\n"
			+ "    -- Budget Full Year\r\n"
			+ "    SELECT \r\n"
			+ "        description,\r\n"
			+ "        natureofaccount,\r\n"
			+ "        'fullYear' AS quater,\r\n"
			+ "        SUM(amount) AS bud,\r\n"
			+ "        0 AS py\r\n"
			+ "    FROM budgetsalespurchase\r\n"
			+ "    WHERE orgid = ?1\r\n"
			+ "      AND year = ?2\r\n"
			+ "      AND clientcode = ?3\r\n"
			+ "      AND type = ?5\r\n"
			+ "    GROUP BY description, natureofaccount\r\n"
			+ "\r\n"
			+ "    UNION ALL\r\n"
			+ "    \r\n"
			+ "    -- Previous Year Full Year\r\n"
			+ "    SELECT \r\n"
			+ "        description,\r\n"
			+ "        natureofaccount,\r\n"
			+ "        'fullYear' AS quater,\r\n"
			+ "        0 AS bud,\r\n"
			+ "        SUM(amount) AS py\r\n"
			+ "    FROM pysalespurchase\r\n"
			+ "    WHERE orgid = ?1\r\n"
			+ "      AND year = ?4\r\n"
			+ "      AND clientcode = ?3\r\n"
			+ "      AND type = ?5\r\n"
			+ "    GROUP BY description, natureofaccount\r\n"
			+ ") t \r\n"
			+ "GROUP BY t.description, t.natureofaccount, t.quater")
	Set<Object[]> getELBudgetSalesPurchaseAnalysisDetails(Long orgId, String finyear, String clientCode,
			String previousYear, String type);

	@Query(nativeQuery =true, value =  "SELECT \r\n"
			+ "    t.description,\r\n"
			+ "    t.natureofaccount,\r\n"
			+ "    t.quater,\r\n"
			+ "    SUM(t.py) AS py\r\n"
			+ "FROM (\r\n"
			+ "    -- Previous Year\r\n"
			+ "    SELECT \r\n"
			+ "        description,\r\n"
			+ "        natureofaccount,\r\n"
			+ "        quater,\r\n"
			+ "        SUM(amount) AS py\r\n"
			+ "    FROM pysalespurchase\r\n"
			+ "    WHERE orgid = ?1\r\n"
			+ "      AND year = ?2\r\n"
			+ "      AND clientcode = ?3\r\n"
			+ "      AND type = ?4\r\n"
			+ "    GROUP BY description, natureofaccount, quater\r\n"
			+ "\r\n"
			+ "    UNION ALL\r\n"
			+ "    SELECT \r\n"
			+ "        description,\r\n"
			+ "        natureofaccount,\r\n"
			+ "        'ytd' AS quater,\r\n"
			+ "        SUM(amount) AS py\r\n"
			+ "    FROM pysalespurchase\r\n"
			+ "    WHERE orgid = ?1\r\n"
			+ "      AND year = ?2\r\n"
			+ "      AND clientcode = ?3\r\n"
			+ "      AND type = ?4 and  monthsequence <= (\r\n"
			+ "			          SELECT MAX(monthsequence)\r\n"
			+ "			         FROM pysalespurchase\r\n"
			+ "		          WHERE year = ?2\r\n"
			+ "			            AND month = ?5\r\n"
			+ "			            AND clientcode = ?3\r\n"
			+ "			      )\r\n"
			+ "    GROUP BY description, natureofaccount\r\n"
			+ "    union all\r\n"
			+ "\r\n"
			+ "    -- Previous Year Full Year\r\n"
			+ "    SELECT \r\n"
			+ "        description,\r\n"
			+ "        natureofaccount,\r\n"
			+ "        'fullYear' AS quater,\r\n"
			+ "        SUM(amount) AS py\r\n"
			+ "    FROM pysalespurchase\r\n"
			+ "    WHERE orgid = ?1\r\n"
			+ "      AND year = ?2\r\n"
			+ "      AND clientcode = ?3\r\n"
			+ "      AND type = ?4\r\n"
			+ "    GROUP BY description, natureofaccount\r\n"
			+ ") t\r\n"
			+ "GROUP BY t.description, t.natureofaccount, t.quater")
	Set<Object[]> getELPySalesPurchaseAnalysisDetails(Long orgId, String previousYear, String clientCode, String type,String month);

	@Modifying
    @Transactional
    @Query(value = "DELETE FROM budget " +
                   "WHERE orgid = ?1 " +
                   "AND clientcode = ?2 " +
                   "AND year = ?3 " +
                   "AND maingroup = ?4 " +
                   "AND subgroup = ?5 " +
                   "AND month = ?6", nativeQuery = true)
	void deleteByOrgIdAndClientAndYearAndMainGroupAndSubGroupAndMonth(Long orgId, String clientCode, String year,
			String mainGroup, String subGroup, String month);
	
	
	
	@Query(nativeQuery = true, value = "SELECT t.customername,\r\n"
			+ "       SUM(t.bud) AS bud,\r\n"
			+ "       SUM(t.act) AS act,\r\n"
			+ "       SUM(t.py) AS py,\r\n"
			+ "       SUM(t.budytd) AS budytd,\r\n"
			+ "       SUM(t.actytd) AS actytd,\r\n"
			+ "       SUM(t.pyytd) AS pyytd,\r\n"
			+ "       SUM(t.budfull) AS budfull,\r\n"
			+ "       SUM(t.actfull) AS actfull,\r\n"
			+ "       SUM(t.pyfull) AS pyfull\r\n"
			+ "FROM (\r\n"
			+ "    SELECT customername, SUM(amount) AS bud, 0 AS act, 0 AS py, 0 AS budytd, 0 AS actytd, 0 AS pyytd, 0 AS budfull, 0 AS actfull, 0 AS pyfull\r\n"
			+ "    FROM budgetob\r\n"
			+ "    WHERE orgid = ?1 AND clientcode = ?2 AND year = ?3 AND month = ?4 AND type = ?6\r\n"
			+ "    GROUP BY customername\r\n"
			+ "\r\n"
			+ "    UNION ALL\r\n"
			+ "\r\n"
			+ "    SELECT customername, 0, SUM(amount), 0, 0, 0, 0, 0, 0, 0\r\n"
			+ "    FROM previousyearob\r\n"
			+ "    WHERE orgid = ?1 AND clientcode = ?2 AND year = ?3 AND month = ?4 AND type = ?6\r\n"
			+ "    GROUP BY customername\r\n"
			+ "\r\n"
			+ "    UNION ALL\r\n"
			+ "\r\n"
			+ "    SELECT customername, 0, 0, SUM(amount), 0, 0, 0, 0, 0, 0\r\n"
			+ "    FROM previousyearob\r\n"
			+ "    WHERE orgid = ?1 AND clientcode = ?2 AND year = ?5 AND month = ?4 AND type = ?6\r\n"
			+ "    GROUP BY customername\r\n"
			+ "\r\n"
			+ "    UNION ALL\r\n"
			+ "\r\n"
			+ "    SELECT customername, 0, 0, 0, SUM(amount), 0, 0, 0, 0, 0\r\n"
			+ "    FROM budgetob\r\n"
			+ "    WHERE orgid = ?1 AND clientcode = ?2 AND year = ?3 AND type = ?6\r\n"
			+ "      AND monthsequence <= (\r\n"
			+ "          SELECT monthsequence FROM budgetob WHERE year = ?3 AND month = ?4 GROUP BY monthsequence\r\n"
			+ "      )\r\n"
			+ "    GROUP BY customername\r\n"
			+ "\r\n"
			+ "    UNION ALL\r\n"
			+ "\r\n"
			+ "    SELECT customername, 0, 0, 0, 0, SUM(amount), 0, 0, 0, 0\r\n"
			+ "    FROM previousyearob\r\n"
			+ "    WHERE orgid = ?1 AND clientcode = ?2 AND year = ?3 AND type = ?6\r\n"
			+ "      AND monthsequence <= (\r\n"
			+ "          SELECT monthsequence FROM previousyearob WHERE year = ?3 AND month = ?4 GROUP BY monthsequence\r\n"
			+ "      )\r\n"
			+ "    GROUP BY customername\r\n"
			+ "\r\n"
			+ "    UNION ALL\r\n"
			+ "\r\n"
			+ "    SELECT customername, 0, 0, 0, 0, 0, SUM(amount), 0, 0, 0\r\n"
			+ "    FROM previousyearob\r\n"
			+ "    WHERE orgid = ?1 AND clientcode = ?2 AND year = ?5 AND type = ?6\r\n"
			+ "      AND monthsequence <= (\r\n"
			+ "          SELECT monthsequence FROM previousyearob WHERE year = ?5 AND month = ?4 GROUP BY monthsequence\r\n"
			+ "      )\r\n"
			+ "    GROUP BY customername\r\n"
			+ "\r\n"
			+ "    UNION ALL\r\n"
			+ "\r\n"
			+ "    SELECT customername, 0, 0, 0, 0, 0, 0, SUM(amount), 0, 0\r\n"
			+ "    FROM budgetob\r\n"
			+ "    WHERE orgid = ?1 AND clientcode = ?2 AND year = ?3 AND type = ?6\r\n"
			+ "    GROUP BY customername\r\n"
			+ "\r\n"
			+ "    UNION ALL\r\n"
			+ "\r\n"
			+ "    SELECT customername, 0, 0, 0, 0, 0, 0, 0, SUM(amount) * 12, 0\r\n"
			+ "    FROM previousyearob\r\n"
			+ "    WHERE orgid = ?1 AND clientcode = ?2 AND year = ?3 AND month = ?4 AND type = ?6\r\n"
			+ "    GROUP BY customername\r\n"
			+ "\r\n"
			+ "    UNION ALL\r\n"
			+ "\r\n"
			+ "    SELECT customername, 0, 0, 0, 0, 0, 0, 0, 0, SUM(amount)\r\n"
			+ "    FROM previousyearob\r\n"
			+ "    WHERE orgid = ?1 AND clientcode = ?2 AND year = ?5 AND type = ?6\r\n"
			+ "    GROUP BY customername\r\n"
			+ ") t\r\n"
			+ "GROUP BY t.customername")
	Set<Object[]> getELActualOrderBooking(Long orgId, String clientCode, String finYear, String month,String previousYear,String type);

}
