package com.base.basesetup.repo;

import java.util.List;
import java.util.Set;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;

import com.base.basesetup.entity.GroupMappingVO;

public interface GroupMappingRepo extends JpaRepository<GroupMappingVO, Long> {

	boolean existsByOrgIdAndGroupNameIgnoreCase(Long orgId, String groupName);

	@Query(nativeQuery =true,value ="select * from groupmapping where orgid=?1")
	List<GroupMappingVO> getGroupMappingAll(Long orgId);

	@Query(nativeQuery = true,value = "SELECT \r\n"
			+ "    a.subgroupname,\r\n"
			+ "    c.accountcode\r\n"
			+ "FROM \r\n"
			+ "    groupledgers a\r\n"
			+ "JOIN \r\n"
			+ "    groupmapping b ON a.groupmappingid = b.groupmappingid\r\n"
			+ "LEFT JOIN \r\n"
			+ "    coa c ON c.accountgroupname = a.subgroupname and c.orgid=a.orgid and c.orgid=?1\r\n"
			+ "WHERE \r\n"
			+ "    a.groupname = ?2\r\n"
			+ "GROUP BY \r\n"
			+ "    a.subgroupname, c.accountcode")
	Set<Object[]> getSubGroupDetails(Long orgId, String mainGroup);
	
	
	@Query(nativeQuery = true,value = "WITH Months AS (\r\n"
			+ "    SELECT 'April' AS month UNION ALL\r\n"
			+ "    SELECT 'May' UNION ALL\r\n"
			+ "    SELECT 'June' UNION ALL\r\n"
			+ "    SELECT 'July' UNION ALL\r\n"
			+ "    SELECT 'August' UNION ALL\r\n"
			+ "    SELECT 'September' UNION ALL\r\n"
			+ "    SELECT 'October' UNION ALL\r\n"
			+ "    SELECT 'November' UNION ALL\r\n"
			+ "    SELECT 'December' UNION ALL\r\n"
			+ "    SELECT 'January' UNION ALL\r\n"
			+ "    SELECT 'February' UNION ALL\r\n"
			+ "    SELECT 'March'\r\n"
			+ "),\r\n"
			+ "Accounts AS (\r\n"
			+ "    SELECT \r\n"
			+ "        a.accountname,\r\n"
			+ "        a.accountcode,\r\n"
			+ "        b.natureofaccount,\r\n"
			+ "        CAST(a.displayseq AS UNSIGNED) AS displayseq\r\n"
			+ "    FROM groupledgers a\r\n"
			+ "    LEFT JOIN coa b ON a.accountname = b.accountgroupname\r\n"
			+ "    WHERE a.groupname = ?4\r\n"
			+ "      AND a.orgid = ?1\r\n"
			+ "      AND (a.subgroupname = ?5 OR ?5 = 'ALL') \r\n"
			+ "      AND a.active = 1\r\n"
			+ ")\r\n"
			+ "SELECT \r\n"
			+ "    a.accountname, \r\n"
			+ "    a.accountcode, \r\n"
			+ "    a.natureofaccount, \r\n"
			+ "    m.month, \r\n"
			+ "    COALESCE(SUM(b.amount), 0) AS totalamount\r\n"
			+ "FROM Accounts a\r\n"
			+ "CROSS JOIN Months m\r\n"
			+ "LEFT JOIN budget b \r\n"
			+ "    ON a.accountname = b.accountname\r\n"
			+ "    AND b.orgid = ?1\r\n"
			+ "    AND b.year = ?2\r\n"
			+ "    AND b.clientcode = ?3\r\n"
			+ "    AND b.maingroup = ?4\r\n"
			+ "    AND (b.subgroup = ?5 or ?5='ALL')\r\n"
			+ "    AND b.month = m.month\r\n"
			+ "GROUP BY \r\n"
			+ "    a.accountname, \r\n"
			+ "    a.accountcode, \r\n"
			+ "    a.natureofaccount, \r\n"
			+ "    m.month, \r\n"
			+ "    a.displayseq,\r\n"
			+ "    FIELD(m.month, 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December', 'January', 'February', 'March')\r\n"
			+ "ORDER BY \r\n"
			+ "    cast(a.displayseq as unsigned),\r\n"
			+ "    FIELD(m.month, 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December', 'January', 'February', 'March')")
	Set<Object[]> getGroupLedgersDetails(Long orgId,String year,String clientCode, String mainGroup,String accountCode);

	@Query(nativeQuery = true, value = "WITH Months AS (\r\n"
			+ "    SELECT 'April' AS month UNION ALL\r\n"
			+ "    SELECT 'May' UNION ALL\r\n"
			+ "    SELECT 'June' UNION ALL\r\n"
			+ "    SELECT 'July' UNION ALL\r\n"
			+ "    SELECT 'August' UNION ALL\r\n"
			+ "    SELECT 'September' UNION ALL\r\n"
			+ "    SELECT 'October' UNION ALL\r\n"
			+ "    SELECT 'November' UNION ALL\r\n"
			+ "    SELECT 'December' UNION ALL\r\n"
			+ "    SELECT 'January' UNION ALL\r\n"
			+ "    SELECT 'February' UNION ALL\r\n"
			+ "    SELECT 'March'\r\n"
			+ "),\r\n"
			+ "Accounts AS (\r\n"
			+ "    SELECT \r\n"
			+ "        a.accountname,\r\n"
			+ "        a.accountcode,\r\n"
			+ "        b.natureofaccount,\r\n"
			+ "        CAST(a.displayseq AS UNSIGNED) AS displayseq\r\n"
			+ "    FROM groupledgers a\r\n"
			+ "    LEFT JOIN coa b ON a.accountname = b.accountgroupname\r\n"
			+ "    WHERE a.groupname = ?4 \r\n"
			+ "      AND a.orgid = ?1\r\n"
			+ "      AND (a.subgroupname = ?5 or ?5='ALL') \r\n"
			+ "      AND a.active = 1\r\n"
			+ ")\r\n"
			+ "SELECT \r\n"
			+ "    a.accountname, \r\n"
			+ "    a.accountcode, \r\n"
			+ "    a.natureofaccount, \r\n"
			+ "    m.month, \r\n"
			+ "    COALESCE(SUM(b.amount), 0) AS totalamount\r\n"
			+ "FROM Accounts a\r\n"
			+ "CROSS JOIN Months m\r\n"
			+ "LEFT JOIN previousyearactual b \r\n"
			+ "    ON a.accountname = b.accountname \r\n"
			+ "    AND b.orgid = ?1 \r\n"
			+ "    AND b.year = ?2\r\n"
			+ "    AND b.clientcode = ?3\r\n"
			+ "    AND b.maingroup = ?4\r\n"
			+ "    AND (b.subgroup = ?5 or ?5='ALL')\r\n"
			+ "    AND b.month = m.month\r\n"
			+ "GROUP BY a.accountname, a.accountcode, a.natureofaccount, m.month, a.displayseq\r\n"
			+ "ORDER BY cast(a.displayseq as unsigned), \r\n"
			+ "         FIELD(m.month, 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December', 'January', 'February', 'March')")
	Set<Object[]> PreviousYearGroupLedgersDetails(Long orgId, String year, String clientCode, String mainGroup,
			String subGroupCode);
	
	@Query(nativeQuery = true, value = "WITH Months AS (\r\n"
			+ "    SELECT 'April' AS month UNION ALL\r\n"
			+ "    SELECT 'May' UNION ALL\r\n"
			+ "    SELECT 'June' UNION ALL\r\n"
			+ "    SELECT 'July' UNION ALL\r\n"
			+ "    SELECT 'August' UNION ALL\r\n"
			+ "    SELECT 'September' UNION ALL\r\n"
			+ "    SELECT 'October' UNION ALL\r\n"
			+ "    SELECT 'November' UNION ALL\r\n"
			+ "    SELECT 'December' UNION ALL\r\n"
			+ "    SELECT 'January' UNION ALL\r\n"
			+ "    SELECT 'February' UNION ALL\r\n"
			+ "    SELECT 'March'\r\n"
			+ "),\r\n"
			+ "Accounts AS (\r\n"
			+ "    SELECT \r\n"
			+ "        a.accountname,\r\n"
			+ "        a.accountcode,\r\n"
			+ "        b.natureofaccount,\r\n"
			+ "        CAST(a.displayseq AS UNSIGNED) AS displayseq\r\n"
			+ "    FROM groupledgers a\r\n"
			+ "    LEFT JOIN coa b ON a.accountname = b.accountgroupname\r\n"
			+ "    WHERE a.groupname = ?4\r\n"
			+ "      AND a.orgid = ?1\r\n"
			+ "      AND (a.subgroupname = ?5 OR ?5 = 'ALL')\r\n"
			+ "      AND a.active = 1\r\n"
			+ "),\r\n"
			+ "Data AS (\r\n"
			+ "    SELECT \r\n"
			+ "        a.accountname, \r\n"
			+ "        a.accountcode, \r\n"
			+ "        a.natureofaccount, \r\n"
			+ "        a.displayseq,\r\n"
			+ "        m.month, \r\n"
			+ "        COALESCE(SUM(b.amount), 0) AS totalamount\r\n"
			+ "    FROM Accounts a\r\n"
			+ "    CROSS JOIN Months m\r\n"
			+ "    LEFT JOIN previousyearactual b \r\n"
			+ "        ON a.accountname = b.accountname\r\n"
			+ "        AND b.orgid = ?1 \r\n"
			+ "        AND b.year = ?2 \r\n"
			+ "        AND b.clientcode = ?3\r\n"
			+ "        AND b.maingroup = ?4\r\n"
			+ "        AND (b.subgroup = ?5 or 'ALL'=?5)\r\n"
			+ "        AND b.month = m.month\r\n"
			+ "    GROUP BY a.accountname, a.accountcode, a.natureofaccount, a.displayseq, m.month\r\n"
			+ ")\r\n"
			+ "SELECT \r\n"
			+ "    accountname,\r\n"
			+ "    accountcode,\r\n"
			+ "    natureofaccount,\r\n"
			+ "    month,\r\n"
			+ "    totalamount\r\n"
			+ "FROM Data\r\n"
			+ "ORDER BY cast(displayseq as unsigned), \r\n"
			+ "         FIELD(month, 'April', 'May', 'June', 'July', 'August', 'September', \r\n"
			+ "                      'October', 'November', 'December', 'January', 'February', 'March')")
	Set<Object[]> ActualGroupLedgersDetails(Long orgId, String year, String clientCode, String mainGroup,
			String subGroupCode);

	@Query(nativeQuery = true, value = "WITH Months AS (\r\n"
			+ "    SELECT 'April' AS month UNION ALL\r\n"
			+ "    SELECT 'May' UNION ALL\r\n"
			+ "    SELECT 'June' UNION ALL\r\n"
			+ "    SELECT 'July' UNION ALL\r\n"
			+ "    SELECT 'August' UNION ALL\r\n"
			+ "    SELECT 'September' UNION ALL\r\n"
			+ "    SELECT 'October' UNION ALL\r\n"
			+ "    SELECT 'November' UNION ALL\r\n"
			+ "    SELECT 'December' UNION ALL\r\n"
			+ "    SELECT 'January' UNION ALL\r\n"
			+ "    SELECT 'February' UNION ALL\r\n"
			+ "    SELECT 'March'\r\n"
			+ ")\r\n"
			+ "SELECT \r\n"
			+ "    b.accountname, \r\n"
			+ "    b.accountcode, \r\n"
			+ "    b.natureofaccount, \r\n"
			+ "    m.month, \r\n"
			+ "    COALESCE(SUM(b.amount), 0) AS totalamount \r\n"
			+ "from Months m\r\n"
			+ "LEFT JOIN budget b \r\n"
			+ "    on b.orgid = ?1\r\n"
			+ "    AND b.year = ?2\r\n"
			+ "    AND b.clientcode = ?3\r\n"
			+ "    AND b.maingroup = ?4\r\n"
			+ "    AND (b.subgroup = ?5)\r\n"
			+ "    AND b.month = m.month\r\n"
			+ "GROUP BY \r\n"
			+ "    b.accountname, \r\n"
			+ "    b.accountcode, \r\n"
			+ "    b.natureofaccount, \r\n"
			+ "    m.month, \r\n"
			+ "    FIELD(m.month, 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December', 'January', 'February', 'March')\r\n"
			+ "ORDER BY\r\n"
			+ "    FIELD(m.month, 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December', 'January', 'February', 'March'); ")
	Set<Object[]> getRatioAnalysisBudgetGroupLedgersDetails(Long orgId, String year, String clientCode,
			String mainGroup, String subGroupCode);

	@Query(nativeQuery = true,value = "WITH Months AS (\r\n"
			+ "    SELECT 'April' AS month UNION ALL\r\n"
			+ "    SELECT 'May' UNION ALL\r\n"
			+ "    SELECT 'June' UNION ALL\r\n"
			+ "    SELECT 'July' UNION ALL\r\n"
			+ "    SELECT 'August' UNION ALL\r\n"
			+ "    SELECT 'September' UNION ALL\r\n"
			+ "    SELECT 'October' UNION ALL\r\n"
			+ "    SELECT 'November' UNION ALL\r\n"
			+ "    SELECT 'December' UNION ALL\r\n"
			+ "    SELECT 'January' UNION ALL\r\n"
			+ "    SELECT 'February' UNION ALL\r\n"
			+ "    SELECT 'March'\r\n"
			+ ")\r\n"
			+ "SELECT \r\n"
			+ "    b.accountname, \r\n"
			+ "    b.accountcode, \r\n"
			+ "    b.natureofaccount, \r\n"
			+ "    m.month, \r\n"
			+ "    COALESCE(SUM(b.amount), 0) AS totalamount \r\n"
			+ "from Months m\r\n"
			+ "LEFT JOIN previousyearactual b \r\n"
			+ "    on b.orgid = ?1\r\n"
			+ "    AND b.year = ?2\r\n"
			+ "    AND b.clientcode = ?3\r\n"
			+ "    AND b.maingroup = ?4\r\n"
			+ "    AND (b.subgroup = ?5)\r\n"
			+ "    AND b.month = m.month\r\n"
			+ "GROUP BY \r\n"
			+ "    b.accountname, \r\n"
			+ "    b.accountcode, \r\n"
			+ "    b.natureofaccount, \r\n"
			+ "    m.month, \r\n"
			+ "    FIELD(m.month, 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December', 'January', 'February', 'March')\r\n"
			+ "ORDER BY\r\n"
			+ "    FIELD(m.month, 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December', 'January', 'February', 'March')")
	Set<Object[]> getRatioAnalysisPYGroupLedgersDetails(Long orgId, String year, String clientCode, String mainGroup,
			String subGroupCode);

	@Query(nativeQuery = true,value = "select displayseq,accountname from groupledgers where groupname=?2 and orgid=?1 and active=1\r\n"
			+ "group by accountname,displayseq order by cast(displayseq as unsigned)asc")
	Set<Object[]> getLedgerDetailsForPL(Long orgId, String mainGroupName);

	@Query(nativeQuery = true, value = "select subgroupname from groupledgers where orgid=?1 and groupname=?2 and active=1\r\n"
			+ "group by subgroupname")
	Set<Object[]> getSubGroupDetailsForPL(Long orgId, String mainGroupName);

	@Query(nativeQuery = true,value = "select accountname,accountcode,groupname,subgroupname from groupledgers where orgid=?1 and groupname=?2 and active=1 and subgroupname=?3\r\n"
			+ "group by accountname,accountcode,groupname,subgroupname")
	Set<Object[]> getLedgerDetailsForSubGroupPL(Long orgId, String mainGroupName, String subGroupName);
	
	
	@Query(nativeQuery =  true, value = "with accounts as(  \r\n"
			+ "    SELECT \r\n"
			+ "        a.accountname,\r\n"
			+ "        a.accountcode,\r\n"
			+ "        CAST(a.displayseq AS UNSIGNED) AS displayseq\r\n"
			+ "    FROM groupledgers a\r\n"
			+ "    WHERE a.groupname = ?4\r\n"
			+ "      AND a.orgid = ?1\r\n"
			+ "      AND (a.subgroupname = ?5 OR ?5 = 'ALL') \r\n"
			+ "      AND a.active = 1)\r\n"
			+ "      select a.accountcode,a.accountname,amount,a.displayseq from Accounts a left join budgetincrementalprofit b ON a.accountname = b.accountname and b.orgid = ?1\r\n"
			+ "    AND b.year = ?2\r\n"
			+ "    AND b.clientcode = ?3 order by a.displayseq asc")
	Set<Object[]> getBudgetIncrementalLedgersDetails(Long orgId,String year,String clientCode, String mainGroup,String subGroup);
	
	
	@Query(nativeQuery =  true, value = "with accounts as(  \r\n"
			+ "    SELECT \r\n"
			+ "        a.accountname,\r\n"
			+ "        a.accountcode,\r\n"
			+ "        CAST(a.displayseq AS UNSIGNED) AS displayseq\r\n"
			+ "    FROM groupledgers a\r\n"
			+ "    WHERE a.groupname = ?4\r\n"
			+ "      AND a.orgid = ?1\r\n"
			+ "      AND (a.subgroupname = ?5 OR ?5 = 'ALL') \r\n"
			+ "      AND a.active = 1)\r\n"
			+ "      select a.accountcode,a.accountname,amount,a.displayseq from Accounts a left join pyincrementalprofit b ON a.accountname = b.accountname and b.orgid = ?1\r\n"
			+ "    AND b.year = ?2\r\n"
			+ "    AND b.clientcode = ?3 order by a.displayseq asc")
	Set<Object[]> getPYIncrementalLedgersDetails(Long orgId,String year,String clientCode, String mainGroup,String subGroup);

	@Query(nativeQuery =  true, value = "with accounts as(  \r\n"
			+ "    SELECT \r\n"
			+ "        a.accountname,\r\n"
			+ "        a.accountcode,\r\n"
			+ "        CAST(a.displayseq AS UNSIGNED) AS displayseq\r\n"
			+ "    FROM groupledgers a\r\n"
			+ "    WHERE a.groupname = ?4\r\n"
			+ "      AND a.orgid = ?1\r\n"
			+ "      AND (a.subgroupname = ?5 OR ?5 = 'ALL') \r\n"
			+ "      AND a.active = 1)\r\n"
			+ "      select a.accountcode,a.accountname,amount,a.displayseq from Accounts a left join pyincrementalprofit b ON a.accountname = b.accountname and b.orgid = ?1\r\n"
			+ "    AND b.year = ?2\r\n"
			+ "    AND b.clientcode = ?3 and b.month=?6 order by a.displayseq asc")
	Set<Object[]> getActualIncrementalLedgersDetails(Long orgId, String year, String clientCode, String mainGroup,
			String subGroup,String month);
}
