package com.base.basesetup.repo;

import java.util.List;
import java.util.Set;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import com.base.basesetup.entity.IssueManifestProviderVO;

@Repository
public interface IssueManifestProviderRepo extends JpaRepository<IssueManifestProviderVO, Long> {

	boolean existsByOrgIdAndTransactionNo(Long orgId, String transactionNo);  

	@Query(nativeQuery = true, value = "select * from mim where orgid=?1")
	List<IssueManifestProviderVO> findAllIssueManifeasrProvider(Long orgId);

	@Query(nativeQuery = true, value = "select * from mim where orgid=?1 and finyear=?2")
	List<IssueManifestProviderVO> getAllIssueManifestProvider(Long orgId, Long finYear);

	@Query(nativeQuery = true, value = "select transactionno,transactiondate,transportername,sender,receiver,amount,hsncode,b.assetcode,b.asset,b.assetqty,kitid,kitname,kitqty from \r\n"
			+ "finance_aip.mim a,finance_aip.mimdetails b where a.mimid = b.mimid and 'MIM' =?1 and a.orgid =?2 and (a.receiver=?3 or 'ALL'=?3) and a.finyear=?4 and (?5 is null or a.transactiondate >= ?5)  and (?6 is null or a.transactiondate <= ?6)\r\n"
			+ "union all \r\n"
			+ "select transactionno,transactiondate,transportername,sender,receiver,0 amount,hsncode,b.assetcode,b.asset,b.assetqty,kitid,kitname,kitqty from \r\n"
			+ "finance_aip.rim a,finance_aip.rimdetails b where a.rimid = b.rimid and  'RIM' =?1 and a.orgid =?2 and (a.sender=?3  or 'ALL'=?3) and a.finyear=?4\r\n"
			+ "and (?5 is null or a.transactiondate >= ?5)  and (?6 is null or a.transactiondate <= ?6)\r\n"
			+ "order by transactiondate")
	Set<Object[]> getMimReportDetails(String type, Long orgId, String customerName, String finYear, String toDate,
			String fromDate);

//	@Query(value = "SELECT \r\n" + "  m.*, \r\n" + "  ?1 AS type\r\n" + "FROM \r\n" + "  mim m\r\n" + "WHERE \r\n"
//			+ "  m.orgid = ?2\r\n" + "  AND m.finyear = ?4\r\n" + "  AND (\r\n" + "    (\r\n"
//			+ "      ?3 IS NOT NULL \r\n" + "      AND ?5 IS NOT NULL \r\n" + "      AND ?6 IS NOT NULL\r\n"
//			+ "      AND m.receiver = ?3\r\n" + "      AND m.transactiondate BETWEEN ?6 AND ?5\r\n" + "    )\r\n"
//			+ "    OR (\r\n" + "      ?3 IS NULL OR ?5 IS NULL OR ?6 IS NULL\r\n" + "    )\r\n"
//			+ "  )", nativeQuery = true)
//	List<IssueManifestProviderVO> findMIMReports(String type, Long orgId, String customerName, String finYear,
//			String toDate, String fromDate);

	@Query(value = "SELECT *\r\n" + "FROM mim a\r\n" + "WHERE ?1 = 'MIM'\r\n" + "  AND a.orgid =?2\r\n"
			+ "  AND (a.receiver =?3 OR ?3 = 'ALL')\r\n" + "  AND a.finyear = ?4\r\n"
			+ "  AND (?6 IS NULL OR a.transactiondate >=?6)\r\n" + "  AND (?5 IS NULL OR a.transactiondate <= ?5)\r\n"
			+ "  order by  a.transactionno ,a.transactiondate", nativeQuery = true)
	List<IssueManifestProviderVO> findMIMReports(String type, Long orgId, String customerName, String finYear,
			String toDate, String fromDate);

//	@Query(value = "SELECT \r\n" + "  a.*, \r\n" + "  ?1 AS type\r\n" + "FROM \r\n" + "  rim a\r\n" + "WHERE \r\n"
//			+ "  a.orgid = ?2\r\n" + "  AND a.finyear = ?4\r\n" + "  AND (\r\n" + "    (\r\n"
//			+ "      ?3 IS NOT NULL \r\n" + "      AND ?5 IS NOT NULL \r\n" + "      AND ?6 IS NOT NULL\r\n"
//			+ "      AND a.sender = ?3\r\n" + "      AND a.transactiondate BETWEEN ?6 AND ?5\r\n" + "    )\r\n"
//			+ "    OR (\r\n" + "      ?3 IS NULL OR ?5 IS NULL OR ?6 IS NULL\r\n" + "    )\r\n"
//			+ "  )",
//    nativeQuery = true)
//List<RetrievalManifestProviderVO> findRIMReports(String type, Long orgId, String sender, String finYear, String toDate, String fromDate);

	@Query(nativeQuery = true, value = "select transactionno,transactiondate,transportername,receiver,amount,hsncode,SUM(kitqty) as sum ,sender from (\r\n"
			+ "			      select  transactionno,transactiondate,transportername,receiver,amount,hsncode,kitqty,orgid,finyear,sender  from mim a,mimdetails m where a.mimid =m.mimid \r\n"
			+ "			     group by transactionno,transactiondate,transportername,receiver,kitid,amount,hsncode,kitqty,orgid,finyear,sender\r\n"
			+ "			      order by transactionno,transactiondate) A  where \r\n"
			+ "                  ?1 = 'MIM'\r\n" + "  AND a.orgid =?2\r\n" + "  AND (a.receiver =?3 OR ?3 = 'ALL')\r\n"
			+ "  AND a.finyear =?4\r\n" + "  AND (?5 IS NULL OR a.transactiondate >=?5)\r\n"
			+ "  AND (?6  IS NULL OR a.transactiondate <=?6) \r\n"
			+ " group by transactionno,transactiondate,transportername,receiver,amount,hsncode,sender")
	Set<Object[]> findMimSummaryReport(String type, Long orgId, String customerName, String finYear, String fromDate,
			String toDate);

	@Query(nativeQuery = true, value = "select transactionno,transactiondate,transportername,sender,0 as  amount,hsncode,SUM(kitqty)  from (\r\n"
			+ "			      select  transactionno,transactiondate,transportername,sender,hsncode,kitqty,orgid,finyear  from rim a,rimdetails m where a.rimid =m.rimid \r\n"
			+ "			     group by transactionno,transactiondate,transportername,sender,kitid,hsncode,kitqty,orgid,finyear\r\n"
			+ "			      order by transactionno,transactiondate) A  where \r\n"
			+ "                  ?1 = 'RIM'\r\n" + "  AND a.orgid =?2\r\n" + "  AND (a.sender =?3 OR ?3 = 'ALL')\r\n"
			+ "  AND a.finyear =?4\r\n" + "  AND (?5 IS NULL OR a.transactiondate >=?5)\r\n"
			+ "  AND (?6  IS NULL OR a.transactiondate <=?6) \r\n"
			+ " group by transactionno,transactiondate,transportername,sender,hsncode")
	Set<Object[]> findRimSummaryReport(String type, Long orgId, String customerName, String finYear, String fromDate,
			String toDate);

//	@Query(nativeQuery = true, value = "SELECT sno,arapdetailsid,branch,subledgercode,subledgername,partytype,salesperson,docid,docdate,\r\n"
//			+ "supprefno,suprefdate,duedate,refno,refdate,amount,outstanding,totaldue,unadjusted,ddays,mslab1,mslab2,mslab3,mslab4,mslab5,creditlimit,creditdays FROM (\r\n"
//			+ "   select 1 sno,t.arapdetailsid,\r\n" + "         t.branch,\r\n" + "         t.subledgercode,\r\n"
//			+ "        CONCAT(t.subledgername, ' , Cr. Limit - ', t.creditlimit, ' , Cr. Days - ', t.creditdays) AS subledgername,\r\n"
//			+ "         t.partytype,\r\n" + "         t.salesperson,\r\n" + "         t.docid,\r\n"
//			+ "         t.docdate,\r\n" + "         t.supprefno,\r\n" + "         t.suprefdate,\r\n"
//			+ "         t.duedate,\r\n" + "         t.refno,\r\n" + "         t.refdate,\r\n"
//			+ "         case when ?5 = 'Base' then t.bamount when ?5='Native' then t.namount else  t.amount end as amount,\r\n"
//			+ "         case when ?5 = 'Base'  then t.boutstanding when ?5='Native'then t.noutstanding else t.outstanding end as outstanding,\r\n"
//			+ "         case when  ?5 = 'Base' then t.btotaldue when  ?5='Native' then t.ntotaldue else  t.totaldue end as totaldue,\r\n"
//			+ "         case when ?5 = 'Base' then t.bunadjusted when ?5='Native'then t.nunadjusted else t.unadjusted end as unadjusted,\r\n"
//			+ "         t.ddays,CASE \r\n" + "    WHEN ?5 = 'Base' THEN t.bmslab1\r\n"
//			+ "    WHEN ?5 = 'Native' THEN t.nmslab1\r\n" + "    ELSE t.mslab1\r\n" + "  END AS mslab1,\r\n"
//			+ "  CASE \r\n" + "    WHEN ?5 = 'Base' THEN t.bmslab2\r\n" + "    WHEN ?5 = 'Native' THEN t.nmslab2\r\n"
//			+ "    ELSE t.mslab2\r\n" + "  END AS mslab2,\r\n" + "  CASE \r\n"
//			+ "    WHEN ?5 = 'Base' THEN t.bmslab3\r\n" + "    WHEN ?5 = 'Native' THEN t.nmslab3\r\n"
//			+ "    ELSE t.mslab3\r\n" + "  END AS mslab3,\r\n" + "  CASE \r\n"
//			+ "    WHEN ?5 = 'Base' THEN t.bmslab4\r\n" + "    WHEN ?5 = 'Native' THEN t.nmslab4\r\n"
//			+ "    ELSE t.mslab4\r\n" + "  END AS mslab4,\r\n" + "\r\n" + "  CASE \r\n"
//			+ "    WHEN ?5 = 'Base' THEN t.bmslab5 + t.bmslab6 + t.bmslab7\r\n"
//			+ "    WHEN ?5 = 'Native' THEN t.nmslab5 + t.nmslab6 + t.nmslab7\r\n"
//			+ "    ELSE t.mslab5 + t.mslab6 + t.mslab7\r\n" + "  END AS mslab5,\r\n"
//			+ "        t.creditlimit,t.creditdays from(\r\n" + "select  a.arapdetailsid,\r\n"
//			+ "                   jbr.branch,\r\n" + "                   P.PARTYCODE subledgercode,\r\n"
//			+ "                   p.partyname subledgername,\r\n" + "                   p.partytype subledgertype,\r\n"
//			+ "                   CASE\r\n"
//			+ "                      WHEN  (p.gstregistered LIKE 'Y%') THEN 'GST Party'\r\n"
//			+ "                      ELSE 'ST Party'\r\n" + "                   END\r\n"
//			+ "                      Partytype,\r\n" + "                   p.creditlimit,\r\n"
//			+ "                   p.creditdays,\r\n" + "                   p.salesperson,a.docid ,\r\n"
//			+ "                   a.docdate,\r\n" + "                   a.supprefno,\r\n"
//			+ "                   a.suprefdate,\r\n"
//			+ "                   DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) duedate,\r\n"
//			+ "                   a.refno,\r\n" + "                   a.refdate,\r\n"
//			+ "                   a.amount AS amount,CASE\r\n"
//			+ "                      WHEN  (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                      THEN\r\n" + "                         0\r\n" + "                      ELSE\r\n"
//			+ "                         a.amount + SUM(r.amount)\r\n" + "                   END\r\n"
//			+ "                      AS outstanding,a.amount + SUM(r.amount) AS totaldue,a.baseamt AS bamount,CASE\r\n"
//			+ "                      WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                      THEN\r\n" + "                         0\r\n" + "                      ELSE\r\n"
//			+ "                         a.baseamt + SUM(r.baseamt)\r\n" + "                   END\r\n"
//			+ "                      AS boutstanding,a.baseamt + SUM(r.baseamt) AS btotaldue,a.nativeamt AS namount,\r\n"
//			+ "                   CASE\r\n"
//			+ "                        WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                      THEN\r\n" + "                         0\r\n" + "                      ELSE\r\n"
//			+ "                         a.nativeamt + SUM(r.nativeamt)\r\n" + "                   END\r\n"
//			+ "                      AS noutstanding,\r\n"
//			+ "                   a.nativeamt + SUM(r.nativeamt) AS ntotaldue,CASE\r\n"
//			+ "                      WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                           AND a.amount +SUM(r.amount) <> 0\r\n" + "                      THEN\r\n"
//			+ "                         a.amount +SUM(r.amount)\r\n" + "                      ELSE\r\n"
//			+ "                         0\r\n" + "                   END\r\n"
//			+ "                      AS unadjusted,CASE\r\n"
//			+ "                       WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                           AND a.baseamt +SUM(r.baseamt) <> 0\r\n" + "                      THEN\r\n"
//			+ "                         a.baseamt +SUM(r.baseamt)\r\n" + "                      ELSE\r\n"
//			+ "                         0\r\n" + "                   END\r\n"
//			+ "                      AS bunadjusted,CASE\r\n"
//			+ "                       WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                           AND a.nativeamt +SUM(r.nativeamt) <> 0\r\n" + "                      THEN\r\n"
//			+ "                         a.nativeamt +SUM(r.nativeamt)\r\n" + "                      ELSE\r\n"
//			+ "                         0\r\n" + "                   END\r\n"
//			+ "                      AS nunadjusted,date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY)\r\n"
//			+ "                      AS ddays,CASE\r\n"
//			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY)<31 THEN\r\n"
//			+ "                         CASE\r\n"
//			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                            THEN\r\n" + "                               0\r\n"
//			+ "                            ELSE\r\n" + "                               a.amount + SUM(r.amount)\r\n"
//			+ "                         END\r\n" + "                      ELSE\r\n" + "                         0\r\n"
//			+ "                   END\r\n" + "                      AS mslab1,CASE\r\n"
//			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY)<31 THEN\r\n"
//			+ "                         CASE\r\n"
//			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                            THEN\r\n" + "                               0\r\n"
//			+ "                            ELSE\r\n" + "                               a.baseamt + SUM(r.baseamt)\r\n"
//			+ "                         END\r\n" + "                      ELSE\r\n" + "                         0\r\n"
//			+ "                   END\r\n" + "                      AS bmslab1,CASE\r\n"
//			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY)<31 THEN\r\n"
//			+ "                         CASE\r\n"
//			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                            THEN\r\n" + "                               0\r\n"
//			+ "                            ELSE\r\n"
//			+ "                               a.nativeamt + SUM(r.nativeamt)\r\n" + "                         END\r\n"
//			+ "                      ELSE\r\n" + "                         0\r\n" + "                   END\r\n"
//			+ "                      AS nmslab1,CASE\r\n"
//			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 31 and 60 THEN\r\n"
//			+ "                         CASE\r\n"
//			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                            THEN\r\n" + "                               0\r\n"
//			+ "                            ELSE\r\n" + "                               a.amount + SUM(r.amount)\r\n"
//			+ "                         END\r\n" + "                      ELSE\r\n" + "                         0\r\n"
//			+ "                   END\r\n" + "                      AS mslab2,CASE\r\n"
//			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 31 and 60 THEN\r\n"
//			+ "                         CASE\r\n"
//			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                            THEN\r\n" + "                               0\r\n"
//			+ "                            ELSE\r\n" + "                               a.baseamt + SUM(r.baseamt)\r\n"
//			+ "                         END\r\n" + "                      ELSE\r\n" + "                         0\r\n"
//			+ "                   END\r\n" + "                      AS bmslab2,\r\n" + "                      CASE\r\n"
//			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 31 and 60 THEN\r\n"
//			+ "                         CASE\r\n"
//			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                            THEN\r\n" + "                               0\r\n"
//			+ "                            ELSE\r\n"
//			+ "                               a.nativeamt + SUM(r.nativeamt)\r\n" + "                         END\r\n"
//			+ "                      ELSE\r\n" + "                         0\r\n" + "                   END\r\n"
//			+ "                      AS nmslab2,\r\n" + "                      CASE\r\n"
//			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 61 and 90 THEN\r\n"
//			+ "                         CASE\r\n"
//			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                            THEN\r\n" + "                               0\r\n"
//			+ "                            ELSE\r\n" + "                               a.amount + SUM(r.amount)\r\n"
//			+ "                         END\r\n" + "                      ELSE\r\n" + "                         0\r\n"
//			+ "                   END\r\n" + "                      AS mslab3,CASE\r\n"
//			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 61 and 90 THEN\r\n"
//			+ "                         CASE\r\n"
//			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                            THEN\r\n" + "                               0\r\n"
//			+ "                            ELSE\r\n" + "                               a.baseamt + SUM(r.baseamt)\r\n"
//			+ "                         END\r\n" + "                      ELSE\r\n" + "                         0\r\n"
//			+ "                   END\r\n" + "                      AS bmslab3,\r\n" + "                      CASE\r\n"
//			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 61 and 90 THEN\r\n"
//			+ "                         CASE\r\n"
//			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                            THEN\r\n" + "                               0\r\n"
//			+ "                            ELSE\r\n"
//			+ "                               a.nativeamt + SUM(r.nativeamt)\r\n" + "                         END\r\n"
//			+ "                      ELSE\r\n" + "                         0\r\n" + "                   END\r\n"
//			+ "                      AS nmslab3,CASE\r\n"
//			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 91 and 120 THEN\r\n"
//			+ "                         CASE\r\n"
//			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                            THEN\r\n" + "                               0\r\n"
//			+ "                            ELSE\r\n" + "                               a.amount + SUM(r.amount)\r\n"
//			+ "                         END\r\n" + "                      ELSE\r\n" + "                         0\r\n"
//			+ "                   END\r\n" + "                      AS mslab4,CASE\r\n"
//			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 91 and 120 THEN\r\n"
//			+ "                         CASE\r\n"
//			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                            THEN\r\n" + "                               0\r\n"
//			+ "                            ELSE\r\n" + "                               a.baseamt + SUM(r.baseamt)\r\n"
//			+ "                         END\r\n" + "                      ELSE\r\n" + "                         0\r\n"
//			+ "                   END\r\n" + "                      AS bmslab4,\r\n" + "                      CASE\r\n"
//			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 91 and 120 THEN\r\n"
//			+ "                         CASE\r\n"
//			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                            THEN\r\n" + "                               0\r\n"
//			+ "                            ELSE\r\n"
//			+ "                               a.nativeamt + SUM(r.nativeamt)\r\n" + "                         END\r\n"
//			+ "                      ELSE\r\n" + "                         0\r\n" + "                   END\r\n"
//			+ "                      AS nmslab4,CASE\r\n"
//			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 121 and 150 THEN\r\n"
//			+ "                         CASE\r\n"
//			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                            THEN\r\n" + "                               0\r\n"
//			+ "                            ELSE\r\n" + "                               a.amount + SUM(r.amount)\r\n"
//			+ "                         END\r\n" + "                      ELSE\r\n" + "                         0\r\n"
//			+ "                   END\r\n" + "                      AS mslab5,CASE\r\n"
//			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 121 and 150 THEN\r\n"
//			+ "                         CASE\r\n"
//			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                            THEN\r\n" + "                               0\r\n"
//			+ "                            ELSE\r\n" + "                               a.baseamt + SUM(r.baseamt)\r\n"
//			+ "                         END\r\n" + "                      ELSE\r\n" + "                         0\r\n"
//			+ "                   END\r\n" + "                      AS bmslab5,\r\n" + "                      CASE\r\n"
//			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 121 and 150 THEN\r\n"
//			+ "                         CASE\r\n"
//			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                            THEN\r\n" + "                               0\r\n"
//			+ "                            ELSE\r\n"
//			+ "                               a.nativeamt + SUM(r.nativeamt)\r\n" + "                         END\r\n"
//			+ "                      ELSE\r\n" + "                         0\r\n" + "                   END\r\n"
//			+ "                      AS nmslab5,CASE\r\n"
//			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 151 and 180 THEN\r\n"
//			+ "                         CASE\r\n"
//			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                            THEN\r\n" + "                               0\r\n"
//			+ "                            ELSE\r\n" + "                               a.amount + SUM(r.amount)\r\n"
//			+ "                         END\r\n" + "                      ELSE\r\n" + "                         0\r\n"
//			+ "                   END\r\n" + "                      AS mslab6,CASE\r\n"
//			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 151 and 180 THEN\r\n"
//			+ "                         CASE\r\n"
//			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                            THEN\r\n" + "                               0\r\n"
//			+ "                            ELSE\r\n" + "                               a.baseamt + SUM(r.baseamt)\r\n"
//			+ "                         END\r\n" + "                      ELSE\r\n" + "                         0\r\n"
//			+ "                   END\r\n" + "                      AS bmslab6,\r\n" + "                      CASE\r\n"
//			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 151 and 180 THEN\r\n"
//			+ "                         CASE\r\n"
//			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                            THEN\r\n" + "                               0\r\n"
//			+ "                            ELSE\r\n"
//			+ "                               a.nativeamt + SUM(r.nativeamt)\r\n" + "                         END\r\n"
//			+ "                      ELSE\r\n" + "                         0\r\n" + "                   END\r\n"
//			+ "                      AS nmslab6,CASE\r\n"
//			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) >180 THEN\r\n"
//			+ "                         CASE\r\n"
//			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                            THEN\r\n" + "                               0\r\n"
//			+ "                            ELSE\r\n" + "                               a.amount + SUM(r.amount)\r\n"
//			+ "                         END\r\n" + "                      ELSE\r\n" + "                         0\r\n"
//			+ "                   END\r\n" + "                      AS mslab7,CASE\r\n"
//			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) >180 THEN\r\n"
//			+ "                         CASE\r\n"
//			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                            THEN\r\n" + "                               0\r\n"
//			+ "                            ELSE\r\n" + "                               a.baseamt + SUM(r.baseamt)\r\n"
//			+ "                         END\r\n" + "                      ELSE\r\n" + "                         0\r\n"
//			+ "                   END\r\n" + "                      AS bmslab7,\r\n" + "                      CASE\r\n"
//			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) > 180 THEN\r\n"
//			+ "                         CASE\r\n"
//			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                            THEN\r\n" + "                               0\r\n"
//			+ "                            ELSE\r\n"
//			+ "                               a.nativeamt + SUM(r.nativeamt)\r\n" + "                         END\r\n"
//			+ "                      ELSE\r\n" + "                         0\r\n" + "                   END\r\n"
//			+ "                      AS nmslab7 from arapdetails a\r\n"
//			+ "LEFT JOIN arapadjustments r ON a.subledgercode = r.subledgercode AND r.cancel = 0\r\n"
//			+ "LEFT JOIN accounts ac ON a.docid = ac.docid and r.docid=ac.vid\r\n"
//			+ "JOIN partymaster p ON a.subledgercode = p.partycode\r\n" + "JOIN branch jbr ON a.branch = jbr.branch\r\n"
//			+ "JOIN groupledger b\r\n" + "JOIN branch br ON a.branch = br.branch\r\n" + "WHERE \r\n"
//			+ "    a.docdate <= DATE(?4) and   a.orgid=r.orgid and r.orgid=p.orgid and b.orgid=r.orgid and p.orgid=br.orgid and r.orgid = ?1\r\n"
//			+ "    AND a.cancel = 0 and p.partytype='CUSTOMER' and (p.partyname = ?3 or ?3 ='ALL')\r\n"
//			+ "    AND (br.branch = ?2 or ?2 ='ALL')\r\n"
//			+ "    AND b.category = 'RECEIVABLE A/C' group by a.arapdetailsid,\r\n"
//			+ "                   jbr.branch,\r\n" + "                   P.PARTYCODE ,\r\n"
//			+ "                   p.partyname ,\r\n" + "                   p.partytype,\r\n"
//			+ "                   p.creditlimit,\r\n" + "                   p.gstregistered,\r\n"
//			+ "                   p.creditdays,\r\n" + "                   p.salesperson,a.docid ,\r\n"
//			+ "                   a.docdate,\r\n" + "                   a.supprefno,\r\n"
//			+ "                   a.suprefdate,\r\n" + "                   a.refno,\r\n"
//			+ "                   a.refdate,\r\n"
//			+ "                   a.amount HAVING (a.amount + SUM(r.amount) != 0))t where t.refno not like('%RT%') and t.refno not like('%PT%') ORDER BY t.branch,t.subledgername,\r\n"
//			+ "         t.partytype,\r\n" + "         t.docdate,\r\n" + "         t.docid\r\n" + ") y\r\n"
//			+ "UNION ALL\r\n" + "SELECT \r\n"
//			+ "   2 sno, NULL arapdetailsid, NULL branch, NULL subledgercode, 'Total' subledgername,\r\n"
//			+ "    NULL partytype, NULL salesperson, NULL docid, NULL docdate, NULL supprefno, NULL suprefdate, NULL duedate, NULL refno, null refdate,\r\n"
//			+ "    SUM(w.amount) amount, SUM(w.outstanding)outstanding , SUM(w.totaldue) totaldue, SUM(w.unadjusted)unadjusted, NULL ddays,\r\n"
//			+ "    SUM(w.mslab1)mslab1, SUM(w.mslab2)mslab2, SUM(w.mslab3)mslab3, SUM(w.mslab4)mslab4, SUM(w.mslab5)mslab5,\r\n"
//			+ "    NULL creditlimit, NULL creditlimit\r\n" + "FROM (\r\n" + "    select t.arapdetailsid,\r\n"
//			+ "         t.branch,\r\n" + "         t.subledgercode,\r\n"
//			+ "        CONCAT(t.subledgername, ' , Cr. Limit - ', t.creditlimit, ' , Cr. Days - ', t.creditdays) AS subledgername,\r\n"
//			+ "         t.partytype,\r\n" + "         t.salesperson,\r\n" + "         t.docid,\r\n"
//			+ "         t.docdate,\r\n" + "         t.supprefno,\r\n" + "         t.suprefdate,\r\n"
//			+ "         t.duedate,\r\n" + "         t.refno,\r\n" + "         t.refdate,\r\n"
//			+ "         case when ?5 = 'Base' then t.bamount when ?5='Native' then t.namount else  t.amount end as amount,\r\n"
//			+ "         case when ?5 = 'Base' then t.boutstanding when ?5='Native'then t.noutstanding else t.outstanding end as outstanding,\r\n"
//			+ "         case when  ?5 = 'Base' then t.btotaldue when  ?5='Native' then t.ntotaldue else  t.totaldue end as totaldue,\r\n"
//			+ "         case when ?5 = 'Base'then t.bunadjusted when ?5='Native'then t.nunadjusted else t.unadjusted end as unadjusted,\r\n"
//			+ "         t.ddays,CASE \r\n" + "    WHEN ?5 = 'Base' THEN t.bmslab1\r\n"
//			+ "    WHEN ?5 = 'Native' THEN t.nmslab1\r\n" + "    ELSE t.mslab1\r\n" + "  END AS mslab1,\r\n"
//			+ "  CASE \r\n" + "    WHEN ?5 = 'Base' THEN t.bmslab2\r\n" + "    WHEN ?5 = 'Native' THEN t.nmslab2\r\n"
//			+ "    ELSE t.mslab2\r\n" + "  END AS mslab2,\r\n" + "  CASE \r\n"
//			+ "    WHEN ?5 = 'Base' THEN t.bmslab3\r\n" + "    WHEN ?5 = 'Native' THEN t.nmslab3\r\n"
//			+ "    ELSE t.mslab3\r\n" + "  END AS mslab3,\r\n" + "  CASE \r\n"
//			+ "    WHEN ?5 = 'Base' THEN t.bmslab4\r\n" + "    WHEN ?5 = 'Native' THEN t.nmslab4\r\n"
//			+ "    ELSE t.mslab4\r\n" + "  END AS mslab4,\r\n" + "\r\n" + "  CASE \r\n"
//			+ "    WHEN ?5 = 'Base' THEN t.bmslab5 + t.bmslab6 + t.bmslab7\r\n"
//			+ "    WHEN ?5 = 'Native' THEN t.nmslab5 + t.nmslab6 + t.nmslab7\r\n"
//			+ "    ELSE t.mslab5 + t.mslab6 + t.mslab7\r\n" + "  END AS mslab5,\r\n"
//			+ "        t.creditlimit,t.creditdays from(\r\n" + "select  a.arapdetailsid,\r\n"
//			+ "                   jbr.branch,\r\n" + "                   P.PARTYCODE subledgercode,\r\n"
//			+ "                   p.partyname subledgername,\r\n" + "                   p.partytype subledgertype,\r\n"
//			+ "                   CASE\r\n"
//			+ "                      WHEN  (p.gstregistered LIKE 'Y%') THEN 'GST Party'\r\n"
//			+ "                      ELSE 'ST Party'\r\n" + "                   END\r\n"
//			+ "                      Partytype,\r\n" + "                   p.creditlimit,\r\n"
//			+ "                   p.creditdays,\r\n" + "                   p.salesperson,a.docid ,\r\n"
//			+ "                   a.docdate,\r\n" + "                   a.supprefno,\r\n"
//			+ "                   a.suprefdate,\r\n"
//			+ "                   DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) duedate,\r\n"
//			+ "                   a.refno,\r\n" + "                   a.refdate,\r\n"
//			+ "                   a.amount AS amount,CASE\r\n"
//			+ "                      WHEN  (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                      THEN\r\n" + "                         0\r\n" + "                      ELSE\r\n"
//			+ "                         a.amount + SUM(r.amount)\r\n" + "                   END\r\n"
//			+ "                      AS outstanding,a.amount + SUM(r.amount) AS totaldue,a.baseamt AS bamount,CASE\r\n"
//			+ "                      WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                      THEN\r\n" + "                         0\r\n" + "                      ELSE\r\n"
//			+ "                         a.baseamt + SUM(r.baseamt)\r\n" + "                   END\r\n"
//			+ "                      AS boutstanding,a.baseamt + SUM(r.baseamt) AS btotaldue,a.nativeamt AS namount,\r\n"
//			+ "                   CASE\r\n"
//			+ "                        WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                      THEN\r\n" + "                         0\r\n" + "                      ELSE\r\n"
//			+ "                         a.nativeamt + SUM(r.nativeamt)\r\n" + "                   END\r\n"
//			+ "                      AS noutstanding,\r\n"
//			+ "                   a.nativeamt + SUM(r.nativeamt) AS ntotaldue,CASE\r\n"
//			+ "                      WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                           AND a.amount +SUM(r.amount) <> 0\r\n" + "                      THEN\r\n"
//			+ "                         a.amount +SUM(r.amount)\r\n" + "                      ELSE\r\n"
//			+ "                         0\r\n" + "                   END\r\n"
//			+ "                      AS unadjusted,CASE\r\n"
//			+ "                       WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                           AND a.baseamt +SUM(r.baseamt) <> 0\r\n" + "                      THEN\r\n"
//			+ "                         a.baseamt +SUM(r.baseamt)\r\n" + "                      ELSE\r\n"
//			+ "                         0\r\n" + "                   END\r\n"
//			+ "                      AS bunadjusted,CASE\r\n"
//			+ "                       WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                           AND a.nativeamt +SUM(r.nativeamt) <> 0\r\n" + "                      THEN\r\n"
//			+ "                         a.nativeamt +SUM(r.nativeamt)\r\n" + "                      ELSE\r\n"
//			+ "                         0\r\n" + "                   END\r\n"
//			+ "                      AS nunadjusted,date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY)\r\n"
//			+ "                      AS ddays,CASE\r\n"
//			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY)<31 THEN\r\n"
//			+ "                         CASE\r\n"
//			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                            THEN\r\n" + "                               0\r\n"
//			+ "                            ELSE\r\n" + "                               a.amount + SUM(r.amount)\r\n"
//			+ "                         END\r\n" + "                      ELSE\r\n" + "                         0\r\n"
//			+ "                   END\r\n" + "                      AS mslab1,CASE\r\n"
//			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY)<31 THEN\r\n"
//			+ "                         CASE\r\n"
//			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                            THEN\r\n" + "                               0\r\n"
//			+ "                            ELSE\r\n" + "                               a.baseamt + SUM(r.baseamt)\r\n"
//			+ "                         END\r\n" + "                      ELSE\r\n" + "                         0\r\n"
//			+ "                   END\r\n" + "                      AS bmslab1,CASE\r\n"
//			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY)<31 THEN\r\n"
//			+ "                         CASE\r\n"
//			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                            THEN\r\n" + "                               0\r\n"
//			+ "                            ELSE\r\n"
//			+ "                               a.nativeamt + SUM(r.nativeamt)\r\n" + "                         END\r\n"
//			+ "                      ELSE\r\n" + "                         0\r\n" + "                   END\r\n"
//			+ "                      AS nmslab1,CASE\r\n"
//			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 31 and 60 THEN\r\n"
//			+ "                         CASE\r\n"
//			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                            THEN\r\n" + "                               0\r\n"
//			+ "                            ELSE\r\n" + "                               a.amount + SUM(r.amount)\r\n"
//			+ "                         END\r\n" + "                      ELSE\r\n" + "                         0\r\n"
//			+ "                   END\r\n" + "                      AS mslab2,CASE\r\n"
//			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 31 and 60 THEN\r\n"
//			+ "                         CASE\r\n"
//			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                            THEN\r\n" + "                               0\r\n"
//			+ "                            ELSE\r\n" + "                               a.baseamt + SUM(r.baseamt)\r\n"
//			+ "                         END\r\n" + "                      ELSE\r\n" + "                         0\r\n"
//			+ "                   END\r\n" + "                      AS bmslab2,\r\n" + "                      CASE\r\n"
//			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 31 and 60 THEN\r\n"
//			+ "                         CASE\r\n"
//			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                            THEN\r\n" + "                               0\r\n"
//			+ "                            ELSE\r\n"
//			+ "                               a.nativeamt + SUM(r.nativeamt)\r\n" + "                         END\r\n"
//			+ "                      ELSE\r\n" + "                         0\r\n" + "                   END\r\n"
//			+ "                      AS nmslab2,\r\n" + "                      CASE\r\n"
//			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 61 and 90 THEN\r\n"
//			+ "                         CASE\r\n"
//			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                            THEN\r\n" + "                               0\r\n"
//			+ "                            ELSE\r\n" + "                               a.amount + SUM(r.amount)\r\n"
//			+ "                         END\r\n" + "                      ELSE\r\n" + "                         0\r\n"
//			+ "                   END\r\n" + "                      AS mslab3,CASE\r\n"
//			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 61 and 90 THEN\r\n"
//			+ "                         CASE\r\n"
//			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                            THEN\r\n" + "                               0\r\n"
//			+ "                            ELSE\r\n" + "                               a.baseamt + SUM(r.baseamt)\r\n"
//			+ "                         END\r\n" + "                      ELSE\r\n" + "                         0\r\n"
//			+ "                   END\r\n" + "                      AS bmslab3,\r\n" + "                      CASE\r\n"
//			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 61 and 90 THEN\r\n"
//			+ "                         CASE\r\n"
//			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                            THEN\r\n" + "                               0\r\n"
//			+ "                            ELSE\r\n"
//			+ "                               a.nativeamt + SUM(r.nativeamt)\r\n" + "                         END\r\n"
//			+ "                      ELSE\r\n" + "                         0\r\n" + "                   END\r\n"
//			+ "                      AS nmslab3,CASE\r\n"
//			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 91 and 120 THEN\r\n"
//			+ "                         CASE\r\n"
//			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                            THEN\r\n" + "                               0\r\n"
//			+ "                            ELSE\r\n" + "                               a.amount + SUM(r.amount)\r\n"
//			+ "                         END\r\n" + "                      ELSE\r\n" + "                         0\r\n"
//			+ "                   END\r\n" + "                      AS mslab4,CASE\r\n"
//			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 91 and 120 THEN\r\n"
//			+ "                         CASE\r\n"
//			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                            THEN\r\n" + "                               0\r\n"
//			+ "                            ELSE\r\n" + "                               a.baseamt + SUM(r.baseamt)\r\n"
//			+ "                         END\r\n" + "                      ELSE\r\n" + "                         0\r\n"
//			+ "                   END\r\n" + "                      AS bmslab4,\r\n" + "                      CASE\r\n"
//			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 91 and 120 THEN\r\n"
//			+ "                         CASE\r\n"
//			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                            THEN\r\n" + "                               0\r\n"
//			+ "                            ELSE\r\n"
//			+ "                               a.nativeamt + SUM(r.nativeamt)\r\n" + "                         END\r\n"
//			+ "                      ELSE\r\n" + "                         0\r\n" + "                   END\r\n"
//			+ "                      AS nmslab4,CASE\r\n"
//			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 121 and 150 THEN\r\n"
//			+ "                         CASE\r\n"
//			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                            THEN\r\n" + "                               0\r\n"
//			+ "                            ELSE\r\n" + "                               a.amount + SUM(r.amount)\r\n"
//			+ "                         END\r\n" + "                      ELSE\r\n" + "                         0\r\n"
//			+ "                   END\r\n" + "                      AS mslab5,CASE\r\n"
//			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 121 and 150 THEN\r\n"
//			+ "                         CASE\r\n"
//			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                            THEN\r\n" + "                               0\r\n"
//			+ "                            ELSE\r\n" + "                               a.baseamt + SUM(r.baseamt)\r\n"
//			+ "                         END\r\n" + "                      ELSE\r\n" + "                         0\r\n"
//			+ "                   END\r\n" + "                      AS bmslab5,\r\n" + "                      CASE\r\n"
//			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 121 and 150 THEN\r\n"
//			+ "                         CASE\r\n"
//			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                            THEN\r\n" + "                               0\r\n"
//			+ "                            ELSE\r\n"
//			+ "                               a.nativeamt + SUM(r.nativeamt)\r\n" + "                         END\r\n"
//			+ "                      ELSE\r\n" + "                         0\r\n" + "                   END\r\n"
//			+ "                      AS nmslab5,CASE\r\n"
//			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 151 and 180 THEN\r\n"
//			+ "                         CASE\r\n"
//			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                            THEN\r\n" + "                               0\r\n"
//			+ "                            ELSE\r\n" + "                               a.amount + SUM(r.amount)\r\n"
//			+ "                         END\r\n" + "                      ELSE\r\n" + "                         0\r\n"
//			+ "                   END\r\n" + "                      AS mslab6,CASE\r\n"
//			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 151 and 180 THEN\r\n"
//			+ "                         CASE\r\n"
//			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                            THEN\r\n" + "                               0\r\n"
//			+ "                            ELSE\r\n" + "                               a.baseamt + SUM(r.baseamt)\r\n"
//			+ "                         END\r\n" + "                      ELSE\r\n" + "                         0\r\n"
//			+ "                   END\r\n" + "                      AS bmslab6,\r\n" + "                      CASE\r\n"
//			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 151 and 180 THEN\r\n"
//			+ "                         CASE\r\n"
//			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                            THEN\r\n" + "                               0\r\n"
//			+ "                            ELSE\r\n"
//			+ "                               a.nativeamt + SUM(r.nativeamt)\r\n" + "                         END\r\n"
//			+ "                      ELSE\r\n" + "                         0\r\n" + "                   END\r\n"
//			+ "                      AS nmslab6,CASE\r\n"
//			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) >180 THEN\r\n"
//			+ "                         CASE\r\n"
//			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                            THEN\r\n" + "                               0\r\n"
//			+ "                            ELSE\r\n" + "                               a.amount + SUM(r.amount)\r\n"
//			+ "                         END\r\n" + "                      ELSE\r\n" + "                         0\r\n"
//			+ "                   END\r\n" + "                      AS mslab7,CASE\r\n"
//			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) >180 THEN\r\n"
//			+ "                         CASE\r\n"
//			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                            THEN\r\n" + "                               0\r\n"
//			+ "                            ELSE\r\n" + "                               a.baseamt + SUM(r.baseamt)\r\n"
//			+ "                         END\r\n" + "                      ELSE\r\n" + "                         0\r\n"
//			+ "                   END\r\n" + "                      AS bmslab7,\r\n" + "                      CASE\r\n"
//			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) > 180 THEN\r\n"
//			+ "                         CASE\r\n"
//			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
//			+ "                            THEN\r\n" + "                               0\r\n"
//			+ "                            ELSE\r\n"
//			+ "                               a.nativeamt + SUM(r.nativeamt)\r\n" + "                         END\r\n"
//			+ "                      ELSE\r\n" + "                         0\r\n" + "                   END\r\n"
//			+ "                      AS nmslab7 from arapdetails a\r\n"
//			+ "LEFT JOIN arapadjustments r ON a.subledgercode = r.subledgercode AND r.cancel = 0\r\n"
//			+ "LEFT JOIN accounts ac ON a.docid = ac.docid and r.docid=ac.vid\r\n"
//			+ "JOIN partymaster p ON a.subledgercode = p.partycode\r\n" + "JOIN branch jbr ON a.branch = jbr.branch\r\n"
//			+ "JOIN groupledger b\r\n" + "JOIN branch br ON a.branch = br.branch\r\n" + "WHERE \r\n"
//			+ "    a.docdate <= DATE(?4) and   a.orgid=r.orgid and r.orgid=p.orgid and b.orgid=r.orgid and p.orgid=br.orgid and r.orgid = ?1\r\n"
//			+ "    AND a.cancel = 0 and p.partytype='CUSTOMER' and (p.partyname = ?3 or ?3 ='ALL')\r\n"
//			+ "    AND (br.branch = ?2 or ?2 ='ALL')\r\n"
//			+ "    AND b.category = 'RECEIVABLE A/C' group by a.arapdetailsid,\r\n"
//			+ "                   jbr.branch,\r\n" + "                   P.PARTYCODE ,\r\n"
//			+ "                   p.partyname ,\r\n" + "                   p.partytype,\r\n"
//			+ "                   p.creditlimit,\r\n" + "                   p.gstregistered,\r\n"
//			+ "                   p.creditdays,\r\n" + "                   p.salesperson,a.docid ,\r\n"
//			+ "                   a.docdate,\r\n" + "                   a.supprefno,\r\n"
//			+ "                   a.suprefdate,\r\n" + "                   a.refno,\r\n"
//			+ "                   a.refdate,\r\n"
//			+ "                   a.amount HAVING (a.amount + SUM(r.amount) != 0))t where t.refno not like('%RT%') and t.refno not like('%PT%') ORDER BY t.branch,t.subledgername,\r\n"
//			+ "         t.partytype,\r\n" + "         t.docdate,\r\n" + "         t.docid\r\n" + ") w\r\n"
//			+ "ORDER BY sno asc")
	
	
	@Query(nativeQuery = true,value="with a as (\r\n"
			+ "   select 1 sno,t.arapdetailsid,\r\n"
			+ "         t.branch,\r\n"
			+ "         t.subledgercode,\r\n"
			+ "        CONCAT(t.subledgername, ' , Cr. Limit - ', t.creditlimit, ' , Cr. Days - ', t.creditdays) AS subledgername,\r\n"
			+ "         t.partytype,\r\n"
			+ "         t.salesperson,\r\n"
			+ "         t.docid,\r\n"
			+ "         t.docdate,\r\n"
			+ "         t.supprefno,\r\n"
			+ "         t.suprefdate,\r\n"
			+ "         t.duedate,\r\n"
			+ "         t.refno,\r\n"
			+ "         t.refdate,\r\n"
			+ "         case when ?5 ='Base' then t.bamount when ?5 ='Native' then t.namount else  t.amount end as amount,\r\n"
			+ "         case when ?5 ='Base' then t.boutstanding when ?5 ='Native'then t.noutstanding else t.outstanding end as outstanding,\r\n"
			+ "         case when  ?5 ='Base' then t.btotaldue when  ?5 ='Native' then t.ntotaldue else  t.totaldue end as totaldue,\r\n"
			+ "         case when ?5 ='Base'then t.bunadjusted when ?5 ='Native'then t.nunadjusted else t.unadjusted end as unadjusted,\r\n"
			+ "         t.ddays,CASE \r\n"
			+ "    WHEN ?5 = 'Base' THEN t.bmslab1\r\n"
			+ "    WHEN ?5 = 'Native' THEN t.nmslab1\r\n"
			+ "    ELSE t.mslab1\r\n"
			+ "  END AS mslab1,\r\n"
			+ "  CASE \r\n"
			+ "    WHEN ?5 = 'Base' THEN t.bmslab2\r\n"
			+ "    WHEN ?5 = 'Native' THEN t.nmslab2\r\n"
			+ "    ELSE t.mslab2\r\n"
			+ "  END AS mslab2,\r\n"
			+ "  CASE \r\n"
			+ "    WHEN ?5 = 'Base' THEN t.bmslab3\r\n"
			+ "    WHEN ?5 = 'Native' THEN t.nmslab3\r\n"
			+ "    ELSE t.mslab3\r\n"
			+ "  END AS mslab3,\r\n"
			+ "  CASE \r\n"
			+ "    WHEN ?5 = 'Base' THEN t.bmslab4\r\n"
			+ "    WHEN ?5 = 'Native' THEN t.nmslab4\r\n"
			+ "    ELSE t.mslab4\r\n"
			+ "  END AS mslab4,\r\n"
			+ "\r\n"
			+ "  CASE \r\n"
			+ "    WHEN ?5 = 'Base' THEN t.bmslab5 + t.bmslab6 + t.bmslab7\r\n"
			+ "    WHEN ?5 = 'Native' THEN t.nmslab5 + t.nmslab6 + t.nmslab7\r\n"
			+ "    ELSE t.mslab5 + t.mslab6 + t.mslab7\r\n"
			+ "  END AS mslab5,\r\n"
			+ "        t.creditlimit,t.creditdays from(\r\n"
			+ "select  a.arapdetailsid,\r\n"
			+ "                   jbr.branch,\r\n"
			+ "                   P.PARTYCODE subledgercode,\r\n"
			+ "                   p.partyname subledgername,\r\n"
			+ "                   p.partytype subledgertype,\r\n"
			+ "                   CASE\r\n"
			+ "                      WHEN  (p.gstregistered LIKE 'Y%') THEN 'GST Party'\r\n"
			+ "                      ELSE 'ST Party'\r\n"
			+ "                   END\r\n"
			+ "                      Partytype,\r\n"
			+ "                   p.creditlimit,\r\n"
			+ "                   p.creditdays,\r\n"
			+ "                   p.salesperson,a.docid , \r\n"
			+ "                   a.docdate,\r\n"
			+ "                   a.supprefno,\r\n"
			+ "                   a.suprefdate,\r\n"
			+ "                   DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) duedate,\r\n"
			+ "                   a.refno,\r\n"
			+ "                   a.refdate,\r\n"
			+ "                   a.amount AS amount,CASE\r\n"
			+ "                      WHEN  (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                      THEN\r\n"
			+ "                         0\r\n"
			+ "                      ELSE\r\n"
			+ "                         a.amount + SUM(r.amount)\r\n"
			+ "                   END\r\n"
			+ "                      AS outstanding,a.amount + SUM(r.amount) AS totaldue,a.baseamt AS bamount,CASE\r\n"
			+ "                      WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                      THEN\r\n"
			+ "                         0\r\n"
			+ "                      ELSE\r\n"
			+ "                         a.baseamt + SUM(r.baseamt)\r\n"
			+ "                   END\r\n"
			+ "                      AS boutstanding,a.baseamt + SUM(r.baseamt) AS btotaldue,a.nativeamt AS namount,\r\n"
			+ "                   CASE\r\n"
			+ "                        WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                      THEN\r\n"
			+ "                         0\r\n"
			+ "                      ELSE\r\n"
			+ "                         a.nativeamt + SUM(r.nativeamt)\r\n"
			+ "                   END\r\n"
			+ "                      AS noutstanding,\r\n"
			+ "                   a.nativeamt + SUM(r.nativeamt) AS ntotaldue,CASE\r\n"
			+ "                      WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                           AND a.amount +SUM(r.amount) <> 0\r\n"
			+ "                      THEN\r\n"
			+ "                         a.amount +SUM(r.amount)\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS unadjusted,CASE\r\n"
			+ "                       WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                           AND a.baseamt +SUM(r.baseamt) <> 0\r\n"
			+ "                      THEN\r\n"
			+ "                         a.baseamt +SUM(r.baseamt)\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS bunadjusted,CASE\r\n"
			+ "                       WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                           AND a.nativeamt +SUM(r.nativeamt) <> 0\r\n"
			+ "                      THEN\r\n"
			+ "                         a.nativeamt +SUM(r.nativeamt)\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS nunadjusted,date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY)\r\n"
			+ "                      AS ddays,CASE\r\n"
			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY)<31 THEN\r\n"
			+ "                         CASE\r\n"
			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.amount + SUM(r.amount)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS mslab1,CASE\r\n"
			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY)<31 THEN\r\n"
			+ "                         CASE\r\n"
			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.baseamt + SUM(r.baseamt)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS bmslab1,CASE\r\n"
			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY)<31 THEN\r\n"
			+ "                         CASE\r\n"
			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.nativeamt + SUM(r.nativeamt)\r\n"
			+ "                         ENd\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS nmslab1,CASE\r\n"
			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 31 and 60 THEN\r\n"
			+ "                         CASE\r\n"
			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.amount + SUM(r.amount)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS mslab2,CASE\r\n"
			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 31 and 60 THEN\r\n"
			+ "                         CASE\r\n"
			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.baseamt + SUM(r.baseamt)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS bmslab2,\r\n"
			+ "                      CASE\r\n"
			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 31 and 60 THEN\r\n"
			+ "                         CASE\r\n"
			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.nativeamt + SUM(r.nativeamt)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS nmslab2,\r\n"
			+ "                      CASE\r\n"
			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 61 and 90 THEN\r\n"
			+ "                         CASE\r\n"
			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.amount + SUM(r.amount)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS mslab3,CASE\r\n"
			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 61 and 90 THEN\r\n"
			+ "                         CASE\r\n"
			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.baseamt + SUM(r.baseamt)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS bmslab3,\r\n"
			+ "                      CASE\r\n"
			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 61 and 90 THEN\r\n"
			+ "                         CASE\r\n"
			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.nativeamt + SUM(r.nativeamt)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS nmslab3,CASE\r\n"
			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 91 and 120 THEN\r\n"
			+ "                         CASE\r\n"
			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.amount + SUM(r.amount)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS mslab4,CASE\r\n"
			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 91 and 120 THEN\r\n"
			+ "                         CASE\r\n"
			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.baseamt + SUM(r.baseamt)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS bmslab4,\r\n"
			+ "                      CASE\r\n"
			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 91 and 120 THEN\r\n"
			+ "                         CASE\r\n"
			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.nativeamt + SUM(r.nativeamt)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS nmslab4,CASE\r\n"
			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 121 and 150 THEN\r\n"
			+ "                         CASE\r\n"
			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.amount + SUM(r.amount)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS mslab5,CASE\r\n"
			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 121 and 150 THEN\r\n"
			+ "                         CASE\r\n"
			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.baseamt + SUM(r.baseamt)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS bmslab5,\r\n"
			+ "                      CASE\r\n"
			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 121 and 150 THEN\r\n"
			+ "                         CASE\r\n"
			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.nativeamt + SUM(r.nativeamt)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS nmslab5,CASE\r\n"
			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 151 and 180 THEN\r\n"
			+ "                         CASE\r\n"
			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.amount + SUM(r.amount)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS mslab6,CASE\r\n"
			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 151 and 180 THEN\r\n"
			+ "                         CASE\r\n"
			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.baseamt + SUM(r.baseamt)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS bmslab6,\r\n"
			+ "                      CASE\r\n"
			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 151 and 180 THEN\r\n"
			+ "                         CASE\r\n"
			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.nativeamt + SUM(r.nativeamt)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS nmslab6,CASE\r\n"
			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) >180 THEN\r\n"
			+ "                         CASE\r\n"
			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.amount + SUM(r.amount)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS mslab7,CASE\r\n"
			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) >180 THEN\r\n"
			+ "                         CASE\r\n"
			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.baseamt + SUM(r.baseamt)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS bmslab7,\r\n"
			+ "                      CASE\r\n"
			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) > 180 THEN\r\n"
			+ "                         CASE\r\n"
			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.nativeamt + SUM(r.nativeamt)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS nmslab7 from arapdetails a\r\n"
			+ "LEFT JOIN arapadjustments r ON a.subledgercode = r.subledgercode AND r.cancel = 0\r\n"
			+ "LEFT JOIN accounts ac ON a.docid = ac.docid \r\n"
			+ "JOIN partymaster p ON a.subledgercode = p.partycode\r\n"
			+ "JOIN branch jbr ON a.branch = jbr.branch\r\n"
			+ "JOIN groupledger b\r\n"
			+ "JOIN branch br ON a.branch = br.branch\r\n"
			+ "WHERE \r\n"
			+ "    a.docdate <= DATE(?4) and   a.orgid=r.orgid and r.orgid=p.orgid and b.orgid=r.orgid and p.orgid=br.orgid and r.orgid = ?1\r\n"
			+ "    AND a.cancel = 0 and p.partytype='CUSTOMER' and (p.partyname = ?3 or ?3 = 'ALL')\r\n"
			+ "    AND (br.branch = ?2 or ?2 ='ALL') \r\n"
			+ "    AND b.category = 'RECEIVABLE A/C' group by a.arapdetailsid,\r\n"
			+ "                   jbr.branch,\r\n"
			+ "                   P.PARTYCODE ,\r\n"
			+ "                   p.partyname ,\r\n"
			+ "                   p.partytype,\r\n"
			+ "                   p.creditlimit,\r\n"
			+ "                   p.gstregistered,\r\n"
			+ "                   p.creditdays,\r\n"
			+ "                   p.salesperson,a.docid ,\r\n"
			+ "                   a.docdate,\r\n"
			+ "                   a.supprefno,\r\n"
			+ "                   a.suprefdate,\r\n"
			+ "                   a.refno,\r\n"
			+ "                   a.refdate,\r\n"
			+ "                   a.amount HAVING (a.amount + SUM(r.amount) != 0))t where t.refno not like('%RT%') and t.refno not like('%PT%') ORDER BY t.branch,t.subledgername,\r\n"
			+ "         t.partytype,\r\n"
			+ "         t.docdate,\r\n"
			+ "         t.docid\r\n"
			+ ") \r\n"
			+ "SELECT sno,arapdetailsid,branch,subledgercode,subledgername,partytype,salesperson,docid,docdate,\r\n"
			+ "supprefno,suprefdate,duedate,refno,refdate,amount,outstanding,totaldue,unadjusted,ddays,mslab1,mslab2,mslab3,mslab4,mslab5,creditlimit,creditdays,subledgername as partyname FROM a\r\n"
			+ "union\r\n"
			+ "SELECT 2 sno,null arapdetailsid,null branch,null subledgercode, subledgername,null partytype,null salesperson,null docid,null docdate,\r\n"
			+ "null supprefno,null suprefdate,null duedate,null refno,null refdate,sum(a.amount)amount,sum(a.outstanding)outstanding,sum(a.totaldue)totaldue,sum(a.unadjusted)unadjusted,null ddays,sum(a.mslab1)mslab1,sum(a.mslab2)mslab2,sum(a.mslab3)mslab3,sum(a.mslab4)mslab4,sum(a.mslab5)mslab5,null creditlimit,null creditdays,'Total' as partyname FROM a\r\n"
			+ "group by a.subledgername\r\n"
			+ "ORDER BY subledgername,sno asc")
	Set<Object[]> getARAgeingReport(Long orgId, String branch, String partyName, String asOnDate, String base);
}
