package com.base.basesetup.repo;

import java.util.List;
import java.util.Set;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;

import com.base.basesetup.entity.OrderBookingVO;

public interface OrderBookingRepo extends JpaRepository<OrderBookingVO, Long> {

	@Query("SELECT a FROM OrderBookingVO a WHERE a.orgId = ?1 AND a.clientCode = ?2 AND a.year = ?3 AND a.month = ?4 AND a.type = ?5 AND LOWER(a.segment) = LOWER(?6) AND LOWER(a.customerName) = LOWER(?7)")
	OrderBookingVO getBudgetDetails(Long orgId, String clientCode, String year, String month, String type,
	                                 String segment, String customerName);

	@Query(nativeQuery = true,value = "WITH Months AS (\r\n"
			+ "    SELECT 'April' AS month UNION ALL\r\n"
			+ "    SELECT 'May' UNION ALL\r\n"
			+ "    SELECT 'June' UNION ALL\r\n"
			+ "    SELECT 'July' UNION ALL\r\n"
			+ "    SELECT 'August' UNION ALL\r\n"
			+ "    SELECT 'September' UNION ALL\r\n"
			+ "    SELECT 'October' UNION ALL\r\n"
			+ "    SELECT 'November' UNION ALL\r\n"
			+ "    SELECT 'December' UNION ALL\r\n"
			+ "    SELECT 'January' UNION ALL\r\n"
			+ "    SELECT 'February' UNION ALL\r\n"
			+ "    SELECT 'March'\r\n"
			+ ")\r\n"
			+ "SELECT \r\n"
			+ "    a.segment, \r\n"
			+ "    a.customername, \r\n"
			+ "    a.ordervalue,\r\n"
			+ "    a.balanceordervalue,\r\n"
			+ "    a.classification,\r\n"
			+ "    a.existingorderplan,\r\n"
			+ "    a.paymentreceived,\r\n"
			+ "    a.yettoreceive,\r\n"
			+ "    a.month, \r\n"
			+ "    COALESCE(SUM(a.amount), 0) AS totalamount\r\n"
			+ "FROM budgetob a\r\n"
			+ "join Months m\r\n"
			+ "    ON a.month = m.month\r\n"
			+ "    AND a.orgid = ?1\r\n"
			+ "    AND a.year = ?2\r\n"
			+ "    AND a.clientcode = ?3\r\n"
			+ "    AND a.type = ?4\r\n"
			+ "GROUP BY \r\n"
			+ "    a.segment,\r\n"
			+ "    a.customername,\r\n"
			+ "    a.ordervalue,\r\n"
			+ "    a.balanceordervalue,\r\n"
			+ "    a.classification,\r\n"
			+ "    a.existingorderplan,\r\n"
			+ "    a.paymentreceived,\r\n"
			+ "    a.yettoreceive,\r\n"
			+ "    a.month,\r\n"
			+ "    FIELD(m.month, 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December', 'January', 'February', 'March')\r\n"
			+ "ORDER BY \r\n"
			+ "    FIELD(m.month, 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December', 'January', 'February', 'March')")
	Set<Object[]> getOrderBookingBudDetails(Long orgId, String year, String clientCode, String type);

	@Query("select a from OrderBookingVO a where a.orgId=?1 and a.clientCode=?2 and a.year=?3 and a.type=?4")
	List<OrderBookingVO> getBudgetListDetails(Long orgId, String clientCode, String year,String type);
	
	
	
	@Query(nativeQuery = true, value = "SELECT \r\n"
			+ "    a.segment,\r\n"
			+ "    a.quater,\r\n"
			+ "    SUM(a.bud) AS bud,\r\n"
			+ "    SUM(a.py)  AS py\r\n"
			+ "FROM (\r\n"
			+ "    -- ====== Quarterly Budget ======\r\n"
			+ "    SELECT \r\n"
			+ "        segment,\r\n"
			+ "        quater,\r\n"
			+ "        SUM(amount) AS bud,\r\n"
			+ "        0 AS py\r\n"
			+ "    FROM budgetob\r\n"
			+ "    WHERE orgid = ?1\r\n"
			+ "      AND clientcode = ?3\r\n"
			+ "      AND year = ?2\r\n"
			+ "      AND type = 'Order Booking Plan'\r\n"
			+ "    GROUP BY segment, quater\r\n"
			+ "    \r\n"
			+ "    UNION ALL\r\n"
			+ "    \r\n"
			+ "    -- ====== Quarterly PY ======\r\n"
			+ "    SELECT \r\n"
			+ "        segment,\r\n"
			+ "        quater,\r\n"
			+ "        0 AS bud,\r\n"
			+ "        SUM(amount) AS py\r\n"
			+ "    FROM previousyearob\r\n"
			+ "    WHERE orgid = ?1\r\n"
			+ "      AND clientcode = ?3\r\n"
			+ "      AND year = ?4\r\n"
			+ "      AND type = 'Order Booking Plan'\r\n"
			+ "    GROUP BY segment, quater\r\n"
			+ "\r\n"
			+ "    UNION ALL\r\n"
			+ "\r\n"
			+ "    -- ====== FullYear Budget ======\r\n"
			+ "    SELECT \r\n"
			+ "        segment,\r\n"
			+ "        'fullYear' AS quater,\r\n"
			+ "        SUM(amount) AS bud,\r\n"
			+ "        0 AS py\r\n"
			+ "    FROM budgetob\r\n"
			+ "    WHERE orgid = ?1\r\n"
			+ "      AND clientcode = ?3\r\n"
			+ "      AND year = ?2\r\n"
			+ "      AND type = 'Order Booking Plan'\r\n"
			+ "    GROUP BY segment\r\n"
			+ "    \r\n"
			+ "    UNION ALL\r\n"
			+ "\r\n"
			+ "    -- ====== FullYear PY ======\r\n"
			+ "    SELECT \r\n"
			+ "        segment,\r\n"
			+ "        'fullYear' AS quater,\r\n"
			+ "        0 AS bud,\r\n"
			+ "        SUM(amount) AS py\r\n"
			+ "    FROM previousyearob\r\n"
			+ "    WHERE orgid = ?1\r\n"
			+ "      AND clientcode = ?3\r\n"
			+ "      AND year = ?4\r\n"
			+ "      AND type = 'Order Booking Plan'\r\n"
			+ "    GROUP BY segment\r\n"
			+ ") a\r\n"
			+ "GROUP BY a.segment, a.quater\r\n"
			+ "ORDER BY a.segment, a.quater")
	Set<Object[]> getElBudgetOrderBookingDetails(Long orgId, String finYear, String clientCode, String previousYear);
	
	
	@Query(nativeQuery = true, value = "SELECT t.segment, t.quater, SUM(t.py)\r\n"
			+ "FROM (\r\n"
			+ "    SELECT \r\n"
			+ "        segment,\r\n"
			+ "        quater,\r\n"
			+ "        SUM(amount) AS py\r\n"
			+ "    FROM previousyearob\r\n"
			+ "    WHERE orgid = ?1\r\n"
			+ "      AND clientcode = ?3\r\n"
			+ "      AND year = ?2\r\n"
			+ "      AND type = 'Order Booking Plan'\r\n"
			+ "    GROUP BY segment, quater\r\n"
			+ "\r\n"
			+ "    UNION\r\n"
			+ "\r\n"
			+ "    SELECT \r\n"
			+ "        segment,\r\n"
			+ "        'ytd' AS quater,\r\n"
			+ "        SUM(amount) AS py\r\n"
			+ "    FROM previousyearob\r\n"
			+ "    WHERE orgid = ?1\r\n"
			+ "      AND clientcode = ?3 \r\n"
			+ "      AND monthsequence <= (\r\n"
			+ "            SELECT MAX(monthsequence)\r\n"
			+ "            FROM previousyearactual\r\n"
			+ "            WHERE year = ?2\r\n"
			+ "              AND month = ?4\r\n"
			+ "              AND clientcode = ?3\r\n"
			+ "        )\r\n"
			+ "      AND year = ?2\r\n"
			+ "      AND type = 'Order Booking Plan'\r\n"
			+ "    GROUP BY segment\r\n"
			+ "\r\n"
			+ "    UNION\r\n"
			+ "\r\n"
			+ "    SELECT \r\n"
			+ "        segment,\r\n"
			+ "        'fullYear' AS quater,\r\n"
			+ "        SUM(amount) AS py\r\n"
			+ "    FROM previousyearob\r\n"
			+ "    WHERE orgid = ?1\r\n"
			+ "      AND clientcode = ?3\r\n"
			+ "      AND year = ?2\r\n"
			+ "      AND type = 'Order Booking Plan'\r\n"
			+ "    GROUP BY segment\r\n"
			+ ") t\r\n"
			+ "GROUP BY t.segment, t.quater")
	Set<Object[]> getElPyOrderBookingDetails(Long orgId, String previousYear, String clientCode,String month);





}
