package com.base.basesetup.repo;

import java.util.List;
import java.util.Set;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import com.base.basesetup.entity.PartyMasterVO;

@Repository
public interface PartyMasterRepo extends JpaRepository<PartyMasterVO, Long> {

	@Query(nativeQuery = true, value = "select * from partymaster where partymasterid=?1")
	List<PartyMasterVO> findPartyMasterVOById(Long id);

	@Query(nativeQuery = true, value = "select * from partymaster where orgid=?1")
	List<PartyMasterVO> findByOrgId(Long orgid);

	@Query(nativeQuery = true, value = "select concat(prefixfield,lpad(lastno,5,0)) AS docid from documenttypemappingdetails where orgid=?1 and finyear=?2 and branchcode=?3 and screencode=?4")
	String getPartyMasterDocId(Long orgId, String finYear, String branchCode, String screenCode);

	@Query(value = "select a from PartyMasterVO a where a.orgId=?1 and a.partyType=?2 and a.active=true")
	List<PartyMasterVO> findByOrgIdAndPartyTypeIgnoreCase(Long orgId, String partyType);

	PartyMasterVO findByPartyCode(String partyCode);

	@Query(nativeQuery = true, value = "select * from partymaster where orgid=?1 and partytype='CUSTOMER'")
	List<PartyMasterVO> getAllCustomers(Long orgId);

	@Query(nativeQuery = true, value = "select * from partymaster where orgid=?1 and partytype='VENDOR'")
	List<PartyMasterVO> getAllVendors(Long orgId);

	boolean existsByPartyNameAndOrgId(String customerName, long orgId);

	boolean existsByPartyNameAndOrgIdAndPartyType(String customerName, long orgId, String partyType);

//	@Query(nativeQuery = true, value = "SELECT * FROM (\r\n"
//			+ "    -- Opening Balance\r\n"
//			+ "    SELECT\r\n"
//			+ "        1 AS sno,\r\n"
//			+ "        NULL AS docid,\r\n"
//			+ "        NULL AS docdate,\r\n"
//			+ "        NULL AS refno,\r\n"
//			+ "        NULL AS refdate,\r\n"
//			+ "        p.partycode AS supprefno,\r\n"
//			+ "        p.partyname AS supprefdate,\r\n"
//			+ "        CONCAT('Opening Balance - ', p.partycode, ' - ', p.partyname, ' -',' INR') AS Particulars,\r\n"
//			+ "        'INR' AS currency,\r\n"
//			+ "        CASE WHEN SUM(t2.debitamount) - SUM(t2.creditamount) > 0 THEN\r\n"
//			+ "            SUM(t2.debitamount) - SUM(t2.creditamount) ELSE 0\r\n"
//			+ "        END AS dbamount,\r\n"
//			+ "        CASE WHEN SUM(t2.debitamount) - SUM(t2.creditamount) < 0 THEN\r\n"
//			+ "            ABS(SUM(t2.debitamount) - SUM(t2.creditamount)) ELSE 0\r\n"
//			+ "        END AS cramount,\r\n"
//			+ "        1 AS sort_order\r\n"
//			+ "    FROM\r\n"
//			+ "        accountsdetails t2\r\n"
//			+ "        JOIN accounts t1 ON t1.accountsid = t2.accountsid\r\n"
//			+ "        JOIN partymaster p ON t2.subledgercode = p.partycode\r\n"
//			+ "        JOIN branch dm ON dm.branchcode = t1.branchcode\r\n"
//			+ "    WHERE\r\n"
//			+ "        t1.CANCEL = 0\r\n"
//			+ "        AND t1.vdate < ?5\r\n"
//			+ "        AND (p.partyname = ?2 OR ?2 = 'ALL')\r\n"
//			+ "        AND p.partytype = ?3\r\n"
//			+ "        AND t2.acategory IN ('PAYABLE A/C', 'RECEIVABLE A/C')\r\n"
//			+ "        AND t1.orgid = ?1\r\n"
//			+ "        AND (?4 = 'ALL' OR t1.branch = ?4)\r\n"
//			+ "    GROUP BY p.partycode, p.partyname\r\n"
//			+ "\r\n"
//			+ "    UNION\r\n"
//			+ "\r\n"
//			+ "    -- Spacer\r\n"
//			+ "    SELECT 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2 FROM dual\r\n"
//			+ "\r\n"
//			+ "    UNION\r\n"
//			+ "\r\n"
//			+ "    -- Transactions\r\n"
//			+ "    SELECT\r\n"
//			+ "        3 AS sno,\r\n"
//			+ "        t1.vid,\r\n"
//			+ "        t1.vdate,\r\n"
//			+ "        t1.refno,\r\n"
//			+ "        t1.refdate,\r\n"
//			+ "        t1.supplierrefno,\r\n"
//			+ "        t1.supplierrefdate,\r\n"
//			+ "          CONCAT_WS(' - ', t1.remarks, t1.sourcescreen) AS Particulars,\r\n"
//			+ "        t1.currency,\r\n"
//			+ "        SUM(t2.debitamount),\r\n"
//			+ "        SUM(t2.creditamount),\r\n"
//			+ "        3 AS sort_order\r\n"
//			+ "    FROM\r\n"
//			+ "        accountsdetails t2\r\n"
//			+ "        JOIN accounts t1 ON t1.accountsid = t2.accountsid\r\n"
//			+ "        JOIN partymaster p ON t2.subledgercode = p.partycode\r\n"
//			+ "        JOIN branch dm ON dm.branchcode = t1.branchcode\r\n"
//			+ "    WHERE\r\n"
//			+ "        t1.CANCEL = 0\r\n"
//			+ "        AND t1.vdate BETWEEN ?5 AND ?6\r\n"
//			+ "        AND (p.partyname = ?2 OR ?2 = 'ALL')\r\n"
//			+ "        AND (p.partytype = ?3 OR ?3 = 'ALL')\r\n"
//			+ "        AND t2.acategory IN ('PAYABLE A/C', 'RECEIVABLE A/C')\r\n"
//			+ "        AND t1.orgid = ?1\r\n"
//			+ "        AND (?4 = 'ALL' OR t1.branch = ?4)\r\n"
//			+ "    GROUP BY\r\n"
//			+ "        t1.vid, t1.vdate, t1.refno, t1.refdate, t1.supplierrefno, t1.supplierrefdate, t1.currency,t1.remarks, t1.sourcescreen\r\n"
//			+ "\r\n"
//			+ "    UNION\r\n"
//			+ "\r\n"
//			+ "    -- Totals (Opening + Transactions)\r\n"
//			+ "    SELECT\r\n"
//			+ "        4 AS sno, NULL, NULL, NULL, NULL, NULL, NULL,\r\n"
//			+ "        'Total', 'INR',\r\n"
//			+ "        SUM(y.dbamount), ABS(SUM(y.cramount)), 4\r\n"
//			+ "    FROM (\r\n"
//			+ "        -- Opening\r\n"
//			+ "        SELECT\r\n"
//			+ "            CASE WHEN SUM(t2.debitamount) - SUM(t2.creditamount) > 0 THEN SUM(t2.debitamount) - SUM(t2.creditamount) ELSE 0 END AS dbamount,\r\n"
//			+ "            CASE WHEN SUM(t2.debitamount) - SUM(t2.creditamount) < 0 THEN SUM(t2.debitamount) - SUM(t2.creditamount) ELSE 0 END AS cramount\r\n"
//			+ "        FROM accountsdetails t2\r\n"
//			+ "            JOIN accounts t1 ON t1.accountsid = t2.accountsid\r\n"
//			+ "            JOIN partymaster p ON t2.subledgercode = p.partycode\r\n"
//			+ "            JOIN branch dm ON dm.branchcode = t1.branchcode\r\n"
//			+ "        WHERE\r\n"
//			+ "            t1.CANCEL = 0\r\n"
//			+ "            AND t1.vdate < ?5\r\n"
//			+ "            AND (p.partyname = ?2 OR ?2 = 'ALL')\r\n"
//			+ "            AND p.partytype = ?3\r\n"
//			+ "            AND t2.acategory IN ('PAYABLE A/C', 'RECEIVABLE A/C')\r\n"
//			+ "            AND t1.orgid = ?1\r\n"
//			+ "            AND (?4 = 'ALL' OR t1.branch = ?4)\r\n"
//			+ "        GROUP BY p.partycode, p.partyname\r\n"
//			+ "\r\n"
//			+ "        UNION\r\n"
//			+ "\r\n"
//			+ "        -- Transactions\r\n"
//			+ "        SELECT\r\n"
//			+ "            SUM(t2.debitamount), SUM(t2.creditamount)\r\n"
//			+ "        FROM accountsdetails t2\r\n"
//			+ "            JOIN accounts t1 ON t1.accountsid = t2.accountsid\r\n"
//			+ "            JOIN partymaster p ON t2.subledgercode = p.partycode\r\n"
//			+ "            JOIN branch dm ON dm.branchcode = t1.branchcode\r\n"
//			+ "        WHERE\r\n"
//			+ "            t1.CANCEL = 0\r\n"
//			+ "            AND t1.vdate BETWEEN ?5 AND ?6\r\n"
//			+ "            AND (p.partyname = ?2 OR ?2 = 'ALL')\r\n"
//			+ "            AND (p.partytype = ?3 OR ?3 = 'ALL')\r\n"
//			+ "            AND t2.acategory IN ('PAYABLE A/C', 'RECEIVABLE A/C')\r\n"
//			+ "            AND t1.orgid = ?1\r\n"
//			+ "            AND (?4 = 'ALL' OR t1.branch = ?4)\r\n"
//			+ "        GROUP BY p.partycode, p.partyname\r\n"
//			+ "    ) y\r\n"
//			+ "\r\n"
//			+ "    UNION\r\n"
//			+ "\r\n"
//			+ "    -- Closing Balance\r\n"
//			+ "    SELECT\r\n"
//			+ "        5 AS sno,\r\n"
//			+ "        NULL, NULL, NULL, NULL, NULL, NULL,\r\n"
//			+ "        'Closing Balance', 'INR',\r\n"
//			+ "        CASE WHEN SUM(t2.debitamount) - SUM(t2.creditamount) <= 0 THEN 0\r\n"
//			+ "             ELSE SUM(t2.debitamount) - SUM(t2.creditamount)\r\n"
//			+ "        END,\r\n"
//			+ "        CASE WHEN SUM(t2.debitamount) - SUM(t2.creditamount) >= 0 THEN 0\r\n"
//			+ "             ELSE abs(SUM(t2.debitamount) - SUM(t2.creditamount))\r\n"
//			+ "        END,\r\n"
//			+ "        5\r\n"
//			+ "    FROM\r\n"
//			+ "        accountsdetails t2\r\n"
//			+ "        JOIN accounts t1 ON t1.accountsid = t2.accountsid\r\n"
//			+ "        JOIN partymaster p ON t2.subledgercode = p.partycode\r\n"
//			+ "        JOIN branch dm ON dm.branchcode = t1.branchcode\r\n"
//			+ "    WHERE\r\n"
//			+ "        t1.CANCEL = 0\r\n"
//			+ "        AND t1.vdate <= ?6\r\n"
//			+ "        AND (p.partyname = ?2 OR ?2 = 'ALL')\r\n"
//			+ "        AND p.partytype = ?3\r\n"
//			+ "        AND t2.acategory IN ('PAYABLE A/C', 'RECEIVABLE A/C')\r\n"
//			+ "        AND t1.orgid = ?1\r\n"
//			+ "        AND (?4 = 'ALL' OR t1.branch = ?4)\r\n"
//			+ "    GROUP BY p.partycode, p.partyname\r\n"
//			+ "\r\n"
//			+ ") AS final_result\r\n"
//			+ "ORDER BY sort_order, CASE WHEN docdate IS NULL THEN NULL ELSE docdate END ASC")
//	Set<Object[]> getAllPartyLedgerReport(Long orgId, String partyName, String partyType, String branch,
//			String fromDate, String toDate);

	
	@Query(nativeQuery = true, value = "SELECT * FROM (\r\n"
			+ "    -- Opening Balance\r\n"
			+ "    SELECT\r\n"
			+ "        1 AS sno,\r\n"
			+ "        NULL AS docid,\r\n"
			+ "        NULL AS docdate,\r\n"
			+ "        NULL AS refno,\r\n"
			+ "        NULL AS refdate,\r\n"
			+ "        p.partycode AS supprefno,\r\n"
			+ "        p.partyname AS supprefdate,\r\n"
			+ "        CONCAT('Opening Balance - ', p.partycode, ' - ', p.partyname, ' -',' INR') AS Particulars,\r\n"
			+ "        'INR' AS currency,\r\n"
			+ "        CASE WHEN SUM(t2.debitamount) - SUM(t2.creditamount) > 0 THEN\r\n"
			+ "            SUM(t2.debitamount) - SUM(t2.creditamount) ELSE 0\r\n"
			+ "        END AS dbamount,\r\n"
			+ "        CASE WHEN SUM(t2.debitamount) - SUM(t2.creditamount) < 0 THEN\r\n"
			+ "            ABS(SUM(t2.debitamount) - SUM(t2.creditamount)) ELSE 0\r\n"
			+ "        END AS cramount,\r\n"
			+ "        1 AS sort_order,\r\n"
			+ "        NULL AS createdon  -- Added for sorting\r\n"
			+ "    FROM\r\n"
			+ "        accountsdetails t2\r\n"
			+ "        JOIN accounts t1 ON t1.accountsid = t2.accountsid\r\n"
			+ "        JOIN partymaster p ON t2.subledgercode = p.partycode\r\n"
			+ "        JOIN branch dm ON dm.branchcode = t1.branchcode\r\n"
			+ "    WHERE\r\n"
			+ "        t1.CANCEL = 0\r\n"
			+ "        AND t1.vdate < ?5\r\n"
			+ "        AND (p.partyname = ?2 OR ?2 = 'ALL')\r\n"
			+ "        AND p.partytype = ?3\r\n"
			+ "        AND t2.acategory IN ('PAYABLE A/C', 'RECEIVABLE A/C')\r\n"
			+ "        AND t1.orgid = ?1\r\n"
			+ "        AND (?4 = 'ALL' OR t1.branch = ?4)\r\n"
			+ "    GROUP BY p.partycode, p.partyname\r\n"
			+ "\r\n"
			+ "    UNION\r\n"
			+ "\r\n"
			+ "    -- Spacer\r\n"
			+ "    SELECT 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, NULL FROM dual\r\n"
			+ "\r\n"
			+ "    UNION\r\n"
			+ "\r\n"
			+ "    -- Transactions\r\n"
			+ "    SELECT\r\n"
			+ "        3 AS sno,\r\n"
			+ "        t1.vid,\r\n"
			+ "        t1.vdate,\r\n"
			+ "        t1.refno,\r\n"
			+ "        t1.refdate,\r\n"
			+ "        t1.supplierrefno,\r\n"
			+ "        t1.supplierrefdate,\r\n"
			+ "        CONCAT_WS(' - ', t1.remarks, t1.sourcescreen) AS Particulars,\r\n"
			+ "        t1.currency,\r\n"
			+ "        SUM(t2.debitamount),\r\n"
			+ "        SUM(t2.creditamount),\r\n"
			+ "        3 AS sort_order,\r\n"
			+ "        t1.createdon  -- Added for sorting\r\n"
			+ "    FROM\r\n"
			+ "        accountsdetails t2\r\n"
			+ "        JOIN accounts t1 ON t1.accountsid = t2.accountsid\r\n"
			+ "        JOIN partymaster p ON t2.subledgercode = p.partycode\r\n"
			+ "        JOIN branch dm ON dm.branchcode = t1.branchcode\r\n"
			+ "    WHERE\r\n"
			+ "        t1.CANCEL = 0\r\n"
			+ "        AND t1.vdate BETWEEN ?5 AND ?6\r\n"
			+ "        AND (p.partyname = ?2 OR ?2 = 'ALL')\r\n"
			+ "        AND (p.partytype = ?3 OR ?3 = 'ALL')\r\n"
			+ "        AND t2.acategory IN ('PAYABLE A/C', 'RECEIVABLE A/C')\r\n"
			+ "        AND t1.orgid = ?1\r\n"
			+ "        AND (?4 = 'ALL' OR t1.branch = ?4)\r\n"
			+ "    GROUP BY\r\n"
			+ "        t1.vid, t1.vdate, t1.refno, t1.refdate, t1.supplierrefno, \r\n"
			+ "        t1.supplierrefdate, t1.currency, t1.remarks, t1.sourcescreen, \r\n"
			+ "        t1.createdon  -- Added to GROUP BY\r\n"
			+ "\r\n"
			+ "    UNION\r\n"
			+ "\r\n"
			+ "    -- Totals (Opening + Transactions)\r\n"
			+ "    SELECT\r\n"
			+ "        4 AS sno, NULL, NULL, NULL, NULL, NULL, NULL,\r\n"
			+ "        'Total', 'INR',\r\n"
			+ "        SUM(y.dbamount), ABS(SUM(y.cramount)), 4,\r\n"
			+ "        NULL  -- Added for sorting\r\n"
			+ "    FROM (\r\n"
			+ "        -- Opening\r\n"
			+ "        SELECT\r\n"
			+ "            CASE WHEN SUM(t2.debitamount) - SUM(t2.creditamount) > 0 THEN SUM(t2.debitamount) - SUM(t2.creditamount) ELSE 0 END AS dbamount,\r\n"
			+ "            CASE WHEN SUM(t2.debitamount) - SUM(t2.creditamount) < 0 THEN SUM(t2.debitamount) - SUM(t2.creditamount) ELSE 0 END AS cramount\r\n"
			+ "        FROM accountsdetails t2\r\n"
			+ "            JOIN accounts t1 ON t1.accountsid = t2.accountsid\r\n"
			+ "            JOIN partymaster p ON t2.subledgercode = p.partycode\r\n"
			+ "            JOIN branch dm ON dm.branchcode = t1.branchcode\r\n"
			+ "        WHERE\r\n"
			+ "            t1.CANCEL = 0\r\n"
			+ "            AND t1.vdate < ?5\r\n"
			+ "            AND (p.partyname = ?2 OR ?2 = 'ALL')\r\n"
			+ "            AND p.partytype = ?3\r\n"
			+ "            AND t2.acategory IN ('PAYABLE A/C', 'RECEIVABLE A/C')\r\n"
			+ "            AND t1.orgid = ?1\r\n"
			+ "            AND (?4 = 'ALL' OR t1.branch = ?4)\r\n"
			+ "        GROUP BY p.partycode, p.partyname\r\n"
			+ "\r\n"
			+ "        UNION\r\n"
			+ "\r\n"
			+ "        -- Transactions\r\n"
			+ "        SELECT\r\n"
			+ "            SUM(t2.debitamount), SUM(t2.creditamount)\r\n"
			+ "        FROM accountsdetails t2\r\n"
			+ "            JOIN accounts t1 ON t1.accountsid = t2.accountsid\r\n"
			+ "            JOIN partymaster p ON t2.subledgercode = p.partycode\r\n"
			+ "            JOIN branch dm ON dm.branchcode = t1.branchcode\r\n"
			+ "        WHERE\r\n"
			+ "            t1.CANCEL = 0\r\n"
			+ "            AND t1.vdate BETWEEN ?5 AND ?6\r\n"
			+ "            AND (p.partyname = ?2 OR ?2 = 'ALL')\r\n"
			+ "            AND (p.partytype = ?3 OR ?3 = 'ALL')\r\n"
			+ "            AND t2.acategory IN ('PAYABLE A/C', 'RECEIVABLE A/C')\r\n"
			+ "            AND t1.orgid = ?1\r\n"
			+ "            AND (?4 = 'ALL' OR t1.branch = ?4)\r\n"
			+ "        GROUP BY p.partycode, p.partyname\r\n"
			+ "    ) y\r\n"
			+ "\r\n"
			+ "    UNION\r\n"
			+ "\r\n"
			+ "    -- Closing Balance\r\n"
			+ "    SELECT\r\n"
			+ "        5 AS sno,\r\n"
			+ "        NULL, NULL, NULL, NULL, NULL, NULL,\r\n"
			+ "        'Closing Balance', 'INR',\r\n"
			+ "        CASE WHEN SUM(t2.debitamount) - SUM(t2.creditamount) <= 0 THEN 0\r\n"
			+ "             ELSE SUM(t2.debitamount) - SUM(t2.creditamount)\r\n"
			+ "        END,\r\n"
			+ "        CASE WHEN SUM(t2.debitamount) - SUM(t2.creditamount) >= 0 THEN 0\r\n"
			+ "             ELSE abs(SUM(t2.debitamount) - SUM(t2.creditamount))\r\n"
			+ "        END,\r\n"
			+ "        5,\r\n"
			+ "        NULL  -- Added for sorting\r\n"
			+ "    FROM\r\n"
			+ "        accountsdetails t2\r\n"
			+ "        JOIN accounts t1 ON t1.accountsid = t2.accountsid\r\n"
			+ "        JOIN partymaster p ON t2.subledgercode = p.partycode\r\n"
			+ "        JOIN branch dm ON dm.branchcode = t1.branchcode\r\n"
			+ "    WHERE\r\n"
			+ "        t1.CANCEL = 0\r\n"
			+ "        AND t1.vdate <= ?6\r\n"
			+ "        AND (p.partyname = ?2 OR ?2 = 'ALL')\r\n"
			+ "        AND p.partytype = ?3\r\n"
			+ "        AND t2.acategory IN ('PAYABLE A/C', 'RECEIVABLE A/C')\r\n"
			+ "        AND t1.orgid = ?1\r\n"
			+ "        AND (?4 = 'ALL' OR t1.branch = ?4)\r\n"
			+ "    GROUP BY p.partycode, p.partyname\r\n"
			+ ") AS final_result\r\n"
			+ "ORDER BY sort_order, \r\n"
			+ "         CASE \r\n"
			+ "             WHEN sno = 3 THEN createdon \r\n"
			+ "             ELSE NULL \r\n"
			+ "         END ASC")
	Set<Object[]> getAllPartyLedgerReport(Long orgId, String partyName, String partyType, String branch,
			String fromDate, String toDate);

	
	@Query(nativeQuery = true, value = "WITH \r\n" + "    b AS (\r\n" + "        SELECT \r\n"
			+ "            branch, \r\n" + "            branchcode\r\n" + "        FROM \r\n" + "            branch\r\n"
			+ "    ), \r\n" + "    p AS (\r\n" + "        SELECT \r\n" + "            partycode, \r\n"
			+ "            partyname\r\n" + "        FROM \r\n" + "            partymaster\r\n" + "    ), \r\n"
			+ "    a AS (\r\n" + "        SELECT \r\n" + "            ACCOUNTNAME, \r\n"
			+ "            subledgername\r\n" + "        FROM \r\n" + "            (\r\n"
			+ "                SELECT \r\n" + "                    ACCOUNTNAME, \r\n"
			+ "                    subledgername, \r\n" + "                    COUNT(accountsid) AS count_accounts,\r\n"
			+ "                    ROW_NUMBER() OVER (PARTITION BY accountsid ORDER BY COUNT(accountsid) DESC) AS row_num  \r\n"
			+ "                FROM \r\n" + "                    accountsdetails\r\n" + "                WHERE \r\n"
			+ "                    subledgername = 'None' \r\n" + "                GROUP BY \r\n"
			+ "                    ACCOUNTNAME, subledgername, accountsid\r\n" + "            ) t  \r\n"
			+ "        WHERE \r\n" + "            row_num = 1\r\n" + "    )\r\n" + "\r\n" + "SELECT \r\n"
			+ "    1 AS ids, \r\n" + "    0 AS recordid, \r\n" + "    b.branch AS branchname, \r\n"
			+ "    NULL AS vid, \r\n" + "    NULL AS vdate, \r\n"
			+ "    COALESCE(t2.subledgername, 'N/A') AS partyname, \r\n"
			+ "       SUM(t2.bcreditamount-t2.bdebitamount ) AS opbal,  \r\n" + "    NULL AS currency, \r\n"
			+ "    0 AS dbamount, \r\n" + "    0 AS cramount, \r\n" + "    0 AS ndbamount, \r\n"
			+ "    0 AS ncramount,\r\n" + "    0 AS clbal\r\n" + "FROM \r\n" + "    accountsdetails t2\r\n"
			+ "JOIN \r\n" + "    accounts t1 ON t1.accountsid = t2.accountsid\r\n" + "JOIN \r\n"
			+ "    b ON t1.branchcode = b.branchcode\r\n" + "JOIN \r\n"
			+ "    groupledger g ON t2.accountname = g.accountgroupname\r\n" + "WHERE \r\n" + "    t1.CANCEL = 0\r\n"
			+ "     AND (\r\n" + "        ?4 IS NULL \r\n" + "        OR ?4 = '' \r\n"
			+ "        OR t1.vdate < STR_TO_DATE(?4, '%Y-%m-%d')  \r\n" + "    )\r\n"
			+ "    AND (?3 = 'ALL' OR b.branchcode = ?3)\r\n" + "    AND t1.orgid = ?1\r\n"
			+ "    AND (g.accountgroupname = ?2 OR ?2 = 'ALL')\r\n" + "GROUP BY \r\n" + "    b.branch, \r\n"
			+ "    t2.subledgername\r\n" + "\r\n" + "UNION \r\n" + "\r\n" + "SELECT \r\n" + "    2 AS ids, \r\n"
			+ "    t1.accountsid AS recordid, \r\n" + "    b.branch AS branchname, \r\n" + "    t1.vdate AS vdate, \r\n"
			+ "    t1.vid AS vid, \r\n" + "    (SELECT subledgername \r\n" + "     FROM accountsdetails \r\n"
			+ "     WHERE accountsid = t1.accountsid \r\n" + "     AND subledgername NOT IN ('None')) AS partyname,\r\n"
			+ "    0 AS opbal, \r\n" + "    t1.currency, \r\n" + "    SUM(t2.bdebitamount) AS dbamount, \r\n"
			+ "    SUM(t2.bcreditamount) AS cramount, \r\n" + "    SUM(t2.debitamount) AS ndbamount, \r\n"
			+ "    SUM(t2.creditamount) AS ncramount,\r\n" + "    0 AS clbal\r\n" + "FROM \r\n"
			+ "    accountsdetails t2\r\n" + "JOIN \r\n" + "    accounts t1 ON t1.accountsid = t2.accountsid\r\n"
			+ "JOIN \r\n" + "    b ON t1.branchcode = b.branchcode\r\n" + "JOIN \r\n"
			+ "    groupledger g ON t2.accountname = g.accountgroupname\r\n" + "LEFT JOIN \r\n"
			+ "    a ON a.subledgername = t2.subledgername\r\n" + "WHERE \r\n" + "    t1.CANCEL = 0 \r\n"
			+ "    AND (\r\n" + "        ?4 IS NULL \r\n" + "        OR ?4 = '' \r\n"
			+ "        OR t1.vdate BETWEEN STR_TO_DATE(?4, '%Y-%m-%d') AND STR_TO_DATE(?5, '%Y-%m-%d')\r\n"
			+ "        OR ?5 IS NULL \r\n" + "        OR ?5 = ''\r\n" + "    )\r\n"
			+ "    AND (?3 = 'ALL' OR b.branchcode = ?3)\r\n" + "    AND t1.orgid = ?1\r\n"
			+ "    AND (g.accountgroupname = ?2 OR ?2 = 'ALL')\r\n" + "GROUP BY \r\n" + "    b.branch, \r\n"
			+ "    t1.currency, \r\n" + "    t1.vdate, \r\n" + "    t1.vid, \r\n" + "    t1.refno, \r\n"
			+ "    t1.refdate, \r\n" + "    t1.chequeno, \r\n" + "    t1.chequedate, \r\n" + "    t1.remarks, \r\n"
			+ "    a.subledgername, \r\n" + "    t1.currency, \r\n" + "    t1.exrate, \r\n" + "    t1.accountsid, \r\n"
			+ "    t2.subledgername\r\n" + "\r\n" + "UNION \r\n" + "\r\n" + "SELECT \r\n" + "    3 AS ids, \r\n"
			+ "    0 AS recordid, \r\n" + "    b.branch AS branchname, \r\n" + "    NULL AS vid, \r\n"
			+ "    NULL AS vdate, \r\n" + "    COALESCE(t2.subledgername, 'N/A') AS partyname, \r\n"
			+ "    0 AS opbal, \r\n" + "    NULL AS currency, \r\n" + "    0 AS dbamount, \r\n"
			+ "    0 AS cramount, \r\n" + "    0 AS ndbamount, \r\n" + "    0 AS ncramount,\r\n"
			+ "    SUM(t2.bcreditamount-t2.bdebitamount) AS clbal\r\n" + "FROM \r\n" + "    accountsdetails t2\r\n"
			+ "JOIN \r\n" + "    accounts t1 ON t1.accountsid = t2.accountsid\r\n" + "JOIN \r\n"
			+ "    b ON t1.branchcode = b.branchcode\r\n" + "JOIN \r\n"
			+ "    groupledger g ON t2.accountname = g.accountgroupname\r\n" + "LEFT JOIN \r\n"
			+ "    a ON a.subledgername = t2.subledgername\r\n" + "WHERE \r\n" + "    t1.CANCEL = 0 \r\n"
			+ "    AND (\r\n" + "        ?4 IS NULL \r\n" + "        OR ?4 = '' \r\n"
			+ "        OR t1.vdate BETWEEN STR_TO_DATE(?4, '%Y-%m-%d') AND STR_TO_DATE(?5, '%Y-%m-%d')\r\n"
			+ "        OR ?5 IS NULL \r\n" + "        OR ?5 = ''\r\n" + "    )\r\n"
			+ "    AND (?3 = 'ALL' OR b.branchcode = ?3)\r\n" + "    AND t1.orgid = ?1\r\n"
			+ "    AND (g.accountgroupname = ?2 OR ?2 = 'ALL')\r\n" + "GROUP BY \r\n" + "    b.branch, \r\n"
			+ "    t2.subledgername")
	Set<Object[]> getAllLedgerReport(Long orgId, String accountName, String branchCode, String fromDate, String toDate);

	@Query(nativeQuery = true, value = "select accountgroupname from groupledger where orgid=?1  and  category in('PAYABLE A/C','RECEIVABLE A/C')")
	Set<Object[]> getAccountNameFromGroup(Long orgId);

	@Query(nativeQuery = true, value = "SELECT t.partyname,SUM(case when g.totalchargeamountlc IS NULL THEN t.totalchargeamountlc else  (t.totalchargeamountlc - g.totalchargeamountlc)  end )AS amt, p.partyshortname\r\n"
			+ "FROM taxinvoice t \r\n" + "JOIN accounts a ON a.refno = t.docid \r\n"
			+ "left JOIN irncreditnote g ON t.docid = g.originbillno and g.approvestatus ='Approved' \r\n"
			+ "JOIN partymaster p ON p.partyname = t.partyname \r\n"
			+ "WHERE t.branchcode = ?4 AND t.cancel = 'F' AND MONTH(t.vdate) = MONTH(CURDATE()) AND ?2 = 'MONTH' AND t.orgid = ?1 and t.approvestatus ='Approved' GROUP BY t.partyname, p.partyshortname \r\n"
			+ "UNION \r\n"
			+ "SELECT t.partyname, SUM(case when g.totalchargeamountlc IS NULL THEN t.totalchargeamountlc else  (t.totalchargeamountlc - g.totalchargeamountlc)  end )AS amt, p.partyshortname \r\n"
			+ "FROM taxinvoice t \r\n" + "JOIN accounts a ON a.refno = t.docid \r\n"
			+ "Left JOIN irncreditnote g ON t.docid = g.originbillno and g.approvestatus ='Approved' \r\n"
			+ "JOIN partymaster p ON p.partyname = t.partyname \r\n"
			+ "WHERE t.branchcode = ?4 AND t.cancel = 'F' AND ?2 = 'ALL' AND t.finyear = ?3 AND t.orgid = ?1 and t.approvestatus ='Approved'  GROUP BY t.partyname, p.partyshortname \r\n")
	Set<Object[]> getMonthlyAndYearWiseData(Long orgId, String month, String year, String branchCode);

	@Query(nativeQuery = true, value = "SELECT \r\n" + "    j.product, \r\n"  
			+ "    sum(case when g.totalchargeamountlc is not null then  (t.totalchargeamountlc - g.totalchargeamountlc)  else t.totalchargeamountlc end )as  amt,\r\n"
			+ "    t.orgid\r\n" + "FROM taxinvoice t left JOIN irncreditnote g ON t.docid = g.originbillno and g.approvestatus ='Approved'\r\n"
			+ "JOIN jobcard j ON j.jobno = t.joborderno\r\n" + "join accounts a on a.refno=t.docid\r\n"
			+ "WHERE t.branchcode=?4 and\r\n" + "    t.cancel = 'F'\r\n"
			+ "    AND (MONTH(t.vdate) = MONTH(CURDATE()) )and ?2 = 'MONTH'\r\n" + "    AND t.finyear =?3\r\n"
			+ "    AND t.orgid = ?1 and t.approvestatus ='Approved'\r\n" + "GROUP BY j.product, t.orgid\r\n" + "UNION\r\n" + "SELECT \r\n"
			+ "    j.product, \r\n"
			+ "    sum(case when g.totalchargeamountlc is not null then  (t.totalchargeamountlc - g.totalchargeamountlc)  else t.totalchargeamountlc end )as  amt,\r\n"
			+ "    t.orgid\r\n" + "FROM taxinvoice t left JOIN irncreditnote g ON t.docid = g.originbillno and g.approvestatus ='Approved'\r\n"
			+ "join accounts a on a.refno=t.docid\r\n" + "JOIN jobcard j ON j.jobno = t.joborderno\r\n"
			+ "WHERE t.branchcode=?4 and\r\n" + "    t.cancel = 'F' and 'ALL'=?2\r\n" + "    AND t.finyear = ?3\r\n"
			+ "    AND t.orgid = ?1 and t.approvestatus ='Approved'\r\n" + "GROUP BY j.product, t.orgid")
	Set<Object[]> getSalesDistributionData(Long orgId, String month, String finYear, String branchCode);
 
	@Query(nativeQuery = true, value = "select partycode,partyname,partyshortname from partymaster where orgid=?1 and bussinesscate='TRANSPORTER'")
	Set<Object[]> getAllTransprtersReport(Long orgId);
	
	
	@Query(nativeQuery = true, value = "SELECT \r\n"
			+ "    a.partyname,\r\n"
			+ "    CONCAT(\r\n"
			+ "        IFNULL(p.addressline1, ''), ' ',\r\n"
			+ "        IFNULL(p.addressline2, ''), ' ',\r\n"
			+ "        IFNULL(p.addressline3, ''),' - ', IFNULL(p.pincode, '')\r\n"
			+ "    ) AS full_address,\r\n"
			+ "    p.stategstin \r\n"
			+ "FROM partymaster a\r\n"
			+ "JOIN partyaddress p ON a.partymasterid = p.partymasterid\r\n"
			+ "WHERE a.partytype = 'VENDOR' and a.orgid =?1  group by a.partyname,addressline1,p.pincode ,addressline2,addressline3 ,stategstin  ")
	Set<Object[]> getVedorsAddressDetails(Long orgId );
	
	@Query(nativeQuery = true, value = "SELECT \r\n"
			+ "    a.partyname,\r\n"
			+ "    CONCAT(\r\n"
			+ "        IFNULL(p.addressline1, ''), ' ',\r\n"
			+ "        IFNULL(p.addressline2, ''), ' ',\r\n"
			+ "        IFNULL(p.addressline3, '')\r\n"
			+ "    ) AS full_address,\r\n"
			+ "    p.stategstin \r\n"
			+ "FROM partymaster a\r\n"
			+ "JOIN partyaddress p ON a.partymasterid = p.partymasterid\r\n"
			+ "WHERE a.partytype = 'CUSTOMER' and a.orgid =?1  group by a.partyname,addressline1 ,addressline2,addressline3 ,stategstin  ")
	Set<Object[]> getCustomersAddressDetails(Long orgId );

//	@Query(nativeQuery = true, value = "SELECT \r\n"
//			+ "    ids, '' cfinyr, stdt, eddt, recordid, branch, voucher_date, \r\n"
//			+ "    voucher_number, manme, opbal, currency, dbamount, cramount, \r\n"
//			+ "    ndbamount, ncramount, particulars, partyname, Narration, tstruct \r\n"
//			+ "FROM (\r\n"
//			+ "    WITH \r\n"
//			+ "    m AS (\r\n"
//			+ "        SELECT accountname \r\n"
//			+ "        FROM accountsdetails \r\n"
//			+ "        WHERE (accountname = ?5 OR ?5 = 'ALL')         \r\n"
//			+ "        GROUP BY accountname\r\n"
//			+ "    ), \r\n"
//			+ "    b AS (\r\n"
//			+ "        SELECT branchid, branch \r\n"
//			+ "        FROM branch \r\n"
//			+ "        WHERE (branch =?2 or ?2='ALL')\r\n"
//			+ "    ), \r\n"
//			+ "    s AS (\r\n"
//			+ "        SELECT partycode, partyname \r\n"
//			+ "        FROM partymaster\r\n"
//			+ "    ),\r\n"
//			+ "    p AS (\r\n"
//			+ "        SELECT accountsid, subledgername \r\n"
//			+ "        FROM (\r\n"
//			+ "            SELECT \r\n"
//			+ "                accountsid, \r\n"
//			+ "                subledgername, \r\n"
//			+ "                ROW_NUMBER() OVER (\r\n"
//			+ "                    PARTITION BY accountsid \r\n"
//			+ "                    ORDER BY COUNT(accountsid) DESC\r\n"
//			+ "                ) AS row_num \r\n"
//			+ "            FROM accountsdetails \r\n"
//			+ "            WHERE subledgername <> 'None' \r\n"
//			+ "            GROUP BY accountsid, subledgername\r\n"
//			+ "        ) t  \r\n"
//			+ "        WHERE row_num = 1\r\n"
//			+ "    )\r\n"
//			+ "\r\n"
//			+ "    SELECT \r\n"
//			+ "        1 AS ids, \r\n"
//			+ "        ?3 AS stdt,                   \r\n"
//			+ "        ?4 AS eddt,                   \r\n"
//			+ "        0 AS recordid, \r\n"
//			+ "        NULL AS transid, \r\n"
//			+ "        b.branch, \r\n"
//			+ "        NULL AS voucher_date, \r\n"
//			+ "        NULL AS voucher_number, \r\n"
//			+ "        m.accountname AS manme, \r\n"
//			+ "        m.accountname AS m1, \r\n"
//			+ "        (SUM(t2.bdebitamount) - SUM(t2.bcreditamount)) AS opbal, \r\n"
//			+ "        NULL AS currency, \r\n"
//			+ "        0 AS dbamount, \r\n"
//			+ "        0 AS cramount, \r\n"
//			+ "        0 AS ndbamount, \r\n"
//			+ "        0 AS ncramount, \r\n"
//			+ "        CONCAT_WS(' - ', t1.remarks, t1.sourcescreen) AS particulars, \r\n"
//			+ "        s.partyname, \r\n"
//			+ "        NULL AS Narration, \r\n"
//			+ "        NULL AS tstruct \r\n"
//			+ "    FROM \r\n"
//			+ "        accountsdetails t2\r\n"
//			+ "        JOIN accounts t1 ON t1.accountsid = t2.accountsid \r\n"
//			+ "        JOIN m ON t2.accountname = m.accountname \r\n"
//			+ "        JOIN s ON t2.subledgercode = s.partycode \r\n"
//			+ "        JOIN b ON t1.branch = b.branch\r\n"
//			+ "    WHERE \r\n"
//			+ "        t1.CANCEL = 'F' \r\n"
//			+ "        AND t1.docdate < ?3            \r\n"
//			+ "    GROUP BY \r\n"
//			+ "        b.branch, m.accountname, s.partyname, b.branchid,t1.remarks, t1.sourcescreen\r\n"
//			+ "\r\n"
//			+ "    UNION ALL\r\n"
//			+ "\r\n"
//			+ "    SELECT \r\n"
//			+ "        2 AS ids, \r\n"
//			+ "        ?3 AS stdt,                   \r\n"
//			+ "        ?4 AS eddt,                   \r\n"
//			+ "        t1.accountsid AS recordid, \r\n"
//			+ "        NULL AS transid, \r\n"
//			+ "        b.branch, \r\n"
//			+ "        t1.docdate AS voucher_date, \r\n"
//			+ "        t1.docid AS voucher_number, \r\n"
//			+ "        m.accountname AS manme, \r\n"
//			+ "        m.accountname AS m1, \r\n"
//			+ "        0 AS opbal, \r\n"
//			+ "        t1.currency, \r\n"
//			+ "        t2.bdebitamount as dbamount, \r\n"
//			+ "        t2.bcreditamount AS cramount, \r\n"
//			+ "        t2.debitamount AS ndbamount, \r\n"
//			+ "        t2.creditamount AS ncramount, \r\n"
//			+ "        CASE \r\n"
//			+ "            WHEN UPPER(?6) = 'YES' THEN CONCAT('Party : ', IFNULL(p.subledgername, ''), \r\n"
//			+ "		                      IFNULL(CONCAT(' - Refno: ', t1.refno, ' Ref Date: ', t1.refdate), ''))   \r\n"
//			+ "            ELSE '' \r\n"
//			+ "        END AS particulars,\r\n"
//			+ "        s.partyname, \r\n"
//			+ "        IFNULL(t1.remarks, NULL) AS Narration, \r\n"
//			+ "        NULL AS tstruct \r\n"
//			+ "    FROM \r\n"
//			+ "        accountsdetails t2\r\n"
//			+ "        JOIN accounts t1 ON t1.accountsid = t2.accountsid \r\n"
//			+ "        JOIN m ON t2.accountname = m.accountname \r\n"
//			+ "        JOIN s ON t2.subledgercode = s.partycode \r\n"
//			+ "        JOIN b ON t1.branch = b.branch\r\n"
//			+ "        LEFT JOIN p ON p.accountsid = t1.accountsid\r\n"
//			+ "    WHERE \r\n"
//			+ "        t1.CANCEL = 'F' \r\n"
//			+ "        AND t1.docdate BETWEEN ?3 AND ?4  \r\n"
//			+ "        AND t1.orgid = ?1                \r\n"
//			+ "    GROUP BY \r\n"
//			+ "        t1.accountsid, b.branch, t1.currency, t1.docdate, t1.docid, \r\n"
//			+ "        t1.refno, t1.refdate, t2.subledgername, p.subledgername, \r\n"
//			+ "        t1.currency, t1.exrate, m.accountname, s.partyname, \r\n"
//			+ "        b.branchid,t2.bdebitamount,t2.bcreditamount,t2.debitamount,t2.creditamount\r\n"
//			+ ") AS result \r\n"
//			+ "ORDER BY ids, voucher_date")
//	Set<Object[]> getLedgerReport(Long orgId, String branch, String fromdate, String toDate, 
//			String accountName, String details);
	
	
	@Query(nativeQuery = true, value = "SELECT \r\n"
			+ "    ids, '' AS cfinyr, stdt, eddt, recordid, branch, voucher_date,\r\n"
			+ "    voucher_number, manme, opbal, currency, dbamount, cramount,\r\n"
			+ "    ndbamount, ncramount, particulars, partyname, Narration, tstruct\r\n"
			+ "FROM (\r\n"
			+ "\r\n"
			+ "    WITH \r\n"
			+ "    m AS (\r\n"
			+ "        SELECT DISTINCT accountname \r\n"
			+ "        FROM accountsdetails \r\n"
			+ "        WHERE ( ?5 = 'ALL' OR accountname = ?5 )\r\n"
			+ "    ), \r\n"
			+ "\r\n"
			+ "    b AS (\r\n"
			+ "        SELECT DISTINCT branchid, branch \r\n"
			+ "        FROM branch \r\n"
			+ "        WHERE ( ?2 = 'ALL' OR branch = ?2)\r\n"
			+ "    ),\r\n"
			+ "\r\n"
			+ "    s AS (\r\n"
			+ "        SELECT \r\n"
			+ "            partycode, \r\n"
			+ "            CASE \r\n"
			+ "                WHEN UPPER(MAX(partyname)) = 'NONE' THEN NULL \r\n"
			+ "                ELSE MAX(partyname) \r\n"
			+ "            END AS partyname\r\n"
			+ "        FROM partymaster\r\n"
			+ "        GROUP BY partycode\r\n"
			+ "    ),\r\n"
			+ "\r\n"
			+ "    p AS (\r\n"
			+ "        SELECT accountsid, subledgername \r\n"
			+ "        FROM (\r\n"
			+ "            SELECT \r\n"
			+ "                accountsid,\r\n"
			+ "                subledgername,\r\n"
			+ "                ROW_NUMBER() OVER (\r\n"
			+ "                    PARTITION BY accountsid \r\n"
			+ "                    ORDER BY COUNT(*) DESC\r\n"
			+ "                ) AS rn\r\n"
			+ "            FROM accountsdetails\r\n"
			+ "            WHERE subledgername <> 'None'\r\n"
			+ "            GROUP BY accountsid, subledgername\r\n"
			+ "        ) x\r\n"
			+ "        WHERE rn = 1\r\n"
			+ "    )\r\n"
			+ "\r\n"
			+ "    -- OPENING\r\n"
			+ "    SELECT \r\n"
			+ "        1 AS ids,\r\n"
			+ "        ?3 AS stdt,\r\n"
			+ "        ?4 AS eddt,\r\n"
			+ "        0 AS recordid,\r\n"
			+ "        b.branch,\r\n"
			+ "        NULL AS voucher_date,\r\n"
			+ "        NULL AS voucher_number,\r\n"
			+ "        m.accountname AS manme,\r\n"
			+ "        ABS(SUM(t2.bdebitamount) - SUM(t2.bcreditamount)) AS opbal,\r\n"
			+ "        NULL AS currency,\r\n"
			+ "        0 AS dbamount,\r\n"
			+ "        0 AS cramount,\r\n"
			+ "        0 AS ndbamount,\r\n"
			+ "        0 AS ncramount,\r\n"
			+ "        CONCAT_WS(' - ', t1.remarks, t1.sourcescreen) AS particulars,\r\n"
			+ "        NULL AS partyname,\r\n"
			+ "        NULL AS Narration,\r\n"
			+ "        NULL AS tstruct\r\n"
			+ "    FROM accountsdetails t2\r\n"
			+ "    JOIN accounts t1 ON t1.accountsid = t2.accountsid\r\n"
			+ "    JOIN m ON t2.accountname = m.accountname\r\n"
			+ "    JOIN b ON t1.branch = b.branch\r\n"
			+ "    WHERE t1.CANCEL = 'F'\r\n"
			+ "      AND t1.docdate < ?3\r\n"
			+ "      AND t1.orgid = ?1\r\n"
			+ "    GROUP BY b.branch, m.accountname, t1.remarks, t1.sourcescreen\r\n"
			+ "\r\n"
			+ "    UNION ALL\r\n"
			+ "\r\n"
			+ "    -- TRANSACTIONS\r\n"
			+ "    SELECT \r\n"
			+ "        2 AS ids,\r\n"
			+ "        ?3,\r\n"
			+ "        ?4,\r\n"
			+ "        t1.accountsid,\r\n"
			+ "        b.branch,\r\n"
			+ "        t1.docdate,\r\n"
			+ "        t1.docid,\r\n"
			+ "        m.accountname,\r\n"
			+ "        0,\r\n"
			+ "        t1.currency,\r\n"
			+ "        t2.bdebitamount,\r\n"
			+ "        t2.bcreditamount,\r\n"
			+ "        t2.debitamount,\r\n"
			+ "        t2.creditamount,\r\n"
			+ "        CASE \r\n"
			+ "            WHEN UPPER(?6) = 'YES' THEN \r\n"
			+ "                CONCAT(\r\n"
			+ "                    'Party : ', IFNULL(p.subledgername, ''), \r\n"
			+ "                    IFNULL(CONCAT(' - Refno: ', t1.refno, ' Ref Date: ', t1.refdate), '')\r\n"
			+ "                )\r\n"
			+ "            ELSE '' \r\n"
			+ "        END AS particulars,\r\n"
			+ "        s.partyname,\r\n"
			+ "        t1.remarks,\r\n"
			+ "        NULL\r\n"
			+ "    FROM accountsdetails t2\r\n"
			+ "    JOIN accounts t1 ON t1.accountsid = t2.accountsid\r\n"
			+ "    JOIN m ON t2.accountname = m.accountname\r\n"
			+ "    JOIN b ON t1.branch = b.branch\r\n"
			+ "    LEFT JOIN s ON t2.subledgercode = s.partycode\r\n"
			+ "    LEFT JOIN p ON p.accountsid = t1.accountsid\r\n"
			+ "    WHERE t1.CANCEL = 'F'\r\n"
			+ "      AND t1.docdate BETWEEN ?3 AND ?4\r\n"
			+ "      AND t1.orgid = ?1\r\n"
			+ "\r\n"
			+ "    UNION ALL\r\n"
			+ "\r\n"
			+ "    -- TOTAL\r\n"
			+ "    SELECT \r\n"
			+ "        3 AS ids,\r\n"
			+ "        ?3,\r\n"
			+ "        ?4,\r\n"
			+ "        0,\r\n"
			+ "        NULL,\r\n"
			+ "        NULL,\r\n"
			+ "        'TotalAmount',\r\n"
			+ "        '',\r\n"
			+ "        0,\r\n"
			+ "        NULL,\r\n"
			+ "        SUM(t2.bdebitamount),\r\n"
			+ "        SUM(t2.bcreditamount),\r\n"
			+ "        SUM(t2.debitamount),\r\n"
			+ "        SUM(t2.creditamount),\r\n"
			+ "        '',\r\n"
			+ "        NULL,\r\n"
			+ "        NULL,\r\n"
			+ "        NULL\r\n"
			+ "    FROM accountsdetails t2\r\n"
			+ "    JOIN accounts t1 ON t1.accountsid = t2.accountsid\r\n"
			+ "    JOIN m ON t2.accountname = m.accountname\r\n"
			+ "    JOIN b ON t1.branch = b.branch\r\n"
			+ "    WHERE t1.CANCEL = 'F'\r\n"
			+ "      AND t1.docdate BETWEEN ?3 AND ?4\r\n"
			+ "      AND t1.orgid = ?1\r\n"
			+ "\r\n"
			+ ") AS result\r\n"
			+ "ORDER BY ids, voucher_date")
	Set<Object[]> getLedgerReport(Long orgId, String branch, String fromdate, String toDate, 
			String accountName, String details);

	@Query(nativeQuery = true, value = "select partyshortname,partyname,partycode from partymaster where orgid=?1 and partytype='Customer' and active=1")
	Set<Object[]> getCustomer(Long orgId);

	@Query(nativeQuery = true, value = "select * from partymaster where orgid=?1 and partytype='CUSTOMER' and active=1 and cancel=0")
	List<PartyMasterVO> getAllActiveCustomers(Long orgId);

}
