package com.base.basesetup.repo;

import java.util.List;
import java.util.Set;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import com.base.basesetup.entity.PartyMasterVO;

@Repository
public interface PartyMasterRepo extends JpaRepository<PartyMasterVO, Long> {

	@Query(nativeQuery = true, value = "select * from partymaster where partymasterid=?1")
	List<PartyMasterVO> findPartyMasterVOById(Long id);

	@Query(nativeQuery = true, value = "select * from partymaster where orgid=?1")
	List<PartyMasterVO> findByOrgId(Long orgid);

	@Query(nativeQuery = true, value = "select concat(prefixfield,lpad(lastno,5,0)) AS docid from documenttypemappingdetails where orgid=?1 and finyear=?2 and branchcode=?3 and screencode=?4")
	String getPartyMasterDocId(Long orgId, String finYear, String branchCode, String screenCode);

	@Query(value = "select a from PartyMasterVO a where a.orgId=?1 and a.partyType=?2 and a.active=true")
	List<PartyMasterVO> findByOrgIdAndPartyTypeIgnoreCase(Long orgId, String partyType);

	PartyMasterVO findByPartyCode(String partyCode);

	@Query(nativeQuery = true, value = "select * from partymaster where orgid=?1 and partytype='CUSTOMER'")
	List<PartyMasterVO> getAllCustomers(Long orgId);

	@Query(nativeQuery = true, value = "select * from partymaster where orgid=?1 and partytype='VENDOR'")
	List<PartyMasterVO> getAllVendors(Long orgId);

	boolean existsByPartyNameAndOrgId(String customerName, long orgId);

	boolean existsByPartyNameAndOrgIdAndPartyType(String customerName, long orgId, String partyType);

	@Query(nativeQuery = true, value = "SELECT \r\n"
			+ "    sno, \r\n"
			+ "    recordid, \r\n"
			+ "    vid, \r\n"
			+ "    vdate, \r\n"
			+ "    refno, \r\n"
			+ "    refdate, \r\n"
			+ "    supprefno, \r\n"
			+ "    supprefdate, \r\n"
			+ "    partycode, \r\n"
			+ "    partyname, \r\n"
			+ "    currency, \r\n"
			+ "    opbal,         \r\n"
			+ "    dbamount,      \r\n"
			+ "    cramount,      \r\n"
			+ "    billdbamount,   \r\n"
			+ "    billcramount,   \r\n"
			+ "    clbal           \r\n"
			+ "FROM (\r\n"
			+ "    -- Opening Balance Query (First one)\r\n"
			+ "    SELECT \r\n"
			+ "        1 AS sno,\r\n"
			+ "        0 AS recordid,\r\n"
			+ "        NULL AS vid,\r\n"
			+ "        NULL AS vdate,\r\n"
			+ "        NULL AS refno,\r\n"
			+ "        NULL AS refdate,\r\n"
			+ "        NULL AS supprefno,\r\n"
			+ "        NULL AS supprefdate,\r\n"
			+ "        p.partycode,\r\n"
			+ "        p.partyname,\r\n"
			+ "        NULL AS currency,\r\n"
			+ "        (SUM(t2.bdebitamount) - SUM(t2.bcreditamount)) AS opbal,  \r\n"
			+ "        0 AS dbamount,\r\n"
			+ "        0 AS cramount,\r\n"
			+ "        0 AS billdbamount,\r\n"
			+ "        0 AS billcramount,\r\n"
			+ "        NULL AS clbal\r\n"
			+ "    FROM \r\n"
			+ "        accountsdetails t2\r\n"
			+ "    JOIN \r\n"
			+ "        accounts t1 ON t1.accountsid = t2.accountsid\r\n"
			+ "    JOIN \r\n"
			+ "        partymaster p ON t2.subledgercode = p.partycode\r\n"
			+ "    JOIN \r\n"
			+ "        branch dm ON dm.branchcode = t1.branchcode\r\n"
			+ "    WHERE \r\n"
			+ "        t1.CANCEL = 0\r\n"
			+ "        AND t1.vdate >=?5  \r\n"
			+ "        AND (p.partyname =?2 OR ?2 = 'ALL')\r\n"
			+ "       AND (p.partytype =?3  OR ?3 = 'ALL' AND ?3 ='ALL' OR ?3 = 'ALL')\r\n"
			+ "        AND t2.acategory IN ('PAYABLE A/C', 'RECEIVABLE A/C')\r\n"
			+ "        AND t1.orgid =?1\r\n"
			+ "        AND (?4 = 'ALL' OR t1.branch =?4)\r\n"
			+ "    GROUP BY \r\n"
			+ "        p.partycode, p.partyname\r\n"
			+ "\r\n"
			+ "    UNION\r\n"
			+ "\r\n"
			+ "    SELECT \r\n"
			+ "        2 AS sno,\r\n"
			+ "        t1.accountsid AS recordid,\r\n"
			+ "        t1.vid,\r\n"
			+ "        t1.vdate,\r\n"
			+ "        t1.refno,\r\n"
			+ "        t1.refdate,\r\n"
			+ "        t1.supplierrefno,\r\n"
			+ "        t1.supplierrefdate,\r\n"
			+ "        p.partycode,\r\n"
			+ "        p.partyname,\r\n"
			+ "        t1.currency,\r\n"
			+ "        0 AS opbal,        \r\n"
			+ "        SUM(t2.bdebitamount) AS dbamount,\r\n"
			+ "        SUM(t2.bcreditamount) AS cramount,\r\n"
			+ "        SUM(t2.debitamount) AS billdbamount,   \r\n"
			+ "        SUM(t2.creditamount) AS billcramount, \r\n"
			+ "        (SUM(t2.bdebitamount) - SUM(t2.bcreditamount)) AS clbal  \r\n"
			+ "    FROM \r\n"
			+ "        accountsdetails t2\r\n"
			+ "    JOIN \r\n"
			+ "        accounts t1 ON t1.accountsid = t2.accountsid\r\n"
			+ "    JOIN \r\n"
			+ "        partymaster p ON t2.subledgercode = p.partycode\r\n"
			+ "    JOIN \r\n"
			+ "        branch dm ON dm.branchcode = t1.branchcode\r\n"
			+ "    WHERE \r\n"
			+ "        t1.CANCEL = 0\r\n"
			+ "        AND (t1.vdate BETWEEN date(?5) AND date(?6) OR (?5 is null AND ?6 is null))\r\n"
			+ "        AND (p.partyname =?2 OR ?2 = 'ALL')\r\n"
			+ "        AND (p.partytype =?3 OR ?3 = 'ALL' AND ?3 ='ALL' OR ?3 = 'ALL')\r\n"
			+ "        AND t2.acategory IN ('PAYABLE A/C', 'RECEIVABLE A/C')\r\n"
			+ "        AND t1.orgid =?1\r\n"
			+ "        AND (?4 = 'ALL' OR t1.branch =?4)\r\n"
			+ "    GROUP BY \r\n"
			+ "        t1.accountsid, t1.vid, t1.vdate, t1.refno, t1.refdate, \r\n"
			+ "        t1.supplierrefno, t1.supplierrefdate, p.partyname, p.partycode, t1.currency\r\n"
			+ "\r\n"
			+ "    UNION\r\n"
			+ "    SELECT \r\n"
			+ "        3 AS sno,\r\n"
			+ "        0 AS recordid,\r\n"
			+ "        NULL AS vid,\r\n"
			+ "        NULL AS vdate,\r\n"
			+ "        NULL AS refno,\r\n"
			+ "        NULL AS refdate,\r\n"
			+ "        NULL AS supprefno,\r\n"
			+ "        NULL AS supprefdate,\r\n"
			+ "        p.partycode,\r\n"
			+ "        p.partyname,\r\n"
			+ "        NULL AS currency,\r\n"
			+ "        NULL AS opbal,\r\n"
			+ "        0 AS dbamount,\r\n"
			+ "        0 AS cramount,\r\n"
			+ "        0 AS billdbamount,\r\n"
			+ "        0 AS billcramount,\r\n"
			+ "        (SUM(t2.bdebitamount) - SUM(t2.bcreditamount)) AS clbal  \r\n"
			+ "    FROM \r\n"
			+ "        accountsdetails t2\r\n"
			+ "    JOIN \r\n"
			+ "        accounts t1 ON t1.accountsid = t2.accountsid\r\n"
			+ "    JOIN \r\n"
			+ "        partymaster p ON t2.subledgercode = p.partycode\r\n"
			+ "    JOIN \r\n"
			+ "        branch dm ON dm.branchcode = t1.branchcode\r\n"
			+ "    WHERE \r\n"
			+ "      t1.CANCEL = 0\r\n"
			+ "        AND (t1.vdate BETWEEN date(?5) AND date(?6) OR (?5 is null AND ?6 is null))\r\n"
			+ "        AND (p.partyname =?2 OR ?2 = 'ALL')\r\n"
			+ "        AND (p.partytype =?3 OR ?3 = 'ALL' AND ?3 ='ALL' OR ?3 = 'ALL')\r\n"
			+ "        AND t2.acategory IN ('PAYABLE A/C', 'RECEIVABLE A/C')\r\n"
			+ "        AND t1.orgid =?1\r\n"
			+ "        AND (?4 = 'ALL' OR t1.branch =?4)\r\n"
			+ "    GROUP BY \r\n"
			+ "        p.partycode, p.partyname\r\n"
			+ ") A\r\n"
			+ "ORDER BY \r\n"
			+ "    sno, vid, vdate, partyname")
	Set<Object[]> getAllPartyLedgerReport(Long orgId,String partyName,String partyType,String branch,String fromDate,String toDate);
	
	
	@Query(nativeQuery = true, value = "WITH \r\n"
			+ "    b AS (\r\n"
			+ "        SELECT \r\n"
			+ "            branch, \r\n"
			+ "            branchcode\r\n"
			+ "        FROM \r\n"
			+ "            branch\r\n"
			+ "    ), \r\n"
			+ "    p AS (\r\n"
			+ "        SELECT \r\n"
			+ "            partycode, \r\n"
			+ "            partyname\r\n"
			+ "        FROM \r\n"
			+ "            partymaster\r\n"
			+ "    ), \r\n"
			+ "    a AS (\r\n"
			+ "        SELECT \r\n"
			+ "            ACCOUNTNAME, \r\n"
			+ "            subledgername\r\n"
			+ "        FROM \r\n"
			+ "            (\r\n"
			+ "                SELECT \r\n"
			+ "                    ACCOUNTNAME, \r\n"
			+ "                    subledgername, \r\n"
			+ "                    COUNT(accountsid) AS count_accounts,\r\n"
			+ "                    ROW_NUMBER() OVER (PARTITION BY accountsid ORDER BY COUNT(accountsid) DESC) AS row_num  \r\n"
			+ "                FROM \r\n"
			+ "                    accountsdetails\r\n"
			+ "                WHERE \r\n"
			+ "                    subledgername = 'None' \r\n"
			+ "                GROUP BY \r\n"
			+ "                    ACCOUNTNAME, subledgername, accountsid\r\n"
			+ "            ) t  \r\n"
			+ "        WHERE \r\n"
			+ "            row_num = 1\r\n"
			+ "    )\r\n"
			+ "\r\n"
			+ "SELECT \r\n"
			+ "    1 AS ids, \r\n"
			+ "    0 AS recordid, \r\n"
			+ "    b.branch AS branchname, \r\n"
			+ "    NULL AS vid, \r\n"
			+ "    NULL AS vdate, \r\n"
			+ "    COALESCE(t2.subledgername, 'N/A') AS partyname, \r\n"
			+ "       SUM(t2.bcreditamount-t2.bdebitamount ) AS opbal,  \r\n"
			+ "    NULL AS currency, \r\n"
			+ "    0 AS dbamount, \r\n"
			+ "    0 AS cramount, \r\n"
			+ "    0 AS ndbamount, \r\n"
			+ "    0 AS ncramount,\r\n"
			+ "    0 AS clbal\r\n"
			+ "FROM \r\n"
			+ "    accountsdetails t2\r\n"
			+ "JOIN \r\n"
			+ "    accounts t1 ON t1.accountsid = t2.accountsid\r\n"
			+ "JOIN \r\n"
			+ "    b ON t1.branchcode = b.branchcode\r\n"
			+ "JOIN \r\n"
			+ "    groupledger g ON t2.accountname = g.accountgroupname\r\n"
			+ "WHERE \r\n"
			+ "    t1.CANCEL = 0\r\n"
			+ "     AND (\r\n"
			+ "        ?4 IS NULL \r\n"
			+ "        OR ?4 = '' \r\n"
			+ "        OR t1.vdate > STR_TO_DATE(?4, '%Y-%m-%d')  \r\n"
			+ "    )\r\n"
			+ "    AND (?3 = 'ALL' OR b.branchcode = ?3)\r\n"
			+ "    AND t1.orgid = ?1\r\n"
			+ "    AND (g.accountgroupname = ?2 OR ?2 = 'ALL')\r\n"
			+ "GROUP BY \r\n"
			+ "    b.branch, \r\n"
			+ "    t2.subledgername\r\n"
			+ "\r\n"
			+ "UNION \r\n"
			+ "\r\n"
			+ "SELECT \r\n"
			+ "    2 AS ids, \r\n"
			+ "    t1.accountsid AS recordid, \r\n"
			+ "    b.branch AS branchname, \r\n"
			+ "    t1.vdate AS vdate, \r\n"
			+ "    t1.vid AS vid, \r\n"
			+ "    (SELECT subledgername \r\n"
			+ "     FROM accountsdetails \r\n"
			+ "     WHERE accountsid = t1.accountsid \r\n"
			+ "     AND subledgername NOT IN ('None')) AS partyname,\r\n"
			+ "    0 AS opbal, \r\n"
			+ "    t1.currency, \r\n"
			+ "    SUM(t2.bdebitamount) AS dbamount, \r\n"
			+ "    SUM(t2.bcreditamount) AS cramount, \r\n"
			+ "    SUM(t2.debitamount) AS ndbamount, \r\n"
			+ "    SUM(t2.creditamount) AS ncramount,\r\n"
			+ "    0 AS clbal\r\n"
			+ "FROM \r\n"
			+ "    accountsdetails t2\r\n"
			+ "JOIN \r\n"
			+ "    accounts t1 ON t1.accountsid = t2.accountsid\r\n"
			+ "JOIN \r\n"
			+ "    b ON t1.branchcode = b.branchcode\r\n"
			+ "JOIN \r\n"
			+ "    groupledger g ON t2.accountname = g.accountgroupname\r\n"
			+ "LEFT JOIN \r\n"
			+ "    a ON a.subledgername = t2.subledgername\r\n"
			+ "WHERE \r\n"
			+ "    t1.CANCEL = 0 \r\n"
			+ "    AND (\r\n"
			+ "        ?4 IS NULL \r\n"
			+ "        OR ?4 = '' \r\n"
			+ "        OR t1.vdate BETWEEN STR_TO_DATE(?4, '%Y-%m-%d') AND STR_TO_DATE(?5, '%Y-%m-%d')\r\n"
			+ "        OR ?5 IS NULL \r\n"
			+ "        OR ?5 = ''\r\n"
			+ "    )\r\n"
			+ "    AND (?3 = 'ALL' OR b.branchcode = ?3)\r\n"
			+ "    AND t1.orgid = ?1\r\n"
			+ "    AND (g.accountgroupname = ?2 OR ?2 = 'ALL')\r\n"
			+ "GROUP BY \r\n"
			+ "    b.branch, \r\n"
			+ "    t1.currency, \r\n"
			+ "    t1.vdate, \r\n"
			+ "    t1.vid, \r\n"
			+ "    t1.refno, \r\n"
			+ "    t1.refdate, \r\n"
			+ "    t1.chequeno, \r\n"
			+ "    t1.chequedate, \r\n"
			+ "    t1.remarks, \r\n"
			+ "    a.subledgername, \r\n"
			+ "    t1.currency, \r\n"
			+ "    t1.exrate, \r\n"
			+ "    t1.accountsid, \r\n"
			+ "    t2.subledgername\r\n"
			+ "\r\n"
			+ "UNION \r\n"
			+ "\r\n"
			+ "SELECT \r\n"
			+ "    3 AS ids, \r\n"
			+ "    0 AS recordid, \r\n"
			+ "    b.branch AS branchname, \r\n"
			+ "    NULL AS vid, \r\n"
			+ "    NULL AS vdate, \r\n"
			+ "    COALESCE(t2.subledgername, 'N/A') AS partyname, \r\n"
			+ "    0 AS opbal, \r\n"
			+ "    NULL AS currency, \r\n"
			+ "    0 AS dbamount, \r\n"
			+ "    0 AS cramount, \r\n"
			+ "    0 AS ndbamount, \r\n"
			+ "    0 AS ncramount,\r\n"
			+ "    SUM(t2.bcreditamount-t2.bdebitamount) AS clbal\r\n"
			+ "FROM \r\n"
			+ "    accountsdetails t2\r\n"
			+ "JOIN \r\n"
			+ "    accounts t1 ON t1.accountsid = t2.accountsid\r\n"
			+ "JOIN \r\n"
			+ "    b ON t1.branchcode = b.branchcode\r\n"
			+ "JOIN \r\n"
			+ "    groupledger g ON t2.accountname = g.accountgroupname\r\n"
			+ "LEFT JOIN \r\n"
			+ "    a ON a.subledgername = t2.subledgername\r\n"
			+ "WHERE \r\n"
			+ "    t1.CANCEL = 0 \r\n"
			+ "    AND (\r\n"
			+ "        ?4 IS NULL \r\n"
			+ "        OR ?4 = '' \r\n"
			+ "        OR t1.vdate BETWEEN STR_TO_DATE(?4, '%Y-%m-%d') AND STR_TO_DATE(?5, '%Y-%m-%d')\r\n"
			+ "        OR ?5 IS NULL \r\n"
			+ "        OR ?5 = ''\r\n"
			+ "    )\r\n"
			+ "    AND (?3 = 'ALL' OR b.branchcode = ?3)\r\n"
			+ "    AND t1.orgid = ?1\r\n"
			+ "    AND (g.accountgroupname = ?2 OR ?2 = 'ALL')\r\n"
			+ "GROUP BY \r\n"
			+ "    b.branch, \r\n"
			+ "    t2.subledgername")
	Set<Object[]> getAllLedgerReport(Long orgId,String accountName, String branchCode,String fromDate,String toDate);
	 
	@Query(nativeQuery = true, value = "select accountgroupname from groupledger where orgid=?1  and  category in('PAYABLE A/C','RECEIVABLE A/C')")
	Set<Object[]> getAccountNameFromGroup(Long orgId);

	@Query(nativeQuery =true,value ="SELECT \r\n"
			+ "    t.partyname, \r\n"
			+ "    SUM(t.totalchargeamountlc) AS amt, \r\n"
			+ "    p.partyshortname\r\n"
			+ "FROM taxinvoice t\r\n"
			+ "JOIN partymaster p ON p.partyname = t.partyname\r\n"
			+ "WHERE \r\n"
			+ "    t.cancel = 'F'\r\n"
			+ "    AND (MONTH(t.docdate) = MONTH(CURDATE()) OR  ?2='MONTH') AND t.finyear=?3 \r\n"
			+ "    AND t.orgid =?1\r\n"
			+ "GROUP BY t.partyname, p.partyshortname\r\n"
			+ "UNION ALL\r\n"
			+ "SELECT \r\n"
			+ "    t.partyname, \r\n"
			+ "    SUM(t.totalchargeamountlc) AS amt, \r\n"
			+ "    p.partyshortname\r\n"
			+ "FROM taxinvoice t\r\n"
			+ "JOIN partymaster p ON p.partyname = t.partyname\r\n"
			+ "WHERE \r\n"
			+ "    t.cancel = 'F'\r\n"
			+ "    AND t.finyear=?3  \r\n"
			+ "    AND t.orgid = ?1\r\n"
			+ "GROUP BY t.partyname, p.partyshortname")
	Set<Object[]> getMonthlyAndYearWiseData(Long orgId, String month,String year);

	
	
	@Query(nativeQuery =true,value ="SELECT \r\n"
			+ "    j.product, \r\n"
			+ "    SUM(t.totalchargeamountlc) AS amt ,\r\n"
			+ "    t.orgid\r\n"
			+ "FROM taxinvoice t \r\n"
			+ "JOIN jobcard j ON j.jobno = t.joborderno\r\n"
			+ "WHERE \r\n"
			+ "    t.cancel = 'F'\r\n"
			+ "    AND (MONTH(docdate) = MONTH(CURDATE()) OR ?2='MONTH') and t.finyear=?3\r\n"
			+ "    AND t.orgid = ?1\r\n"
			+ "GROUP BY j.product,t.orgid\r\n"
			+ "UNION \r\n"
			+ "SELECT \r\n"
			+ "    j.product, \r\n"
			+ "    SUM(t.totalchargeamountlc) AS amt ,\r\n"
			+ "    t.orgid\r\n"
			+ "FROM taxinvoice t \r\n"
			+ "JOIN jobcard j ON j.jobno = t.joborderno\r\n"
			+ "WHERE \r\n"
			+ "    t.cancel = 'F'\r\n"
			+ "    AND t.finyear=?3\r\n"
			+ "    AND t.orgid = ?1\r\n"
			+ "GROUP BY j.product,t.orgid\r\n"
			+ "")
	Set<Object[]> getSalesDistributionData(Long orgId, String month, String finYear);

}
