package com.base.basesetup.repo;

import java.util.List;
import java.util.Set;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import com.base.basesetup.entity.ReceiptVO;

@Repository
public interface ReceiptRepo extends JpaRepository<ReceiptVO, Long> {

	@Query(nativeQuery = true, value = "select * from receipt where orgid=?1 and finyear=?2 and branchcode=?3")
	List<ReceiptVO> getAllReceiptReceivableByOrgId(Long orgId,String finYear, String branchCode);

	@Query(nativeQuery = true, value = "select * from receipt where receiptid=?1")
	List<ReceiptVO> getAllReceiptReceivableById(Long id);

	@Query(nativeQuery = true, value = "select * from receipt where active=1")
	List<ReceiptVO> findReceiptReceivablesByActive();

	@Query(nativeQuery = true, value = "select partyname,partycode from partymaster where orgid=?1 and active=1 and partytype='CUSTOMER'")
	Set<Object[]> getCustomerNameAndCodeForReceipt(Long orgId);

	@Query(nativeQuery = true, value = "select a.docid,a.docdate,a.customername,a.bankcashacc,a.receiptamt,a.bankchargeacc,a.taxamt,a.tdsamt,b.invno,b.invdate,b.refno,b.refdate,a.chequebank,a.chequeutino,b.amount,b.outstanding,b.settled,a.createdon,a.createdby from receipt a, receiptinvdetails b where a.receiptid=b.receiptid and a.orgid=?1 and a.docdate BETWEEN ?2 AND ?3 and a.customername =?4")
	Set<Object[]> findAllReceiptRegister(Long orgId, String fromDate, String toDate, String subLedgerName);

	@Query(nativeQuery = true, value = "select concat(prefixfield,lpad(lastno,5,0)) AS docid from documenttypemappingdetails where orgid=?1 and finyear=?2 and branchcode=?3 and screencode=?4")
	String getReceiptDocId(Long orgId, String finYear, String branchCode, String screenCode);

	@Query(nativeQuery = true, value = "select concat(prefixfield,lpad(lastno,5,0)) AS docid from documenttypemappingdetails where orgid=?1 and finyear=?2 and branchcode=?3 and screencode=?4")
	String getArBillBalanceDocId(Long orgId, String finYear, String branchCode, String screenCode);

	@Query(nativeQuery = true, value = "WITH b AS (\r\n"
			+ "    SELECT \r\n"
			+ "        subledgercode, \r\n"
			+ "        refno AS docid, \r\n"
			+ "        SUM(amount) AS settled\r\n"
			+ "    FROM arapadjustments\r\n"
			+ "    WHERE CANCEL = 'F'\r\n"
			+ "    GROUP BY subledgercode, refno \r\n"
			+ "    HAVING SUM(amount) > 0\r\n"
			+ "),n AS (\r\n"
			+ "    SELECT \r\n"
			+ "        orgid, \r\n"
			+ "        refno, \r\n"
			+ "        SUM(amount) AS settamt \r\n"
			+ "    FROM arapadjustments \r\n"
			+ "    WHERE amount > 0 \r\n"
			+ "    GROUP BY orgid, refno\r\n"
			+ ") select ROW_NUMBER() OVER () AS id,\r\n"
			+ "    a.branch,\r\n"
			+ "    a.subledgercode,\r\n"
			+ "    c.vid,\r\n"
			+ "    c.vdate,\r\n"
			+ "    a.refno,\r\n"
			+ "    a.refdate,\r\n"
			+ "    a.supprefno,\r\n"
			+ "    a.suprefdate,\r\n"
			+ "    a.acccurrency,\r\n"
			+ "    a.exrate,\r\n"
			+ "    SUM(d.totalchargeamountlc - COALESCE(h.totalchargeamountlc, 0)) AS totalAmount,\r\n"
			+ "    SUM(d.totalinvamountlc - COALESCE(h.totalinvamountlc, 0)) - COALESCE(n.settamt, 0) AS invamount,\r\n"
			+ "    a.chargableamt,\r\n"
			+ "    a.tdsamt,\r\n"
			+ "    t.gstpercent,\r\n"
			+ "    SUM(d.totaltaxamountlc - COALESCE(h.totaltaxamountlc, 0)) AS gstamount FROM arapdetails a\r\n"
			+ "LEFT JOIN b \r\n"
			+ "    ON a.subledgercode = b.subledgercode \r\n"
			+ "    AND a.docid = b.docid JOIN taxinvoice d \r\n"
			+ "    ON a.refno = d.docid JOIN taxinvoicedetails t \r\n"
			+ "    ON d.taxinvoiceid = t.taxinvoiceid JOIN accounts c \r\n"
			+ "    ON a.docid = c.docid LEFT JOIN irncreditnote h \r\n"
			+ "    ON d.docid = h.originbillno and h.approvestatus='Approved' left JOIN n \r\n"
			+ "    ON n.orgid = a.orgid \r\n"
			+ "    AND n.refno = c.vid WHERE \r\n"
			+ "    d.branchcode = ?3 \r\n"
			+ "    AND a.CANCEL = 'F'\r\n"
			+ "    AND a.subledgercode = ?2\r\n"
			+ "    AND a.orgid = ?1\r\n"
			+ "    group by \r\n"
			+ "    a.branch,\r\n"
			+ "    a.subledgercode,\r\n"
			+ "    c.vid,\r\n"
			+ "    c.vdate,\r\n"
			+ "    a.refno,\r\n"
			+ "    a.refdate,\r\n"
			+ "    a.supprefno,\r\n"
			+ "    a.suprefdate,\r\n"
			+ "    a.acccurrency,\r\n"
			+ "    a.exrate,\r\n"
			+ "    b.settled,\r\n"
			+ "    a.chargableamt,\r\n"
			+ "    a.tdsamt,\r\n"
			+ "    t.gstpercent,\r\n"
			+ "    n.settamt having SUM(d.totalinvamountlc - COALESCE(h.totalinvamountlc, 0)) - COALESCE(n.settamt, 0)>0\r\n"
			+ "    ORDER BY \r\n"
			+ "    a.refdate,\r\n"
			+ "    c.vid")
	Set<Object[]> findReciptFillGrid(Long orgId, String partyCode,String branchCode);


	@Query(nativeQuery = true, value = "select * from receipt where orgid=?1 and branchcode=?2 and cancel=0")
	List<ReceiptVO> getAllReceiptByOrgIdAndBranchCode(Long orgId, String branchCode);

	@Query(nativeQuery =true,value ="SELECT r.orgid, r.branchcode, r.finyear, \r\n"


			+ "    r.createdby, \r\n"
			+ "    r.createdon, \r\n"
			+ "    r.docid, \r\n"
			+ "    r.docdate, \r\n"
			+ "    r.receipt_type AS subtypecode, \r\n"
			+ "    r.chequebank, \r\n"
			+ "    r.chequeutino AS chqnumber, \r\n"
			+ "    r.customercode AS subledgercode, \r\n"
			+ "    r.customername AS subledgername, \r\n"
			+ "    r.receiptamt AS receiptamount, \r\n"
			+ "    r.bankcharges AS bankchargesamt, \r\n"
			+ "    CASE \r\n"

			+ "        WHEN tds_rank = 1 THEN r.tdsamt ELSE 0 \r\n"

			+ "    END AS tdsamount, \r\n"
			+ "    rd.invno AS invoiceno, \r\n"
			+ "    rd.invdate AS invoicedate, \r\n"
			+ "    rd.refno, \r\n"
			+ "    rd.refdate, \r\n"
			+ "    adj.amount AS arapamount, \r\n"
			+ "    adj.chargeableamt, \r\n"
			+ "    rd.outstanding AS arapoutstanding, \r\n"
			+ "    rd.settled AS arapsettled, \r\n"
			+ "    ?4 AS fyr, \r\n"
			+ "    ?5 AS stdt, \r\n"
			+ "    ?6 AS eddt \r\n"
			+ "FROM (\r\n"
			+ "    SELECT r.receiptid,\r\n"

			+ "        r.orgid, \r\n"
			+ "        r.branchcode, \r\n"
			+ "        r.finyear, \r\n"
			+ "        r.createdby, \r\n"
			+ "        r.createdon, \r\n"
			+ "        r.docid, \r\n"
			+ "        r.docdate, \r\n"
			+ "        r.receipt_type, \r\n"
			+ "        r.chequebank, \r\n"
			+ "        r.chequeutino, \r\n"
			+ "        r.customercode, \r\n"
			+ "        r.customername, \r\n"
			+ "        r.receiptamt, \r\n"
			+ "        r.bankcharges, \r\n"
			+ "        r.tdsamt, \r\n"
			+ "        ROW_NUMBER() OVER (PARTITION BY r.docid ORDER BY r.docid) AS tds_rank \r\n"
			+ "    FROM receipt r \r\n"
			+ "    WHERE \r\n"
			+ "        COALESCE(r.cancel, 0) = 1  \r\n"
			+ "        AND (LOWER(COALESCE(r.customername, '')) = LOWER(?2) OR 'ALL' = ?2) \r\n"
			+ "        AND (r.docdate BETWEEN date(?5) AND date(?6) OR ( 'NULL'=?5 AND 'NULL'=?6))\r\n"
			+ "        AND (LOWER(COALESCE(r.branchcode, '')) = LOWER(?3) OR 'ALL' = ?3)\r\n"
			+ ") r\r\n"
			+ "LEFT JOIN receiptinvdetails rd ON r.receiptid = rd.receiptid\r\n"
			+ "LEFT JOIN arapadjustments adj ON adj.docid = r.docid \r\n"
			+ "WHERE r.orgid = ?1\r\n"
			+ "AND (r.finyear = ?4 OR 'ALL' = ?4) \r\n"
			+ "ORDER BY r.orgid, r.branchcode, r.finyear, \r\n"

			+ "    r.createdon, \r\n"
			+ "    r.createdby, \r\n"
			+ "    r.docdate, \r\n"
			+ "    r.docid, \r\n"
			+ "    r.chequebank, \r\n"
			+ "    r.chequeutino, \r\n"
			+ "    r.customername\r\n"
			+ "")

	Set<Object[]> getReceiptRegisterReport(Long orgId, String partyName, String branchCode, String finYear,
			String fromDate, String toDate);

	
	@Query(nativeQuery = true, value = "SELECT \r\n"
			+ "    a.createdby,\r\n"
			+ "    a.createdon,\r\n"
			+ "    a.docid,\r\n"
			+ "    a.docdate,\r\n"
			+ "    a.subtypecode,\r\n"
			+ "    a.subtypename,\r\n"
			+ "    a.chequebank,\r\n"
			+ "    a.chequeno,\r\n"
			+ "    a.subledgercode,\r\n"
			+ "    a.subledgername,\r\n"
			+ "    m.accountname,\r\n"
			+ "    a.receiptamt AS receiptamount,\r\n"
			+ "    a.bankcharges AS bankchargesamt,\r\n"
			+ "    CASE WHEN rnk = 1 THEN a.tdsamt ELSE 0 END AS tdsamt,\r\n"
			+ "    a.servicetaxamt AS staxamount,\r\n"
			+ "    a.invno AS invoiceno,\r\n"
			+ "    a.invdate AS invoicedate,\r\n"
			+ "    a.refno,\r\n"
			+ "    a.refdate,\r\n"
			+ "    a.amount AS arapamount,\r\n"
			+ "    a.outstanding AS arapoutstanding,\r\n"
			+ "    a.settled AS arapsettled\r\n"
			+ "FROM  \r\n"
			+ "    (SELECT \r\n"
			+ "        p.createdby,\r\n"
			+ "        p.createdon,\r\n"
			+ "        p.docid,\r\n"
			+ "        p.docdate,\r\n"
			+ "        p.paymenttype AS subtypecode,\r\n"
			+ "        p.type AS subtypename,\r\n"
			+ "        p.chequebank,\r\n"
			+ "        p.chequeno,\r\n"
			+ "        p.partycode AS subledgercode,\r\n"
			+ "        p.partyname AS subledgername,\r\n"
			+ "        p.receiptamt,\r\n"
			+ "        p.bankcharges,\r\n"
			+ "        p.tdsamt,\r\n"
			+ "        p.servicetaxamt,\r\n"
			+ "        pi.invno,\r\n"
			+ "        pi.invdate,\r\n"
			+ "        pi.refno,\r\n"
			+ "        pi.refdate,\r\n"
			+ "        pi.amount,\r\n"
			+ "        pi.outstanding,\r\n"
			+ "        pi.settled,\r\n"
			+ "        ROW_NUMBER() OVER (PARTITION BY p.docid ORDER BY p.docid) AS rnk\r\n"
			+ "    FROM payment p\r\n"
			+ "    LEFT JOIN paymentinvdtls pi ON p.paymentid = pi.paymentid\r\n"
			+ "    LEFT JOIN account m ON m.accountid = p.bankcashacc\r\n"
			+ "    LEFT JOIN branch br ON p.branch = br.branch\r\n"
			+ "    WHERE p.cancel = 0\r\n"
			+ "      AND (p.partycode=?2 OR ?2 = 'ALL')\r\n"
			+ "      AND (p.docdate BETWEEN date(?5) AND date(?6) OR (?5 is null AND ?6 is null))\r\n"
			+ "      AND (br.branchcode =?3 OR ?3 = 'ALL')\r\n"
			+ "      AND  p.orgid =?1\r\n"
			+ "     AND (p.finyear =?4 OR ?4 = 'ALL')\r\n"
			+ "    ) AS a \r\n"
			+ "LEFT JOIN account m ON a.subledgercode = m.accountcode\r\n"
			+ "ORDER BY \r\n"
			+ "    a.createdon, \r\n"
			+ "    a.createdby, \r\n"
			+ "    a.docdate, \r\n"
			+ "    a.docid, \r\n"
			+ "    rnk, \r\n"
			+ "    a.subtypename, \r\n"
			+ "    a.chequebank, \r\n"
			+ "    a.chequeno, \r\n"
			+ "    a.subledgername")
	Set<Object[]> getPaymentRegisterReport(Long orgId, String partyCode, String branchCode, String finYear,
	                                        String fromDate, String toDate);

	@Query(nativeQuery =true,value ="SELECT SUM(r.receiptamt) AS receiptAmnt\r\n"
			+ "FROM receipt r\r\n"
			+ "WHERE r.orgid = ?1 and r.finyear=?3 and ((month(docdate)=month(current_date()) and ?2='Month')or ?2 is null )")
	Set<Object[]> getReceiptAmont(Long orgId, String month, String year);


	@Query(nativeQuery =true,value ="SELECT \r\n"
			+ "    groupname, \r\n"
			+ "    accountcode, \r\n"
			+ "    subledgercode, \r\n"
			+ "    subledgername, \r\n"
			+ "\r\n"
			+ "    CASE \r\n"
			+ "        WHEN (SUM(odbamount) - SUM(ocramount)) > 0 \r\n"
			+ "        THEN SUM(odbamount) - SUM(ocramount) \r\n"
			+ "        ELSE 0 \r\n"
			+ "    END AS odbamount,\r\n"
			+ "\r\n"
			+ "    CASE \r\n"
			+ "        WHEN (SUM(odbamount) - SUM(ocramount)) > 0 \r\n"
			+ "        THEN 0 \r\n"
			+ "        ELSE ABS(SUM(odbamount) - SUM(ocramount)) \r\n"
			+ "    END AS ocramount,\r\n"
			+ "\r\n"
			+ "    SUM(tdbamount) AS tdbamount,\r\n"
			+ "    SUM(tcramount) AS tcramount,\r\n"
			+ "\r\n"
			+ "    CASE \r\n"
			+ "        WHEN (SUM(odbamount) - SUM(ocramount) + SUM(tdbamount) - SUM(tcramount)) > 0 \r\n"
			+ "        THEN SUM(odbamount) - SUM(ocramount) + SUM(tdbamount) - SUM(tcramount) \r\n"
			+ "        ELSE 0 \r\n"
			+ "    END AS cdbamount,\r\n"
			+ "\r\n"
			+ "    CASE \r\n"
			+ "        WHEN (SUM(odbamount) - SUM(ocramount) + SUM(tdbamount) - SUM(tcramount)) > 0 \r\n"
			+ "        THEN 0 \r\n"
			+ "        ELSE ABS(SUM(odbamount) - SUM(ocramount) + SUM(tdbamount) - SUM(tcramount)) \r\n"
			+ "    END AS ccramount\r\n"
			+ "\r\n"
			+ "FROM (\r\n"
			+ "    -- Opening Balances\r\n"
			+ "    SELECT \r\n"
			+ "        g.accountcode AS accountcode,\r\n"
			+ "        g.accountgroupname AS groupname,\r\n"
			+ "        CASE \r\n"
			+ "            WHEN UPPER(?4) = 'YES' THEN IFNULL(p.partycode, 'None')\r\n"
			+ "            ELSE 'None'\r\n"
			+ "        END AS subledgercode,\r\n"
			+ "        CASE \r\n"
			+ "            WHEN UPPER(?4) = 'YES' THEN IFNULL(p.partyname, 'None')\r\n"
			+ "            ELSE 'None'\r\n"
			+ "        END AS subledgername,\r\n"
			+ "        SUM(b.bdebitamount) AS odbamount,\r\n"
			+ "        SUM(b.bcreditamount) AS ocramount,\r\n"
			+ "        0 AS tdbamount,\r\n"
			+ "        0 AS tcramount\r\n"
			+ "    FROM \r\n"
			+ "        accounts a\r\n"
			+ "        JOIN accountsdetails b ON a.accountsid = b.accountsid\r\n"
			+ "        JOIN groupledger g ON b.accountname = g.accountgroupname\r\n"
			+ "        LEFT JOIN partymaster p ON b.subledgercode = p.partycode\r\n"
			+ "        JOIN financialyear f ON a.finyear = f.finyear\r\n"
			+ "        JOIN branch b1 ON a.branch = b1.branch\r\n"
			+ "    WHERE \r\n"
			+ "        a.cancel = 'F'\r\n"
			+ "        AND a.docdate <=?1\r\n"
			+ "        AND (b1.branch =?3)\r\n"
			+ "    GROUP BY \r\n"
			+ "        g.accountcode, \r\n"
			+ "        g.accountgroupname, \r\n"
			+ "        p.partycode, \r\n"
			+ "        p.partyname\r\n"
			+ "\r\n"
			+ "    UNION ALL\r\n"
			+ "\r\n"
			+ "    -- Transactions\r\n"
			+ "    SELECT \r\n"
			+ "        g.accountcode AS accountcode,\r\n"
			+ "        g.accountgroupname AS groupname,\r\n"
			+ "        CASE \r\n"
			+ "            WHEN UPPER(?4) = 'YES' THEN IFNULL(p.partycode, 'None')\r\n"
			+ "            ELSE 'None'\r\n"
			+ "        END AS subledgercode,\r\n"
			+ "        CASE \r\n"
			+ "            WHEN UPPER(?4) = 'YES' THEN IFNULL(p.partyname, 'None')\r\n"
			+ "            ELSE 'None'\r\n"
			+ "        END AS subledgername,\r\n"
			+ "        0 AS odbamount,\r\n"
			+ "        0 AS ocramount,\r\n"
			+ "        SUM(b.bdebitamount) AS tdbamount,\r\n"
			+ "        SUM(b.bcreditamount) AS tcramount\r\n"
			+ "    FROM \r\n"
			+ "        accounts a\r\n"
			+ "        JOIN accountsdetails b ON a.accountsid = b.accountsid\r\n"
			+ "        JOIN groupledger g ON b.accountname = g.accountgroupname\r\n"
			+ "        LEFT JOIN partymaster p ON b.subledgercode = p.partycode\r\n"
			+ "        JOIN financialyear f ON a.finyear = f.finyear\r\n"
			+ "        JOIN branch b1 ON a.branch = b1.branch\r\n"
			+ "    WHERE \r\n"
			+ "        a.cancel = 'F'\r\n"
			+ "        AND (a.docdate BETWEEN date(?1) AND date(?2) OR (?1 is null AND ?2 is null))and \r\n"
			+ "        a.finyear=?5 \r\n"
			+ "        AND b1.branch =?3\r\n"
			+ "       \r\n"
			+ "    GROUP BY \r\n"
			+ "        g.accountcode, \r\n"
			+ "        g.accountgroupname, \r\n"
			+ "        p.partycode, \r\n"
			+ "        p.partyname\r\n"
			+ ") AS derived_table  \r\n"
			+ "\r\n"
			+ "GROUP BY \r\n"
			+ "    groupname, \r\n"
			+ "    accountcode, \r\n"
			+ "    subledgercode, \r\n"
			+ "    subledgername\r\n"
			+ "\r\n"
			+ "ORDER BY \r\n"
			+ "    groupname, \r\n"
			+ "    accountcode")
	Set<Object[]> getTrailBalanceReport(String startDate, String endDate, String branch,String message,String finYear);

}
