package com.base.basesetup.repo;

import java.util.List;
import java.util.Set;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import com.base.basesetup.entity.ReceiptVO;
import com.base.basesetup.entity.TaxInvoiceVO;

@Repository
public interface ReceiptRepo extends JpaRepository<ReceiptVO, Long> {

	@Query(nativeQuery = true, value = "select * from receipt where orgid=?1 and finyear=?2 and branchcode=?3")
	List<ReceiptVO> getAllReceiptReceivableByOrgId(Long orgId,String finYear, String branchCode);

	@Query(nativeQuery = true, value = "select * from receipt where receiptid=?1")
	List<ReceiptVO> getAllReceiptReceivableById(Long id);

	@Query(nativeQuery = true, value = "select * from receipt where active=1")
	List<ReceiptVO> findReceiptReceivablesByActive();

	@Query(nativeQuery = true, value = "select partyname,partycode,partyshortname from partymaster where orgid=?1 and active=1 and partytype='CUSTOMER'")
	Set<Object[]> getCustomerNameAndCodeForReceipt(Long orgId);

	@Query(nativeQuery = true, value = "select a.docid,a.docdate,a.customername,a.bankcashacc,a.receiptamt,a.bankchargeacc,a.taxamt,a.tdsamt,b.invno,b.invdate,b.refno,b.refdate,a.chequebank,a.chequeutino,b.amount,b.outstanding,b.settled,a.createdon,a.createdby from receipt a, receiptinvdetails b where a.receiptid=b.receiptid and a.orgid=?1 and a.docdate BETWEEN ?2 AND ?3 and a.customername =?4")
	Set<Object[]> findAllReceiptRegister(Long orgId, String fromDate, String toDate, String subLedgerName);

	@Query(nativeQuery = true, value = "select concat(prefixfield,lpad(lastno,5,0)) AS docid from documenttypemappingdetails where orgid=?1 and finyear=?2 and branchcode=?3 and screencode=?4")
	String getReceiptDocId(Long orgId, String finYear, String branchCode, String screenCode);

	@Query(nativeQuery = true, value = "select concat(prefixfield,lpad(lastno,5,0)) AS docid from documenttypemappingdetails where orgid=?1 and finyear=?2 and branchcode=?3 and screencode=?4")
	String getArBillBalanceDocId(Long orgId, String finYear, String branchCode, String screenCode);

	@Query(nativeQuery = true, value = "WITH b AS (\r\n"
			+ "    SELECT \r\n"
			+ "        subledgercode, \r\n"
			+ "        refno AS docid, \r\n"
			+ "        SUM(amount) AS settled\r\n"
			+ "    FROM arapadjustments\r\n"
			+ "    WHERE CANCEL = 'F'\r\n"
			+ "    GROUP BY subledgercode, refno \r\n"
			+ "    HAVING SUM(amount) > 0\r\n"
			+ "),\r\n"
			+ "n AS (\r\n"
			+ "    SELECT \r\n"
			+ "        orgid, \r\n"
			+ "        refno, \r\n"
			+ "        SUM(amount) AS settamt \r\n"
			+ "    FROM arapadjustments \r\n"
			+ "    WHERE amount > 0 \r\n"
			+ "    GROUP BY orgid, refno\r\n"
			+ "),\r\n"
			+ "tax_summary AS (\r\n"
			+ "    SELECT \r\n"
			+ "        taxinvoiceid, \r\n"
			+ "        MAX(gstpercent) AS gstpercent\r\n"
			+ "    FROM taxinvoicedetails \r\n"
			+ "    GROUP BY taxinvoiceid\r\n"
			+ "),\r\n"
			+ "invoice_data AS (\r\n"
			+ "    SELECT \r\n"
			+ "        d.docid,\r\n"
			+ "        SUM(d.totalchargeamountlc) AS totalchargeamountlc,\r\n"
			+ "        SUM(d.totalinvamountlc) AS totalinvamountlc,\r\n"
			+ "        SUM(d.totaltaxamountlc) AS totaltaxamountlc\r\n"
			+ "    FROM taxinvoice d where d.approvestatus = 'Approved' \r\n"
			+ "    GROUP BY d.docid\r\n"
			+ "),\r\n"
			+ "creditnote_data AS (\r\n"
			+ "    SELECT \r\n"
			+ "        originbillno,\r\n"
			+ "        SUM(totalchargeamountlc) AS totalchargeamountlc,\r\n"
			+ "        SUM(totalinvamountlc) AS totalinvamountlc,\r\n"
			+ "        SUM(totaltaxamountlc) AS totaltaxamountlc\r\n"
			+ "    FROM irncreditnote\r\n"
			+ "    WHERE approvestatus = 'Approved'\r\n"
			+ "    GROUP BY originbillno\r\n"
			+ "),\r\n"
			+ "receipt_data AS (\r\n"
			+ "    SELECT \r\n"
			+ "        customercode,\r\n"
			+ "        b.invno,\r\n"
			+ "        SUM(tdsamt) AS tdsamt\r\n"
			+ "    FROM receipt a \r\n"
			+ "    JOIN receiptinvdetails b ON a.receiptid = b.receiptid\r\n"
			+ "    GROUP BY customercode, b.invno\r\n"
			+ ")\r\n"
			+ "SELECT \r\n"
			+ "    ROW_NUMBER() OVER () AS id,\r\n"
			+ "    a.branch,\r\n"
			+ "    a.subledgercode,\r\n"
			+ "    c.vid,\r\n"
			+ "    c.vdate,\r\n"
			+ "    a.refno,\r\n"
			+ "    a.refdate,\r\n"
			+ "    a.supprefno,\r\n"
			+ "    a.suprefdate,\r\n"
			+ "    a.acccurrency,\r\n"
			+ "    a.exrate,\r\n"
			+ "    COALESCE(inv.totalchargeamountlc, 0) \r\n"
			+ "        - COALESCE(crn.totalchargeamountlc, 0) AS totalamount,\r\n"
			+ "    COALESCE(inv.totalinvamountlc, 0) \r\n"
			+ "        - COALESCE(crn.totalinvamountlc, 0) \r\n"
			+ "        - COALESCE(n.settamt, 0) AS invamount,\r\n"
			+ "    a.chargableamt,\r\n"
			+ "    a.tdsamt,\r\n"
			+ "    tx.gstpercent,\r\n"
			+ "    COALESCE(inv.totaltaxamountlc, 0) \r\n"
			+ "        - COALESCE(crn.totaltaxamountlc, 0) AS gstamount\r\n"
			+ "FROM arapdetails a\r\n"
			+ "JOIN accounts c ON a.docid = c.docid\r\n"
			+ "JOIN invoice_data inv ON a.refno = inv.docid\r\n"
			+ "LEFT JOIN creditnote_data crn ON a.refno = crn.originbillno\r\n"
			+ "LEFT JOIN b ON a.subledgercode = b.subledgercode AND a.docid = b.docid\r\n"
			+ "LEFT JOIN n ON n.orgid = a.orgid AND n.refno = c.vid\r\n"
			+ "LEFT JOIN taxinvoice d ON a.refno = d.docid\r\n"
			+ "LEFT JOIN receipt_data rcpt ON a.subledgercode = rcpt.customercode AND rcpt.invno = d.vid\r\n"
			+ "LEFT JOIN tax_summary tx ON d.taxinvoiceid = tx.taxinvoiceid\r\n"
			+ "WHERE \r\n"
			+ "    a.CANCEL = 'F'\r\n"
			+ "    AND d.branchcode = ?3\r\n"
			+ "    AND a.subledgercode = ?2\r\n"
			+ "    AND a.orgid = ?1\r\n"
			+ "    AND COALESCE(inv.totalinvamountlc, 0) \r\n"
			+ "        - COALESCE(crn.totalinvamountlc, 0)\r\n"
			+ "        - COALESCE(rcpt.tdsamt, 0) \r\n"
			+ "        - COALESCE(n.settamt, 0) > 0\r\n"
			+ "ORDER BY \r\n"
			+ "    a.refdate,\r\n"
			+ "    c.vid")
	Set<Object[]> findReciptFillGrid(Long orgId, String partyCode,String branchCode);


	@Query(nativeQuery = true, value = "SELECT p.onaccount - COALESCE(SUM(a2.settled), 0) AS netAmount,p.docid,p.docdate FROM receipt p LEFT JOIN aradjustmentoffset a1 ON p.docid = a1.receiptdocid \r\n"
			+ "	LEFT JOIN aroffsetinvoicedetails a2 ON a1.aradjustmentoffsetid = a2.aradjustmentoffsetid\r\n"
			+ "		WHERE p.orgid =?1 AND p.branchcode =?2 AND p.cancel = 0 AND p.customername =?3 AND p.approvestatus = 'Approved' AND \r\n"
			+ "p.onaccount > 0 GROUP BY p.onaccount,  p.docid,p.docdate HAVING p.onaccount - COALESCE(SUM(a2.settled), 0) > 0")
	Set<Object[]> getAllReceiptByOrgIdAndBranchCode(Long orgId, String branchCode,String customerName);

	@Query(nativeQuery =true,value ="WITH receipt_data AS (\r\n"
			+ "    SELECT \r\n"
			+ "        r.orgid,\r\n"
			+ "        r.branchcode,\r\n"
			+ "        r.finyear,\r\n"
			+ "        r.createdby,\r\n"
			+ "        r.createdon,\r\n"
			+ "        r.docid,\r\n"
			+ "        r.docdate,\r\n"
			+ "        r.receipt_type AS subtypecode,\r\n"
			+ "        r.bankcashacc,\r\n"
			+ "        r.chequeutino AS chqnumber,\r\n"
			+ "        r.customercode AS subledgercode,\r\n"
			+ "        r.customername AS subledgername,\r\n"
			+ "        r.receiptamt AS receiptamount,\r\n"
			+ "        r.bankcharges AS bankchargesamt,\r\n"
			+ "        CASE \r\n"
			+ "            WHEN ROW_NUMBER() OVER (PARTITION BY r.docid ORDER BY r.docid) = 1 THEN r.tdsamt \r\n"
			+ "            ELSE 0 \r\n"
			+ "        END AS tdsamount,\r\n"
			+ "        adj.amount AS arapamount,\r\n"
			+ "        adj.chargeableamt AS chargeableamt,\r\n"
			+ "        rd.r.totaloutstanding  AS arapoutstanding,\r\n"
			+ "        r.netamount AS arapsettled,\r\n"
			+ "        r.chqdate,\r\n"
			+ "        acc.totalcreditamount AS totalAmount,\r\n"
			+ "        r.shortname,\r\n"
			+ "        r.netamount,\r\n"
			+ "        r.onaccount,\r\n"
			+ "        ROW_NUMBER() OVER (PARTITION BY r.docid ORDER BY r.docid) AS rn,\r\n"
			+ "        r.totalchargeamount AS chargeAmount,\r\n"
			+ "        r.receivableamount AS receivableAmount\r\n"
			+ "    FROM (\r\n"
			+ "        SELECT \r\n"
			+ "            r.receiptid,\r\n"
			+ "            r.orgid,\r\n"
			+ "            r.branchcode,\r\n"
			+ "            r.finyear,\r\n"
			+ "            r.createdby,\r\n"
			+ "            r.createdon,\r\n"
			+ "            r.docid,\r\n"
			+ "            r.docdate,\r\n"
			+ "            r.receipt_type,\r\n"
			+ "            r.bankcashacc,\r\n"
			+ "            r.chequeutino,\r\n"
			+ "            r.chequeutidate AS chqdate,\r\n"
			+ "            r.customercode,\r\n"
			+ "            r.customername,\r\n"
			+ "            r.receiptamt,\r\n"
			+ "            r.bankcharges,\r\n"
			+ "            r.tdsamt,\r\n"
			+ "            r.shortname,\r\n"
			+ "            r.netamount,\r\n"
			+ "            r.onaccount,\r\n"
			+ "            r.totalchargeamount,\r\n"
			+ "            r.totaloutstanding,\r\n"
			+ "            r.receivableamount\r\n"
			+ "        FROM receipt r\r\n"
			+ "        WHERE \r\n"
			+ "            r.cancel = 0\r\n"
			+ "            AND r.orgid = ?1\r\n"
			+ "            AND r.finyear = ?4\r\n"
			+ "            AND (r.customername = ?2 OR ?2 = 'ALL')\r\n"
			+ "            AND (r.branchcode = ?3 OR ?3 = 'ALL')\r\n"
			+ "            AND (?5 IS NULL OR r.docdate >= ?5)\r\n"
			+ "            AND (?6 IS NULL OR r.docdate <= ?6)\r\n"
			+ "    ) r\r\n"
			+ "\r\n"
			+ "    LEFT JOIN receiptinvdetails rd \r\n"
			+ "        ON rd.receiptid = r.receiptid\r\n"
			+ "\r\n"
			+ "    LEFT JOIN (\r\n"
			+ "        SELECT \r\n"
			+ "            docid,\r\n"
			+ "            amount,\r\n"
			+ "            chargeableamt\r\n"
			+ "        FROM arapadjustments\r\n"
			+ "        WHERE cancel = 'F'\r\n"
			+ "    ) adj \r\n"
			+ "        ON adj.docid = r.docid\r\n"
			+ "\r\n"
			+ "    LEFT JOIN (\r\n"
			+ "        SELECT \r\n"
			+ "            refno,\r\n"
			+ "            totalcreditamount\r\n"
			+ "        FROM accounts\r\n"
			+ "    ) acc \r\n"
			+ "        ON acc.refno = r.docid\r\n"
			+ "\r\n"
			+ "    GROUP BY\r\n"
			+ "        r.orgid,\r\n"
			+ "        r.branchcode,\r\n"
			+ "        r.finyear,\r\n"
			+ "        r.createdby,\r\n"
			+ "        r.createdon,\r\n"
			+ "        r.docid,\r\n"
			+ "        r.docdate,\r\n"
			+ "        r.receipt_type,\r\n"
			+ "        r.bankcashacc,\r\n"
			+ "        r.chequeutino,\r\n"
			+ "        r.customercode,\r\n"
			+ "        r.customername,\r\n"
			+ "        r.receiptamt,\r\n"
			+ "        r.bankcharges,\r\n"
			+ "        r.tdsamt,\r\n"
			+ "        adj.amount,\r\n"
			+ "        adj.chargeableamt,\r\n"
			+ "        rd.outstanding,\r\n"
			+ "        r.chqdate,\r\n"
			+ "        acc.totalcreditamount,\r\n"
			+ "        r.shortname,\r\n"
			+ "        r.netamount,\r\n"
			+ "        r.onaccount,\r\n"
			+ "        r.totalchargeamount,\r\n"
			+ "        r.totaloutstanding,\r\n"
			+ "        r.receivableamount\r\n"
			+ ")\r\n"
			+ "\r\n"
			+ "SELECT *\r\n"
			+ "FROM receipt_data\r\n"
			+ "WHERE rn = 1\r\n"
			+ "ORDER BY \r\n"
			+ "    orgid,\r\n"
			+ "    branchcode,\r\n"
			+ "    finyear,\r\n"
			+ "    createdon,\r\n"
			+ "    createdby,\r\n"
			+ "    docdate,\r\n"
			+ "    docid,\r\n"
			+ "    chqnumber,\r\n"
			+ "    chqdate,\r\n"
			+ "    subledgername")
	Set<Object[]> getReceiptRegisterReport(Long orgId, String partyName, String branchCode, String finYear,
			String fromDate, String toDate);

	
	@Query(nativeQuery = true, value = "SELECT  \r\n"
			+ "			     a.createdby, \r\n"
			+ "			     a.createdon, \r\n"
			+ "			     a.docid, \r\n"
			+ "			     a.docdate, \r\n"
			+ "			      a.subtypecode, \r\n"
			+ "			     a.subtypename, \r\n"
			+ "			     a.chequebank, \r\n"
			+ "			     a.chequeno, \r\n"
			+ "			     a.subledgercode, \r\n"
			+ "			     a.subledgername, \r\n"
			+ "			      a.partyshortname, \r\n"
			+ "			     a.paymentamt AS paymentamount, \r\n"
			+ "			     a.bankcharges AS bankchargesamt, \r\n"
			+ "			     CASE WHEN rnk = 1 THEN a.tdsamt ELSE 0 END AS tdsamt, \r\n"
			+ "			     a.servicetaxamt AS staxamount, \r\n"
		//	+ "			     a.invno AS invoiceno, \r\n"
		//	+ "			     a.invdate AS invoicedate, \r\n"
		//	+ "			     a.refno, \r\n"
		//	+ "			     a.refdate, \r\n"
			+ "			     a.amount AS arapamount, \r\n"
			+ "			     a.outstanding AS arapoutstanding, \r\n"
			+ "			     a.settled AS arapsettled,a.chequedate,a.bankCashAcc,a.onaccount,a.netamount,chargeamt \r\n"
			+ "			 FROM   \r\n"
			+ "			     (SELECT  \r\n"
			+ "			         p.createdby, \r\n"
			+ "			         p.createdon, \r\n"
			+ "			         p.docid, \r\n"
			+ "			         p.docdate, \r\n"
			+ "			         p.paymenttype AS subtypecode, \r\n"
			+ "			         p.type AS subtypename, \r\n"
			+ "			         p.chequebank, \r\n"
			+ "			         p.chequeno,p.chequedate, \r\n"
			+ "			         p.partycode AS subledgercode, \r\n"
			+ "			         p.partyname AS subledgername, \r\n"
			+ "			         p.paymentamt, \r\n"
			+ "			         p.bankcharges, p.onaccount,p.netamount, \r\n"
			+ "			         p.tdsamt, \r\n"
			+ "			         p.servicetaxamt, \r\n"
			+ "			         pi.invno, \r\n"
			+ "			         pi.invdate, \r\n"
			+ "			         pi.refno, \r\n"
			+ "			         pi.refdate, \r\n"
			+ "			         pi.amount, \r\n"
			+ "			         pi.outstanding, p1.partyshortname,pi.chargeamt ,\r\n"
			+ "			         pi.settled,p.bankCashAcc, \r\n"
			+ "			         ROW_NUMBER() OVER (PARTITION BY p.docid ORDER BY p.docid) AS rnk \r\n"
			+ "			     FROM payment p \r\n"
			+ "			     LEFT JOIN paymentinvdtls pi ON p.paymentid = pi.paymentid \r\n"
			+ "			     LEFT JOIN accounts m ON  p.docid =m.refno   \r\n"
			+ "			     left join partymaster p1 on p.partycode = p1.partycode \r\n"
			+ "			     LEFT JOIN branch br ON p.branch = br.branch \r\n"
			+ "			     WHERE p.cancel = 0 \r\n"
			+ "			       AND (p.partyname= ?2 OR  ?2 = 'ALL') \r\n"
			+ "			       AND (p.docdate BETWEEN date( ?5) AND date( ?6) OR ( ?5 is null AND  ?6 is null)) \r\n"
			+ "			       AND (br.branchcode = ?3 OR  ?3 = 'ALL') \r\n"
			+ "			       AND  p.orgid = ?1 \r\n"
			+ "			      AND (p.finyear = ?4 OR  ?4 = 'ALL') \r\n"
			+ "			     ) AS a  \r\n"
			+ "			 ORDER BY  \r\n"
			+ "			     a.createdon,  \r\n"
			+ "			     a.createdby,  \r\n"
			+ "			     a.docdate,  \r\n"
			+ "			     a.docid,  \r\n"
			+ "			     rnk,  \r\n"
			+ "			     a.subtypename,  \r\n"
			+ "			     a.chequebank,  \r\n"
			+ "			     a.chequeno,  \r\n"
			+ "			     a.subledgername")
	Set<Object[]> getPaymentRegisterReport(Long orgId, String partyCode, String branchCode, String finYear,
	                                        String fromDate, String toDate);

	@Query(nativeQuery =true,value ="SELECT SUM(r.receiptamt) AS receiptAmnt\r\n"
			+ "FROM receipt r\r\n"
			+ "WHERE r.orgid = ?1 and r.finyear=?3 and ((month(docdate)=month(current_date()) and ?2='Month')or ?2 is null )")
	Set<Object[]> getReceiptAmont(Long orgId, String month, String year);

	@Query(nativeQuery =true,value = "SELECT \r\n"
			+ "    a.docid, \r\n"
			+ "    a.docdate, \r\n"
			+ "    a.refno, \r\n"
			+ "    a.refdate, \r\n"
			+ "    a.currency, \r\n"
			+ "    a.exrate,\r\n"
		//	+ "   -- fn_getexrate(a.currency, ?docdate) AS texrate,\r\n"
			+ "    a.AMOUNT, \r\n"
			+ "    (a.AMOUNT + a.baseamt) AS outstanding,\r\n"
			+ "    (a.AMOUNT + a.baseamt) AS settled\r\n"
			+ "    -- a.arapdetailsID \r\n"
			+ "FROM \r\n"
			+ "    arapadjustments a\r\n"
			+ "WHERE \r\n"
			+ "    a.SUBLEDGERcode = ?2\r\n"
			+ "    AND (a.AMOUNT + a.baseamt) <> 0\r\n"
			+ "    AND a.docdate <= ?5\r\n"
			+ "    AND a.docid <> ?3\r\n"
			+ "    AND a.branch = ?4\r\n"
			+ "    AND a.orgid=?1\r\n"
			+ "ORDER BY \r\n"
			+ "    a.docdate, a.docid")
	Set<Object[]> getArOffsetFillgrid(Long orgId, String subLedgerCode, String docId, String branch, String docDate);


	@Query(nativeQuery =true,value ="SELECT \r\n"
			+ "    groupname, \r\n"
			+ "    accountcode, \r\n"
			+ "    subledgercode, \r\n"
			+ "    subledgername, \r\n"
			+ "\r\n"
			+ "    CASE \r\n"
			+ "        WHEN (SUM(odbamount) - SUM(ocramount)) > 0 \r\n"
			+ "        THEN SUM(odbamount) - SUM(ocramount) \r\n"
			+ "        ELSE 0 \r\n"
			+ "    END AS odbamount,\r\n"
			+ "\r\n"
			+ "    CASE \r\n"
			+ "        WHEN (SUM(odbamount) - SUM(ocramount)) > 0 \r\n"
			+ "        THEN 0 \r\n"
			+ "        ELSE ABS(SUM(odbamount) - SUM(ocramount)) \r\n"
			+ "    END AS ocramount,\r\n"
			+ "\r\n"
			+ "    SUM(tdbamount) AS tdbamount,\r\n"
			+ "    SUM(tcramount) AS tcramount,\r\n"
			+ "\r\n"
			+ "    CASE \r\n"
			+ "        WHEN (SUM(odbamount) - SUM(ocramount) + SUM(tdbamount) - SUM(tcramount)) > 0 \r\n"
			+ "        THEN SUM(odbamount) - SUM(ocramount) + SUM(tdbamount) - SUM(tcramount) \r\n"
			+ "        ELSE 0 \r\n"
			+ "    END AS cdbamount,\r\n"
			+ "\r\n"
			+ "    CASE \r\n"
			+ "        WHEN (SUM(odbamount) - SUM(ocramount) + SUM(tdbamount) - SUM(tcramount)) > 0 \r\n"
			+ "        THEN 0 \r\n"
			+ "        ELSE ABS(SUM(odbamount) - SUM(ocramount) + SUM(tdbamount) - SUM(tcramount)) \r\n"
			+ "    END AS ccramount\r\n"
			+ "\r\n"
			+ "FROM (\r\n"
			+ "    -- Opening Balances\r\n"
			+ "    SELECT \r\n"
			+ "        g.accountcode AS accountcode,\r\n"
			+ "        g.accountgroupname AS groupname,\r\n"
			+ "        CASE \r\n"
			+ "            WHEN UPPER(?4) = 'YES' THEN IFNULL(p.partycode, 'None')\r\n"
			+ "            ELSE 'None'\r\n"
			+ "        END AS subledgercode,\r\n"
			+ "        CASE \r\n"
			+ "            WHEN UPPER(?4) = 'YES' THEN IFNULL(p.partyname, 'None')\r\n"
			+ "            ELSE 'None'\r\n"
			+ "        END AS subledgername,\r\n"
			+ "        SUM(b.bdebitamount) AS odbamount,\r\n"
			+ "        SUM(b.bcreditamount) AS ocramount,\r\n"
			+ "        0 AS tdbamount,\r\n"
			+ "        0 AS tcramount\r\n"
			+ "    FROM \r\n"
			+ "        accounts a\r\n"
			+ "        JOIN accountsdetails b ON a.accountsid = b.accountsid\r\n"
			+ "        JOIN groupledger g ON b.accountname = g.accountgroupname\r\n"
			+ "        LEFT JOIN partymaster p ON b.subledgercode = p.partycode\r\n"
			+ "        JOIN financialyear f ON a.finyear = f.finyear\r\n"
			+ "        JOIN branch b1 ON a.branch = b1.branch\r\n"
			+ "    WHERE \r\n"
			+ "        a.cancel = 'F'\r\n"
			+ "        AND a.docdate <=?1\r\n"
			+ "        AND (b1.branch =?3)\r\n"
			+ "    GROUP BY \r\n"
			+ "        g.accountcode, \r\n"
			+ "        g.accountgroupname, \r\n"
			+ "        p.partycode, \r\n"
			+ "        p.partyname\r\n"
			+ "\r\n"
			+ "    UNION ALL\r\n"
			+ "\r\n"
			+ "    -- Transactions\r\n"
			+ "    SELECT \r\n"
			+ "        g.accountcode AS accountcode,\r\n"
			+ "        g.accountgroupname AS groupname,\r\n"
			+ "        CASE \r\n"
			+ "            WHEN UPPER(?4) = 'YES' THEN IFNULL(p.partycode, 'None')\r\n"
			+ "            ELSE 'None'\r\n"
			+ "        END AS subledgercode,\r\n"
			+ "        CASE \r\n"
			+ "            WHEN UPPER(?4) = 'YES' THEN IFNULL(p.partyname, 'None')\r\n"
			+ "            ELSE 'None'\r\n"
			+ "        END AS subledgername,\r\n"
			+ "        0 AS odbamount,\r\n"
			+ "        0 AS ocramount,\r\n"
			+ "        SUM(b.bdebitamount) AS tdbamount,\r\n"
			+ "        SUM(b.bcreditamount) AS tcramount\r\n"
			+ "    FROM \r\n"
			+ "        accounts a\r\n"
			+ "        JOIN accountsdetails b ON a.accountsid = b.accountsid\r\n"
			+ "        JOIN groupledger g ON b.accountname = g.accountgroupname\r\n"
			+ "        LEFT JOIN partymaster p ON b.subledgercode = p.partycode\r\n"
			+ "        JOIN financialyear f ON a.finyear = f.finyear\r\n"
			+ "        JOIN branch b1 ON a.branch = b1.branch\r\n"
			+ "    WHERE \r\n"
			+ "        a.cancel = 'F'\r\n"
			+ "        AND (a.docdate BETWEEN date(?1) AND date(?2) OR (?1 is null AND ?2 is null))and \r\n"
			+ "        a.finyear=?5 \r\n"
			+ "        AND b1.branch =?3\r\n"
			+ "       \r\n"
			+ "    GROUP BY \r\n"
			+ "        g.accountcode, \r\n"
			+ "        g.accountgroupname, \r\n"
			+ "        p.partycode, \r\n"
			+ "        p.partyname\r\n"
			+ ") AS derived_table  \r\n"
			+ "\r\n"
			+ "GROUP BY \r\n"
			+ "    groupname, \r\n"
			+ "    accountcode, \r\n"
			+ "    subledgercode, \r\n"
			+ "    subledgername\r\n"
			+ "\r\n"
			+ "ORDER BY \r\n"
			+ "    groupname, \r\n"
			+ "    accountcode")
	Set<Object[]> getTrailBalanceReport(String startDate, String endDate, String branch,String message,String finYear);

	ReceiptVO findByOrgIdAndIdAndDocId(Long orgId, Long id, String docId);
	
	
	@Query(nativeQuery = true, value = "SELECT \r\n"
			+ "    a.finyear,\r\n"
			+ "    b.invno,\r\n"
			+ "    b.invdate,\r\n"
			+ "    a.docid,\r\n"
			+ "    a.docdate,\r\n"
			+ "    b.refno,\r\n"
			+ "    b.refdate,\r\n"
			+ "    a.customername,\r\n"
			+ "    a.customercode,\r\n"
			+ "    a.receiptamt,\r\n"
			+ "    a.netamount,\r\n"
			+ "    a.onaccount,\r\n"
			+ "    a.chequeutino,\r\n"
			+ "    a.chequeutidate,\r\n"
			+ "    a.tdsamt,\r\n"
			+ "    b.amount,\r\n"
			+ "    b.gstamt,\r\n"
			+ "    b.chargeamt,\r\n"
			+ "    b.tds,\r\n"
			+ "    b.settled,\r\n"
			+ "    b.outstanding,\r\n"
			+ "    b.tdsamount\r\n"
			+ "FROM \r\n"
			+ "    receipt a,\r\n"
			+ "    receiptinvdetails b\r\n"
			+ "WHERE \r\n"
			+ "    a.receiptid = b.receiptid\r\n"
			+ "    AND a.orgid =?1\r\n"
			+ "    AND a.finyear =?2\r\n"
			+ " AND (a.customername = ?3 OR ?3 = 'ALL')\r\n"
			+ "    AND (?4 IS NULL OR a.docdate >= ?4)\r\n"
			+ "     AND (?5 IS NULL OR a.docdate <= ?5)\r\n"
			+ "    AND (a.branchcode = ?6 OR ?6 = 'ALL')\r\n"
			+ "ORDER BY \r\n"
			+ "    a.createdon DESC")
	Set<Object[]> getReceiptDetails(Long orgId, String finYear, String partyname, String fromDate, String toDate,String branchCode);

	@Query(nativeQuery = true, value = "SELECT \r\n"
			+ "    a.finyear, \r\n"
			+ "    a.docid, \r\n"
			+ "    a.docdate,\r\n"
			+ "    a.customername,\r\n"
			+ "    a.customercode,\r\n"
			+ "    a.chequeutino, \r\n"
			+ "    a.chequeutidate,\r\n"
			+ "    a.receiptamt, \r\n"
			+ "    a.netamount,\r\n"
			+ "    a.tdsamt, \r\n"
			+ "    a.onaccount, \r\n"
			+ "    a.bankcashacc,\r\n"
			+ "    a.approvestatus \r\n"
			+ "FROM \r\n"
			+ "    receipt a\r\n"
			+ "WHERE \r\n"
			+ "    a.orgid =?1\r\n"
			+ "     AND (a.customername = ?3 OR ?3 = 'ALL')\r\n"
			+ "    AND a.finyear =?2\r\n"
			+ "    AND (?4 IS NULL OR a.docdate >= ?4)\r\n"
			+ "     AND (?5 IS NULL OR a.docdate <= ?5)\r\n"
			+ "     AND (a.branchcode = ?6 OR ?6 = 'ALL')\r\n"
			+ "ORDER BY \r\n"
			+ "    a.createdon DESC")
	Set<Object[]> getReceiptSummary(Long orgId, String finYear, String partyname, String fromDate, String toDate,String branchCode);
	
	@Query(nativeQuery = true, value = "select * from receipt where  docid=?1")
	ReceiptVO getReceiptByDocId(String docId);
	 
	
	@Query(nativeQuery = true, value = "with a as (\r\n"
			+ "   select 1 sno,t.arapdetailsid,\r\n"
			+ "         t.branch,\r\n"
			+ "         t.subledgercode,\r\n"
			+ "        CONCAT(t.subledgername, ' , Cr. Limit - ', t.creditlimit, ' , Cr. Days - ', t.creditdays) AS subledgername,\r\n"
			+ "         t.partytype,\r\n"
			+ "         t.salesperson,\r\n"
			+ "         t.docid,\r\n"
			+ "         t.docdate,\r\n"
			+ "         t.supprefno,\r\n"
			+ "         t.suprefdate,\r\n"
			+ "         t.duedate,\r\n"
			+ "         t.refno,\r\n"
			+ "         t.refdate,\r\n"
			+ "         case when ?5 ='Base' then t.bamount when ?5 ='Native' then t.namount else  t.amount end as amount,\r\n"
			+ "         case when ?5 ='Base' then t.boutstanding when ?5 ='Native'then t.noutstanding else t.outstanding end as outstanding,\r\n"
			+ "         case when  ?5 ='Base' then t.btotaldue when  ?5 ='Native' then t.ntotaldue else  t.totaldue end as totaldue,\r\n"
			+ "         case when ?5 ='Base'then t.bunadjusted when ?5 ='Native'then t.nunadjusted else t.unadjusted end as unadjusted,\r\n"
			+ "         t.ddays,CASE \r\n"
			+ "    WHEN ?5 = 'Base' THEN t.bmslab1\r\n"
			+ "    WHEN ?5 = 'Native' THEN t.nmslab1\r\n"
			+ "    ELSE t.mslab1\r\n"
			+ "  END AS mslab1,\r\n"
			+ "  CASE \r\n"
			+ "    WHEN ?5 = 'Base' THEN t.bmslab2\r\n"
			+ "    WHEN ?5 = 'Native' THEN t.nmslab2\r\n"
			+ "    ELSE t.mslab2\r\n"
			+ "  END AS mslab2,\r\n"
			+ "  CASE \r\n"
			+ "    WHEN ?5 = 'Base' THEN t.bmslab3\r\n"
			+ "    WHEN ?5 = 'Native' THEN t.nmslab3\r\n"
			+ "    ELSE t.mslab3\r\n"
			+ "  END AS mslab3,\r\n"
			+ "  CASE \r\n"
			+ "    WHEN ?5 = 'Base' THEN t.bmslab4\r\n"
			+ "    WHEN ?5 = 'Native' THEN t.nmslab4\r\n"
			+ "    ELSE t.mslab4\r\n"
			+ "  END AS mslab4,\r\n"
			+ "\r\n"
			+ "  CASE \r\n"
			+ "    WHEN ?5 = 'Base' THEN t.bmslab5 + t.bmslab6 + t.bmslab7\r\n"
			+ "    WHEN ?5 = 'Native' THEN t.nmslab5 + t.nmslab6 + t.nmslab7\r\n"
			+ "    ELSE t.mslab5 + t.mslab6 + t.mslab7\r\n"
			+ "  END AS mslab5,\r\n"
			+ "        t.creditlimit,t.creditdays from(\r\n"
			+ "select  a.arapdetailsid,\r\n"
			+ "                   jbr.branch,\r\n"
			+ "                   P.PARTYCODE subledgercode,\r\n"
			+ "                   p.partyname subledgername,\r\n"
			+ "                   p.partytype subledgertype,\r\n"
			+ "                   CASE\r\n"
			+ "                      WHEN  (p.gstregistered LIKE 'Y%') THEN 'GST Party'\r\n"
			+ "                      ELSE 'ST Party'\r\n"
			+ "                   END\r\n"
			+ "                      Partytype,\r\n"
			+ "                   p.creditlimit,\r\n"
			+ "                   p.creditdays,\r\n"
			+ "                   p.salesperson,a.docid , \r\n"
			+ "                   a.docdate,\r\n"
			+ "                   a.supprefno,\r\n"
			+ "                   a.suprefdate,\r\n"
			+ "                   DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) duedate,\r\n"
			+ "                   a.refno,\r\n"
			+ "                   a.refdate,\r\n"
			+ "                   a.amount AS amount,CASE\r\n"
			+ "                      WHEN  (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                      THEN\r\n"
			+ "                         0\r\n"
			+ "                      ELSE\r\n"
			+ "                         a.amount + SUM(r.amount)\r\n"
			+ "                   END\r\n"
			+ "                      AS outstanding,a.amount + SUM(r.amount) AS totaldue,a.baseamt AS bamount,CASE\r\n"
			+ "                      WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                      THEN\r\n"
			+ "                         0\r\n"
			+ "                      ELSE\r\n"
			+ "                         a.baseamt + SUM(r.baseamt)\r\n"
			+ "                   END\r\n"
			+ "                      AS boutstanding,a.baseamt + SUM(r.baseamt) AS btotaldue,a.nativeamt AS namount,\r\n"
			+ "                   CASE\r\n"
			+ "                        WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                      THEN\r\n"
			+ "                         0\r\n"
			+ "                      ELSE\r\n"
			+ "                         a.nativeamt + SUM(r.nativeamt)\r\n"
			+ "                   END\r\n"
			+ "                      AS noutstanding,\r\n"
			+ "                   a.nativeamt + SUM(r.nativeamt) AS ntotaldue,CASE\r\n"
			+ "                      WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                           AND a.amount +SUM(r.amount) <> 0\r\n"
			+ "                      THEN\r\n"
			+ "                         a.amount +SUM(r.amount)\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS unadjusted,CASE\r\n"
			+ "                       WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                           AND a.baseamt +SUM(r.baseamt) <> 0\r\n"
			+ "                      THEN\r\n"
			+ "                         a.baseamt +SUM(r.baseamt)\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS bunadjusted,CASE\r\n"
			+ "                       WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                           AND a.nativeamt +SUM(r.nativeamt) <> 0\r\n"
			+ "                      THEN\r\n"
			+ "                         a.nativeamt +SUM(r.nativeamt)\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS nunadjusted,date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY)\r\n"
			+ "                      AS ddays,CASE\r\n"
			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY)<31 THEN\r\n"
			+ "                         CASE\r\n"
			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.amount + SUM(r.amount)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS mslab1,CASE\r\n"
			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY)<31 THEN\r\n"
			+ "                         CASE\r\n"
			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.baseamt + SUM(r.baseamt)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS bmslab1,CASE\r\n"
			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY)<31 THEN\r\n"
			+ "                         CASE\r\n"
			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.nativeamt + SUM(r.nativeamt)\r\n"
			+ "                         ENd\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS nmslab1,CASE\r\n"
			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 31 and 60 THEN\r\n"
			+ "                         CASE\r\n"
			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.amount + SUM(r.amount)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS mslab2,CASE\r\n"
			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 31 and 60 THEN\r\n"
			+ "                         CASE\r\n"
			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.baseamt + SUM(r.baseamt)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS bmslab2,\r\n"
			+ "                      CASE\r\n"
			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 31 and 60 THEN\r\n"
			+ "                         CASE\r\n"
			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.nativeamt + SUM(r.nativeamt)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS nmslab2,\r\n"
			+ "                      CASE\r\n"
			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 61 and 90 THEN\r\n"
			+ "                         CASE\r\n"
			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.amount + SUM(r.amount)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS mslab3,CASE\r\n"
			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 61 and 90 THEN\r\n"
			+ "                         CASE\r\n"
			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.baseamt + SUM(r.baseamt)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS bmslab3,\r\n"
			+ "                      CASE\r\n"
			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 61 and 90 THEN\r\n"
			+ "                         CASE\r\n"
			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.nativeamt + SUM(r.nativeamt)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS nmslab3,CASE\r\n"
			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 91 and 120 THEN\r\n"
			+ "                         CASE\r\n"
			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.amount + SUM(r.amount)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS mslab4,CASE\r\n"
			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 91 and 120 THEN\r\n"
			+ "                         CASE\r\n"
			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.baseamt + SUM(r.baseamt)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS bmslab4,\r\n"
			+ "                      CASE\r\n"
			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 91 and 120 THEN\r\n"
			+ "                         CASE\r\n"
			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.nativeamt + SUM(r.nativeamt)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS nmslab4,CASE\r\n"
			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 121 and 150 THEN\r\n"
			+ "                         CASE\r\n"
			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.amount + SUM(r.amount)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS mslab5,CASE\r\n"
			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 121 and 150 THEN\r\n"
			+ "                         CASE\r\n"
			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.baseamt + SUM(r.baseamt)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS bmslab5,\r\n"
			+ "                      CASE\r\n"
			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 121 and 150 THEN\r\n"
			+ "                         CASE\r\n"
			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.nativeamt + SUM(r.nativeamt)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS nmslab5,CASE\r\n"
			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 151 and 180 THEN\r\n"
			+ "                         CASE\r\n"
			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.amount + SUM(r.amount)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS mslab6,CASE\r\n"
			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 151 and 180 THEN\r\n"
			+ "                         CASE\r\n"
			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.baseamt + SUM(r.baseamt)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS bmslab6,\r\n"
			+ "                      CASE\r\n"
			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) between 151 and 180 THEN\r\n"
			+ "                         CASE\r\n"
			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.nativeamt + SUM(r.nativeamt)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS nmslab6,CASE\r\n"
			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) >180 THEN\r\n"
			+ "                         CASE\r\n"
			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.amount + SUM(r.amount)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS mslab7,CASE\r\n"
			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) >180 THEN\r\n"
			+ "                         CASE\r\n"
			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.baseamt + SUM(r.baseamt)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS bmslab7,\r\n"
			+ "                      CASE\r\n"
			+ "                      WHEN date(?4) - DATE_ADD(a.docdate, INTERVAL p.creditdays DAY) > 180 THEN\r\n"
			+ "                         CASE\r\n"
			+ "                             WHEN    (a.refno LIKE '%RT%' OR a.refno LIKE '%PT%')\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.nativeamt + SUM(r.nativeamt)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS nmslab7 from arapdetails a\r\n"
			+ "LEFT JOIN arapadjustments r ON a.subledgercode = r.subledgercode AND r.cancel = 0\r\n"
			+ "LEFT JOIN accounts ac ON a.docid = ac.docid \r\n"
			+ "JOIN partymaster p ON a.subledgercode = p.partycode\r\n"
			+ "JOIN branch jbr ON a.branch = jbr.branch\r\n"
			+ "JOIN groupledger b\r\n"
			+ "JOIN branch br ON a.branch = br.branch\r\n"
			+ "WHERE \r\n"
			+ "    a.docdate <= DATE(?4) and   a.orgid=r.orgid and r.orgid=p.orgid and b.orgid=r.orgid and p.orgid=br.orgid and r.orgid = ?1\r\n"
			+ "    AND a.cancel = 0 and p.partytype='VENDOR' and (p.partyname = ?3 or ?3 = 'ALL')\r\n"
			+ "    AND (br.branch = ?2 or ?2 ='ALL') \r\n"
			+ "    AND b.category = 'PAYABLE A/C' group by a.arapdetailsid,\r\n"
			+ "                   jbr.branch,\r\n"
			+ "                   P.PARTYCODE ,\r\n"
			+ "                   p.partyname ,\r\n"
			+ "                   p.partytype,\r\n"
			+ "                   p.creditlimit,\r\n"
			+ "                   p.gstregistered,\r\n"
			+ "                   p.creditdays,\r\n"
			+ "                   p.salesperson,a.docid ,\r\n"
			+ "                   a.docdate,\r\n"
			+ "                   a.supprefno,\r\n"
			+ "                   a.suprefdate,\r\n"
			+ "                   a.refno,\r\n"
			+ "                   a.refdate,\r\n"
			+ "                   a.amount HAVING (a.amount + SUM(r.amount) != 0))t where t.refno not like('%RT%') and t.refno not like('%PT%') ORDER BY t.branch,t.subledgername,\r\n"
			+ "         t.partytype,\r\n"
			+ "         t.docdate,\r\n"
			+ "         t.docid\r\n"
			+ ") \r\n"
			+ "SELECT sno,arapdetailsid,branch,subledgercode,subledgername as partyname,subledgername,partytype,salesperson,docid,docdate,\r\n"
			+ "supprefno,suprefdate,duedate,refno,refdate,amount,outstanding,totaldue,unadjusted,ddays,mslab1,mslab2,mslab3,mslab4,mslab5,creditlimit,creditdays FROM a\r\n"
			+ "union\r\n"
			+ "SELECT 2 sno,null arapdetailsid,null branch,null subledgercode,'Total' as partyname, subledgername,null partytype,null salesperson,null docid,null docdate,\r\n"
			+ "null supprefno,null suprefdate,null duedate,null refno,null refdate,sum(a.amount)amount,sum(a.outstanding)outstanding,sum(a.totaldue)totaldue,sum(a.unadjusted)unadjusted,null ddays,sum(a.mslab1)mslab1,sum(a.mslab2)mslab2,sum(a.mslab3)mslab3,sum(a.mslab4)mslab4,sum(a.mslab5)mslab5,null creditlimit,null creditdays FROM a\r\n"
			+ "group by a.subledgername\r\n"
			+ "ORDER BY subledgername,sno asc")
	Set<Object[]> getApAgeing(Long orgId, String branch, String partyname, String asdate, String baseType);
	
	
//	@Query(nativeQuery = true, value = "select a.onaccount from receipt a,aradjustmentoffset a1 where a.docid=a1.receiptdocid and a.orgid=?1")
//	Set<Object[]> getOnAccountAmount(Long orgId);
//	
//	@Query(nativeQuery = true, value = "select * from receipt a,aradjustmentoffset a1 where a.docid=a1.receiptdocid and a.orgid=?1")
//	ReceiptVO getAccounts(Long orgId);
}

