package com.base.basesetup.repo;

import java.util.Set;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;

import com.base.basesetup.entity.TrialBalanceVO;

public interface TrialBalanceRepo extends JpaRepository<TrialBalanceVO, Long> {

	@Query(nativeQuery =true,value ="select m.accountcode,m.accountname,n.coacode,n.coa, m.opbalancedb,m.opbalancecr,m.transdebit,m.transcredit,m.clbalancedb,m.clbalancecr,row_number() over() from\r\n"
			+ "(select a.accountcode accountcode,a.accountname, a.opbalancedb,a.opbalancecr,a.transdebit,a.transcredit,a.clbalancedb,a.clbalancecr,a.client,a.clientcode from tbexcelupload a \r\n"
			+ "where  a.finyear=?2 and a.month=?3   and a.orgid=?1 and a.client=?4 and a.clientcode=?5)m left join ledgermapping n on \r\n"
			+ "m.accountcode=n.clientcoacode and n.orgid=?1 and n.clientname=?4 and n.clientcode=?5")
	Set<Object[]> getFillGridForTbExcelUpload(Long orgId, String finYear,String tbMonth, String client,String clientCode );

	
	@Query(nativeQuery = true, value = "select row_number() over()id,a.accountcode,a.accountname,a.coacode,a.coa,a.opbaldebit,a.opbalcredit,a.transdebit,a.transcredit,a.clbaldebit,a.clbalcredit,a.closingbalance,a.natureofaccount,b.groupname from vw_elytdtb a,coa b where a.coacode=b.accountcode and  a.orgid=?1 and a.clientcode=?2 and finyear=?3 \r\n"
			+ "	and month=?4")
	Set<Object[]> getElYTDTbdetails(Long orgId, String clientCode, String finyear, String month);
	

	@Query(nativeQuery = true,value = "WITH params AS (\r\n"
			+ "    SELECT \r\n"
			+ "        ?3 AS currentFinYear,\r\n"
			+ "        ?5 AS previousFinYear,\r\n"
			+ "        ?4 AS currentMonth\r\n"
			+ "),\r\n"
			+ "prev_params AS (\r\n"
			+ "    SELECT \r\n"
			+ "        CASE \r\n"
			+ "            WHEN currentMonth = 'January' THEN 'December'\r\n"
			+ "            WHEN currentMonth = 'February' THEN 'January'\r\n"
			+ "            WHEN currentMonth = 'March' THEN 'February'\r\n"
			+ "            WHEN currentMonth = 'April' THEN 'March'\r\n"
			+ "            WHEN currentMonth = 'May' THEN 'April'\r\n"
			+ "            WHEN currentMonth = 'June' THEN 'May'\r\n"
			+ "            WHEN currentMonth = 'July' THEN 'June'\r\n"
			+ "            WHEN currentMonth = 'August' THEN 'July'\r\n"
			+ "            WHEN currentMonth = 'September' THEN 'August'\r\n"
			+ "            WHEN currentMonth = 'October' THEN 'September'\r\n"
			+ "            WHEN currentMonth = 'November' THEN 'October'\r\n"
			+ "            WHEN currentMonth = 'December' THEN 'November'\r\n"
			+ "        END AS previousMonth\r\n"
			+ "    FROM params\r\n"
			+ ")\r\n"
			+ "SELECT \r\n"
			+ "    ROW_NUMBER() OVER() AS id,\r\n"
			+ "    h.coacode,\r\n"
			+ "    h.coa,\r\n"
			+ "    h.natureofaccount,\r\n"
			+ "    h.groupname,\r\n"
			+ "    SUM(h.currentMonthDebit) AS currentMonthDebit,\r\n"
			+ "    SUM(h.currentMonthCredit) AS currentMonthCredit,\r\n"
			+ "    SUM(h.currentMonthClosing) AS currentMonthClosing,\r\n"
			+ "    SUM(h.previousMonthDebit) AS previousMonthDebit,\r\n"
			+ "    SUM(h.previousMonthCredit) AS previousMonthCredit,\r\n"
			+ "    SUM(h.previousMonthClosing) AS previousMonthClosing,\r\n"
			+ "    SUM(h.currentMonthDebit) - SUM(h.previousMonthDebit) AS forMonthActDebit,\r\n"
			+ "    SUM(h.currentMonthCredit) - SUM(h.previousMonthCredit) AS forMonthActCredit,\r\n"
			+ "    SUM(h.currentMonthClosing) - SUM(h.previousMonthClosing) AS forMonthActClosing,\r\n"
			+ "    CASE \r\n"
			+ "        WHEN h.natureofaccount = 'Cr' AND SUM(h.currentMonthClosing) - SUM(h.previousMonthClosing) > 0 THEN 'Yes'\r\n"
			+ "        WHEN h.natureofaccount = 'Db' AND SUM(h.currentMonthClosing) - SUM(h.previousMonthClosing) < 0 THEN 'Yes'\r\n"
			+ "        ELSE 'No'\r\n"
			+ "    END AS mismatch,0 provisiondebit,0 provisioncredit,0 provisionclosing,0 forthemonthdebit,0 forthemonthcredit,0 forthemonthclosing,'No' approvestatus\r\n"
			+ "FROM (\r\n"
			+ "    -- Current Month Data\r\n"
			+ "    SELECT \r\n"
			+ "        a.coacode,\r\n"
			+ "        a.coa,\r\n"
			+ "        a.natureofaccount,\r\n"
			+ "        b.groupname,\r\n"
			+ "        SUM(a.clbaldebit) AS currentMonthDebit,\r\n"
			+ "        SUM(a.clbalcredit) AS currentMonthCredit,\r\n"
			+ "        SUM(a.closingbalance) AS currentMonthClosing,\r\n"
			+ "        0 AS previousMonthDebit,\r\n"
			+ "        0 AS previousMonthCredit,\r\n"
			+ "        0 AS previousMonthClosing      \r\n"
			+ "    FROM vw_elytdtb a \r\n"
			+ "    JOIN coa b ON a.coacode = b.accountcode\r\n"
			+ "    CROSS JOIN params p  \r\n"
			+ "    WHERE a.finyear = p.currentFinYear\r\n"
			+ "    AND a.month = p.currentMonth\r\n"
			+ "    AND a.orgid = ?1\r\n"
			+ "    AND a.clientcode = ?2\r\n"
			+ "    GROUP BY a.coacode, a.coa, a.natureofaccount, b.groupname\r\n"
			+ "\r\n"
			+ "    UNION\r\n"
			+ "\r\n"
			+ "    -- Previous Month Data\r\n"
			+ "    SELECT \r\n"
			+ "        a.coacode,\r\n"
			+ "        a.coa,\r\n"
			+ "        a.natureofaccount,\r\n"
			+ "        b.groupname,\r\n"
			+ "        0 AS currentMonthDebit,\r\n"
			+ "        0 AS currentMonthCredit,\r\n"
			+ "        0 AS currentMonthClosing,\r\n"
			+ "        SUM(a.clbaldebit) AS previousMonthDebit,\r\n"
			+ "        SUM(a.clbalcredit) AS previousMonthCredit,\r\n"
			+ "        SUM(a.closingbalance) AS previousMonthClosing\r\n"
			+ "    FROM vw_elytdtb a \r\n"
			+ "    JOIN coa b ON a.coacode = b.accountcode\r\n"
			+ "    CROSS JOIN prev_params p, params pp  \r\n"
			+ "    WHERE a.finyear = pp.previousFinYear\r\n"
			+ "    AND a.month = p.previousMonth\r\n"
			+ "    AND a.orgid = ?1\r\n"
			+ "    AND a.clientcode = ?2\r\n"
			+ "    GROUP BY a.coacode, a.coa, a.natureofaccount, b.groupname\r\n"
			+ ") h \r\n"
			+ "WHERE (h.coacode, h.coa) IN (\r\n"
			+ "    SELECT c.accountcode, c.accountgroupname \r\n"
			+ "    FROM groupmapping a\r\n"
			+ "    JOIN groupledgers d ON a.groupmappingid = d.groupmappingid AND d.active = 1\r\n"
			+ "    JOIN coa c ON d.subgroupname = c.groupname \r\n"
			+ "              AND c.orgid = d.orgid \r\n"
			+ "              AND c.accountcode = d.accountcode \r\n"
			+ "              AND c.active = 1\r\n"
			+ "    WHERE a.orgid = ?1\r\n"
			+ "    AND a.groupname = ?6\r\n"
			+ "    AND d.subgroupname = ?7 or 'ALL'=?7 \r\n"
			+ "    GROUP BY c.accountgroupname, c.accountcode, c.natureofaccount\r\n"
			+ ")and (h.coacode, h.coa,h.groupname) not in(select j.accountcode coacode,j.accountname coa,j.groupname from(\r\n"
			+ "SELECT \r\n"
			+ "    ROW_NUMBER() OVER() id,\r\n"
			+ "    a.accountcode,\r\n"
			+ "    a.accountname,\r\n"
			+ "    a.natureofaccount,\r\n"
			+ "    a.groupname,\r\n"
			+ "    a.currentmonthdebit,\r\n"
			+ "    a.currentmonthcredit,\r\n"
			+ "    a.currentmonthclosing,\r\n"
			+ "    a.previousmonthdebit,\r\n"
			+ "    a.previousmonthcredit,\r\n"
			+ "    a.previousmonthclosing,\r\n"
			+ "    a.forthemonthactdebit,\r\n"
			+ "    a.forthemonthactcredit,\r\n"
			+ "    a.forthemonthactclosing,\r\n"
			+ "    CASE \r\n"
			+ "        WHEN a.mismatch = 1 THEN 'Yes'\r\n"
			+ "        ELSE 'No'\r\n"
			+ "    END AS mismatch,\r\n"
			+ "    a.provisiondebit,\r\n"
			+ "    a.provisioncredit,\r\n"
			+ "    a.provisionclosing,\r\n"
			+ "    a.forthemonthdebit,\r\n"
			+ "    a.forthemonthcredit,\r\n"
			+ "    a.forthemonthclosing,\r\n"
			+ "    CASE \r\n"
			+ "        WHEN a.approvestatus = 1 THEN 'Yes'\r\n"
			+ "        ELSE 'No'\r\n"
			+ "    END AS approvestatus\r\n"
			+ "FROM monthlyprocessdetails a \r\n"
			+ "WHERE a.orgid = ?1 \r\n"
			+ "AND a.clientcode = ?2 \r\n"
			+ "AND a.month = ?4 \r\n"
			+ "AND a.year = ?3 \r\n"
			+ "AND a.maingroup = ?6  \r\n"
			+ "AND (a.groupname = ?7 OR 'ALL' = ?7))j group by j.accountcode,j.accountname,j.groupname) GROUP BY h.coacode, h.coa, h.natureofaccount, h.groupname\r\n"
			+ "union\r\n"
			+ "select row_number() over() id,a.accountcode,a.accountname,a.natureofaccount,a.groupname,a.currentmonthdebit,a.currentmonthcredit,a.currentmonthclosing,a.previousmonthdebit,a.previousmonthcredit,a.previousmonthclosing,\r\n"
			+ "a.forthemonthactdebit,a.forthemonthactcredit,a.forthemonthactclosing,CASE \r\n"
			+ "        WHEN a.mismatch = 1 THEN 'Yes'\r\n"
			+ "        ELSE 'No'\r\n"
			+ "    END AS mismatch,a.provisiondebit,a.provisioncredit,a.provisionclosing,a.forthemonthdebit,a.forthemonthcredit,a.forthemonthclosing,CASE \r\n"
			+ "        WHEN a.approvestatus = 1 THEN 'Yes'\r\n"
			+ "        ELSE 'No'\r\n"
			+ "    END AS approvestatus\r\n"
			+ " from monthlyprocessdetails a where a.orgid=?1 and a.clientcode=?2 and a.month=?4 and a.year=?3 and a.maingroup=?6  and a.groupname=?7 or 'ALL'=?7")
	Set<Object[]> getElYTDTbdetailsforMonthlyProcess(Long orgId, String clientCode, String finyear, String month,
			String previousYear,String mainGroupName,String subGroupCode);
	
//	@Query(nativeQuery = true, value = "WITH params AS (\r\n"
//			+ "    SELECT \r\n"
//			+ "        ?3 AS currentFinYear,\r\n"
//			+ "        ?5 AS previousFinYear,\r\n"
//			+ "        ?4 AS currentMonth\r\n"
//			+ "),\r\n"
//			+ "prev_params AS (\r\n"
//			+ "    SELECT \r\n"
//			+ "        CASE \r\n"
//			+ "            WHEN currentMonth = 'January' THEN 'December'\r\n"
//			+ "            WHEN currentMonth = 'February' THEN 'January'\r\n"
//			+ "            WHEN currentMonth = 'March' THEN 'February'\r\n"
//			+ "            WHEN currentMonth = 'April' THEN 'March'\r\n"
//			+ "            WHEN currentMonth = 'May' THEN 'April'\r\n"
//			+ "            WHEN currentMonth = 'June' THEN 'May'\r\n"
//			+ "            WHEN currentMonth = 'July' THEN 'June'\r\n"
//			+ "            WHEN currentMonth = 'August' THEN 'July'\r\n"
//			+ "            WHEN currentMonth = 'September' THEN 'August'\r\n"
//			+ "            WHEN currentMonth = 'October' THEN 'September'\r\n"
//			+ "            WHEN currentMonth = 'November' THEN 'October'\r\n"
//			+ "            WHEN currentMonth = 'December' THEN 'November'\r\n"
//			+ "        END AS previousMonth\r\n"
//			+ "    FROM params\r\n"
//			+ ")\r\n"
//			+ "SELECT \r\n"
//			+ "    ROW_NUMBER() OVER() AS id,\r\n"
//			+ "    h.coacode,\r\n"
//			+ "    h.coa,\r\n"
//			+ "    h.natureofaccount,\r\n"
//			+ "    h.groupname,\r\n"
//			+ "    SUM(h.currentMonthDebit) AS currentMonthDebit,\r\n"
//			+ "    SUM(h.currentMonthCredit) AS currentMonthCredit,\r\n"
//			+ "    SUM(h.currentMonthClosing) AS currentMonthClosing,\r\n"
//			+ "    case when 'Balance Sheet Schedule'= ?6 then 0 else SUM(h.previousMonthDebit) end previousMonthDebit,\r\n"
//			+ "    case when 'Balance Sheet Schedule' = ?6 then 0 else SUM(h.previousMonthCredit) end previousMonthCredit,\r\n"
//			+ "    case when 'Balance Sheet Schedule'= ?6 then 0 else SUM(h.previousMonthClosing) end previousMonthClosing,\r\n"
//			+ "    case when 'Balance Sheet Schedule'= ?6 then SUM(h.currentMonthDebit) else SUM(h.currentMonthDebit) - SUM(h.previousMonthDebit) end forMonthActDebit,\r\n"
//			+ "    case when 'Balance Sheet Schedule'= ?6 then SUM(h.currentMonthCredit) else SUM(h.currentMonthCredit) - SUM(h.previousMonthCredit) end forMonthActCredit,\r\n"
//			+ "    case when 'Balance Sheet Schedule'= ?6 then SUM(h.currentMonthClosing) else SUM(h.currentMonthClosing) - SUM(h.previousMonthClosing) end forMonthActClosing,\r\n"
//			+ "    CASE \r\n"
//			+ "        WHEN h.natureofaccount = 'Cr' AND SUM(h.currentMonthClosing) - SUM(h.previousMonthClosing) > 0 THEN 'Yes'\r\n"
//			+ "        WHEN h.natureofaccount = 'Db' AND SUM(h.currentMonthClosing) - SUM(h.previousMonthClosing) < 0 THEN 'Yes'\r\n"
//			+ "        ELSE 'No'\r\n"
//			+ "    END AS mismatch,\r\n"
//			+ "    0 provisiondebit,\r\n"
//			+ "    0 provisioncredit,\r\n"
//			+ "    0 provisionclosing,\r\n"
//			+ "    0 forthemonthdebit,\r\n"
//			+ "    0 forthemonthcredit,\r\n"
//			+ "    0 forthemonthclosing,\r\n"
//			+ "    'No' approvestatus\r\n"
//			+ "FROM (\r\n"
//			+ "    -- Current Month Data\r\n"
//			+ "    SELECT \r\n"
//			+ "        a.coacode,\r\n"
//			+ "        a.coa,\r\n"
//			+ "        a.natureofaccount,\r\n"
//			+ "        b.groupname,\r\n"
//			+ "        SUM(a.clbaldebit) AS currentMonthDebit,\r\n"
//			+ "        SUM(a.clbalcredit) AS currentMonthCredit,\r\n"
//			+ "        SUM(a.closingbalance) AS currentMonthClosing,\r\n"
//			+ "        0 AS previousMonthDebit,\r\n"
//			+ "        0 AS previousMonthCredit,\r\n"
//			+ "        0 AS previousMonthClosing\r\n"
//			+ "    FROM vw_elytdtb a \r\n"
//			+ "    JOIN coa b ON a.coacode = b.accountcode\r\n"
//			+ "    CROSS JOIN params p  \r\n"
//			+ "    WHERE a.finyear = p.currentFinYear\r\n"
//			+ "    AND a.month = p.currentMonth\r\n"
//			+ "    AND a.orgid = ?1\r\n"
//			+ "    AND a.clientcode = ?2\r\n"
//			+ "    GROUP BY a.coacode, a.coa, a.natureofaccount, b.groupname\r\n"
//			+ "\r\n"
//			+ "    UNION\r\n"
//			+ "\r\n"
//			+ "    -- Previous Month Data\r\n"
//			+ "    SELECT \r\n"
//			+ "        a.coacode,\r\n"
//			+ "        a.coa,\r\n"
//			+ "        a.natureofaccount,\r\n"
//			+ "        b.groupname,\r\n"
//			+ "        0 AS currentMonthDebit,\r\n"
//			+ "        0 AS currentMonthCredit,\r\n"
//			+ "        0 AS currentMonthClosing,\r\n"
//			+ "        SUM(a.clbaldebit) AS previousMonthDebit,\r\n"
//			+ "        SUM(a.clbalcredit) AS previousMonthCredit,\r\n"
//			+ "        SUM(a.closingbalance) AS previousMonthClosing\r\n"
//			+ "    FROM vw_elytdtb a \r\n"
//			+ "    JOIN coa b ON a.coacode = b.accountcode\r\n"
//			+ "    CROSS JOIN prev_params p, params pp  \r\n"
//			+ "    WHERE a.finyear = pp.previousFinYear\r\n"
//			+ "    AND a.month = p.previousMonth\r\n"
//			+ "    AND a.orgid = ?1\r\n"
//			+ "    AND a.clientcode = ?2\r\n"
//			+ "    GROUP BY a.coacode, a.coa, a.natureofaccount, b.groupname\r\n"
//			+ ") h \r\n"
//			+ "WHERE (h.coacode, h.coa) IN (\r\n"
//			+ "    SELECT c.accountcode, c.accountgroupname \r\n"
//			+ "    FROM groupmapping a\r\n"
//			+ "    JOIN groupledgers d ON a.groupmappingid = d.groupmappingid AND d.active = 1\r\n"
//			+ "    JOIN coa c ON d.subgroupname = c.groupname \r\n"
//			+ "              AND c.orgid = d.orgid \r\n"
//			+ "              AND c.accountcode = d.accountcode \r\n"
//			+ "              AND c.active = 1\r\n"
//			+ "    WHERE a.orgid = ?1\r\n"
//			+ "    AND a.groupname = ?6\r\n"
//			+ "    AND (d.subgroupname = ?7 OR 'ALL' = ?7)\r\n"
//			+ "    GROUP BY c.accountgroupname, c.accountcode, c.natureofaccount\r\n"
//			+ ")\r\n"
//			+ "AND (h.coacode, h.coa, h.groupname) NOT IN (\r\n"
//			+ "    SELECT j.accountcode, j.accountname, j.groupname FROM (\r\n"
//			+ "        SELECT \r\n"
//			+ "            ROW_NUMBER() OVER() id,\r\n"
//			+ "            a.accountcode,\r\n"
//			+ "            a.accountname,\r\n"
//			+ "            a.natureofaccount,\r\n"
//			+ "            a.groupname,\r\n"
//			+ "            a.currentmonthdebit,\r\n"
//			+ "            a.currentmonthcredit,\r\n"
//			+ "            a.currentmonthclosing,\r\n"
//			+ "            a.previousmonthdebit,\r\n"
//			+ "            a.previousmonthcredit,\r\n"
//			+ "            a.previousmonthclosing,\r\n"
//			+ "            a.forthemonthactdebit,\r\n"
//			+ "            a.forthemonthactcredit,\r\n"
//			+ "            a.forthemonthactclosing,\r\n"
//			+ "            CASE \r\n"
//			+ "                WHEN a.mismatch = 1 THEN 'Yes'\r\n"
//			+ "                ELSE 'No'\r\n"
//			+ "            END AS mismatch,\r\n"
//			+ "            a.provisiondebit,\r\n"
//			+ "            a.provisioncredit,\r\n"
//			+ "            a.provisionclosing,\r\n"
//			+ "            a.forthemonthdebit,\r\n"
//			+ "            a.forthemonthcredit,\r\n"
//			+ "            a.forthemonthclosing,\r\n"
//			+ "            CASE \r\n"
//			+ "                WHEN a.approvestatus = 1 THEN 'Yes'\r\n"
//			+ "                ELSE 'No'\r\n"
//			+ "            END AS approvestatus\r\n"
//			+ "        FROM monthlyprocessdetails a \r\n"
//			+ "        WHERE a.orgid = ?1\r\n"
//			+ "        AND a.clientcode = ?2\r\n"
//			+ "        AND a.month = ?4\r\n"
//			+ "        AND a.year = ?3\r\n"
//			+ "        AND a.maingroup = ?6 \r\n"
//			+ "        AND (a.groupname = ?7 OR 'ALL' = ?7)\r\n"
//			+ "    ) j GROUP BY j.accountcode, j.accountname, j.groupname\r\n"
//			+ ")\r\n"
//			+ "GROUP BY h.coacode, h.coa, h.natureofaccount, h.groupname\r\n"
//			+ "\r\n"
//			+ "UNION\r\n"
//			+ "\r\n"
//			+ "SELECT \r\n"
//			+ "    ROW_NUMBER() OVER() id,\r\n"
//			+ "    a.accountcode,\r\n"
//			+ "    a.accountname,\r\n"
//			+ "    a.natureofaccount,\r\n"
//			+ "    a.groupname,\r\n"
//			+ "    a.currentmonthdebit,\r\n"
//			+ "    a.currentmonthcredit,\r\n"
//			+ "    a.currentmonthclosing,\r\n"
//			+ "    a.previousmonthdebit,\r\n"
//			+ "    a.previousmonthcredit,\r\n"
//			+ "    a.previousmonthclosing,\r\n"
//			+ "    a.forthemonthactdebit,\r\n"
//			+ "    a.forthemonthactcredit,\r\n"
//			+ "    a.forthemonthactclosing,\r\n"
//			+ "    CASE \r\n"
//			+ "        WHEN a.mismatch = 1 THEN 'Yes'\r\n"
//			+ "        ELSE 'No'\r\n"
//			+ "    END AS mismatch,\r\n"
//			+ "    a.provisiondebit,\r\n"
//			+ "    a.provisioncredit,\r\n"
//			+ "    a.provisionclosing,\r\n"
//			+ "    a.forthemonthdebit,\r\n"
//			+ "    a.forthemonthcredit,\r\n"
//			+ "    a.forthemonthclosing,\r\n"
//			+ "    CASE \r\n"
//			+ "        WHEN a.approvestatus = 1 THEN 'Yes'\r\n"
//			+ "        ELSE 'No'\r\n"
//			+ "    END AS approvestatus\r\n"
//			+ "FROM monthlyprocessdetails a \r\n"
//			+ "WHERE a.orgid = ?1 \r\n"
//			+ "AND a.clientcode = ?2\r\n"
//			+ "AND a.month = ?4\r\n"
//			+ "AND a.year = ?3 \r\n"
//			+ "AND a.maingroup = ?6\r\n"
//			+ "AND (a.groupname = ?7 OR 'ALL' = ?7)")
//	Set<Object[]> getElYTDTbdetailsforMonthlyProcess(Long orgId, String clientCode, String finyear, String month,
//			String previousYear,String mainGroupName,String subGroupCode);
}
