package com.base.basesetup.config;

import javax.annotation.PostConstruct;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Configuration;
import org.springframework.jdbc.core.JdbcTemplate;

@Configuration
public class Views {
	
	@Autowired
    private JdbcTemplate jdbcTemplate;

    @PostConstruct
    public void initialize() {
        try {
            executeQueries();
        } catch (Exception e) {
            throw new RuntimeException("Error initializing database", e);
        }
    }

    private void executeQueries() {
    	
    	// Exrates View
    	jdbcTemplate.execute("create or replace view vw_exrates as\r\n"
    			+ "SELECT \r\n"
    			+ "    c.dailymonthlyexratesdtlid,\r\n"
    			+ "    g.orgid,\r\n"
    			+ "    g.date,\r\n"
    			+ "    g.month,\r\n"
    			+ "    c.currency, \r\n"
    			+ "    c.currencydescripition, \r\n"
    			+ "    c.buyingexrate, \r\n"
    			+ "    c.sellingexrate\r\n"
    			+ "FROM \r\n"
    			+ "    dailymonthlyexratesdtl c\r\n"
    			+ "JOIN \r\n"
    			+ "    dailymonthlyexrates g\r\n"
    			+ "ON \r\n"
    			+ "    c.dailymonthlyexratesid = g.dailymonthlyexratesid\r\n"
    			+ "JOIN (\r\n"
    			+ "    SELECT \r\n"
    			+ "        a.currency,\r\n"
    			+ "        MAX(a.dailymonthlyexratesdtlid) AS dailymonthlyexratesdtlid\r\n"
    			+ "    FROM \r\n"
    			+ "        dailymonthlyexratesdtl a\r\n"
    			+ "    JOIN \r\n"
    			+ "        dailymonthlyexrates b\r\n"
    			+ "    ON \r\n"
    			+ "        a.dailymonthlyexratesid = b.dailymonthlyexratesid\r\n"
    			+ "    GROUP BY \r\n"
    			+ "        a.currency\r\n"
    			+ ") d \r\n"
    			+ "ON c.dailymonthlyexratesdtlid = d.dailymonthlyexratesdtlid");
    	
    	jdbcTemplate.execute("CREATE OR REPLACE VIEW vw_REVENUE AS\r\n"
    			+ "SELECT \r\n"
    			+ "    h.orgid, \r\n"
    			+ "    h.billmonth, \r\n"
    			+ "    h.finyear,\r\n"
    			+ "    h.branch,\r\n"
    			+ "    h.branchcode,\r\n"
    			+ "    h.docid, \r\n"
    			+ "    h.docdate, \r\n"
    			+ "    (h.totalchargeamountlc - COALESCE(j.totalchargeamountlc, 0)) AS amount\r\n"
    			+ "FROM \r\n"
    			+ "    (SELECT \r\n"
    			+ "        a.orgid, \r\n"
    			+ "        DATE_FORMAT(a.vdate, '%M') AS billmonth, \r\n"
    			+ "        a.finyear, \r\n"
    			+ "        a.branch,\r\n"
    			+ "        a.branchcode,\r\n"
    			+ "        b.vid AS docid, \r\n"
    			+ "        b.vdate AS docdate, \r\n"
    			+ "        b.totalchargeamountlc\r\n"
    			+ "     FROM accounts a\r\n"
    			+ "     JOIN taxinvoice b ON a.orgid = b.orgid AND a.refno = b.docid\r\n"
    			+ "     WHERE b.cancel = 0\r\n"
    			+ "    ) h\r\n"
    			+ "LEFT JOIN \r\n"
    			+ "    (SELECT \r\n"
    			+ "        a.orgid, \r\n"
    			+ "        DATE_FORMAT(a.vdate, '%M') AS billmonth, \r\n"
    			+ "        a.finyear, \r\n"
    			+ "        a.branch,\r\n"
    			+ "        a.branchcode,\r\n"
    			+ "        c.vid AS docid, \r\n"
    			+ "        c.vdate AS docdate, \r\n"
    			+ "         b.totalchargeamountlc \r\n"
    			+ "     FROM accounts a\r\n"
    			+ "     JOIN irncreditnote b ON a.orgid = b.orgid AND b.docid = a.refno\r\n"
    			+ "     JOIN taxinvoice c ON b.orgid = c.orgid AND c.docid = b.originbillno\r\n"
    			+ "     WHERE b.cancel = 0\r\n"
    			+ "    ) j\r\n"
    			+ "ON h.orgid = j.orgid AND h.docid = j.docid");
    	
    	jdbcTemplate.execute("create or replace view vw_cost as \r\n"
    			+ "SELECT \r\n"
    			+ "    h.orgid AS orgid,\r\n"
    			+ "    h.billmonth AS billmonth,\r\n"
    			+ "    h.finyear AS finyear,\r\n"
    			+ "    h.branch AS branch,\r\n"
    			+ "    h.branchcode AS branchcode,\r\n"
    			+ "    h.docid AS docid,\r\n"
    			+ "    h.docdate AS docdate,\r\n"
    			+ "    (h.totalcreditamount - COALESCE(j.totalcreditamount, 0)) AS amount\r\n"
    			+ "FROM (\r\n"
    			+ "    SELECT \r\n"
    			+ "        a.orgid AS orgid,\r\n"
    			+ "        DATE_FORMAT(a.vdate, '%M') AS billmonth,\r\n"
    			+ "        a.finyear AS finyear,\r\n"
    			+ "        a.branch AS branch,\r\n"
    			+ "        a.branchcode AS branchcode,\r\n"
    			+ "        b.vid AS docid,\r\n"
    			+ "        b.vdate AS docdate,\r\n"
    			+ "       a.chargeableamount as totalcreditamount\r\n"
    			+ "    FROM accounts a\r\n"
    			+ "    JOIN costinvoice b \r\n"
    			+ "       ON a.orgid = b.orgid AND a.refno = b.docid\r\n"
    			+ "    WHERE b.cancel = 0\r\n"
    			+ ") h\r\n"
    			+ "LEFT JOIN (\r\n"
    			+ "    SELECT \r\n"
    			+ "        a.orgid AS orgid,\r\n"
    			+ "        DATE_FORMAT(a.vdate, '%M') AS billmonth,\r\n"
    			+ "        a.finyear AS finyear,\r\n"
    			+ "        a.branch AS branch,\r\n"
    			+ "        a.branchcode AS branchcode,\r\n"
    			+ "        c.vid AS docid,\r\n"
    			+ "        c.vdate AS docdate,\r\n"
    			+ "        a.chargeableamount AS totalcreditamount\r\n"
    			+ "    FROM accounts a\r\n"
    			+ "    JOIN costdebitnote b \r\n"
    			+ "        ON a.orgid = b.orgid AND b.docid = a.refno\r\n"
    			+ "    JOIN costinvoice c \r\n"
    			+ "        ON b.orgid = c.orgid AND c.docid = b.orginbill\r\n"
    			+ "    WHERE b.cancel = 0\r\n"
    			+ ") j \r\n"
    			+ "    ON h.orgid = j.orgid AND h.docid = j.docid");
    	
    	jdbcTemplate.execute("CREATE OR REPLACE  VIEW EINVOICEGENARATE\r\n"
    			+ "(\r\n"
    			+ "   DOCID,\r\n"
    			+ "   DOCDATE\r\n"
    			+ ")\r\n"
    			+ "AS\r\n"
    			+ "     SELECT docid, docdate\r\n"
    			+ "       FROM einvoice\r\n"
    			+ "      WHERE geneinvoice = 1 AND apicall = 0 AND ackno IS NULL\r\n"
    			+ "   GROUP BY docid, docdate");
    	
    	jdbcTemplate.execute("CREATE OR REPLACE VIEW EWAYBILLGENERATE\r\n"
    			+ "(\r\n"
    			+ "   DOCID,\r\n"
    			+ "   DOCDATE\r\n"
    			+ ")\r\n"
    			+ "AS\r\n"
    			+ "     SELECT docid, docdate\r\n"
    			+ "       FROM einvoice e\r\n"
    			+ "      WHERE genewaybill = 1 AND eapicall = 0 AND ewbno IS NULL\r\n"
    			+ "   GROUP BY docid, docdate");
    	
    	jdbcTemplate.execute("create or replace view vw_eltb as\r\n"
    			+ "SELECT \r\n"
    			+ "    a.coacode AS coacode,\r\n"
    			+ "    a.coa AS coa,\r\n"
    			+ "    a.orgid,\r\n"
    			+ "    a.clientcode,\r\n"
    			+ "    a.finyear,\r\n"
    			+ "    a.month,\r\n"
    			+ "    a.natureofaccount AS natureofaccount,\r\n"
    			+ "    SUM(a.opbalancedb) AS OPBalDebit,\r\n"
    			+ "    SUM(a.opbalancecr) AS OPBalCredit,\r\n"
    			+ "    SUM(a.transdebit) AS TransDebit,\r\n"
    			+ "    SUM(a.transcredit) AS TransCredit,\r\n"
    			+ "    SUM(a.clbalancedb) AS CLBalDebit,\r\n"
    			+ "    SUM(a.clbalancecr) AS CLBalCredit\r\n"
    			+ "FROM\r\n"
    			+ "    (SELECT \r\n"
    			+ "        a.orgid,\r\n"
    			+ "        a.clientcode,\r\n"
    			+ "        a.finyear,\r\n"
    			+ "        a.month,\r\n"
    			+ "        b.coacode AS coacode,\r\n"
    			+ "        b.coa AS coa,\r\n"
    			+ "        c.natureofaccount AS natureofaccount,\r\n"
    			+ "        a.opbalancedb AS opbalancedb,\r\n"
    			+ "        a.opbalancecr AS opbalancecr,\r\n"
    			+ "        a.transdebit AS transdebit,\r\n"
    			+ "        a.transcredit AS transcredit,\r\n"
    			+ "        a.clbalancedb AS clbalancedb,\r\n"
    			+ "        a.clbalancecr AS clbalancecr\r\n"
    			+ "    FROM\r\n"
    			+ "        tbexcelupload a\r\n"
    			+ "    JOIN ledgermapping b ON a.orgid = b.orgid \r\n"
    			+ "        AND a.clientcode = b.clientcode \r\n"
    			+ "        AND a.accountname = b.clientcoa\r\n"
    			+ "    JOIN coa c ON c.accountcode = b.coacode) a\r\n"
    			+ "GROUP BY \r\n"
    			+ "    a.coacode, \r\n"
    			+ "    a.coa, \r\n"
    			+ "    a.natureofaccount, \r\n"
    			+ "    a.orgid, \r\n"
    			+ "    a.clientcode, \r\n"
    			+ "    a.finyear, \r\n"
    			+ "    a.month\r\n"
    			+ "ORDER BY a.coacode");
    	
    	jdbcTemplate.execute("create or replace view vw_elytdtb as\r\n"
    			+ "SELECT \r\n"
    			+ "    a.accountcode,\r\n"
    			+ "    a.accountname,\r\n"
    			+ "    a.coacode,\r\n"
    			+ "    a.coa,\r\n"
    			+ "    a.orgid,\r\n"
    			+ "    a.clientcode,\r\n"
    			+ "    a.finyear,\r\n"
    			+ "    a.month,\r\n"
    			+ "    a.natureofaccount,\r\n"
    			+ "    SUM(a.opbalancedb) AS OPBalDebit,\r\n"
    			+ "    SUM(a.opbalancecr) AS OPBalCredit,\r\n"
    			+ "    SUM(a.transdebit) AS TransDebit,\r\n"
    			+ "    SUM(a.transcredit) AS TransCredit,\r\n"
    			+ "    SUM(a.clbalancedb) AS CLBalDebit,\r\n"
    			+ "    SUM(a.clbalancecr) AS CLBalCredit,\r\n"
    			+ "    SUM(a.clbalancedb) - SUM(a.clbalancecr)  closingbalance\r\n"
    			+ "FROM (\r\n"
    			+ "    SELECT \r\n"
    			+ "        a.orgid,\r\n"
    			+ "        a.clientcode,\r\n"
    			+ "        a.finyear,\r\n"
    			+ "        a.month,\r\n"
    			+ "        a.accountcode,\r\n"
    			+ "        a.accountname,\r\n"
    			+ "        b.coacode,\r\n"
    			+ "        b.coa,\r\n"
    			+ "        c.natureofaccount,\r\n"
    			+ "        a.opbalancedb,\r\n"
    			+ "        a.opbalancecr,\r\n"
    			+ "        a.transdebit,\r\n"
    			+ "        a.transcredit,\r\n"
    			+ "        a.clbalancedb,\r\n"
    			+ "        a.clbalancecr\r\n"
    			+ "    FROM tbexcelupload a\r\n"
    			+ "    JOIN ledgermapping b \r\n"
    			+ "        ON a.orgid = b.orgid \r\n"
    			+ "        AND a.clientcode = b.clientcode \r\n"
    			+ "        AND a.accountname = b.clientcoa\r\n"
    			+ "    JOIN coa c \r\n"
    			+ "        ON c.accountcode = b.coacode\r\n"
    			+ ") a\r\n"
    			+ "GROUP BY \r\n"
    			+ "    a.accountcode,\r\n"
    			+ "    a.accountname,\r\n"
    			+ "    a.coacode,\r\n"
    			+ "    a.coa,\r\n"
    			+ "    a.natureofaccount,\r\n"
    			+ "    a.orgid,\r\n"
    			+ "    a.clientcode,\r\n"
    			+ "    a.finyear,\r\n"
    			+ "    a.month order by a.accountcode");
   }
    
    

}
